### ISSUE TITLE
Add 'light()' and 'darken()' functions

### ISSUE THREAD

**Issue by wesselgrift** [six7/figma-tokens#1003]
Would be very useful to add 'lighten()' and 'darken()' functions for color tokens, in the same way it is applied in SCSS.
Example:

`token ABC = lighten({primary color}, 15%`

If this could be used, one could very easily great all kinds of shades and color variants based on one main color.

**Comment by six7** [comment]
We're tracking this in another issue already, closing this one.

Duplicate of #85
