### ISSUE TITLE
Renaming a token group name in a duplicated token set renames in the original set as well

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#1006]
**Describe the bug**
Renaming a token group name in a duplicated token set renames in the original set as well

**To Reproduce**
1. Duplicate a token set and rename it 
2. On the Duplicated token set, rename a token group
3. Check the original token set
4. The token group in the original token set is also renamed

**Expected behavior**
The token group in the original token set should not be affected by the renaming in the duplicated token set.

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/66366384/178239522-b88d1119-6fbc-475c-a2f0-c7ce5657f5df.mov

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
@LiamMartens can you link the PR that fixed this?
