### ISSUE TITLE
No color preview available when using HSLA color, without adding all the variables.

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1008]
**Describe the bug**
There is no color preview available when using HSLA color, when not all variables are filled. The color in the design itself works fine.

**To Reproduce**
1. Create a color token
2. Put in a HSLA color, without all the variables. (for example: hsla(270))
3. The value is set, but the preview of the color is not shown (also not when the token is created).

Note: for RGB & RGBA: when not all the variables are filled, the preview color and also the color in the design doesn't work.

**Expected behavior**
Expect to see a preview of the color (in the example used: purple).
Example of expected result: hsla(270, 50%, 50%, 1)

**Screenshots or Screencasts**
<img width="80" alt="image" src="https://user-images.githubusercontent.com/109062656/178258731-9b4c7f45-7835-42e2-922d-765257ff23b2.png">

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
From what I understand hsl requires all 3 properties to work. I don't think we'd want to support just using hue?

**Comment by six7** [comment]
I'll close this for now, please let me know if you think this is a mistake, however I don't think we should be supporting something that even CSS doesn't support.
