### ISSUE TITLE
Push to GitLab on multi file not working (enterprise)

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#1018]
**Describe the bug**
Pushing to GitLab with multi file setup not working for GitLab enterprise

**To Reproduce**
1. Connect to GitLab enterprise
2. Make changes in the plugin 
3. Push changes
4. Push not working 

**Expected behavior**
Push to gitlab should work as expected.

**Screenshots or Screencasts**
![Screenshot_20220712-212750](https://user-images.githubusercontent.com/66366384/178546963-abe741ab-0754-4d4e-ad20-49b4eba4205c.jpg)

**Comment by six7** [comment]
@esthercheran is this fixed by https://github.com/six7/figma-tokens/pull/1043 ?

**Comment by esthercheran** [comment]
Yes, this is fixed by https://github.com/six7/figma-tokens/pull/1043
