### ISSUE TITLE
Unexpected undo behaviour (cache issue?)

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1031]
I apply a color token to a bunch of layers, and undo this using cmd+z in figma. This does remove the color fill, but does not remove the token. So now when I press update again, the fill will again be applied, which I think is causing a lot of frustration and is an unexpected behaviour. On further investigation, this seems to be an issue with our token cash, because when I restart the plugin, the tokens are actually not there on the layers after CMD+Z

**Comment by six7** [comment]
Can we get a reproducible  screen cap of this?
