### ISSUE TITLE
Pull from GitHub occasionally doesn't seem to pull or update pulled changes from icon next to branch switcher.

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1034]
Description: I have noticed on quite a few occasions, that when I pull from GitHub using the icon next to branch switcher, my changes are not pulled properly. Of course when I try to record it, it works every time  but I will try to record an instance.

Jira issue: FT-158

**Comment by six7** [comment]
I think we already fixed this with recent caching. Let's reopen if it appears again.
