### ISSUE TITLE
[JIRA] Add Sentry to the backend 

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1036]
Description: We need to add Sentry to the backend so we can better handle the errors.
- The errors are right now only logged and we use Logtail on heroku (Free account)
- Sentry would help us identify and fix the license backend issues

https://docs.sentry.io/platforms/node/guides/express/

Jira issue: FT-343

**Comment by six7** [comment]
I'll close this as it's in the wrong repository
