### ISSUE TITLE
Height token not respected when nested and imported as library

### ISSUE THREAD

**Issue by HegeBa** [six7/figma-tokens#1046]
**`Design System File`**
1. Button component is given a height token
2. Two themes were created, one with a button height of 48px and the second with 56px
3. Button component nested inside a card component with auto layout
4. Switching theme inside the design system file works great - buttons change height as intended both in the button and card component
5. Tokens stored in JSONBin.io with a Figma Tokens PRO license

**`Work file`**
1. Design system file imported as an asset library
2. Pulling out an instance of the button component, changing theme -  sizing works as expected
3. Pulling out an instance of the card component, changing theme, button size is now the size of the active theme in the design system file and does not update when changing themes.
4. Makes no difference if I turn auto-layout off
5. Makes no difference if I attach the same height token to the button group
6. Makes no difference if I ungroup the buttons
7. Makes no difference if the button is the only item inside the card, with no sizing or auto-layouts attached to the card

**`Conclusion`**
 - **The height token does not work on nested components when imported as an asset library** 
  It does however work inside the design system file itself, and all the other tokens such as colors, fonts, and borders seem to be working fine

**Comment by six7** [comment]
The reason for this is that in Figma you can't change a component instance layer's height. A plugin can't do anything about that.

I'd suggest creating dedicated variants for the alternating heights or trying to not use height as a property in the component and instead rely on padding to do the same.
