### ISSUE TITLE
Problem with color tokens

### ISSUE THREAD

**Issue by bellentani** [six7/figma-tokens#105]
Hi. 

I found another issue. The color tokens isnt working on Fill. 

The token was updated on Inspect, but is not showing the color change on Figma UI. And nothing comes on debugging mode - the console log is empty.

I make this video to show the problem => https://drive.google.com/file/d/1O7r_um5jjBb8M9p0et_zXK8t0cHnpOQa/view

This problem started today.

But, when I change token value and apply again, all nodes are updated with the new color. But, the token dont receive the update on UI (Example: If change a value Token that was #ebebeb to #cccccc the color on UI not change, but, the value aplied changes).

**Comment by six7** [comment]
Hey @bellentani - thanks for reporting! Can you confirm this bug still persists with today's update? I pushed an update some hours ago that I hope could fix this problem.

**Comment by bellentani** [comment]
Hello again! 

Made tests here and problem is solved. ;) 

Thanks again. 

P.S.: Your plugin is awesome! Congratulations and thanks a lot for the amazing work! ;) Put a Paypal "Donate" button in your doc! :) I ll be glad in pay some cash to it! 🍡

**Comment by six7** [comment]
Great! Ah, you're right. Should definitely include a Sponsor button on GitHub as well :D

https://www.buymeacoffee.com/six7

Closing this, feel free to reopen when it reappears (which I hope it won't)

**Comment by bellentani** [comment]
Coffee bought! ☕ ❤️
