### ISSUE TITLE
[Dev] Plugin error on In-development version

### ISSUE THREAD

**Issue by pat270** [six7/figma-tokens#1054]
**Describe the bug**
Plugin doesn't work in Figma when using `yarn build` or `yarn build:watch`. I'm on `node@18.6.0` and `yarn@1.19.1`.

**To Reproduce**
1. Follow instructions at https://github.com/six7/figma-tokens#contribute
2. Plugin Error: TypeError: Cannot read properties of undefined (reading 'document')

**Expected behavior**
It should work.

**Screenshots or Screencasts**
![dev-mode](https://user-images.githubusercontent.com/788266/179225712-68cc8f63-de22-43b6-9360-cf378adab5a7.jpg)

**Comment by six7** [comment]
See here: https://docs.figmatokens.com/contributing#cannot-read-property-document-of-undefined
