### ISSUE TITLE
Creating typography styles don't respect font size

### ISSUE THREAD

**Issue by hmbrg** [six7/figma-tokens#1061]
**Describe the bug**
When creating a typography style, the font size set in that style doesn't convert to to created Figma text styles. The Figma text style just defaults to a size of 12.

**To Reproduce**
1. Create a typography style with a custom font size
2. Click on Styles > Create styles
4. Check the generated styles and see that the font size is 12

**Expected behavior**
Expected to defined font-size to be converted to the Figma text style.

**Screenshots or Screencasts**
![CleanShot 2022-07-17 at 13 51 29@2x](https://user-images.githubusercontent.com/7304269/179396902-1baee274-9717-47ad-a5ee-c05b5a950a2b.png)

**Comment by six7** [comment]
This is most probably becaues your font family / weight combination doesn't exist in Figma.

Can you check the Console and post your full JSON here? Make sure that Font family and Weight exist in Figma (not `500` but `Regular` for example). Those are case sensitive.

**Comment by six7** [comment]
Closing this, as it's most probably related to your family/weight combination.
