### ISSUE TITLE
Typography Tooltip doesn’t pipe through the values from selected reference token when using the alias mode.

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1066]
**Describe the bug**
Typography Tooltip doesn’t pipe through the values from selected reference token when using the alias mode. For the input mode, the Tooltip does work.

**To Reproduce**
1. Go to Typography and click '+' to add a new token
2. Switch from input mode to alias/reference mode
3. Complete the token and click 'Create'
4. Now hover over the token and the tooltip doesn't contain values.
![image](https://user-images.githubusercontent.com/109062656/179493548-87b0be5b-4cab-4b94-87ad-298629281bc9.png)

**Expected behavior**

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/109062656/179493486-50775dd1-1726-4182-b98e-04ce2baf7846.png)
https://user-images.githubusercontent.com/109062656/179493290-92fe218a-d923-411b-abae-40db446508fe.mov

**Comment by six7** [comment]
I think this is a duplicate of https://github.com/six7/figma-tokens/issues/938

**Comment by rbosker** [comment]
indeed duplicated by the linked issue (938), therefore closing this issue.
