### ISSUE TITLE
Standard spacing token attached to one or more parts of the Auto Layout without targeting (target = value)

### ISSUE THREAD

**Issue by bewarai** [six7/figma-tokens#1067]
I would love to have the ability to create a spacing token that is attached to just one or more parts of the auto-lay out without always having to choose over and over again the target for each component. The target should be an option along the name, value and description.

**Comment by six7** [comment]
Would this issue do what you'd like? https://github.com/six7/figma-tokens/issues/110

**Comment by bewarai** [comment]
> Would this issue do what you'd like? #110

It is partly solved with the combo tokens. I can make a token, add for example a padding right or multiple values (like #110 ), but the only issue is than you can not use 2 combo's which leads to issue #1085

**Comment by six7** [comment]
I think for now we'll close this given we shipped multi-value spacing tokens. We can keep discussion in 1085.
