### ISSUE TITLE
Enable new Figma token rolethat can use github to get tokens without privileges to edit or push tokens

### ISSUE THREAD

**Issue by Design2Well** [six7/figma-tokens#1070]
Basically other designers should be able to use tokens without the ability to edit the tokens in Figma. 

In other words there should be token admins, and token users. Token users can pull from a remote source but not make changes locally or push back to the repo.

**Comment by six7** [comment]
Closing this, feel free to reopen if the GitHub provided way of defining permissions doesn't suffice.

**Comment by Design2Well** [comment]
FYI... just tested removing my Pro license and was able to still pull multiple .json files from github. This issue appears to be specific to Read Github user roles only.
