### ISSUE TITLE
Typography tokens are not recreated in styles in Figma file

### ISSUE THREAD

**Issue by sarahconvex** [six7/figma-tokens#1082]
**Describe the bug**
After creating a typography token that includes font family, weight, size, and line-height, I clicked "create styles" to generate the styles in my Figma file. The style created in Figma has only the font-family and has defaulted to font-size of 12px (which is not the correct size from the token.) It has not inherited the line-height or font-weight. The only correct information is the font-family.

**To Reproduce**
1. Set up a typography token containing font-family, font-weight, font-size, and line-height.
2. Create styles.
3. Select text and apply the style, either from the Figma Tokens plugin or from the Figma text styles panel.
4. Selected text will alter to the incorrect style.

**Expected behavior**
After create styles, a text style is created in the Figma document that is an exact match for the typography token that was created in the Figma Tokens plugin.

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/109759093/180286274-376a844c-c666-4bf0-933f-f28fedcc5e3d.png)
![image](https://user-images.githubusercontent.com/109759093/180286395-5cb6cce1-596d-4024-b2ed-4a40ec7f6f54.png)

**Figma file (optional)**
Unable to send.

**JSON (optional)**
Unable to send.

**Comment by six7** [comment]
Change font weight from `bold` to `Bold` and it will work.

**Comment by AndySobol** [comment]
The same problem. Figma does not update styles if you change the token in the plugin.
