### ISSUE TITLE
Interference between Typography tokens and Text-decoration & Text Case tokens

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1084]
**Describe the bug**
There seems to be interference between typography tokens and text-decoration/text case tokens. 
When you apply a typography token and afterwards try to apply a decoration/case token, the decoration/case token won't be applied. 
When you first apply the text decoration/text case token and afterwards the typography token, that works fine.

**To Reproduce**
1. Apply a typography token
2. Afterwards try to apply a text decoration or text case token > nothing happens

**Expected behavior**

**Screenshots or Screencasts**
https://user-images.githubusercontent.com/109062656/180446984-19346017-b75c-4805-bac5-d1dbc02c3b40.mov

**Comment by tylerhellner** [comment]
Yeah the Typography token seems to override any other text styles — even if the styles are undefined / left blank in the Typography set. It would be really handy if this was fixed as it would free up the Composition slot for another token.
