### ISSUE TITLE
headings passed through token-transformer are incompatible with Style Dictionary

### ISSUE THREAD

**Issue by wraybowling** [six7/figma-tokens#1088]
**Describe the bug**
Consider the following section from the attached [tokens.json file](https://github.com/six7/figma-tokens/files/9183616/tokens.json.zip) which came from the Figma Tokens plugin

```json
    "heading": {
      "level-1": {
        "value": {
          "fontFamily": "{fontFamily-brand}",
          "fontWeight": "Light",
          "lineHeight": "48",
          "fontSize": "{fontSize.2xl}",
          "letterSpacing": "0%",
          "paragraphSpacing": "0",
          "textDecoration": "none",
          "textCase": "none"
        },
        "type": "typography",
        "description": "Heading 1"
      }
    }
```

When the above is passed through token-transformer, and then Style Dictionary, the following SCSS (abridged) is produced:
```scss
$font-size-4xl: 64;
$font-size-5xl: 96;
$normal: 140%;
$heading-level-1: [object Object];
$heading-level-2: [object Object];
$heading-level-3: [object Object];
$body-thin: [object Object];
$body-regular: [object Object];
$body-medium: [object Object];
$body-bold: [object Object];
$display-medium: [object Object];
$display-large: [object Object];
$caption-regular: [object Object];
$xs-bold: [object Object];
$background-white: #ffffff;
$background-light: #f9f9f9;
$background-blue: #0059B8;
```

**To Reproduce**
1. Create headings
2. export tokens
3. feed into token-transformer
4. feed transformed tokens through style dictionary to scss

Alternatively, download my [test project zip file](https://github.com/six7/figma-tokens/files/9183719/Design.Tokens.Test.zip) and run `npm run build`

**Expected behavior**
I expect to see tokens converted into valid SCSS variables of any kind

**Comment by six7** [comment]
Try using `token-transformer … --expandTypography=true` or write your custom transformer like I did here to convert them to css shorthands: https://gist.github.com/six7/9cbce8bcbb16b308c5c87f3729392d21

**Comment by wraybowling** [comment]
It was my understanding that token-transformer was a tool specifically designed to build data that is compatible with Style Dictionary. While it's somewhat convenient that there's potentially an existing flag that could solve this issue, I think most users will expect it to be the out-of-the-box default.

**Comment by six7** [comment]
This is only due to the fact that style dictionary doesn't support typography composite tokens so far, which ideally they will

**Comment by six7** [comment]
Closing this as we won't be changing this to a default. The hope is that style dictionary at some point supports this, as it's in the W3C spec.

I'm not changing this to a default because by expanding you lose functionality. If you want to e.g. use a custom written style dictionary transformer then you can use these with that one to e.g. create css shorthands (as described in the comment above).

**Comment by wraybowling** [comment]
Hi again. Thank you for bringing to my attention that design tokens had a w3c spec at all. I was wondering where on earth these ideas were coming from. For the future lurker, the official hub is here https://www.w3.org/community/design-tokens/ and at the time of this writing composite tokens for typography are in second draft https://second-editors-draft.tr.designtokens.org/format/#composite-types
