### ISSUE TITLE
Pull is working, push in not working

### ISSUE THREAD

**Issue by bohdank1995** [six7/figma-tokens#1090]
**Describe the bug**
If I want to publish new changes to GitHub it shows me an endless loader 'Pushing to GitHub'. For some reasons I'm not able to publish my changes. Could you please help me with that?

**To Reproduce**
1. Open FigmaToken Plugin
2. Pull from GitHub
3. Create/Update the design token
4. Push to GitHub
5. Writing a Commit message
6. Press the Push button
7. Pushing to GitHub popup appears (at this step my flow ends and nothing happens)

**Expected behavior**
After the 7th step, I expect that 'Pushing to GitHub' process will end in some time and I will push my updates to GitHub.

**Screenshots or Screencasts**
<img width="403" alt="Screenshot 2022-07-26 at 20 04 30" src="https://user-images.githubusercontent.com/104136805/181067367-60a87383-2af2-4fb2-b50e-1814566ef330.png">

**Comment by six7** [comment]
Can you give us more context? Token JSON stored on github, what sync settings you have, etc

**Comment by bohdank1995** [comment]
Yes, token Json stored on GitHub

My sync settings:
Token Storage — GitHub
All credentials are correct

I'm pushing changes into the main branch

**Comment by six7** [comment]
> Yes, token Json stored on GitHub
> 
> 
> 
> My sync settings:
> 
> Token Storage — GitHub
> 
> All credentials are correct
> 
> 
> 
> I'm pushing changes into the main branch
> 
> 

Does your repository have main set as a protected branch on github?

**Comment by bohdank1995** [comment]
I guess it doesn't matter in my case cause for my coworker the same sync settings works but for me not

**Comment by six7** [comment]
Usually this is due to different configuration of credentials. If it works for your coworker I'd suggest double checking if the credentials, branch, filePath, repo, etc are really all matching.

**Comment by six7** [comment]
Closing this as no further information was provided
