### ISSUE TITLE
Support multi-value radii and spacing tokens

### ISSUE THREAD

**Issue by jofralogo** [six7/figma-tokens#110]
## Description
In addition to users being able to completely set border radii as they can do now, we'd allow multi-value tokens for borderRadii.

When applying a token, we'd just check if that token is a single-value token or a multi-value token, then we'd know where to apply it to.

Multi-value tokens shouldn't be allowed to be set on individual corners though, so the plugin showing that token would have to have some sort of logic to differentiate between the two, and thus disabling the other options.

## Radius, Spacing tokens can be:
> Single value (like today)
> Clicking this on radii will apply to all corners (like today)
> Clicking this on spacing will apply to the gap property (like today)
> 10px
> 
> Two values
> Clicking this on radii will apply top-left-and-bottom-right | top-right-and-bottom-left
> Clicking this on spacing will apply top-and-bottom | left-and-right
> 10px 5px
> 
> Three values
> Clicking this on radii will apply top-left | top-right-and-bottom-left | bottom-right
> Clicking this on spacing will apply top | right-and-left | bottom
> 2px 4px 2px
> 
> Four values
> Clicking this on radii will apply top-left | top-right | bottom-right | bottom-left
> Clicking this on spacing will apply top | right | bottom | left
> 1px 0 3px 4px

![Image](https://user-images.githubusercontent.com/4548309/189476864-c362a5b1-45a9-455c-bde6-078d168827fa.png)

## Requirements
- When right-clicking such a token, the individual side entries are disabled (border-radius: top left, top right, bottom left, bottom right | spacing: top, bottom, left, right), only the `All` option is present.
- For Spacing, the default for left-clicking such a token changes from `Gap` to `All`.
![Image](https://user-images.githubusercontent.com/109062656/188841470-31158d2f-9424-418a-a925-768645c38db9.png)
![Image](https://user-images.githubusercontent.com/109062656/188841657-c6e3e81b-36bc-41d6-b7d0-3378b0a377e2.png)

## Initial description
Think in a way to allow to set multiple `boderRadius` values inline in order to have a different radius for each corner (like CSS does).

**Comment by six7** [comment]
Just so I understand correctly: You'd like to be able to create a token that defines each corner independently? 

Because right now you can set tokens on individual corners by right-clicking a borderRadius token and then choosing which corners to apply it on (you can mix tokens).

I think introducing the option to combine these definitely makes sense (think certain shapes that always appear in a certain combination of radii).

if we introduced these combination tokens, I agree we should stay close to what you can do in css right now:
- single value
- two values
- three values
- four values

**Comment by jofralogo** [comment]
Yes. As far as I know, I can't set a value the two top or bottom corners, for example.

It will be great if we can set the border radius like CSS does:

- If one value is set, this radius applies to all 4 corners.
- If two values are set, the first applies to top-left and bottom-right corner, the second applies to top-right and bottom-left corner.
- Three values: The second value applies to top-right and also bottom-left.
- Four values apply to the top-left, top-right, bottom-right, bottom-left corner in that order.

**Comment by six7** [comment]
I like it!

So in addition to users being able to completely set border radii as they can do now, we'd allow multi-value tokens for borderRadii.

When applying a token, we'd just check if that token is a single-value token or a multi-value token, then we'd know where to apply it to.

Multi-value tokens shouldn't be allowed to be set on individual corners though, so the plugin showing that token would have to have some sort of logic to differentiate between the two, and thus disabling the other options.

So when a user right-clicks a multi-value token, the following from this screenshot should be disabled:
- Top Left (disabled)
- Top Right (disabled)
- Bottom Right (disabled)
- Bottom Left (disabled)

![image](https://user-images.githubusercontent.com/4548309/115142655-3f4a0280-a043-11eb-80db-715f01c2804d.png)

**Comment by jofralogo** [comment]
I like it!

**Comment by badjar** [comment]
What would this multi-value tokens look like in the JSON code? I want to communicate the figma design intent (i.e. different radii on each corner) to the development team through the token.

If a best practice already exists for this use case please can someone tell me how? Should I set up aliases for a token for each corner?

**Comment by six7** [comment]
> What would this multi-value tokens look like in the JSON code? I want to communicate the figma design intent (i.e. different radii on each corner) to the development team through the token.
> 
> If a best practice already exists for this use case please can someone tell me how? Should I set up aliases for a token for each corner?

Most probably this will be an array:

`[0, 0, 4, 4]`

because then we're able to use tokens in all of these:

`[0, 0, "{radius.md}", "{radius.md}"]`

**Comment by akosarch** [comment]
I guess simple CSS like string should work well:
```
borderRadius: {
    top: "8 8 0 0",                                                  // top-left: 8, top-right: 8
    bottom: "0 0 $basic.small $basic.small"      // bottom-right: 8, bottom-left: 8
}
```
https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

**Comment by six7** [comment]
We'll move forward with this:

Radius, Spacing tokens can be:

> **Single value (like today)**
Clicking this on radii will apply to all corners (like today)
Clicking this on spacing will apply to the `gap` property (like today)
`10px`

> **Two values**
Clicking this on radii will apply `top-left-and-bottom-right | top-right-and-bottom-left`
Clicking this on spacing will apply `top-and-bottom | left-and-right`
`10px 5px`

> **Three values**
Clicking this on radii will apply `top-left | top-right-and-bottom-left | bottom-right`
Clicking this on spacing will apply `top | right-and-left | bottom`
`2px 4px 2px`

> **Four values**
Clicking this on radii will apply `top-left | top-right | bottom-right | bottom-left`
Clicking this on spacing will apply `top | right | bottom | left`
`1px 0 3px 4px`


When right-clicking such a token, the individual side entries are disabled, only the `All` option is present.
For Spacing, the default for left-clicking such a token changes from `Gap` to `All`.

**Comment by mazzzzzzzy** [comment]
The syntax I think should be optional in the settings, but not sure.

**Comment by benw31** [comment]
Any updates on this one? Be a great one to have as it could be used as a basic concept of a branded shape token.

**Comment by six7** [comment]
The day has come! 👀  This was shipped as part of V123 🎉
