### ISSUE TITLE
Allow to parse tokens with `sets` names

### ISSUE THREAD

**Issue by Lazarencjusz** [six7/figma-tokens#1103]
**Is your feature request related to a problem? Please describe.**
I have raw design tokens provided by wrapping by `set`s. The plugin works like it removes `set` names from parsed file and additional structure for raw tokens is required.

**Describe the solution you'd like**
The module should parse raw design tokens without loosing `set` names.

**Describe alternatives you've considered**
When I agreed with designers the tokens structure I can use it a bit like with `set`s, but it adds additional levels of tokens within `set`s itself.

**Additional context**
Each `set` below (Global, Transaction, Maps) has its own `Color` tokens. Some `set`s uses `Global` values by variables/references. If I provide JSON of such structure to the module, I always get parsed file with only one `Color` resolved values, there is no distinguish there by `set`s, only values overwritten by last `set` (when keys in JSON tree match each other). 

So this way I loose token values in such JSON structure.

![image](https://user-images.githubusercontent.com/6573466/182138430-fe6dad2e-8bf8-46a1-acb3-f7527453818b.png)

**Comment by six7** [comment]
We currently don't have plans to change that behaviour, a token set is basically like a file, so its name is never part of the token name itself, you'd have to manually add it, which leads to the additional level you mentioned.
