### ISSUE TITLE
Cannot get started: No nodes updated

### ISSUE THREAD

**Issue by yoniholmes** [six7/figma-tokens#111]
Hi, thanks for your plug-in, looks great! I'm struggling to get started though. I have installed your plugin, opened it, selected 'JSON', Load preset. Then when I click Save & update I see a message saying 'No nodes updated' at the bottom of the screen. 

I have tried selecting a frame, a rectangle, a blank document. And it's always the same. 

What should happen when clicking 'Update page' or Save & update?

I'm on Figma 97.7. 

Many thanks & kind regards,

Jonathan

**Comment by six7** [comment]
Hey Jonathan!

What you can do to get started is to apply the tokens that are visible in the plugin to a certain node.

E.g. create a rectangle in figma, then select one of the `sizing` tokens from the plugin window. It will then resize the selected layer to that token's sizes.

Or, you could select an Auto Layout layer and apply one of the `Spacing` tokens (hint: right-click, two-finger click on a trackpad, will show more options).

Also, the plugin can create styles for you! To do that, click the "Create styles" button near the Color or Typography tokens.

Feel free to check out the [documentation](https://docs.tokens.studio/) for guides on how to do each of the tasks I mentioned.

If you have any other questions, let me know!

**Comment by six7** [comment]
Closing this, feel free to reopen if the issue still persists
