### ISSUE TITLE
Documentation "skips" tokens

### ISSUE THREAD

**Issue by neatlittlemacapps** [six7/figma-tokens#1117]
**Describe the bug**
When inspecting a component, I clearly see multiple color tokens applied.
When using the deep inspect and hitting the documentation function, the resulting annotation does not hold the specific token

**To Reproduce**
1. Go to a nested component with multiple color tokens 
2. Click on deep inspect and create the annotations
3. You'll see the color tokens are missing.

**Expected behavior**
I'd see all color tokens

**Screenshots or Screencasts**
https://www.loom.com/share/3e07e93c616e4ed0b4bbf14e526dcff8

**Comment by six7** [comment]
In the screencast you have `Deep inspect` on, which shows you tokens not only from this layer, but from layers beneath it.

Annotations always only apply what's stored on the current layer.

Thats the reason why there's just 1 color visible, but Inspect shows 2.

**Comment by six7** [comment]
Let me know if that doesn't solve your issue, otherwise I'd close this in a couple days.

**Comment by neatlittlemacapps** [comment]
OK, that businessrule was not clear to me. I thought the annotation would respect the "deep inspect" selection.
Got it.
