### ISSUE TITLE
Collaborators with Read only github permissions cannot sync with a repo that has multiple .json token files

### ISSUE THREAD

**Issue by Design2Well** [six7/figma-tokens#1133]
Closing this, feel free to reopen if the GitHub provided way of defining permissions doesn't suffice.

_Originally posted by @six7 in https://github.com/six7/figma-tokens/issues/1070#issuecomment-1193082353_

------------------------------------------------------------------

Reopening related issue....

Ok, so I have created a second collaborator in our github repo with their role set to Read permissions as you have suggested. They are able to authenticate through the plugin's github integration to the branch but are NOT able to pull the token sets down. We have currently 3 .json files there. None are pulled when a pull request is made.

Based on the documentation it look like multi-file sync requires a Pro license.

Does sync'ing require a Pro license for those that only need Read access to multiple .json files?

**Comment by Design2Well** [comment]
FYI... just tested removing my Pro license and was able to still pull multiple .json files from github. This issue appears to be specific to Read Github user roles only.

**Comment by Design2Well** [comment]
@six7 FYI... we also tested changing the Github role to Read/Write privs today. With Read/Write privs these individuals were able to pull multiple .json files down from the remote Github without the Pro license too. 

So in summary... GitHub repo Read roles currently cannot pull through the latest plugin version as we had hoped and you had suggested in #1070.

Your help here is much appreciated.

**Comment by six7** [comment]
We hopefully fixed this in 114 as we discovered an issue that caused the behaviour you outlined. Let me know if that fixed it for you 🙏
