### ISSUE TITLE
Update to JSONbin not working

### ISSUE THREAD

**Issue by Riki007B** [six7/figma-tokens#1174]
**Describe the bug**
When I add/change token values and Save it (also update it afterwards) these changes are not propagated to JSONbin and I cannot see them in other Figma file.

**To Reproduce**
1. Change token 
2. Save and Update
3. Changes are visible in plugin
4. Go to other Figma file
5. Open plugin
6. Don't see changes
7. Pull from JSONbin.io 
8. Still do not see changes

**Screenshots or Screencasts**
One example:
Changes done in plugin (added transparency):
<img width="447" alt="Screenshot 2022-08-16 at 10 46 10" src="https://user-images.githubusercontent.com/92311150/184837920-7c79a787-e24e-42f3-8c19-cad60a06e910.png">

Visible in other Figma file (transparency not visible)
<img width="433" alt="Screenshot 2022-08-16 at 10 46 27" src="https://user-images.githubusercontent.com/92311150/184838035-8be1cebe-3ea9-4040-8414-3734c33dfc40.png">

**Comment by six7** [comment]
Can you check if `Update remote` is checked? 

<img width="162" alt="image" src="https://user-images.githubusercontent.com/4548309/185054401-a6fea392-5257-4800-a1b8-65b1d8913238.png">

If this isn't checked there won't be any updates

**Comment by Riki007B** [comment]
Unfortunately it is checked :(
<img width="147" alt="Screenshot 2022-08-17 at 9 00 59" src="https://user-images.githubusercontent.com/92311150/185060839-7795c1d7-2f1c-4552-a435-73c59d4aa703.png">

**Comment by Riki007B** [comment]
Finally I found the problem. JSONbin has a limitation for file sizes (I was running on free account). 
I apology for wasting your time.

**Comment by six7** [comment]
Oh i didnt know that! It seems they changed a few things since we worked on the integration. i'll make sure we include that in the Docs!
