### ISSUE TITLE
Composite tokens do not switch when switching between themes

### ISSUE THREAD

**Issue by Design2Well** [six7/figma-tokens#1185]
**Describe the bug**
Plugin Version: 115
Composite tokens do not switch when switching themes (note we verified this was not due to an incorrect token set order)

**To Reproduce**
1. Create a composite token in Theme A
2. Create another composite token in Theme B and change one token within the composite token

**Expected behavior**
When switching between theme A and B any object with the composite token applied should update to reflect its themes' values.

**Theme A (JSON):**
"button": {
  "default": {
    "value": {
      "fill": "{bjc.colors.core.blue.700}",
      "borderRadius": "{bjc.borderRadius.6}",
      "boxShadow": "{bjc.shadow.sm}",
    },
    "type": "composition"
  }
}

**Theme B (JSON):**
"button": {
  "default": {
    "value": {
      "fill": "{bjc.colors.core.green.700}",  **// theme B intends to just change this** 
      "borderRadius": "{bjc.borderRadius.6}",
      "boxShadow": "{bjc.shadow.sm}",
    },
    "type": "composition"
  }
}

Note I think this issue may be similar to another issue overriding a token within a typography token (which is basically a composite token). For example...

**Base Typography token similar to all type tokens used for body and header text**
"type": {
      "p": {
        "sm": {
          "semibold": {
            "value": {
              "fontFamily": "{bjc.fontFamilies.open-sans}",
              "fontWeight": "{bjc.fontWeights.600}",
              "lineHeight": "{bjc.lineHeights.2}",
              "fontSize": "{bjc.fontSize.sm}",
              "letterSpacing": "{bjc.letterSpacing.4}",
              "paragraphSpacing": "{bjc.paragraphSpacing.sm}",
              "textCase": "{bjc.textCase.none}",
              "textDecoration": "{bjc.textDecoration.none}"
            },
            "type": "typography",
            "description": "14px / 0.875rem"
          }
        }
      }
    }

**Base Button Typography token used for just button text**
  "bjc": {
    "type": {
      "p": {
        "sm": {
          "semibold": {
            "button": {
              "default": {
                "value": {
                  "typography": "{bjc.type.p.sm.semibold}",  **// this token refers to Base Typography token above**
                  "lineHeight": "{bjc.lineHeights.1}", **// this is expected to override the value nested within the above typography token**
                  "fill": "{bjc.button.primary.text.default}"
                },
                "type": "composition"
              }
            }
          }
        }
      }
    }
  }
  
**Note I also tried building a composite token with all of the type tokens separately instead of referencing a typography token which did not work.**
    "bjc": {
    "type": {
      "p": {
        "sm": {
          "semibold": {
            "button": {
              "default": {
                "value": {
                  "fontFamily": "{bjc.fontFamilies.open-sans}",
                  "fontWeight": "{bjc.fontWeights.600}",
                  "lineHeight": "{bjc.lineHeights.1}",
                  "fontSize": "{bjc.fontSize.sm}",
                  "letterSpacing": "{bjc.letterSpacing.4}",
                  "paragraphSpacing": "{bjc.paragraphSpacing.sm}",
                  "textCase": "{bjc.textCase.none}",
                  "textDecoration": "{bjc.textDecoration.none}",
                  "fill": "{bjc.button.primary.text.default}"
                },
                "type": "composition"
              }
            }
          }
        }
      }
    }
  }
  
  ...which means the only thing left that I could do is create multiple typography tokens just for lineHeight variations which is not preferred nor address the core issue I think is going on here - namely - that overriding / swapping composite token definitions is not functioning.

**Comment by Design2Well** [comment]
Yes we can chat on the Slack channel. Note though that I think I'm no longer able to repro too.From: Esther Cheran ***@***.***>Sent: Thursday, September 8, 2022, 8:06 AMTo: six7/figma-tokens ***@***.***>Cc: Design2Well ***@***.***>; Mention ***@***.***>Subject: Re: [six7/figma-tokens] Composite tokens do not switch when switching between themes (Issue #1185)
@Design2Well I am unable to reproduce the issue that you have mentioned here. Would it be possible to DM me on our slack channel and I can get more details? Thank you

**Comment by esthercheran** [comment]
Closing the issue after confirming with @Design2Well that it is no longer reproducible.
