### ISSUE TITLE
Typograhy Token → ignores/reorders key value for textCase, paragraphSpacing, textDecoration

### ISSUE THREAD

**Issue by StefanEndress** [six7/figma-tokens#1188]
**Describe the bug**
When you reference a semantic typography token that doesn't have a value for all three of the following tokens → textCase, paragraphSpacing and textDecoration, it doesn't keep the order or basically ignores empty fields.

Please see attached screenshot for more clarity

**Expected behavior**
If no value is set, then field should stay empty. That means if you only define textCase it should keep the value to it's key.

**Screenshot**
![typography token bug](https://user-images.githubusercontent.com/5189598/185393134-7ecfb4aa-5c81-4626-a416-b886e5576d80.jpg)

**Comment by six7** [comment]
@swordEdge can we take this on in the next sprint? Seems like a quick fix, the current implementation needs to be refactored from an array based thing to just showing the keys that we have available with the matching value.
