### ISSUE TITLE
When duplicating a token, renaming it, and changing the value, the name persists, the value does not

### ISSUE THREAD

**Issue by TheeMattOliver** [six7/figma-tokens#1190]
**Describe the bug**

From Slack:

`When duplicating a token, and editing it’s properties. it forgets the value upon saving. Though it does remember the name.`

When I duplicate a token, then rename that token and change the token value, the name is saved, but the value is not.

In order to save the new value, I need to Edit the newly-renamed token as I would any other token.

Context: 
Sometimes it's convenient to use the Duplicate Token feature to build a new token name out the existing token's naming convention, then updating the value. 

**To Reproduce**

1. Duplicate a token
2. Change token name
3. Change token value
4. Observe name persists, but new value does not

**Expected behavior**

Both token value and newly changed token name should persist

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/9900326/185424491-ffcea62d-bdff-4578-a1d2-6cc477af3458.mov

**Comment by six7** [comment]
This should've been fixed in https://github.com/six7/figma-tokens/pull/1179 which will be part of 116 (we'll probably do a bugfix release these coming days)
