### ISSUE TITLE
Allow pulling in multiple "spaces" or files for Tokens

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#12]
Would be great to have multiple "inputs" for tokens, split up files into their different areas, for example a spacing.json with the following structure:

```{
    "name": "Space",
    "tokens": [
        {
            "id": "1",
            "value": { "web": "4px", "ios": "CGFloat = 4.0" }
        },
        {
            "id": "2",
            "value": { "web": "8px", "ios": "CGFloat = 8.0" }
        },
        {
            "id": "3",
            "value": { "web": "16px", "ios": "CGFloat = 16.0" }
        }
    ]
}```

**Comment by color2life** [comment]
A similar idea can be used for theming.
`Theme
   -dark
   -light
`

**Comment by chris-pearce** [comment]
I'm actually using [Style Dictionary](https://amzn.github.io/style-dictionary) to handle this which works quite well. I just need to run a script to convert the Figma Tokens JSON to be in the Style Dictionary JSON format:

**Figma Tokens**

```json
"spacing": {
    "small3x": 4
},
```

→ → 

**Style Dictionary**

```json
"spacing": {
    "small3x": {
      "value": 4
    }
},
```

**Comment by six7** [comment]
Closing this as Themes have landed and no import is planned for multiple spaces right now. I am working on an Export feature however, that would handle splitting up your token sets into multiple files.
