### ISSUE TITLE
[object Object] When applying Raw Value documentation token on Typography tokens

### ISSUE THREAD

**Issue by phantasmagoriadigital** [six7/figma-tokens#120]
It would be great if the object (currently it shows [object Object] in the Figma file) actually shows the whole data as key-value pairs so that it's easy to get all the linked primitives in a single text field one key:value per line.

**Comment by six7** [comment]
Thanks for raising this issue! I encountered it while developing that feature but decided to ship the current version of it and investigate a solution to the [object Object] problem when it occurs.

I think inserting key-value pairs would be the best way, so I would like the text entered to be

```
fontFamily: Inter,
fontWeight: Regular,
fontSize: 24,
letterSpacing: 5%,
...

```

**Comment by phantasmagoriadigital** [comment]
Yes this sounds like a great plan. By the way, we've been using your plugin extensively and would love to help you in furthering this project. There's a bunch of ideas, but rather bounce them in a conversation than making heaps of tickets.

In relation to this ticket though, I was imagining integrating something on the lines of what google sheet sync does for content, if we could do the same for token documentation based on all the existing tokens. For example (simplified):

for color I create a frame with a color dot, color code, token name, etc. I name the layer as #@Colors and this layer is repeated inside an autolayout for as many color tokens as there are. I understand the issue with having levels of colors and tokens, but I'm sure those will be fairly consistent in most design systems, but if a tokens document could be always in sync with the JSON would be great.

I'm coming especially from an Agency perspective, it would be of great valye if we can just load a new JSON into a predefined design tokens documentation template.

Anyways, there's a bunch of ideas and thinking on our end, if you're up for a chat let me know.

Cheers!

**Comment by six7** [comment]
Yes! That's my goal, I started with this quite a while ago in #37 but stopped as that process involved too many guesses on how to style things. I was also thinking of a solution as you mentioned, having an auto layout parent called something like #@Colors and a child frame that serves as a basis for filling this frame with data. Text content such as {name} or {rawValue} or {value} (as layer name) or {description} could be used to insert the token values inside this text frame.

Sure, sounds good! Could you contact me at six.jan@gmail.com so we could discuss further?

**Comment by ptrckschrdtr** [comment]
heya – i just stumbled upon the same behavior while trying to render the values. looks like it's still happening.

**Comment by six7** [comment]
Already fixed on the `next` branch, will be part of the next major release.

https://github.com/six7/figma-tokens/pull/146

**Comment by six7** [comment]
This should be live now, feel free to reopen if it persists
