### ISSUE TITLE
Token Sets (Themes) not working as expected

### ISSUE THREAD

**Issue by edvinlynch** [six7/figma-tokens#121]
Hi there, I'm trying to use the Sets to create different themes, [as shown in your screen recording](https://docs.tokens.studio/token-sets), but it's not working. Or I've just not set it up correctly, in which case, some more documentation would be greatly appreciated because it's a useful feature for what I'm doing currently.

I've tried changing the styles with either Sets selected, but when toggling the Set on it doesn't make the change that I want.

Thanks for this btw, awesome plugin!

**Comment by phantasmagoriadigital** [comment]
@edvinlynch I've been using it for a while in my design system and it's working great. If you could post a short video or screenshots I could probably help you out.

**Comment by phantasmagoriadigital** [comment]
Maybe this helps:

![2021-05-01 09 25 16](https://user-images.githubusercontent.com/61656324/116770173-4fa8a700-aa5f-11eb-9521-038ae2874368.gif)

**Comment by edvinlynch** [comment]
Hey Mike, thanks for trying to help & sharing that screen recording.

I tried recreating exactly what you did, but it doesn't work the same for
me. It's just not updating the colors as I would expect it to… It seems I
haven't set it up correctly? I'm a bit confused about the difference
between checking the box and "selecting" the theme.

Thanks,
Edvin

**Comment by edvinlynch** [comment]
@phantasmagoriadigital Not sure if the video got attached since I replied to the email thread, but here's my screen recording trying to recreate the same steps:

https://user-images.githubusercontent.com/7635078/116774943-e0a66080-aa14-11eb-9bf9-88b00701c92f.mov

**Comment by six7** [comment]
> @phantasmagoriadigital Not sure if the video got attached since I replied to the email thread, but here's my screen recording trying to recreate the same steps:
> 
>  Screen.Recording.2021-05-01.at.12.22.33.AM.mov

Hey Edvin! Are you sure your `success/500` token has a different value? It looks to me like it's the same even in the plugin UI? 

Here's a quick reproduction of the feature:

https://www.loom.com/share/082286d2b5d846beae8a803056e1d456

Also, are your styles local to this document? If styles are found with the same name then the plugin will try to update any styles it finds that match the name.

**Comment by edvinlynch** [comment]
Ah! That's it. Yes, I get it now, each theme has to have different color sets/values in order to work… I totally missed that from the documentation. I thought I could have a "global" color set and simply assign different colors to the other set/theme.

Now I understand how it works, and the example video from the https://docs.tokens.studio/token-sets does show it correctly. Could be helpful to emphasize this in your documentation?

Thanks @six7 !

**Comment by six7** [comment]
Awesome, glad that it's working now 🙏

I will make sure that it's mentioned in the docs, I created an issue over there to address this. https://github.com/six7/figma-tokens-docs/issues/3

Closing this, feel free to reopen if anything's still unclear.
