### ISSUE TITLE
Update button loses unsaved local changes 

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#1216]
**Describe the bug**
Unsaved local changes are lost when update button is clicked and plugin is re-opened

**To Reproduce**
1. Connect to a remote storage. Create a new token or edit a token
2. Click on the `Update` button
3. Close the plugin without pushing the changes to remote and restart it
4. The dialog to recover local changes does not appear and the changes are no-longer available

**Expected behavior**
On restarting the plugin, if there is any changes that are not pushed to remote the dialog to recover local changes should appear. On clicking `Yes` the changes should be available

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/66366384/186089017-1e4f0c23-bc40-4c7e-a017-8c236d1d4c02.mov

**Comment by six7** [comment]
@swordEdge let's work on this from `main` so we can release this before the next major release. This feels like something that is causing frustration.
