### ISSUE TITLE
Uninstalling the plugin does not remove the link to the plugin

### ISSUE THREAD

**Issue by vedam** [six7/figma-tokens#1231]
**Describe the bug**
Even if I delete all set tokens on an element in a file, a link to the plugin is still shown in the right sidebar.
Definitely no tokens set. Saved. Reopened, the sidebar still shows:

<img width="238" alt="screenshot" src="https://user-images.githubusercontent.com/64245/187026866-cb389d7f-7191-4930-90f9-45084d27dd5b.png">

**Expected behavior**
When I uninstall a plugin I don't want to be confronted with the traces of this plugin in my files. Also I have no way to remove these traces, which is unacceptable in my eyes.

Reproducible example:
https://www.figma.com/file/XR2Ln0Yaswn4vje1tWkpEK/remove-token-bug?node-id=0%3A1

**To Reproduce**
Have a look at the size-instances inside the icon-components. Even if I delete the connection to the Plugin and uninstall the plugin, the connection is still showing up on reopening the file.

**Comment by six7** [comment]
Unfortunately there's nothing we can do about that, that's Figma behaviour. Care creating a feature request over at the Figma forums?
