### ISSUE TITLE
Sync local document pointing to an actual file

### ISSUE THREAD

**Issue by wayne-shih** [six7/figma-tokens#1232]
## **Is your feature request related to a problem? Please describe.**

I just want to prefix this ticket by saying this is probably an extreme edge case and I may be the only one? Keen to be proven wrong and if any alternatives / hacks anyone can think of, keen to hear em too!

Currently I'm using the GitHub integration on Figma Tokens with branch switching etc etc. Great stuff! 

1. However it can be a bit daunting when I forget what actual stuff I changed and if I even want to push it as a commit or just pull and start from scratch. (I would need to push, go to github.com to see the code diff, and potentially revert it manually). 
2. Additionally, some organisations I've participated in requires [signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) as their internal policy and practice. This currently can't be done via the GitHub integration. (this is even if a user has configured `~/.gitconfig` with the signing key on their local machine)
3. I've found out that when I push a commit via Figma Tokens the signing email is the "primary" email (https://github.com/settings/emails) aka. your account-related notifications and password resets email. And this can't be changed to another git commit sign-off email.

2 and 3 are far fetched problems which may never be resolved via the GitHub integration. Totally fine and tbh no expectations on it being resolved. 

Proposed solution (below) is a workaround I can see to resolve all 3 pain-points above and hopefully more! 

## **Describe the solution you'd like**

Under _Settings > Token Storage > Local document_ we have an add button (similar to add credential on GitHub tab) where one can point to a local file path of the JSON file. 

How it would work in practice I imagine it to be similar to how GH integration is done. 
However the following functionality will be removed and tweaked name wise... 
```diff
-   1. Branch viewing and branch switching 
+   /** functionality removed **/
-   2. Pull from GitHub
+   2. Reload file / Reset to last saved 
-   3. Push to GitHub
+   3. Save
```
Red is what the current GitHub integration looks like and green is what the potential sync from local document would look like. 

So essentially by doing this I would control pull and pushes to github manually via terminal or github desktop app. This would also allow a user to have multiple "local documents" similar to how one can have multiple repositories and files on github. 

## **Describe alternatives you've considered**

Problem 2 and 3 – our current workaround is to add a github workflow action to re-sign the commit or to disable signed commit requirement on a particular repository. Or re-sign locally and force push it upstream again. Okay for branches but really dangerous when working directly on the master/main branch. 

Problem 1 – other than my laborious (push–view–_revert_) workflow as described above... none I can think of unless we add a diff viewer on the "Push changes" popup model...

## **Additional context**

If this gets implemented I assume it would be a PRO features as it could potentially act as a bypass to get branch switching on a free version. But that's a commercial convo and not really a product feature conversation. That's about it really...

**Comment by six7** [comment]
As much as I'd love this (and I know some teams have requested this!) I don't think it can be done?

Figma plugins have no access to the file system, and so we can't write to a file in the way we'd like to. What we can do is trigger a download like we do in the Import/Export flow, which was hoping to solve that (it's _way_ slower than doing it the way you described, though).

If somebody thinks this can be done, I'd love to include it!

**Comment by six7** [comment]
I think the link you provided is the wrong one, it points to this issue? Also not sure if it's related to this one. I'll close this issue given we just can't support it due to Figma constraints.
