### ISSUE TITLE
Importing outdated styles

### ISSUE THREAD

**Issue by anehls** [six7/figma-tokens#125]
I'm running into an issue where Figma Tokes plugin seems to keep old outdated metadata around. Even after clearing all tokens and then reimporting from Figma, some text styles are still using old values, in my case a font that isn't even available anymore, old letterSpacing, etc ... where Figma clearly has different values for these styles. Even worse, the plugin seems to be changing the actual styles after applying them through the plugin. This makes me believe the plugin is getting this data from some hidden metadata on those layers/styles. Maybe there is a way to just clean all of this cruft when using the "clear" button?

**Comment by six7** [comment]
Could you share a video recording and/or possibly the Figma file with me ? six.jan@gmail.com is the mail.

Would like to be able to reproduce this bug 🤔

**Comment by anehls** [comment]
I won't be able to share the file I'm afraid but I will try to make a recording today.
