### ISSUE TITLE
Suggestion: Current value reference

### ISSUE THREAD

**Issue by nthypes** [six7/figma-tokens#126]
I don't know if this is currently possible. I know that is possible reference current token values, but would be great if we can reference actual sizing values of the element for a token.

i.e:

currently `button-min-width: 2.25 * $some.other.token.value`
suggestion `button-min-width: 2.25 * %current.element.applied.height`

**Comment by six7** [comment]
I like this idea! Users could use it to create aspect ratios as you described.

As it's not directly related to the concept of tokens I'm unsure of when and if we'd like to include that.

Having some sort of placeholder that'll serve as a command to the plugin makes total sense, exposing options such as %element.height %element.width %element.radius etc

The plugin could at a level where it's applying tokens to the layers decide what to do with the data we just received. As we do have the current node available, we also have it's current data such as width, height and so on.

**Comment by six7** [comment]
While I think there's great value in this feature it doesn't align with what can be done with design tokens, which is why I'm closing this issue.
