### ISSUE TITLE
Introduce new Start screen with helpful links

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1261]
In order to provide users a better getting started experience let's change our start screen to something that gives users helpful links and information.

![image](https://user-images.githubusercontent.com/4548309/190957446-cd6629d3-1cde-4e5a-9e99-4bf39d6b8e12.png)

We can get started with just that right column, let's add the left one at a later point.

Links:
Getting started: https://docs.figmatokens.com/getting-started - later on the Tutorial file
Documentation: https://docs.figmatokens.com
Slack: https://figmatokens.com/slack (redirects to slack invite)

**Comment by six7** [comment]
This was shipped as part of V123 🎉
