### ISSUE TITLE
Add support for Asset tokens

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1265]
### Description
Sometimes users want to reference an image to be replaced when switching between brands. As a first start, we should allow them to just point to a URL that we can then fetch.

### Background
```
type: 'asset',
label: 'Assets',
appliedToken: 'asset',
value: The value will be a string pointing to a URL.
placeholder: Public URL of your asset
```

### Applying
Applying this token would have an effect on the `fills`. When applying an asset token we need to fetch the image from the provided source and then apply that as an image fill. If both an `asset` and a color `fill` are present, the `asset` should win.
Related docs: https://www.figma.com/plugin-docs/working-with-images/

**Comment by jpzwarte** [comment]
So we have a slightly different use case: different icons per theme. We want to be able to have different icons in the design system component based on the theme. And use SVGs inside Figma for them (not every product uses FontAwesome).

**Comment by jpzwarte** [comment]
So in our case we would have a place in Figma where the SVG icons are defined. And then using asset tokens, we would "point" the Figma token to the icon "element" on that Figma page??? And Figma Tokens would perhaps serialise the icon inside the JSON?

**Comment by six7** [comment]
This was shipped as part of V123 🎉
