### ISSUE TITLE
Updating tokens in the plugin resets styles sizes/weights

### ISSUE THREAD

**Issue by t-e-lition** [six7/figma-tokens#129]
Every time edit tokens in the plugin it resets all text styles sizes/weights in the Figma file. Please help. See attached before/after screen shots.

![Screenshot 2021-05-20 at 10 52 14](https://user-images.githubusercontent.com/84501353/118950144-37d78b00-b95a-11eb-8734-06a7af30d0dd.png)
![Screenshot 2021-05-20 at 10 52 42](https://user-images.githubusercontent.com/84501353/118950159-3a39e500-b95a-11eb-8d16-b820aeb24ec8.png)

**Comment by six7** [comment]
Can you post your JSON (or only the "Typography/Headings" part) of your JSON? Seems to me like your figma styles have different values than what you have defined in your tokens, so the plugin updates the styles to the values it knows about.

**Comment by t-e-lition** [comment]
Hi, here you go:

 "fontFamilies": {
    "font-gilroy": "Gilroy"
  },
  "lineHeights": {
    "0": 64,
    "1": 52,
    "2": 32,
    "3": 28,
    "4": 30,
    "5": 18,
    "6": 12,
    "7": 46,
    "8": 21,
    "9": 24,
    "10": 16
  },
  "fontWeights": {
    "font-gilroy-0": "Semibold",
    "font-gilroy-1": "Medium",
    "font-gilroy-2": "Regular",
    "font-gilroy-3": "Medium Italic",
    "font-gilroy-4": "Extrabold"
  },
  "fontSizes": {
    "0": 10,
    "1": 12,
    "2": 14,
    "3": 16,
    "4": 20,
    "5": 24,
    "6": 36,
    "7": 42,
    "8": 52,
    "9": 52
  },
  "letterSpacing": {
    "0": 0.2,
    "1": 0.2,
    "2": 0.5
  },
  "paragraphSpacing": {
    "0": 0
  },
  "typography": {
    "Type": {},
    "Type ": {},
    "Body copy": {},
    "type": {},
    "Caption": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-1",
        "lineHeight": "$lineHeights.5",
        "fontSize": "$fontSizes.1",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "caption"
    },
    "Prices": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-0",
        "lineHeight": "$lineHeights.7",
        "fontSize": "$fontSizes.6",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "prices"
    },
    "Error": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-1",
        "lineHeight": "$lineHeights.3",
        "fontSize": "$fontSizes.3",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "error"
    },
    "Quotation": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-4",
        "lineHeight": "$lineHeights.7",
        "fontSize": "$fontSizes.6",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      }
    },
    "In-Text-Link": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-0",
        "lineHeight": "$lineHeights.4",
        "fontSize": "$fontSizes.3",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "in-text-link"
    },
    "Small-Print": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-3",
        "lineHeight": "$lineHeights.6",
        "fontSize": "$fontSizes.0",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "small-print"
    },
    "Body-Copy": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-1",
        "lineHeight": "$lineHeights.3",
        "fontSize": "$fontSizes.3",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "body-copy"
    },
    "Body-Copy-Bold": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-2",
        "lineHeight": "$lineHeights.3",
        "fontSize": "$fontSizes.3",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "Body-Copy-Bold"
    },
    "Body-Copy-Small": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-1",
        "lineHeight": "$lineHeights.8",
        "fontSize": "$fontSizes.2",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "Body-Copy-Small"
    },
    "Type-Fields": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-3",
        "lineHeight": "$lineHeights.9",
        "fontSize": "$fontSizes.3",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "type-fields"
    },
    "Button-title": {
      "value": {
        "fontFamily": "$fontFamilies.font-gilroy",
        "fontWeight": "$fontWeights.font-gilroy-1",
        "lineHeight": "$lineHeights.9",
        "fontSize": "$fontSizes.3",
        "letterSpacing": "$letterSpacing.1",
        "paragraphSpacing": "$paragraphSpacing.0"
      },
      "description": "Button-title"
    },
    "Heading": {
      "H1": {
        "value": {
          "fontFamily": "$fontFamilies.font-gilroy",
          "fontWeight": "$fontWeights.font-gilroy-1",
          "lineHeight": "$lineHeights.4",
          "fontSize": "$fontSizes.9",
          "letterSpacing": "$letterSpacing.1",
          "paragraphSpacing": "$paragraphSpacing.0"
        },
        "description": "h1"
      },
      "H2": {
        "value": {
          "fontFamily": "$fontFamilies.font-gilroy",
          "fontWeight": "$fontWeights.font-gilroy-1",
          "lineHeight": "$lineHeights.5",
          "fontSize": "$fontSizes.8",
          "letterSpacing": "$letterSpacing.1",
          "paragraphSpacing": "$paragraphSpacing.0"
        },
        "description": "h2"
      },
      "H3": {
        "value": {
          "fontFamily": "$fontFamilies.font-gilroy",
          "fontWeight": "$fontWeights.font-gilroy-2",
          "lineHeight": "$lineHeights.7",
          "fontSize": "$fontSizes.7",
          "letterSpacing": "$letterSpacing.1",
          "paragraphSpacing": "$paragraphSpacing.0"
        },
        "description": "h4"
      },
      "H4": {
        "value": {
          "fontFamily": "$fontFamilies.font-gilroy",
          "fontWeight": "$fontWeights.font-gilroy-2",
          "lineHeight": "$lineHeights.6",
          "fontSize": "$fontSizes.6",
          "letterSpacing": "$letterSpacing.1",
          "paragraphSpacing": "$paragraphSpacing.0"
        },
        "description": "h4"
      },
      "H5": {
        "value": {
          "fontFamily": "$fontFamilies.font-gilroy",
          "fontWeight": "$fontWeights.font-gilroy-2",
          "lineHeight": "$lineHeights.0",
          "fontSize": "$fontSizes.5",
          "letterSpacing": "$letterSpacing.0",
          "paragraphSpacing": "$paragraphSpacing.0"
        },
        "description": "h5"
      },
      "H6": {
        "value": {
          "fontFamily": "$fontFamilies.font-gilroy",
          "fontWeight": "$fontWeights.font-gilroy-2",
          "lineHeight": "$lineHeights.0",
          "fontSize": "$fontSizes.4",
          "letterSpacing": "$letterSpacing.1",
          "paragraphSpacing": "$paragraphSpacing.0"
        },
        "description": "h6"
      }

**Comment by six7** [comment]
So in the example of your H3 style: Your H3 token is declared as fontFamily: `$font-gilroy-2`, which is `Regular` with a fontSize of `$fontSizes.7`, which is `42`. 

So in my eyes the plugin is behaving exactly as it should, but your "before" styles are different than the tokens you have setup. You should probably edit your tokens to match your styles (or delete them and hit Import styles again)

Could it be that you expected the plugin to "overwrite" your tokens by hitting the "Import styles" button again? Because right now, once you have styles imported you'd have to manually edit your tokens to reflect changes. In the coming weeks I'll be publishing a more sophisitacted Import feature which allows you to import styles again and choose what changes get imported and what not.

**Comment by t-e-lition** [comment]
Got it. I did expect the overwrite function to kick in but now I see where the problem comes form. Yes this would be amazing if this feature could be added as soon as possible. As we edit our DS constantly, it is impossible to work around this menually every time we update our styles. 

Is there any way to clear all tokens at once instead of deleting them one-by-one?

**Comment by t-e-lition** [comment]
....and would be a way in the near future to export directly to Git. or is there a workaround currently to do so?

**Comment by six7** [comment]
> Got it. I did expect the overwrite function to kick in but now I see where the problem comes form. Yes this would be amazing if this feature could be added as soon as possible. As we edit our DS constantly, it is impossible to work around this menually every time we update our styles.
> 
> Is there any way to clear all tokens at once instead of deleting them one-by-one?

You can go to the JSON Tab and hit the `Clear` button, which effectively deletes all tokens. Or you could edit the JSON and remove the ones you don't need (the JSON is your source of truth).

Got it, would you be interested in participating in the upcoming beta for this version? Would like to get some feedback on that Import process before I release it. If so, could you mail me at six.jan@gmail.com ?

**Comment by six7** [comment]
> ....and would be a way in the near future to export directly to Git. or is there a workaround currently to do so?

I do have that planned! Right now you'd have to set up a webhook with JSONbin so that whenever you update tokens another service gets triggered, but I haven't gone down that route yet

**Comment by six7** [comment]
Created a seperate issue for the Git integration: #134

Closing this, feel free to reopen.

**Comment by t-e-lition** [comment]
Hi Jan

Hope youre doing well. Just watched your recent talk today on you tube, explaining many i=cool things I needed to know actually so thx for that.

Regarding our recent corresponding: “Got it, would you be interested in participating in the upcoming beta for this version? Would like to get some feedback on that Import process before I release it. If so, could you mail me at ***@***.******@***.***> ?
“


I have pointed out that whenever you want to create a new token you have to double-do it on both FT and Figma correspondingly. Are there any news regarding this feature? What is your best practice there recommended?

(btw would love to join the beta testing but I fear I have less time then anyway needed😊)

Looking forward to hearing back

Best

Tal
__

Tal Engel
Senior UX/UI Designer
Mobil: +49(0)1721719366
E-Mail: ***@***.******@***.***>
__________________________________________________
​
***@***.***D711CA.7C64B640]<http://www.lition.de/>
Lition Energie GmbH. Kurfürstendamm 21, 10719 Berlin
Geschäftsführer: Dr. Richard Lohwasser und Dr. Kyung Hun-Ha
Amtsgericht Berlin Charlottenburg HR B 19 3505 B
__________________________________________________
Follow us:
***@***.***D711CA.7C64B640]<https://lition.de/#footer>


From: Jan Six ***@***.***>
Date: Thursday, 20. May 2021 at 15:43
To: six7/figma-tokens ***@***.***>
Cc: Tal Engel ***@***.***>, Author ***@***.***>
Subject: Re: [six7/figma-tokens] Updating tokens in the plugin resets styles sizes/weights (#129)

Got it. I did expect the overwrite function to kick in but now I see where the problem comes form. Yes this would be amazing if this feature could be added as soon as possible. As we edit our DS constantly, it is impossible to work around this menually every time we update our styles.

Is there any way to clear all tokens at once instead of deleting them one-by-one?

You can go to the JSON Tab and hit the Clear button, which effectively deletes all tokens. Or you could edit the JSON and remove the ones you don't need (the JSON is your source of truth).

Got it, would you be interested in participating in the upcoming beta for this version? Would like to get some feedback on that Import process before I release it. If so, could you mail me at ***@***.******@***.***> ?
