### ISSUE TITLE
When swapping themes (in Tokens UI) Figma autolayout spec 'Space Between' flips to 'Packed' 

### ISSUE THREAD

**Issue by vizguy** [six7/figma-tokens#1290]
**Describe the bug**
Upon swapping themes to specified components ('Apply to selection' in tokens UI), the application itself flips Figma autolayout spec 'Space Between' to 'Packed'.

**To Reproduce**
1. 'Apply to Selection' in Tokens UI
2. Select a Component on Figma Canvas
3. Swap themes in Tokens UI

**Expected behavior**
I only am swapping color themes, so expecting only colors to swap, not spacing attributes.  Both themes use the same 'Spacing' tokens.

**Screenshots or Screencasts**
- In screenshot - 'Light theme' is the default theme, when flipping the second line to 'dark theme,' the error occurs.

<img width="936" alt="Screen Shot 2022-09-16 at 1 31 52 PM" src="https://user-images.githubusercontent.com/107507400/190707767-b093c714-a442-42d3-87bf-5bf5c50a3880.png">

**Comment by six7** [comment]
Can you make sure there's no `spacing` token applied on that layer? That behaviour only appears when there's a spacing token applied on auto layout layers currently.

Best to include a screenshot of the `Inspect` tab with `Deep inspect` on and one of those card layers selected.
