### ISSUE TITLE
Add color to the typography category or possibility to use compositions as aliases.

### ISSUE THREAD

**Issue by ian-schechter** [six7/figma-tokens#1292]
**Is your feature request related to a problem? Please describe.**
Hey y'all! Our typography styles and their variants are paired with color. It's always bummed me out we aren't able to pair color to type styles in Figma (and maybe that's the blocker). To get around it I've set up our type styles as "compositions" but now I'm blocked by applying a type style to a component's token because I can't use compositions as aliases :(

**Describe the solution you'd like**
Add color as something we can tie to typography or allow compositions to be used as aliases.

Thanks y'all! This plugin is amazing

**Comment by six7** [comment]
You could create a composition token that contains `typography` that equals that style and then also add a `fill` property, you'd do that for each and every style you want created.

**Comment by six7** [comment]
You could create a `composition` token that contains a `typography` and a `fill` decision, you could do that for every typography variation to get the result you need :+1:

**Comment by ian-schechter** [comment]
Hey @six7 thanks for the tip! We were doing it that way but realized it was more efficient for us and less tokens to just link up the tokens from the `typography` category and the `color` category separately in Figma rather than creating the composition token of both of them. Thanks again though 🙏

**Comment by six7** [comment]
Closing this as we probably wont include color in the typography tokens - they're also not including color in the w3c format typography tokens
