### ISSUE TITLE
Duplicate A Nested Folder In A Specific Location

### ISSUE THREAD

**Issue by stephen-salyer** [six7/figma-tokens#1300]
In this example i would like to duplicate the typography folder in primary over to secondary and change its values but keep the naming structure.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/39383255/191325165-6383a447-4e55-41a7-a1ee-96dae849cf32.png">

**Comment by six7** [comment]
And you'd like to do that only in the current set, or would you like to choose the set as well?

**Comment by stephen-salyer** [comment]
Current for this example. Like how one token can be click and drag. Doing the same for a token set would be cool.

**Comment by six7** [comment]
We'll probably support this in another way over with https://github.com/six7/figma-tokens/issues/1411 - you'd be able to rename the typography token after duplicating so you can place it in the secondary set.
