### ISSUE TITLE
Unable to assign colours

### ISSUE THREAD

**Issue by engegu** [six7/figma-tokens#1307]
**Describe the bug**
I am unable to assign color values from a previously working token set. As you can see from the screenshot everything is fine except for the color not changing, if I inspect the correct token Is shown. There are no broken refrences, and all aliases resolve correctly. non-colour values are assigned as expected.

**To Reproduce**
Try to assign a color to an unstyled rectangle (or anything else for the matter) by clicking or right clicking and choosing what to assign.

**Expected behavior**
Color changes and correct style is applied

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/38129827/192102361-5b8195e4-3d97-4fe4-8cac-21568c95bb78.png)
![image](https://user-images.githubusercontent.com/38129827/192102714-5d8e5c71-8c29-4187-9ea8-a763cbf6f247.png)

**Comment by six7** [comment]
Can you paste the color value of that token?

**Comment by engegu** [comment]
Sure, it resolves fine… everything works except the color changing. It gets everything correct for documentation tokens too

![image](https://user-images.githubusercontent.com/38129827/192149808-1204f4dd-5153-4ce5-9b6a-0447b58a37ab.png)

**Comment by six7** [comment]
We've been unable to reproduce so far.. if you have a file where this happens do you mind sharing that one with us?

**Comment by engegu** [comment]
Had a chat with Mike on Slack earlier today and sent him a .fig and more info re this issue

**Comment by engegu** [comment]
So it seems :)
