### ISSUE TITLE
Tokens not applying

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#1316]
**Describe the bug**
When styles are created from the plugin. The sets that were created and deleted, do not apply on the canvas.

**To Reproduce**
1. Create a theme, don't set any set as source
2. Create styles from the plugin
3. Delete a set of styles (example core)
4. Apply any token from that set (core)
5. The appearance on the canvas does not change
6. On inspect, the tokens are applied but changes cannot be seen on the Figma canvas

**Expected behavior**
Applying tokens should always reflect on the Figma canvas

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/66366384/193522256-7ea463d8-47fa-4d39-940a-2b52cf6b40ff.mp4

**Comment by six7** [comment]
@esthercheran there is no video attached
