### ISSUE TITLE
Found error converting to Style-dictionary

### ISSUE THREAD

**Issue by diehendrick** [six7/figma-tokens#1318]
**Describe the bug**
I got an error when I use tokens, that I upload to github.  and pull to editor.  build as SCSCC using style-dictionary. 

**To Reproduce**
1. Upload tokens to github repo. 
2. Pull repo to my project on visual studio. 
3. setup config.js from style-dictionary
4. hit command on git-bash "style-dictionary build"

**Expected behavior**
my expectation it was no issue as default, when I generated using style-dictionary. 

**Screenshots or Screencasts**
here is the generate result: get an error
![image](https://user-images.githubusercontent.com/1661591/193636163-514d6219-09f2-4d37-a5ac-7dc8d111c841.png)
here is config.js as default setting from style-dictionary
![image](https://user-images.githubusercontent.com/1661591/193636338-eb277978-3d38-4ea0-90bc-917a16115304.png)

** another case without error.
I tested and export manual and uncheck global parent key on json.  no upload to github. 
![image](https://user-images.githubusercontent.com/1661591/193636668-60a10316-6e78-48e8-ae4b-bc1c16d4de58.png)

and no issue. 

**Question**
is the issue from figma tokens JSON? or from style dictionary?   
I follow step by step from style-dictionary without change the command parameter.  FYI. 

Thanks,
Dei.

**Comment by six7** [comment]
If you're syncing to a single file then you'll need to split your json file into individual sets before passing them into style dictionary.

You can do that in the plugin in Export or by using a script that just takes the first level keys and takes those contents into their own files.

Otherwise you'll have the set names as part of the file you pass into style dictionary, which expects a regular token file without set names.

**Comment by diehendrick** [comment]
I am not expert in coding, but I want to learn in practical how to use tokens and convert it. if you don't mind can you share the script and split it, please..  really apricate it.  thank you.

**Comment by six7** [comment]
https://gist.github.com/six7/ddb9b1f0d0c6e434be4f1cdb8bfe56e1

Running this file splits a tokens.json dir into the 'tokens' directory, each set becoming a file in it.

**Comment by diehendrick** [comment]
Thanks!, it worked.

**Comment by six7** [comment]
Awesome! Closing this 👍
