### ISSUE TITLE
Iteration Plan for November 2022

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1334]
### Dates
**Start iteration:** _24-10-2022_
**End iteration:** tba
**Beta testing from:** tba

### Sprint Goals
- Performance and reliability

Legend of annotations:
Mark | Description
-- | --
🔺 | P0 - first to to be worked on
💪 | Stretch goal for this iteration
🕜 | In Progress
⛔ | Blocked
🤞 | To be released

**Comment by six7** [comment]
Shall we fill this up with issues now that it's started?
