### ISSUE TITLE
Add sync with Git

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#134]
It would be great if users could sync their tokens to a Git repository.

However, we wouldn't want every token change to generate a commit, we'd possibly want to batch our token changes.

This would require some sort of interface when Git has been chosen as a Sync provider where users could then see all "non-synced" changes, add a commit message and then have the option to upload the changes similar to Figma's native Publish dialog.

## Batch-token changes
We need users to be able to batch their token changes into one commit instead of one commit per change

## Custom commit messages
- Users should be able to add a commit message

## Configuration
- Users should be able to specify which target (GitHub, GitLab, etc)
- Users should be able to specify a branch - default would be `main`

## Merge conflict
So we dont run into merge conflicts it would be easiest if we force the user to pull newest tokens if the remote has changes before pushing their changes.

**Comment by leonardoferreiradg** [comment]
Hey @six7 . I have one example here:
https://github.com/lukasoppermann/design-tokens/raw/main/_resources/settings.png

One of FigmaTokens players did that: https://github.com/lukasoppermann/design-tokens

**Comment by six7** [comment]
One thing that we need that the mentioned repo doesnt do is two-way sync. We need to be able to pull tokens in, not just push them to a repo.

That brings a bit more complexity, but codewise its a great start!

**Comment by six7** [comment]
Updated description to match new requirements.

**Comment by thomasoreilly** [comment]
Sounds like a great feature @six7. 

Would be great to be able to generate different formats such as less, json, sass etc. And even the option to package up and deploy to a registry such as NPM. Not sure if that's within the scope of this or even if it's a feature already.

**Comment by electroheadfx** [comment]
> Sounds like a great feature @six7.
> 
> Would be great to be able to generate different formats such as less, json, sass etc. And even the option to package up and deploy to a registry such as NPM. Not sure if that's within the scope of this or even if it's a feature already.

Use Style Dictionary for convert everythings from json : https://amzn.github.io/style-dictionary

**Comment by thomasoreilly** [comment]
> > Sounds like a great feature @six7.
> > Would be great to be able to generate different formats such as less, json, sass etc. And even the option to package up and deploy to a registry such as NPM. Not sure if that's within the scope of this or even if it's a feature already.
> 
> Use Style Dictionary for convert everythings from json : https://amzn.github.io/style-dictionary

Thanks for this @electroheadfx, I wasn't aware of this lib. 

On a separate note, @six7 would this feature support Github Enterprise?

**Comment by six7** [comment]
> > > Sounds like a great feature @six7.
> > > Would be great to be able to generate different formats such as less, json, sass etc. And even the option to package up and deploy to a registry such as NPM. Not sure if that's within the scope of this or even if it's a feature already.
> > 
> > 
> > Use Style Dictionary for convert everythings from json : https://amzn.github.io/style-dictionary
> 
> Thanks for this @electroheadfx, I wasn't aware of this lib.
> 
> On a separate note, @six7 would this feature support Github Enterprise?

I'll have to dig deeper into the requirements for GitHub Enterprise, ideally it will but I can't promise it'll land in v1 of that feature

**Comment by six7** [comment]
To anyone wanting to test this, a beta has just been released, information can be found here: https://figma-tokens-docs-git-git-sync-beta-six7.vercel.app/sync/github
