### ISSUE TITLE
Auto layout resets resizing to fixed height and width

### ISSUE THREAD

**Issue by senthil87** [six7/figma-tokens#135]
Hi,

When we change from one spacing value to other value using tokens, the auto layout resizes to fixed height and fixed width rather than following the "Hug contents" which was already chosen. Its so annoying that every time we change, we have to fix it manually.
<img width="257" alt="Screenshot 2021-05-27 at 5 52 11 PM" src="https://user-images.githubusercontent.com/5101306/119825139-47d00b80-bf14-11eb-8219-006f1382bc29.png">

Also, when we edit the spacing value of MD from 16 to 24 and click on Update, it just resets all the components which are using that particular token. You can understand that we have to fix at all those numerous places in the design. :(.

 This issue was not there in the previous release, this happened with a recent update (Not sure about the number).

**Comment by six7** [comment]
This sounds odd, nothing regarding Auto Layout behaviour was changed. Will investigate tomorrow. You dont by chance have a screen recording documenting that weird behaviour? That could help a lot.

**Comment by senthil87** [comment]
I have attached the screengrab here. Please take a look. Actually it resets, whenever I change any property. Just now noticed that even changing the color resets it.[](url)

https://user-images.githubusercontent.com/5101306/119920970-d7180600-bf8a-11eb-9964-7fb70402f3a4.mov

**Comment by six7** [comment]
> I have attached the screengrab here. Please take a look. Actually it resets, whenever I change any property. Just now noticed that even changing the color resets it.
> 
>  ScreenGrab-.Autolayout.issue.mov

Thanks for the screengrab!

You do have a `sizing.lg` token set on your layers , remove that token from the layer and everything will work again.

Why does this happen? Whenever you set an auto layout layer that has Hug contents set to a specified width it will reset to "Fixed width". This is behaviour that comes from Figma, not from the plugin. It's perfectly correct as well, as you basically tell the plugin to keep that layer to a specified size, so it will do just that. In your example the `sizing.lg` layer is set to a size of 48, so your layers become resized to that size.

Closing this, feel free to reopen if it still persists.

**Comment by senthil87** [comment]
Thank you for the clarification. Works fine after removing the sizing token.
