### ISSUE TITLE
WIP: When combining token sets, sub groups disappear from the UI 

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1362]
**Describe the bug**
When combining token sets with sub groups, the sub groups disappear from the UI. They are still present in the JSON.

**To Reproduce**
1. Create a token group 'X'
2. Create a token group 'Y' with a subfolder
3. Rename token group 'Y' to 'X'
4. The tokens in group 'Y' will be shown in token group 'X' in UI, but the subfolder doesn't show.

**Expected behavior**
Combine the token groups and show the subfolder in UI and json.

**Screenshots or Screencasts**
https://drive.google.com/file/d/1ZkemIURk4kL3iGAjk8SQ_VQANgkbzyhT/view?usp=sharing

**Comment by six7** [comment]
@rbosker is this still 'WIP'?
