### ISSUE TITLE
It is not setting the styles into figma document.

### ISSUE THREAD

**Issue by TBrayner** [six7/figma-tokens#1367]
1- Create a token
2- Select "Style/Create Style"
3- mark all the options
4- press create

(apply to document selected)

Nothing happens

**Comment by six7** [comment]
> 1- Create a token 2- Select "Style/Create Style" 3- mark all the options 4- press create
> 
> (apply to document selected)
> 
> Nothing happens

Make sure that the token set is activated (checkbox)

![image](https://user-images.githubusercontent.com/4548309/197366070-f36db0e3-f184-4e0f-9f08-dc3077bb9c83.png)

**Comment by six7** [comment]
Closing this as my suggestion will probably solve this, if not please feel free to reopen.
