### ISSUE TITLE
Support for different FigmaTokens titles (minor fix)

### ISSUE THREAD

**Issue by leonardoferreiradg** [six7/figma-tokens#137]
**Nowadays I need follow the naming structure of FigmaTokens to my job works fine.**

When I'm working in Figma and try propose alternative titles for tokens, I have some problems... For example:

I have Box Shadow tokens....

If I change the name in Json file for box-shadow, the plugin doesn't work in Figma, because it doesn't understand the tokens in JSON and hidden the values._

**My suggestion is use some common variations of tokens.** 

Example: Box Permission to rename for shadow, BoxShadow, boxShadow and Boxshadow (commun cases)

**Comment by six7** [comment]
The next branch basically fixes this by introducing `type` properties, so you could name your tokens however you want, as long as the have a matching type prop.

That will also fix this issue in an even more flexible way.
