### ISSUE TITLE
Tokens synced to Github don't include parent key, which breaks token-transformer

### ISSUE THREAD

**Issue by nicollecastrog** [six7/figma-tokens#1375]
**Describe the bug**
I have two token sets, `Core` and `Custom` which are synced to Github. In the Figma UI, if you manually export a token set, you get the option to "include parent key":

![image](https://user-images.githubusercontent.com/5670279/197584117-ae123c5d-16d6-4112-b666-f7959fff8001.png)

However, this isn't an option when you set up the Github sync. This is a problem because **`token-transformer` _expects_ there to be a parent key** that it strips as part of its logic. When there isn't, referencing breaks.

**To Reproduce**
1. Take this simplified version of my `Core` token data, as synced to Github (ie: without a parent key):

```json
{
  "color": {
    "primary": {
      "main": {
        "value": "#C8102E",
        "type": "color"
      },
      "light": {
        "value": "#F9E7EA",
        "type": "color"
      },
      "dark": {
        "value": "#A00D25",
        "type": "color"
      },
      "contrastText": {
        "value": "{color.common.white}",
        "type": "color"
      }
    },
    "common": {
      "black": {
        "value": "#000000",
        "type": "color"
      },
      "white": {
        "value": "#FFFFFF",
        "type": "color"
      }
    }
  }
}
```

2. Save the above to `Core.json`. Then run `npx token-transformer ./Core.json ./transformed/Core.json` (replace input and ouput paths as needed for your filesystem)

3. Note the failure in the transformation (`failedToResolve`):

```json
{
  "primary": {
    "main": {
      "value": "#C8102E",
      "type": "color"
    },
    "light": {
      "value": "#F9E7EA",
      "type": "color"
    },
    "dark": {
      "value": "#A00D25",
      "type": "color"
    },
    "contrastText": {
      "value": "{color.common.white}",
      "type": "color",
      "failedToResolve": true
    }
  },
  "common": {
    "black": {
      "value": "#000000",
      "type": "color"
    },
    "white": {
      "value": "#FFFFFF",
      "type": "color"
    }
  }
}
```
... the `"color"` key is clearly being viewed as the "parent key" and being stripped out by `token-transformer`, which then breaks the `color.common.white` referencing.

4. Add a `"Core"` parent key to `Core.json`:

```json
{
  "Core": {
    "color": {
      ...
  }
}
```

5. Run the transform again and note that the resulting JSON now has no `failedToResolve` tokens 🎉 

**Expected behavior**
Given that, as I understand it, there's no good way for `token-transformer` to know if the top-level key is a parent key or a "proper" key, I get that by default it assumes the former and strips it out. So, if that's the case, then I expect the Figma Tokens Github sync to _include_ the parent key by default and/or allow the parent key to be included in the Github sync settings (much like in the manual export settings)

**Comment by six7** [comment]
You can pass a `folder` to token-transformer instead of the file. That will treat the filename as the `parent key`.

So in your example, you'd type

`npx token-transformer . transformed/Core.json`

however i'd advise to point it to a folder containing all the sets

`npx token-transformer foldername transformed/Core.json`

**Comment by nicollecastrog** [comment]
Thanks for getting back to me @six7! That sounds like a nice way around it, however I'm weirdly getting a `SyntaxError: Unexpected token  in JSON at position 0`. I've run both of my token JSON files through several JSON validators and its definitely correct JSON...

The output is in one file, correct? So the below command is correct, right?

`npx token-transformer ./themes/figma-tokens ./themes/style-dictionary/properties/output.json`

**Comment by six7** [comment]
yes, that should work and output is one file. is there possibly some error in that json input file? seems like it's having trouble parsing it. any chance you could upload it ? maybe i could take a look

**Comment by nicollecastrog** [comment]
Ahhh sorry, this one is on me, there was a sneaky `.DS_Store` file in my input directory that was causing the JSON error above. Once I removed that, it worked fine.

That said, it'd still be great if we could include the parent key when sycning the tokens to Github, as we have reason to want to transform each token file separately, so then we can't rely on the folder name to act as the parent key.

**Comment by six7** [comment]
How about an option in transformer that treats the file name as the parent key? I dont think we'll implement a different sync behavior but I understand your use case.

**Comment by justinmarsan** [comment]
Hello, I'm facing the same issues : we're using set to split components tokens and global tokens, in manual export we can chose to "Include parent key" but there doesn't seem to be a way to do that in the CLI transformer.

This pretty much removes our most important level of nesting. Would it be possible to add this as an option in the CLI as is done for the --expandTypography options maybe ?

I tried writing an attribute transform in style-dictionary but when in a transform the structure or the set is completely lost and have not found any way around it.

**Comment by six7** [comment]
Can you create a dedicated issue for this @justinmarsan ? It feels like it's slightly different than the use case described hered.
