### ISSUE TITLE
Paragraph indent as a single token

### ISSUE THREAD

**Issue by denkwerk-ui-team** [six7/figma-tokens#1389]
**Is your feature request related to a problem? Please describe.**
It's complicated and redundant to have an extra typography style everywhere just to have extra paragraph indent. 

**Describe the solution you'd like**
A separate single token to apply like Paragraph Spacing or Text Decoration would be great.

**Comment by six7** [comment]
We'll let you use `dimension` tokens for this in the next (major) release, but there won't be a dedicated token for paragraphIndent.
