### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by qvsoft** [six7/figma-tokens#139]
This plugin is great, thank you so much. While trying to apply this plugin to my design, i got some issues:
1. I use this plugin to control token of my components only(few special cases with instances), but when i set token to components, then apply changes to whole document, it override the property of instances also, so i lost the control by change property in component -> instance is not inherited from parent component changes. This issue seems only happens with big UI System with hundreds of components. I tried with empty file then create few components and instances, it seems to working properly, but when i try with big file like this UI System(it takes me ~10min when change any value if i set to change in whole file), then the override error happens(try to duplicate this file and apply token you will see the issue): https://www.figma.com/file/WgaMLq0tu7Wf9Kz64zdBm0/Ant-Design-Open-Source
2. If token name change, then its settings on applied elements will be lost, is there anyway to keep changes on applied elements when change token name?
3. It's good if we can have option to select pages to apply changes(or ignored pages that will not be applied), i want to apply the change with all pages(which contain components), except the layout page(where i create the website from components from other pages).
4. Is there any way i can manage all the elements that i applied the token. Eg: Create a token named: Radius 5px, then apply this token to 50 elements. It's good if i can select token "Radius 5px", then list/select all elements that applying this token.
5. Is there any way i can create kind of short cut to apply token, eg: Create a token named: Radius 5px, then assign short cut Ctrl + R + 5, then with any element that i want to apply this token, just select it and press short cut keys.

**Comment by qvsoft** [comment]
And when i selected an element that applied token, eg applied border radius, i only see **Plugin** - Tokens - borderRadius at the bottom right of figma, without details. And if i open the plugin i see the token highlighted(need to right click to see which value is applied). It's better if i can see more details when i click on element, eg: borderRadius 2px 4px 4px 2px in both figma and plugin config.

**Comment by qvsoft** [comment]
I got another issue, using the file above as an example:
1. I create a token Radius 5px, then apply for all buttons in button page.
2. I go to Modal page, then apply token Radius 5px to all modals, but in this page has some instance of button, i just select modal, dont select any button, but it seems apply token Radius 5px to all instances of button. When i come back to button page and change radius of button to 10px, but all buttons(instances) in Modal page still 5px, i lost the control by component to these instances. If i want to get control by component again with these instance, i need to select all instance then click on [Reset others] at the right panel to reset some override on these instance.
3. Please help to resolve this issue, i want to apply token to components and don't want to touch to instances, so with tokens, i can control over all components using the same value to keep UI System consistent. Instances should be as it is, so it will inherit all changes from parent component.

**Comment by six7** [comment]
> This plugin is great, thank you so much. While trying to apply this plugin to my design, i got some issues:
> 
> 1. I use this plugin to control token of my components only(few special cases with instances), but when i set token to components, then apply changes to whole document, it override the property of instances also, so i lost the control by change property in component -> instance is not inherited from parent component changes. This issue seems only happens with big UI System with hundreds of components. I tried with empty file then create few components and instances, it seems to working properly, but when i try with big file like this UI System(it takes me ~10min when change any value if i set to change in whole file), then the override error happens(try to duplicate this file and apply token you will see the issue): https://www.figma.com/file/WgaMLq0tu7Wf9Kz64zdBm0/Ant-Design-Open-Source
> 2. If token name change, then its settings on applied elements will be lost, is there anyway to keep changes on applied elements when change token name?
> 3. It's good if we can have option to select pages to apply changes(or ignored pages that will not be applied), i want to apply the change with all pages(which contain components), except the layout page(where i create the website from components from other pages).
> 4. Is there any way i can manage all the elements that i applied the token. Eg: Create a token named: Radius 5px, then apply this token to 50 elements. It's good if i can select token "Radius 5px", then list/select all elements that applying this token.
> 5. Is there any way i can create kind of short cut to apply token, eg: Create a token named: Radius 5px, then assign short cut Ctrl + R + 5, then with any element that i want to apply this token, just select it and press short cut keys.

1. I'd advise to not apply changes to the whole document, except you're certain that the tokens you set are the ones you want. I would work in smaller pages (less objects on a page the faster the plugin can run), and when I'm happy with my Tokens then apply to whole document (which can take its time as you said, but there's not a lot we can do as we have to traverse each and every layer to find references to tokens)
2. Right, that's not ideal. It would be best if the plugin could scan the page for "lost tokens", that have no reference any more, and users could choose which token they want to replace the "not found token" with.
3. Selecting which pages to not apply tokens to is probably not on the roadmap, currently there's #123 that enables "Apply to selection", but that only applies to whatever you have selected on your current page.
4. You could always use the "Similayer" plugin to select all with same properties and then apply the token to all that you have selected (Tokens will apply your token to all selected layers)
5. Unfortunately not right now, but I'll try to integrate a "Apply last used token" maybe, that could save a lot of time

**Comment by six7** [comment]
> I got another issue, using the file above as an example:
> 
> 1. I create a token Radius 5px, then apply for all buttons in Button page.
> 2. In button page i only select variants of component of button, dont select any instance of button, but it seems apply token Radius 5px to all instances of button. When i change radius of button to 10px, but all instances still 5px, i lost the control by component to these instances. If i want to get control by component again with these instance, i need to select all instance then click on [Reset others] at the right panel to reset some override on these instance.
> 3. Please help to resolve this issue, i want to apply token to components and don't want to touch to instances, so with tokens, i can control over all components using the same value to keep UI System consistent. Instances should be as it is, so it will inherit all changes from parent component. This happens in some case i update token in Page, if i update token in document, it always happen, but with almost of instances, not all the instances.
> 
> And another suggestion, if a frame has border radius 2px, i apply token 5px, then it changes to 5px, but if i remove the token, it return 0px. Is there anyway we can remember the value before apply token, if token removed then we rollback to original value. Note: If this is an instance, then 2px inherit from its component also different than 2px override by instance(will lost control of inherit from its master component)

I've been thinking of allowing this as a setting. So users could choose to either "update instances" or "dont update instances". That choice would be saved for future plugin launches.

Regarding the other suggestion: Yes I think the whole setting values to 0 is something we can get rid of, I think it would be very much OK to just leave the value as-is, but just remove the token..

Closing this, feel free to reopen (will create seperate issues that mention this one so you can keep track)

**Comment by qvsoft** [comment]
Thanks Six7,
I just want to reopen this ticket to reply your answer to make it more clear:

> I'd advise to not apply changes to the whole document, except you're certain that the tokens you set are the ones you want. I would work in smaller pages (less objects on a page the faster the plugin can run), and when I'm happy with my Tokens then apply to whole document (which can take its time as you said, but there's not a lot we can do as we have to traverse each and every layer to find references to tokens)

This is not just the time to execute the plugin in whole document, it's also about of lost control on the instances, i can not find the rule or replicate it exactly when it can happen, i have hundreds component in my file, but when i apply for whole file, i lost control on almost of instances, not all, some of them still look good(can be override by main component). It seems happen randomize, so after 2 days spent on tweak my tokens, then i found this issue and didn't want to use the file that i was editing then i rolled back to file 2 days before, because i'm afraid that plugin could breaks my file and i don't know what are instances has been changed, what are not. My 2 days lost :(

> Right, that's not ideal. It would be best if the plugin could scan the page for "lost tokens", that have no reference any more, and users could choose which token they want to replace the "not found token" with.

What do you think if the plugin generate an unique key that used to link with token, and the name of token just link with the that unique key, so we can change the name as we want but still keep the connection with token, because the reference is the unique key.

Selecting which pages to not apply tokens to is probably not on the roadmap, currently there's #123 that enables "Apply to selection", but that only applies to whatever you have selected on your current page.
> I think that would be good, because i face the #1 problem above even in case i apply token to current page. Hope you can figure out what's the problem of instance also be applied token from main component.

> You could always use the "Similayer" plugin to select all with same properties and then apply the token to all that you have selected (Tokens will apply your token to all selected layers)
Similayer not work exactly in this case, eg: i have 100 frames with round border radius 5px, but just 50 of them from applied token. Then no way to just find 50 frames applied token to change to another token or remove token. Need to click on one by one then see what kind of token has been applied.

> Unfortunately not right now, but I'll try to integrate a "Apply last used token" maybe, that could save a lot of time
It's a good idea, also please specify the name of last used token, then we can confidence to apply.

> I've been thinking of allowing this as a setting. So users could choose to either "update instances" or "dont update instances". That choice would be saved for future plugin launches.
That's great if we can combine this with "Apply to selection", so we can limit where the plugin will be applied to make it faster and avoid any token accidentally applying.

**Comment by six7** [comment]
> Thanks Six7,
> I just want to reopen this ticket to reply your answer to make it more clear:
> 
> > I'd advise to not apply changes to the whole document, except you're certain that the tokens you set are the ones you want. I would work in smaller pages (less objects on a page the faster the plugin can run), and when I'm happy with my Tokens then apply to whole document (which can take its time as you said, but there's not a lot we can do as we have to traverse each and every layer to find references to tokens)
> 
> This is not just the time to execute the plugin in whole document, it's also about of lost control on the instances, i can not find the rule or replicate it exactly when it can happen, i have hundreds component in my file, but when i apply for whole file, i lost control on almost of instances, not all, some of them still look good(can be override by main component). It seems happen randomize, so after 2 days spent on tweak my tokens, then i found this issue and didn't want to use the file that i was editing then i rolled back to file 2 days before, because i'm afraid that plugin could breaks my file and i don't know what are instances has been changed, what are not. My 2 days lost :(

Sorry to hear that! The only valid solution would indeed be to add this setting, because I do see the use case for overwriting instances. Ideally, Figma would know when I set a fill color to the same as the main component has and not treat it as an Override anymore, but that's not the case..

> > Right, that's not ideal. It would be best if the plugin could scan the page for "lost tokens", that have no reference any more, and users could choose which token they want to replace the "not found token" with.
> 
> What do you think if the plugin generate an unique key that used to link with token, and the name of token just link with the that unique key, so we can change the name as we want but still keep the connection with token, because the reference is the unique key.

That would remove the capability of just copying layers, pasting it into a document with different tokens as a source and then getting it "re-themed". But I understand your point, and I have thought about this before as well. But ultimately decided that layers would benefit more from being coupled to a specific decision rather than a token id. Maybe we re-evaluate that in the future though!

> 
> > Selecting which pages to not apply tokens to is probably not on the roadmap, currently there's #123 that enables "Apply to selection", but that only applies to whatever you have selected on your current page.
> 
> I think that would be good, because i face the #1 problem above even in case i apply token to current page. Hope you can figure out what's the problem of instance also be applied token from main component.
> 
> > You could always use the "Similayer" plugin to select all with same properties and then apply the token to all that you have selected (Tokens will apply your token to all selected layers)
> 
> Similayer not work exactly in this case, eg: i have 100 frames with round border radius 5px, but just 50 of them from applied token. Then no way to just find 50 frames applied token to change to another token or remove token. Need to click on one by one then see what kind of token has been applied.

Got it, that makes sense! Kind of a "Select all layers with that token".

> > Unfortunately not right now, but I'll try to integrate a "Apply last used token" maybe, that could save a lot of time
> 
> It's a good idea, also please specify the name of last used token, then we can confidence to apply.

Unfortunately that's not possible :/ Can't write anything dynamic in that context menu

> > I've been thinking of allowing this as a setting. So users could choose to either "update instances" or "dont update instances". That choice would be saved for future plugin launches.
> 
> That's great if we can combine this with "Apply to selection", so we can limit where the plugin will be applied to make it faster and avoid any token accidentally applying.

**Comment by qvsoft** [comment]
> That would remove the capability of just copying layers, pasting it into a document with different tokens as a source and then getting it "re-themed". But I understand your point, and I have thought about this before as well. But ultimately decided that layers would benefit more from being coupled to a specific decision rather than a token id. Maybe we re-evaluate that in the future though!

What do you think if in the case we copy layer(with tokens) to another file, then the id will not be found, we can run a function to find invalid id, then allow user to map it with another token (Auto suggest token if there is a same name token)? Or if when we change the token name, we search for all layers that applied that token then remap them with new token name(must be unique). If change the name of token will be the cause of applied token lost control, then we should let user know to thinking carefully when they create new token, and when they change the token name to know what will happen.

> Got it, that makes sense! Kind of a "Select all layers with that token".

Yes, it's kind of "Saved selection" or "Select layer by token name", i think this could be very useful and we will use this often, eg: Apply new tokens for layers with a specific token, Remove applied tokens, Change value of token on Selections, To see what layers has been applied token and reoptimize them,...

> Unfortunately that's not possible :/ Can't write anything dynamic in that context menu

So better to put the message after token applied, eg: Successfully applied token "Token Name", because with one run, plugin can change on mass layers, so if we see the name of token applied, it make us more confidence of what's done. Just better UX :)
