### ISSUE TITLE
Allow add transparency value for colors

### ISSUE THREAD

**Issue by exclama** [six7/figma-tokens#14]
i'we tried to add rgba ou hexadecimal with alpha values, but this broke the plugin :O

**Comment by six7** [comment]
Thanks for raising this issue! Got a fix ready, will publish in the evening!

**Comment by six7** [comment]
Fixed and published! You can now enter:

`#fafafa` (hex)
`#fafafa80` (hex with alpha)
`rgb(255,255,0)` (rgb)
`rgba(255,255, 0.5)` (rgba)
