### ISSUE TITLE
Color Group update error

### ISSUE THREAD

**Issue by qvsoft** [six7/figma-tokens#140]
Steps to replicate:
1. Create new Token set
2. Import Styles
3. Change color value from Figma Tokens Plugin
-> Color NOT in a folder, eg: Primary, it will be updated in Figma accordingly, working fine
-> Color IN a folder, eg: Red/1 will not be updated, instead of that it will create a new color in Figma Color Styles with the same name. If before applying Token set, i click on name of each color then enter(do nothing), then plugin will recognize the color then update correctly when i change color in plugin without create a new one.

**Comment by qvsoft** [comment]
It also get issue if the color name contains the dot "." then auto split to new folder, i think the folder splitter only accept "/" character.
And if the color name contains special character like, eg: → , this color can not be deleted.
If the color name contain dot "." at the begining, eg: Color/.85 Black, then it will create 2 empty folders wrap the 85 Black, then if i edit this color, it pop out one level of folder.
You can replicate the issue by import style from this file: https://www.figma.com/file/WgaMLq0tu7Wf9Kz64zdBm0/Ant-Design-Open-Source

**Comment by qvsoft** [comment]
There is another plugin, that can read/write the styles perfectly. It works for both folder, style name with special characters and effects with multi values.
Please check to see if we have an idea to apply the same to Figma Tokens
https://www.figma.com/community/plugin/820660579767995949/Styler
https://github.com/andrei-inc/Styler

**Comment by six7** [comment]
Hey @qvsoft - thank you for your feedback!

Can you post a screenshot of the styles you were trying to import? The plugin relies on your Style structure to import these tokens and will then create tokens out of that.

Also, did you activate that new token set? Only activated sets get exposed to Figma.

Regarding the dot-notation: Right, Figma only divides by "/". However, internall the plugin uses a dot notation to split, so it's best to avoid dots in your token names.

**Comment by qvsoft** [comment]
![2021-06-07_22-46-28](https://user-images.githubusercontent.com/3038514/121050547-dd0bb380-c7e2-11eb-9030-4f0d653d10a5.png)
Here is the style i tried to import, it was imported correctly(if i change all dot "." to an other character). But change on plugin it does not change style on figma, until i rename each color style in figma to name of itself.(Double click on name then do nothing, click out, then it works)

> Also, did you activate that new token set? Only activated sets get exposed to Figma.

Yes, i did activate it. Please try with the file above, then you will immediately see the issue.

> Regarding the dot-notation: Right, Figma only divides by "/". However, internall the plugin uses a dot notation to split, so it's best to avoid dots in your token names.

The dot used by UI System file which is not mine, of course i can change it before import, but is there any reason why don't we do the same as Figma does, that's only using "/" to group the styles?

**Comment by six7** [comment]
Got it! Found the issue. The file still had some of the old Figma style names that contained a "space" between the `/`. That means right now some of the styles are named

`Volcano / 1`

in newer Figma versions they are named

`Volcano/1` - no matter if you added a space or not (they remove it).

The plugin right now just compares if they are equal. So `Volcano/1` vs `Volcano / 1` - which they are not.

I will add a bugfix for this!

Thanks for reporting ❤
