### ISSUE TITLE
Plugin crashes when referencing a token with '++' in the naming of the token/token group

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1404]
**Describe the bug**
When referencing a token with '++' in the name (tested other characters, but this seems to be an edge case) and removing the closing bracket, the plugin crashed.

**To Reproduce**
1. Create a token or tokengroup with '++' within the naming.
2. Reference this token in another token and save it. 
3. When editing the token, you remove the bracket at the end and the plugin crashes.
**Expected behavior**
The reference to work properly

**Screenshots or Screencasts**
https://user-images.githubusercontent.com/109062656/199701931-41030ac9-4f0b-418c-a172-304820d06096.mov

**Comment by six7** [comment]
To add to this, the same seems to be true for other characters, such as

Name of token `color.text.roadpass.[default]`
Using it in a reference like `{color.text.roadpass.[default]}` and removing the last characters to try to get `{color.text.roadpass.[default` will crash the plugin.

We do have quite a few errors in Sentry that refer to this which might all be related: https://sentry.io/organizations/figma-tokens/issues/?groupStatsPeriod=auto&project=5220409&query=is%3Aunresolved+regular+expression&referrer=issue-list&statsPeriod=90d

I have a feeling this might be solved if we escape when trying to resolve the reference.

Adding this to the current iteration given it's matching our performance/stability focus.
