### ISSUE TITLE
Color-fill show hexcode instead of token-name

### ISSUE THREAD

**Issue by ppyenqq** [six7/figma-tokens#141]
When you apply a token, which was **created by the Plugin**, on an element, the raw value(hexcode, sizenumber, font-family...) of that token is shown instead of the token name. If you change the value of that token, it is still beeing applied to the element. (Imported token works fine, they show the token-name)
It is kind of difficult to work with it, since you don't know whether a token has been applied and what token has been applied.

**Comment by six7** [comment]
Hey @ppyenqq could you provide a screenshot? I'm kind of unsure of where that raw value shows up

**Comment by ppyenqq** [comment]
[](url)
![grafik](https://user-images.githubusercontent.com/32959130/121474032-c83a4600-c9c3-11eb-92ed-786e720cf920.png)
I hope this is more understandable. I've just notice, that if you rename the imported Figma token inside the plugin, the same thing happens.

**Comment by six7** [comment]
Is the "green-Figma" style defined in that file?

Also, did you let the plugin create styles for you? By default the plugin doesnt create styles for you, you'd have to tell it to create them for you. It automatically updates though if you're in the file with the local files.

Using color tokens outside of the local file where styles are define is not yet possible, but will be once we tackle #145 

If the linked issue matches your description let me know so I can merge the two issues.

**Comment by ppyenqq** [comment]
Yes, the styles was defined in that file. Until now, I have only used them in the local file, where it was created.
_"Also, did you let the plugin create styles for you? By default the plugin doesnt create styles for you, you'd have to tell it to create them for you. It automatically updates though if you're in the file with the local files."_
Well, that was kind of confusing xD.  I mean, I created a new color by clicking at "Add a new token" and I though, if I apply that token to an element, it would show the name of the token, but it shows only hexcode instead. However the tokens, which I created in Figma first and imported into the plugin, they show the names of the tokens. 
The problem is only about the display of the token name. My main goal was creating color-aliases in order to be more precise and being able to change similar elements faster. Figma can't create aliases, but your plugin does a great job in it. However if I want to change the background of every Profile-Card for example: First, I would look at the color. If the color has a name like colors.background.profileCard then I know I can change that token in the plugin, but if there is only hexcode, then I don't know which token I should look for. I would have to go and  change every single Profile-Card instead.

Yeah sure, you can link them. They don't address the same problem, but I think they kind of go into the same direction (saving the ID).

**Comment by six7** [comment]
Got it!

I intentionally decided against auto-creating styles when creating tokens because users might not be located in their foundational document.

Usually, whenever I create a color or typography token I click the "create styles" button afterwards. But I realize that might be a habit I've trained myself.

Would you say an option in the token edit dialog to "create style" would be good enough?
Or, another solution could be to add that to the Settings dialog, although I prefer to have it visible when creating a token, as that gives exposure (like a toggle that could be disabled by default).

For your usecase, simply hit the 'Create Styles' button and then you can just apply the color style, no need to apply a token if you're only using the plugin to generate styles for you.

**Comment by ppyenqq** [comment]
Yey, I got it. Problem solved thank you 👍 
I think the problem was that I didn't know what "Creating styles" was for and partly because I didn't read the docs thoroughly enough :D . When I tried to find a solution in the docs, I've mainly searched somewhere under "Token" especially in "Creating Tokens". I've just looked at the docs again and found something under "Keeping style in sync". However I didn't associate my problem with "Keeping style in Sync", therefore I didn't read through it. Maybe you can add a short text  in "Creating tokens" where you explain what use "create style"  has and the differerence between create token and create style. 
Well, I think if there was for example a checkbox saying "Automatically create figma color styles"  was inside the create new token/edit token dialog, I may have tried that out and may could have found the solution on my own. But I also think it is okay the way it is right now. Maybe it is just me, who couldn't find it. If you ever notice multiple people having the same problem, then you could try out new approaches.

**Comment by ppyenqq** [comment]
Again, thanks a lot for your help :D

**Comment by six7** [comment]
Will rework the way we "Create" or "Import" styles in the next major release, I think it's confusing as it is.

Thank you for the feedback!
