### ISSUE TITLE
Allow duplication of tokens

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#142]
Would it be possible to add a feature to copy a ‘token set’?

With token set I mean all properties in i.e. a typography.heading-1.

Currently I have a token set for a heading-1 that contains the typographic properties for a heading level one. For level heading two I only want to change the font-size but I have to create a new heading-2 set and re-enter all the properties one by one.

It would be great if I could just duplicate heading-1, rename it to heading-2 and only change the font-size. Or maybe better yet, reference heading-1 and only set the font-size as a cascading overwrite in heading-2.

I hope I explained it clearly…

<img width="255" alt="Screenshot 2021-06-07 at 16 31 42" src="https://user-images.githubusercontent.com/248921/121035569-4b824e80-c7ae-11eb-8c3e-0c06c33497e2.png">

**Comment by usethetics** [comment]
I tried copying the heading-1 entry in the JSON file but that seems a no-go since it resolves in an ‘Invalid Values’ error.

**Comment by six7** [comment]
Hey @usethetics - I think what would solve many use cases would be a way for users to simply duplicate a token. Of course, having some more logic like a cascading overwrite would be even better, but I think for simplicity's sake a duplication method should suffice.

In a way, it would be great if we could duplicate not only single tokens but possibly a token group (such a gray color palette).

**Comment by usethetics** [comment]
> I think what would solve many use cases would be a way for users to simply duplicate a token.
> for simplicity's sake a duplication method should suffice.

Agree, being able to simply duplicate a token (and token group) would solve many use cases.

**Comment by six7** [comment]
Changed title to not create confusion with token sets (themes).

Plus, a duplicate feature would probably be the same for all token types (be it a single value token or a composable like typography)
