### ISSUE TITLE
Reply on #139: Some questions and suggestions

### ISSUE THREAD

**Issue by qvsoft** [six7/figma-tokens#143]
Hi @six7,

I just want to create this ticket to reply your answers on #139 to make it more clear:
(After i replied on #139 it still closed, so i'm not sure if you get notified on that ticket)

> I'd advise to not apply changes to the whole document, except you're certain that the tokens you set are the ones you want. I would work in smaller pages (less objects on a page the faster the plugin can run), and when I'm happy with my Tokens then apply to whole document (which can take its time as you said, but there's not a lot we can do as we have to traverse each and every layer to find references to tokens)

This is not just the time to execute the plugin in whole document, it's also about of lost control on the instances, i can not find the rule or replicate it exactly when it can happen, i have hundreds component in my file, but when i apply for whole file, i lost control on almost of instances, not all, some of them still look good(can be override by main component). It seems happen randomize, so after 2 days spent on tweak my tokens, then i found this issue and didn't want to use the file that i was editing then i rolled back to file 2 days before, because i'm afraid that plugin could breaks my file and i don't know what are instances has been changed, what are not. My 2 days lost :(

> Right, that's not ideal. It would be best if the plugin could scan the page for "lost tokens", that have no reference any more, and users could choose which token they want to replace the "not found token" with.

What do you think if the plugin generate an unique key that used to link with token, and the name of token just link with the that unique key, so we can change the name as we want but still keep the connection with token, because the reference is the unique key.

> Selecting which pages to not apply tokens to is probably not on the roadmap, currently there's #123 that enables "Apply to selection", but that only applies to whatever you have selected on your current page.

I think that would be good, because i face the #1 problem above even in case i apply token to current page. Hope you can figure out what's the problem of instance also be applied token from main component.

> You could always use the "Similayer" plugin to select all with same properties and then apply the token to all that you have selected (Tokens will apply your token to all selected layers)

Similayer not work exactly in this case, eg: i have 100 frames with round border radius 5px, but just 50 of them from applied token. Then no way to just find 50 frames applied token to change to another token or remove token. Need to click on one by one then see what kind of token has been applied.

> Unfortunately not right now, but I'll try to integrate a "Apply last used token" maybe, that could save a lot of time

It's a good idea, also please specify the name of last used token, then we can confidence to apply.

> I've been thinking of allowing this as a setting. So users could choose to either "update instances" or "dont update instances". That choice would be saved for future plugin launches.

That's great if we can combine this with "Apply to selection", so we can limit where the plugin will be applied to make it faster and avoid any token accidentally applying.

**Comment by six7** [comment]
Closing this in favor of #139
