### ISSUE TITLE
Support for font styles from FT to Styled Dictionary [question]

### ISSUE THREAD

**Issue by remy** [six7/figma-tokens#1432]
Firstly, I'm fairly sure I'm doing something wrong because I couldn't find this issue being raised before - so hopefully that's the case.

I've got an export of tokens ([gist](https://gist.github.com/remy/6cfcc46683c67f9b43649cde2843793d)) and I've run it through the `token-transformer` which generally works (certainly no errors).

But when I run it through style dictionary, with defaults for css, the fonts can't be transformed at all - I end up with things like this in my output css file: `--textBaseRegular: [object Object];`

I believe it's because of the nested format of the typography tokens [described here](https://docs.figmatokens.com/available-tokens/typography-tokens) and I'm considering writing my own transform to try to flatten this structure, but that feels… wrong.

Should the FT transform tool have typography support for style dictionary?

Thanks in advance.

**Comment by six7** [comment]
Hey! Have you tried running it with `--expandTypography=true`? This would essentially convert each individual typography values into their own token, making it work with style dictionary.

You could use your own transform in style dictionary to make it all work (I'm using this and there's less need for token-transformer). We're planning to build an official transform for style dictionary, but in the meantime here's the config we've been using to transform typography tokens to css shorthands (or css classes!): https://gist.github.com/six7/9cbce8bcbb16b308c5c87f3729392d21

Let me know if that solves it for you!

**Comment by remy** [comment]
That did the trick, thanks so much 👍
