### ISSUE TITLE
Is it correct to duplicate the category for categories to work properly? (question)

### ISSUE THREAD

**Issue by remy** [six7/figma-tokens#1451]
**Describe the bug**

I'm in the process of automating the pipeline from Figma Tokens to CSS code to be used with components and I'm just trying to get a good understanding whether we're doing this right or if there's a bug in our process.

Below is a screenshot of some of the tokens that our designer has used, note specifically that under "sizing" and "spacing" they've included a category that has the same name. 

Without this duplication of (what I thought was the category), they aren't allowed to create their tokens more than once - because there looks to be a naming collision across the sizing and spacing. **First question** this the correct way to create categories - by duplicating the type it's within?

![SCR-20221123-lb3-min](https://user-images.githubusercontent.com/13700/203584033-42bc2a07-b8fb-45b1-8b22-1782205f9511.png)

Secondly, during the style dictionary transform process, I've noticed that a lot of the transforms I'm using don't work, but it's because the `category` is missing from the `tokens.json`. I can see this in the export below:

![SCR-20221123-lbe-min](https://user-images.githubusercontent.com/13700/203584863-5efc3a83-f4ec-445f-afce-88a39a6413da.png)

In the colours section, the designer _hasn't_ duplicated the type label (as we saw in the previous screenshot), and I believe this means that the `tokens.json` is then missing the top level `category` that is used by style dictionary to apply a number of transforms (such as `size/px` or `name/cti/kebab`).

Again, is this just a matter of process that we need to make sure we duplicate the labels that the Figma Tokens plugin shows us to ensure the category comes through - or have we got something wrong in our setup?

Thanks in advance (sorry for the wordy question!)

<details>
<summary>tokens.json</summary>

<pre><code>{
  "core/typography": {
    "fontFamily": {
      "text": {
        "value": "GT America Trial",
        "type": "fontFamilies"
      },
      "number": {
        "value": "GT America Mono Trial",
        "type": "fontFamilies"
      }
    },
    "lineHeight": {
      "body": {
        "value": "150%",
        "type": "lineHeights"
      },
      "heading": {
        "value": "120%",
        "type": "lineHeights"
      },
      "data": {
        "value": "100%",
        "type": "lineHeights"
      }
    },
    "fontWeight": {
      "heading": {
        "value": "Bl",
        "type": "fontWeights"
      },
      "small-heading": {
        "value": "Md",
        "type": "fontWeights"
      },
      "body": {
        "value": "Lt",
        "type": "fontWeights"
      },
      "medium-heading": {
        "value": "Bd",
        "type": "fontWeights"
      }
    },
    "fontSize": {
      "h1": {
        "value": "roundTo({fontSize.h2} * {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "h2": {
        "value": "roundTo({fontSize.h3} * {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "h3": {
        "value": "roundTo({fontSize.h4} * {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "h4": {
        "value": "roundTo({fontSize.h5} * {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "h5": {
        "value": "roundTo({fontSize.large} * {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "xs": {
        "value": "9",
        "type": "fontSizes"
      },
      "small": {
        "value": "roundTo({fontSize.base} / {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "base": {
        "value": "14",
        "type": "fontSizes"
      },
      "large": {
        "value": "roundTo({fontSize.base} * {fontSize.scale},0)",
        "type": "fontSizes"
      },
      "scale": {
        "value": "1.2",
        "type": "fontSizes"
      }
    },
    "letterSpacing": {
      "body": {
        "value": "0%",
        "type": "letterSpacing"
      },
      "heading": {
        "value": "-1%",
        "type": "letterSpacing"
      },
      "data": {
        "value": "0%",
        "type": "letterSpacing"
      }
    },
    "paragraphSpacing": {
      "none": {
        "value": "0",
        "type": "paragraphSpacing"
      }
    },
    "typography": {
      "copy-text": {
        "h1": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.heading}",
            "lineHeight": "ceil(roundTo({fontSize.h1}*{lineHeight.heading},0) /4)*4",
            "fontSize": "{fontSize.h1}",
            "letterSpacing": "{letterSpacing.heading}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "paragraphIndent": "",
            "textCase": "",
            "textDecoration": ""
          },
          "type": "typography"
        },
        "h2": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.heading}",
            "lineHeight": "ceil(roundTo({fontSize.h2}*{lineHeight.heading},0) /4)*4",
            "fontSize": "{fontSize.h2}",
            "letterSpacing": "{letterSpacing.heading}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textCase": "{textCase.regular}",
            "textDecoration": "{textDecoration.none}"
          },
          "type": "typography"
        },
        "h3": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.heading}",
            "lineHeight": "ceil(roundTo({fontSize.h3}*{lineHeight.heading},0) /4)*4",
            "fontSize": "{fontSize.h3}",
            "letterSpacing": "{letterSpacing.heading}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "h4": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.medium-heading}",
            "lineHeight": "ceil(roundTo({fontSize.h4}*{lineHeight.heading},0) /4)*4",
            "fontSize": "{fontSize.h4}",
            "letterSpacing": "{letterSpacing.heading}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "h5": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.medium-heading}",
            "lineHeight": "ceil(roundTo({fontSize.h5}*{lineHeight.heading},0) /4)*4",
            "fontSize": "{fontSize.h5}",
            "letterSpacing": "{letterSpacing.heading}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "large": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.large}*{lineHeight.body},0) /4)*4",
            "fontSize": "{fontSize.large}",
            "letterSpacing": "{letterSpacing.body}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "base": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.base}*{lineHeight.body},0) /4)*4",
            "fontSize": "{fontSize.base}",
            "letterSpacing": "{letterSpacing.body}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "small": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.small}*{lineHeight.body},0) /4)*4",
            "fontSize": "{fontSize.small}",
            "letterSpacing": "{letterSpacing.body}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        }
      },
      "data-text": {
        "heading": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.small-heading}",
            "lineHeight": "ceil(roundTo({fontSize.h5}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.h5}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "large": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.large}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.large}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "large-emphasis": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.small-heading}",
            "lineHeight": "ceil(roundTo({fontSize.large}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.large}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "base": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.base}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.base}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "base-emphasis": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.small-heading}",
            "lineHeight": "ceil(roundTo({fontSize.base}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.base}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "small": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.small}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.small}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "small-emphasis": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.small-heading}",
            "lineHeight": "ceil(roundTo({fontSize.small}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.small}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "xs": {
          "value": {
            "fontFamily": "{fontFamily.text}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.xs}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.xs}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "number-large": {
          "value": {
            "fontFamily": "{fontFamily.number}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.large}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.large}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "number-base": {
          "value": {
            "fontFamily": "{fontFamily.number}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.base}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.base}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        },
        "number-small": {
          "value": {
            "fontFamily": "{fontFamily.number}",
            "fontWeight": "{fontWeight.body}",
            "lineHeight": "ceil(roundTo({fontSize.small}*{lineHeight.data},0) /4)*4",
            "fontSize": "{fontSize.small}",
            "letterSpacing": "{letterSpacing.data}",
            "paragraphSpacing": "{paragraphSpacing.none}",
            "textDecoration": "{textDecoration.none}",
            "textCase": "{textCase.regular}"
          },
          "type": "typography"
        }
      }
    },
    "textCase": {
      "regular": {
        "value": "none",
        "type": "textCase"
      }
    },
    "textDecoration": {
      "none": {
        "value": "none",
        "type": "textDecoration"
      }
    }
  },
  "core/colour": {
    "blue": {
      "1": {
        "value": "#e6f7ff",
        "type": "color"
      },
      "2": {
        "value": "#bae7ff",
        "type": "color"
      },
      "3": {
        "value": "#91d5ff",
        "type": "color"
      },
      "4": {
        "value": "#69c0ff",
        "type": "color"
      },
      "5": {
        "value": "#40a9ff",
        "type": "color"
      },
      "6": {
        "value": "#1890ff",
        "type": "color"
      },
      "7": {
        "value": "#096dd9",
        "type": "color"
      },
      "8": {
        "value": "#0050b3",
        "type": "color"
      },
      "9": {
        "value": "#003a8c",
        "type": "color"
      },
      "10": {
        "value": "#002766",
        "type": "color"
      }
    },
    "cyan": {
      "1": {
        "value": "#e6fffb",
        "type": "color"
      },
      "2": {
        "value": "#b5f5ec",
        "type": "color"
      },
      "3": {
        "value": "#87e8de",
        "type": "color"
      },
      "4": {
        "value": "#5cdbd3",
        "type": "color"
      },
      "5": {
        "value": "#36cfc9",
        "type": "color"
      },
      "6": {
        "value": "#13c2c2",
        "type": "color"
      },
      "7": {
        "value": "#08979c",
        "type": "color"
      },
      "8": {
        "value": "#006d75",
        "type": "color"
      },
      "9": {
        "value": "#00474f",
        "type": "color"
      },
      "10": {
        "value": "#002329",
        "type": "color"
      }
    },
    "geekblue": {
      "1": {
        "value": "#f0f5ff",
        "type": "color"
      },
      "2": {
        "value": "#d6e4ff",
        "type": "color"
      },
      "3": {
        "value": "#adc6ff",
        "type": "color"
      },
      "4": {
        "value": "#85a5ff",
        "type": "color"
      },
      "5": {
        "value": "#597ef7",
        "type": "color"
      },
      "6": {
        "value": "#2f54eb",
        "type": "color"
      },
      "7": {
        "value": "#1d39c4",
        "type": "color"
      },
      "8": {
        "value": "#10239e",
        "type": "color"
      },
      "9": {
        "value": "#061178",
        "type": "color"
      },
      "10": {
        "value": "#030852",
        "type": "color"
      }
    },
    "gold": {
      "1": {
        "value": "#fffbe6",
        "type": "color"
      },
      "2": {
        "value": "#fff1b8",
        "type": "color"
      },
      "3": {
        "value": "#ffe58f",
        "type": "color"
      },
      "4": {
        "value": "#ffd666",
        "type": "color"
      },
      "5": {
        "value": "#ffc53d",
        "type": "color"
      },
      "6": {
        "value": "#faad14",
        "type": "color"
      },
      "7": {
        "value": "#d48806",
        "type": "color"
      },
      "8": {
        "value": "#ad6800",
        "type": "color"
      },
      "9": {
        "value": "#874d00",
        "type": "color"
      },
      "10": {
        "value": "#613400",
        "type": "color"
      }
    },
    "green": {
      "1": {
        "value": "#f6ffed",
        "type": "color"
      },
      "2": {
        "value": "#d9f7be",
        "type": "color"
      },
      "3": {
        "value": "#b7eb8f",
        "type": "color"
      },
      "4": {
        "value": "#95de64",
        "type": "color"
      },
      "5": {
        "value": "#73d13d",
        "type": "color"
      },
      "6": {
        "value": "#52c41a",
        "type": "color"
      },
      "7": {
        "value": "#389e0d",
        "type": "color"
      },
      "8": {
        "value": "#237804",
        "type": "color"
      },
      "9": {
        "value": "#135200",
        "type": "color"
      },
      "10": {
        "value": "#092b00",
        "type": "color"
      }
    },
    "lime": {
      "1": {
        "value": "#fcffe6",
        "type": "color"
      },
      "2": {
        "value": "#f4ffb8",
        "type": "color"
      },
      "3": {
        "value": "#eaff8f",
        "type": "color"
      },
      "4": {
        "value": "#d3f261",
        "type": "color"
      },
      "5": {
        "value": "#bae637",
        "type": "color"
      },
      "6": {
        "value": "#a0d911",
        "type": "color"
      },
      "7": {
        "value": "#7cb305",
        "type": "color"
      },
      "8": {
        "value": "#5b8c00",
        "type": "color"
      },
      "9": {
        "value": "#3f6600",
        "type": "color"
      },
      "10": {
        "value": "#254000",
        "type": "color"
      }
    },
    "magenta": {
      "1": {
        "value": "#fff0f6",
        "type": "color"
      },
      "2": {
        "value": "#ffd6e7",
        "type": "color"
      },
      "3": {
        "value": "#ffadd2",
        "type": "color"
      },
      "4": {
        "value": "#ff85c0",
        "type": "color"
      },
      "5": {
        "value": "#f759ab",
        "type": "color"
      },
      "6": {
        "value": "#eb2f96",
        "type": "color"
      },
      "7": {
        "value": "#c41d7f",
        "type": "color"
      },
      "8": {
        "value": "#9e1068",
        "type": "color"
      },
      "9": {
        "value": "#780650",
        "type": "color"
      },
      "10": {
        "value": "#520339",
        "type": "color"
      }
    },
    "orange": {
      "1": {
        "value": "#fff7e6",
        "type": "color"
      },
      "2": {
        "value": "#ffe7ba",
        "type": "color"
      },
      "3": {
        "value": "#ffd591",
        "type": "color"
      },
      "4": {
        "value": "#ffc069",
        "type": "color"
      },
      "5": {
        "value": "#ffa940",
        "type": "color"
      },
      "6": {
        "value": "#fa8c16",
        "type": "color"
      },
      "7": {
        "value": "#d46b08",
        "type": "color"
      },
      "8": {
        "value": "#ad4e00",
        "type": "color"
      },
      "9": {
        "value": "#873800",
        "type": "color"
      },
      "10": {
        "value": "#612500",
        "type": "color"
      }
    },
    "purple": {
      "1": {
        "value": "#f9f0ff",
        "type": "color"
      },
      "2": {
        "value": "#efdbff",
        "type": "color"
      },
      "3": {
        "value": "#d3adf7",
        "type": "color"
      },
      "4": {
        "value": "#b37feb",
        "type": "color"
      },
      "5": {
        "value": "#9254de",
        "type": "color"
      },
      "6": {
        "value": "#722ed1",
        "type": "color"
      },
      "7": {
        "value": "#531dab",
        "type": "color"
      },
      "8": {
        "value": "#391085",
        "type": "color"
      },
      "9": {
        "value": "#22075e",
        "type": "color"
      },
      "10": {
        "value": "#120338",
        "type": "color"
      }
    },
    "red": {
      "1": {
        "value": "#fff1f0",
        "type": "color"
      },
      "2": {
        "value": "#ffccc7",
        "type": "color"
      },
      "3": {
        "value": "#ffa39e",
        "type": "color"
      },
      "4": {
        "value": "#ff7875",
        "type": "color"
      },
      "5": {
        "value": "#ff4d4f",
        "type": "color"
      },
      "6": {
        "value": "#f5222d",
        "type": "color"
      },
      "7": {
        "value": "#cf1322",
        "type": "color"
      },
      "8": {
        "value": "#a8071a",
        "type": "color"
      },
      "9": {
        "value": "#820014",
        "type": "color"
      },
      "10": {
        "value": "#5c0011",
        "type": "color"
      }
    },
    "volcano": {
      "1": {
        "value": "#fff2e8",
        "type": "color"
      },
      "2": {
        "value": "#ffd8bf",
        "type": "color"
      },
      "3": {
        "value": "#ffbb96",
        "type": "color"
      },
      "4": {
        "value": "#ff9c6e",
        "type": "color"
      },
      "5": {
        "value": "#ff7a45",
        "type": "color"
      },
      "6": {
        "value": "#fa541c",
        "type": "color"
      },
      "7": {
        "value": "#d4380d",
        "type": "color"
      },
      "8": {
        "value": "#ad2102",
        "type": "color"
      },
      "9": {
        "value": "#871400",
        "type": "color"
      },
      "10": {
        "value": "#610b00",
        "type": "color"
      }
    },
    "yellow": {
      "1": {
        "value": "#feffe6",
        "type": "color"
      },
      "2": {
        "value": "#ffffb8",
        "type": "color"
      },
      "3": {
        "value": "#fffb8f",
        "type": "color"
      },
      "4": {
        "value": "#fff566",
        "type": "color"
      },
      "5": {
        "value": "#ffec3d",
        "type": "color"
      },
      "6": {
        "value": "#fadb14",
        "type": "color"
      },
      "7": {
        "value": "#d4b106",
        "type": "color"
      },
      "8": {
        "value": "#ad8b00",
        "type": "color"
      },
      "9": {
        "value": "#876800",
        "type": "color"
      },
      "10": {
        "value": "#614700",
        "type": "color"
      }
    },
    "grey": {
      "1": {
        "value": "#FAFAFA",
        "type": "color"
      },
      "2": {
        "value": "#F4F4F5",
        "type": "color"
      },
      "3": {
        "value": "#E4E4E7",
        "type": "color"
      },
      "4": {
        "value": "#D4D4D8",
        "type": "color"
      },
      "5": {
        "value": "#A1A1AA",
        "type": "color"
      },
      "6": {
        "value": "#71717A",
        "type": "color"
      },
      "7": {
        "value": "#52525B",
        "type": "color"
      },
      "8": {
        "value": "#3F3F46",
        "type": "color"
      },
      "9": {
        "value": "#27272A",
        "type": "color"
      },
      "10": {
        "value": "#18181B",
        "type": "color"
      }
    },
    "white": {
      "value": "#ffffff",
      "type": "color"
    }
  },
  "core/sizes": {
    "sizing": {
      "xxxs": {
        "value": "8px",
        "type": "sizing"
      },
      "xxs": {
        "value": "12px",
        "type": "sizing"
      },
      "xs": {
        "value": "16px",
        "type": "sizing"
      },
      "sm": {
        "value": "20px",
        "type": "sizing"
      },
      "m": {
        "value": "24px",
        "type": "sizing"
      },
      "lg": {
        "value": "32px",
        "type": "sizing"
      },
      "xl": {
        "value": "40px",
        "type": "sizing"
      },
      "xxl": {
        "value": "64px",
        "type": "sizing"
      },
      "xxxl": {
        "value": "80px",
        "type": "sizing"
      }
    },
    "spacing": {
      "xxs": {
        "value": "4px",
        "type": "spacing"
      },
      "xs": {
        "value": "8px",
        "type": "spacing"
      },
      "sm": {
        "value": "12px",
        "type": "spacing"
      },
      "m": {
        "value": "16px",
        "type": "spacing"
      },
      "lg": {
        "value": "24px",
        "type": "spacing"
      },
      "xl": {
        "value": "40px",
        "type": "spacing"
      }
    }
  },
  "core/radii": {
    "none": {
      "value": "0",
      "type": "borderRadius"
    },
    "xs": {
      "value": "4",
      "type": "borderRadius"
    },
    "sm": {
      "value": "8",
      "type": "borderRadius"
    },
    "m": {
      "value": "16",
      "type": "borderRadius"
    },
    "lg": {
      "value": "32",
      "type": "borderRadius"
    },
    "xl": {
      "value": "40",
      "type": "borderRadius"
    }
  },
  "semantic": {
    "badge": {
      "red": {
        "value": "{red.1}",
        "type": "color"
      },
      "volcano": {
        "value": "{volcano.1}",
        "type": "color"
      },
      "gold": {
        "value": "{gold.1}",
        "type": "color"
      },
      "yellow": {
        "value": "{yellow.1}",
        "type": "color"
      },
      "lime": {
        "value": "{lime.1}",
        "type": "color"
      },
      "green": {
        "value": "{green.1}",
        "type": "color"
      },
      "cyan": {
        "value": "{cyan.1}",
        "type": "color"
      },
      "blue": {
        "value": "{geekblue.1}",
        "type": "color"
      },
      "purple": {
        "value": "{purple.1}",
        "type": "color"
      },
      "magenta": {
        "value": "{magenta.1}",
        "type": "color"
      },
      "blue-text": {
        "value": "{geekblue.10}",
        "type": "color"
      },
      "purple-text": {
        "value": "{purple.10}",
        "type": "color"
      },
      "magenta-text": {
        "value": "{magenta.10}",
        "type": "color"
      },
      "red-text": {
        "value": "{red.10}",
        "type": "color"
      },
      "gold-text": {
        "value": "{gold.10}",
        "type": "color"
      },
      "lime-text": {
        "value": "{lime.10}",
        "type": "color"
      },
      "green-text": {
        "value": "{green.10}",
        "type": "color"
      },
      "cyan-text": {
        "value": "{cyan.10}",
        "type": "color"
      }
    },
    "bg": {
      "lightest": {
        "value": "#FAFAFA",
        "type": "color"
      },
      "light": {
        "value": "#f5f5f5",
        "type": "color"
      },
      "base": {
        "value": "#f0f0f0",
        "type": "color"
      },
      "medium": {
        "value": "#e6e6e6",
        "type": "color"
      },
      "dark": {
        "value": "#d6d6d6",
        "type": "color"
      }
    },
    "badge-rg": {
      "value": "{spacing.m}",
      "type": "borderRadius"
    },
    "badge-sm": {
      "value": "{spacing.xs}",
      "type": "borderRadius"
    },
    "text": {
      "primary": {
        "value": "#222222",
        "type": "color"
      },
      "secondary": {
        "value": "#757575",
        "type": "color"
      }
    },
    "table-cell-width": {
      "xs": {
        "value": "40",
        "type": "sizing"
      },
      "sm": {
        "value": "96",
        "type": "sizing"
      },
      "m": {
        "value": "120",
        "type": "sizing"
      },
      "lg": {
        "value": "152",
        "type": "sizing"
      },
      "xl": {
        "value": "176",
        "type": "sizing"
      },
      "xxl": {
        "value": "216",
        "type": "sizing"
      }
    },
    "table": {
      "cell-border": {
        "value": "{basic.border}",
        "type": "color"
      },
      "header-bg": {
        "value": "{grey.1}",
        "type": "color"
      },
      "cell-bg": {
        "value": "{white}",
        "type": "color"
      },
      "header-bg-hover": {
        "value": "{grey.2}",
        "type": "color"
      }
    },
    "table-cell-height": {
      "m": {
        "value": "{sizing.lg}",
        "type": "sizing"
      },
      "sm": {
        "value": "{sizing.m}",
        "type": "sizing"
      }
    },
    "button": {
      "primary": {
        "fill": {
          "value": "{grey.7}",
          "type": "color"
        },
        "text": {
          "value": "{white}",
          "type": "color"
        },
        "hover": {
          "value": "{grey.6}",
          "type": "color"
        },
        "pressed": {
          "value": "{grey.8}",
          "type": "color"
        }
      },
      "icon": {
        "value": "32",
        "type": "borderRadius"
      },
      "basic": {
        "value": "0",
        "type": "borderRadius"
      },
      "default": {
        "fill": {
          "value": "{basic.fill}",
          "type": "color"
        },
        "text": {
          "value": "{grey.8}",
          "type": "color"
        },
        "hover": {
          "value": "{grey.2}",
          "type": "color"
        },
        "pressed": {
          "value": "{grey.4}",
          "type": "color"
        }
      }
    },
    "disabled": {
      "bg": {
        "value": "{grey.2}",
        "type": "color"
      },
      "border": {
        "value": "{basic.border}",
        "type": "color"
      },
      "hover": {
        "value": "{grey.5}",
        "type": "color"
      },
      "text": {
        "value": "{grey.6}",
        "type": "color"
      }
    },
    "scroll-bar": {
      "track": {
        "value": "{grey.2}",
        "type": "color"
      },
      "bar": {
        "value": "{grey.3}",
        "type": "color"
      }
    },
    "dropdown-menu": {
      "value": "{spacing.xxs}",
      "type": "borderRadius"
    },
    "input": {
      "value": "{spacing.xs}",
      "type": "borderRadius",
      "border": {
        "value": "{grey.3}",
        "type": "color"
      }
    },
    "chip": {
      "border": {
        "value": "{basic.border}",
        "type": "color"
      },
      "padding-lr": {
        "value": "{spacing.xs}",
        "type": "spacing"
      },
      "padding-lr-compressed": {
        "value": "{spacing.xxs}",
        "type": "spacing"
      },
      "space-between": {
        "value": "{spacing.xxs}",
        "type": "spacing"
      }
    },
    "basic": {
      "border": {
        "value": "{grey.4}",
        "type": "color"
      },
      "fill": {
        "value": "{grey.1}",
        "type": "color"
      }
    },
    "chip-height": {
      "small": {
        "value": "{sizing.xs}",
        "type": "sizing"
      },
      "table": {
        "value": "{sizing.sm}",
        "type": "sizing"
      },
      "lg": {
        "value": "{sizing.m}",
        "type": "sizing"
      }
    },
    "input-height": {
      "regular": {
        "value": "{sizing.lg}",
        "type": "sizing"
      }
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "core/typography",
      "core/colour",
      "core/sizes",
      "core/radii",
      "semantic"
    ]
  }
}</code></pre>

</details>

**Comment by six7** [comment]
So there's a few things to unpack here:

First, the Figma Tokens plugin doesnt force you to use any naming structure. It's completely up to you how you name things (in earlier days we forced the first level to be the type, like style dictionary does, we went away from that for flexibility teams need).

Then, we try to follow the w3c format closely, even though we're not quite there yet. But that said, we do treat the `type` field as the primary way to understand the type of a token, not as style dictionary the `category` field.

As for naming: Yes, in my eyes it's correct to add the 'sizing' group name to the first level of the token name, but again it's totally up to you! We're currently displaying tokens grouped by type, but that type is not part of the name. We're working on a different visualization that groups by name, not by type (as a choice).

As for the category field, I personally use my own transforms that pick up the `type` field, I think there's others who have just copied over the `type` field to the `category` field.

Ideally in the near future both Figma Tokens and style dictionary both use the w3c format for types so this process will be much smoother - and is also a great reason for why we need a standard!

I hope this made some sense, if not please let me know - happy to help!

**Comment by remy** [comment]
Thank you - that's useful and helps me understand better how to group things in the FT plugin.

I definitely think the UI would benefit from making the `type` clearer (because we took it as a category), but I imagine there's probably lots of little tweaks ahead anyway.

Thanks for takin the time to reply 👍

**Comment by yumyo** [comment]
@six7 
> I personally use my own transforms that pick up the type field,
Could you please expand on that?

**Comment by six7** [comment]
you can just use style dictionary's custom transforms to transform tokens depending on their token type, which is superior to the cti method.

e.g. like this https://gist.github.com/six7/9cbce8bcbb16b308c5c87f3729392d21

or using our official sd transforms https://www.npmjs.com/package/@tokens-studio/sd-transforms

**Comment by yumyo** [comment]
Amazing! Thank you
