### ISSUE TITLE
Multiple effects in one token

### ISSUE THREAD

**Issue by matt3224** [six7/figma-tokens#151]
It doesnt look like its possible to define multiple effects such as shadow with a toke and the current behaviour overrides one shadow with another.

If im to replicate the shadow styles of android material i need layered shadows, can this be added ?

**Comment by six7** [comment]
Unfortunately for now there's only one fill (for all tokens), this includes boxShadow tokens. I do understand we definitely need multiples, which is especially true for shadows.

I'd like to merge this issue with #152 so we can track progress there.

**Comment by six7** [comment]
Closing this in favor of #152
