### ISSUE TITLE
Style Dictionary and/or Theo JSON compatible output

### ISSUE THREAD

**Issue by JoshMormann** [six7/figma-tokens#153]
While looking to implement a solid hand-off workflow at an agency with a number of different development code bases, the desire for an open source translation layer such as Style Dictionary from Amazon, or Theo from SalesForce is quite strong. We're very busy with lots of clients, and having to build our own translation layer could be hard to find commitment and cycles for, since the desire to implement an integrated design system approach and workflow is largely lost on our development staff. 

Are there any plans to implement SD or Theo output?

**Comment by six7** [comment]
From my experience the output should already be SD compliant. Is there anything that goes wrong with it (except for aliases?)

I'm working closely with the folks at [useArcade.com](https://usearcade.com/) who provide a translation layer for tokens (and I've worked with them on their Figma integration plugin). If that's an option I can highly recommend these, an example can be seen [here](https://www.youtube.com/watch?v=Ka1I5TphDb0).

**Comment by JoshMormann** [comment]
I will definitely have a deeper look. My apologies for not having a direct example, I'm operating on a theoretical conclusion based on a visual JSON format comparison between known quantities, and the SD documentation. I may have spoken out of turn here. I will get back to you on this once I have a test up and running.

**Comment by six7** [comment]
Closing this, please let me know if there's any problem with the export to SD.🙏
