### ISSUE TITLE
Self-Referential JSON Export

### ISSUE THREAD

**Issue by JoshMormann** [six7/figma-tokens#154]
While it is relatively simple to copy and paste self-referential output from the plugin UI, the export function appears to flatten/render the references, while while useable seems to lose some of the efficiency. JSONbin.io syncing appears however to receive the kind of document I was expecting from the export function. Any plans to allow for export options? Flat or 
self-referential?

**Comment by six7** [comment]
Definitely! An option would probably be best, so users could export tokens and use them in some environment that doesn't allow aliases.

I think Style Dictionary writes aliases in `this.way` - the plugin allows two ways: `this.way` and `$this.way`. I think we'd need to transform all aliases to be parseable by style dictionary, but that shouldn't be too much work.

**Comment by JoshMormann** [comment]
This sounds great. 🙏 Many thank yous by the way. This plugin is incredibly powerful in its current form. Hopefully you can find a way to get paid handsomely for all your community work.

**Comment by six7** [comment]
Closing this in favor of #167 - let's keep all discussion there as it's about the same topic.
