### ISSUE TITLE
Gradient import appears to corrupt style when angled

### ISSUE THREAD

**Issue by Poimen** [six7/figma-tokens#156]
We have quite a few gradients that we have converted to single property colors (due to #152). 

However, once we do `Import Styles` from Figma Tokens, the gradients are corrupted.

To give an example:
1. We create a box (300x300)
2. Create a gradient start `#009677`, stop `#50B848` (opacity 100%), and angle the gradient bottom left corner to the top right corner.
3. Create style based on that gradient

At this point, Figma has:
```css
background: linear-gradient(45deg, #009677 0%, #50B848 100%);
```

Now, perform `Import Style` into Figma Tokens - the Figma sheet changes to:
```css
background: linear-gradient(45deg, #009677 -20.42%, #50B848 50%);
```

There is now a `-20.42%` that has arrived from Figma Tokens.

If I look at the Figma Token that has been saved:
```json
"Gradient issue": {
    "value": "linear-gradient(315deg, #009677 0%, #50b848 100%)"
  }
```

So it would seem that the issue is that there is some interpretation going on that changes the angle. We have also noticed that the floating point math is a little out compared Figma as well.  This is also not reproducible with those numbers.

The input of:
```css
background: linear-gradient(45deg, #009677 0%, #50B848 100%);
```

at one point produced:
```css
background: linear-gradient(45deg, #009677 -20.42%, #50B848 50%);
```

What we observe is that the `-20.42%` is a common occurrence, whereas the `50%` change is less.

We have noticed that even updating manually the token, to:
```json
"Gradient issue": {
      "value": "linear-gradient(45deg, #009677 0%, #50B848 100%)"
    }
```

causes the gradient to be corrupted as well:
```css
background: linear-gradient(135deg, #009677 0%, #50B848 70.42%);
```

Is this a known issue?

**Comment by Poimen** [comment]
So I have done some digging around. From what I can make out the idea in the code is that the gradient angle degree is related to Figma's transformation matrix. As far as I can tell, with just the CSS values, you can't really backwards engineer the transformation because the (x,y) co-ordinates are related to the deg but not governed by the deg of the gradient..

For examples - 45deg could apply across any amount of transformations, but the angle of the gradient is still 45deg.

Hence, I'm not sure you could just use the css to get back to the Figma transformation. Is the goal?

To further illustrate, if you create a gradient from top-left corner to bottom-left corner of a 300x300 rectangle, Figma generates:
```css
background: linear-gradient(360deg, #009677 0%, #50B848 100%);
```

Moving that to top-right to bottom-right, Figma generates:
```css
background: linear-gradient(360deg, #009677 0%, #50B848 100%);
```

So identical css...

But the transform matrix is different - case 1:
```json
"gradientTransform": [
 [ -8.940696716308594e-8, -1, 1 ],
 [ 0.5394624471664429, -1.6653345369377348e-16, 0.5 ]
]
```

Case 2:
```json
"gradientTransform": [
 [ -1.295973248716109e-7, -1, 1.0000001192092896 ],
 [ 0.5394624471664429, -2.1681188400179963e-8, -0.03946239873766899 ]
]
```

So there are two different transform matrixes but the same css.

I can fix the gradient creation such that the correct angle is generated, but in the current structure for the JSON, if you wanted to give the same transform back, there would need to be some storage of extra info.

What do you think?

**Comment by six7** [comment]
Thanks for this detailed report! I'm aware gradients are currently not 100% correct, especially with the case you mentioned as Figma allows users to set these transformations in a very specific manner. I think what would be ideal is if we could mimic CSS behaviour, and lose some of Figma's capability along the way. Storing some of these transforms as metaData sounds good, but I think for now we should focus on fixing the correct angle.

When I was working on the gradientTransforms I was kind of struggling with understanding how Figma handles these transformations to be honest, so your help would be greatly appreciated! As I'm primarily a Designer this is a little out of my league 😅

Development is currently based on the `next` branch, where a larger refactoring has been made. If you need any help to get it set up, I'd be able to jump on a quick video call if you'd like that.

**Comment by Poimen** [comment]
Yeah, I've got some time to work on this 😄 

I'm in the opposite boat, this is the first time I'm working with designers - server developer by trade - but I a designer team that have invested into the plugin as it integrates quite well into our environment and helps designers sync with the dev team. I think this is a great bit of tooling that can go far.

I'll see about a putting a PR together on the `next` branch. I haven't tried getting this into Figma just yet, but played with the tests 👍

**Comment by Poimen** [comment]
Oh, I forgot to mention - I started to use this library:
https://github.com/rafaelcaricio/gradient-parser

In some OSS projects they want to limit external libraries.

Are you happy with including other packages?

**Comment by six7** [comment]
> Oh, I forgot to mention - I started to use this library:
> https://github.com/rafaelcaricio/gradient-parser
> 
> In some OSS projects they want to limit external libraries.
> 
> Are you happy with including other packages?

Sure, I have no objections on using external libraries, feel free to do so!

Let me know if you need any help on setting it up in Figma, the readme has some info on how to add the development plugin to Figma itself.

**Comment by Poimen** [comment]
So after hitting my head for the last two days, I'm only a little closer to understanding what Figma is doing.

I can work out the gradient angle fine through so matrix manipulation, but the stop points are a complete mystery to me. I can work out the stop points when the angles are well known - like 90, 45, etc. - so it has some relation to the sin/cos calculations. Once the gradient line doesn't go through the center point, I have no idea what Figma is giving back and how to make it work.

For now I'm going to park this.

I've push this up to my github fork on branch `issue-156` if you want to have a look. Its rough, but the angle should be ok...real hacky code though. 

I'll see if I have some brain spark later this week to see what could be happening with the stop points.

**Comment by six7** [comment]
Fixed in version 77! 🎉
