### ISSUE TITLE
Empty values for tokens?

### ISSUE THREAD

**Issue by akosarch** [six7/figma-tokens#157]
Is it possible to assign a token (eg color) an empty value? I already tried: `" ", "none", "null"` – those are not working 🙁
I want to assign an empty placeholder token to the element first to change it to something meaningful later. Let's say, for example, I'm building a versatile UI kit and I want my secondary button to have transparent fill and a 1px outline by default. But I also want it to preserve the link to the fill token, so I could customize it later.

I know there is the trick with the color transparency but that requires me to give it a color value and a 0 opacity but that's tedious to write and my exported JSON would contain that value, which is semantically wrong (absence of color is not the same as color with transparency).

Great plugin, btw! Please keep doing it! 🔥🤘🏻

**Comment by six7** [comment]
I think the main difficulty lies in having to type the transparent value again and again. #6 would probably solve this if you were able to just set transparency with the click of a button.

**Comment by akosarch** [comment]
Thank you for the reply! Already solved this by defining the `none` preset with white color and 0 transparency. And I'm referencing this color each time I need explicitly tell that the color is absent. But having the visual color picker would be a great addition, for sure! 🙂
