### ISSUE TITLE
Color swatch does not reflect HSLa color

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#158]
I just noticed that for an HSLa color the swatch in the plugin palette does not reflect the color. See attached image, the `color-black` has an HSLa value, the grey swatch underneath a hex value, which does reflect its color value.

[Edit: The color is applied correctly on the canvas, it’s just not reflected in the plugin’s color swatch.]

<img width="406" alt="Screenshot 2021-06-18 at 09 34 34" src="https://user-images.githubusercontent.com/248921/122524738-c7835e80-d018-11eb-9b2a-4e97f93915b7.png">

**Comment by usethetics** [comment]
Both RGB and RGBa values seem to work fine.

<img width="271" alt="Screenshot 2021-06-18 at 09 41 09" src="https://user-images.githubusercontent.com/248921/122525249-57c1a380-d019-11eb-88d5-ff1ad744faa5.png">

**Comment by six7** [comment]
I just checked again and HSLA is working fine as long as you're specifying it correctly: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsla()

`hsla(0, 0%, 11%, 1)` works
`hsla(0, 0, 11, 1)` doesn't.

The plugin basically gives the token button the input value un-transformed and thus if the hsla is css-compliant it works.

**Comment by usethetics** [comment]
Thanks, and sorry, this was an error on my part since I indeed did not specify the colors correctly.
