### ISSUE TITLE
Rearranging token order from Tokens panel

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#159]
In order to rearrange tokens it seems currently only possible to re-structure JSON. Would it be possible to rearrange tokens by dragging in the Tokens panel?

I.e. in the attached example if I create a size-20 token, it gets added to the end of the tokenlist, in order to sort the tokens I have to dig into the JSON file to reorder.

![image](https://user-images.githubusercontent.com/248921/122560608-13e29480-d041-11eb-8a6c-cc0134ddd8f4.png)

**Comment by six7** [comment]
This seems to be a duplicate of #122, let's move discussion there. I think the description there covers your needs, I hope.
