### ISSUE TITLE
Allow Themes

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#16]
Thought about Theming quite a bit now and I think it would be best if we:
- Keep all options in the same structure as we do right now
- Allow a user to create Theme-Decisions, allowing to check or uncheck Themes (depending on what different tokens get applied), e.g.:

User has base tokens of:
```
colors:
  white: #fff
  black: #000
  gray: #333
```

User has "light theme":
```
colors: 
  textColor: "colors.white"
  backgroundColor: "colors.black"
```

"black theme"
```
colors:
  textColor: "colors.black"
  backgroundColor: "colors.white"
```

Depending on what theme the user activates a different token setup is given - resulting in different themes.

As we can't change Styles if Styles are located in a different file I think it would be best to create something akin to Themer: Replacing Style references by a different one

**Comment by martinmaricak** [comment]
This is something I wanted to build a plugin for.

**Comment by okayjeffrey** [comment]
Would you consider Themes displaying in another "tab" in the interface. It would be easier to understand how the tokens are applied? Maybe when in the tab a dropdown or selection box that would let you choose a theme?

**Comment by six7** [comment]
I think it would make sense to place them in their own tab, especially as the goal the user has is a different one than in the Tokens tab (applying tokens, editing tokens), here a user may only wish to replace the Theme for the whole file (or possibly Selection?)

Still not sure how to handle Tokens though, but I think something like the following:
1. When we associate a token to a style we save the styles' ID next to the token value
2. When creating a theme property (e.g. cardBackgroundColor) we iterate over each cardBackgroundColor for various themes.
3. When changing themes we look for cardBackgroundColor Id's (apart from the theme the user wants to switch to) and replace those with the now active theme style ID

**Comment by six7** [comment]
This is now in Figma Tokens Version 36! Read docs on subject here: https://docs.tokens.studio/token-sets
