### ISSUE TITLE
Gitlab : Contents don't pass schema validation

### ISSUE THREAD

**Issue by valguenichon** [six7/figma-tokens#1617]
I encounter an error when trying to setup gitlab credentials.
I'm using the free version of the plugin.
I attach a screenshot of the modal with the error.
What is weird is when I add a slash to the end of the repository, it generates another error : "Error syncing with GitLab, check credentials".
I'm a bit lost, usually we just have to provide an URL but not here.
Thanks for any help !

![Capture d’écran 2023-02-15 à 15 07 34](https://user-images.githubusercontent.com/16956819/219050779-57383529-b1be-4196-8c09-82787ed2a641.png)

**Comment by six7** [comment]
Is the repository empty by chance? Make sure it contains the token files (or if you dont have the token files yet make sure it's initialized with a README.md).

This error can basically mean `the token file you have provided here is malformed` or `there's no contents on the repository`

If you're sure there's something in the repo (under that branch) then could you share the token json stored there?

**Comment by six7** [comment]
Is the repository empty by chance? Make sure it contains the token files (or if you dont have the token files yet make sure it's initialized with a README.md).

This error can basically mean `the token file you have provided here is malformed` or `there's no contents on the repository`

If you're sure there's something in the repo (under that branch) then could you share the token json stored there?

**Comment by valguenichon** [comment]
OK there's a file but this file is empty. It's named tokens.json
Should I put a readme file too?

**Comment by six7** [comment]
I'd either fill the file with contents or remove the file and push from the plugin which will setup a proper structure.

It's just important that the repository is not entirely empty so a readme.md file would suffice

**Comment by valguenichon** [comment]
Thanks a lot!
It works fine to get the connection. I get the push window and now I have
to test if it works with my colleagues.

**Comment by six7** [comment]
Yeah i'd try that, also probably not good to have an empty file - i guess that's the reason why it can't be parsed.

I'll close this, feel free to reopen if it persists
