### ISSUE TITLE
Pause sync to jSONbin (feature request)

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#162]
Would it be possible to pause syncing to JSONbin and manually push to remote? 

Currently every change I make to a token results in a a remote update, adding to the number of requests in my JSONbin plan.

**Comment by six7** [comment]
As #134 requires us to "batch" our token changes anyway (we wouldn't want to generate a new PR everytime we make a token change) we could very well also implement that for the JSONBin integration!
