### ISSUE TITLE
Box shadow tokens does not support opacity setting for colour

### ISSUE THREAD

**Issue by chris-pearce** [six7/figma-tokens#163]
<img width="1047" alt="Design System 2021-06-24 09-33-05" src="https://user-images.githubusercontent.com/1342772/123180771-4e2fb400-d4cf-11eb-8f25-699823fe45ec.png">

**Comment by chris-pearce** [comment]
I got around it using the "CSS" value option: `rgba(0, 0, 0, 0.25)`. However, this is very developer-focused and wasn't immediately apparent to me. It would help to have an explicit opacity field.

**Comment by six7** [comment]
You're right, expecting designers to know how to input this with `rgb(...)` is not a user-friendly way. I think this can be solved if our Color Input had a better UI, kind of like the one Figma provides. #6 would try to solve this at some point.

**Comment by six7** [comment]
Closing this in favor of https://github.com/six7/figma-tokens/issues/6 which will solve this issue
