### ISSUE TITLE
Manage tokens applied to multiple elements

### ISSUE THREAD

**Issue by akosarch** [six7/figma-tokens#165]
![Image](https://user-images.githubusercontent.com/46430445/123825610-b8998780-d907-11eb-8f15-fa922ceccf40.png)

Currently, when selecting an element, I can see the list of tokens applied to it. But this stops working when I select multiple elements, even that I know they all have the same tokens applied.  This kinda annoying because it doesn't allow me to delete the tokens altogether, instead I should select each individual element to remove the tokens.

As a long-term improvement, I would like to be able to `replace` the applied tokens with another ones, just like Figma allows us to do this with the colors. This would allow me to speed up the process of modifying the existing set of components. For example, I could duplicate a set of small-sized inputs and readjust them to be medium-sized quickly, using this `replace` functionality 😏

**Comment by six7** [comment]
This would be great, ideally the user could just select the whole page and see all tokens that have been applied there.

As you mentioned users could then swap tokens with different ones or delete certain tokens.

**Comment by six7** [comment]
Will be released with version 80 some time tomorrow morning.
