### ISSUE TITLE
Math isn't working inside rgba() function

### ISSUE THREAD

**Issue by akosarch** [six7/figma-tokens#166]
![Знімок екрана 2021-06-30 о 17 06 41](https://user-images.githubusercontent.com/46430445/123976759-15a84280-d9c7-11eb-9e7c-7324286cbd60.png)

I want to invert the opacity by subtracting some value from 1 when creating new color with the help of rgba() function. Unfortunately, this doesn't work as expected. However, it works if I define a separate opacity token with this math but not directly inside the rgba() function.

**Comment by electroheadfx** [comment]
I have too a problem with rgba when I reference a color by:
rgba($colors.brand.default, 0.5)
I get a white color, brand.default is : $colors.blue.500
blue.500 is : hsl($colors.blue._hue, 100%, 50%)
and _hue is : 210

**Comment by maartensaulx** [comment]
@electroheadfx you can solve this by using a hex color value for your blue.500. Worked for me at least.

**Comment by electroheadfx** [comment]
> @electroheadfx you can solve this by using a hex color value for your blue.500. Worked for me at least.

yes of course it works, just it doens't support color with utils like : hsl($colors.blue._hue, 100%, 50%), its useful because I dont need to convert in hex, just use the saturation.

**Comment by coolmanlume** [comment]
Same issue using hsla:
```json
"TKSC": {
    "color": {
      "cyan~teal": {
        "hue": {
          "value": 177,
          "type": "other"
        },
        "saturation": {
          "value": 44,
          "type": "other"
        },
        "lightness": {
          "value": 41,
          "type": "other"
        }
      }
},
"TKM": {
    "color": {
      "primary.300": {
        "value": "hsla($TKSC.color.cyan~teal.hue, $TKSC.color.cyan~teal.saturation, $TKSC.color.cyan~teal.lightness * 1.2439, 1)",
        "description": "Primary background color light",
        "type": "color"
      }
}
```
**The Token doesn't work:**

<details>
<summary><strong>See screenshot</strong></summary>
<img src="https://user-images.githubusercontent.com/12875139/130556759-ef3bc6ab-3273-401d-99f6-4fe43eea6893.jpg">
</details>

Also please note that the colors chips (palette) inside the plugin panel are not displaying the calculated colors. I will open another Issue for this soon.

**Comment by coolmanlume** [comment]
@six7: FYI if you watch [this Loom](https://www.loom.com/share/102c59c3865843ac9b9687b05fb49755) captured on July 22 you will notice that everything was functioning¹ then.
I Hope that this can help.

(1) Here's the snippet I was using, and doesn't work anymore
> `$colors.lightness._secondary-bg * 4.5 + 0.175` translates into `"15 * 4.5 + 0.175"` instead of `45.175` (‹ properly evaluated in the `colors.lightness._secondary-AA` node)
```json
{
  "colors": {
    "lightness": {
      "_secondary-bg": {
        "value": "25",
        "description": "Lightness of the Secondary background color",
        "type": "color"
      },
      "_secondary-AA": {
        "value": "$colors.lightness._secondary-bg * 4.5 + 0.175",
        "description": "AA lightness of the Secondary text color",
        "type": "color"
      }
    },
    "color": {
      "secondary": {
        "value": "hsl(172,50,$colors.lightness._secondary-bg)",
        "description": "Secondary background color",
        "type": "color"
      }
    },
    "secondary-AA": {
      "value": "hsl(172,50,$colors.lightness._secondary-AA)",
      "description": "AA Color of text on Secondary",
      "type": "color"
    }
  }
}
```
Also I've noticed that sometimes removing the space character after the comma inside the hsl() function sometimes leads to a `null` eval.
