### ISSUE TITLE
JSON file doesn't show Alias Tokens

### ISSUE THREAD

**Issue by Houssamsaleh1** [six7/figma-tokens#167]
![EXPORT ALIAS](https://user-images.githubusercontent.com/86772114/124124584-46e54900-da81-11eb-95e4-258d475d980e.jpg)

When I reference Tokens (Alias tokens) and try to export them, I only see raw values in the JSON file.
Does the plugin supports different types of tokens? (ex: Global/Alias/...)

**Comment by six7** [comment]
Thanks for the report! This is on the same topic as #154 — currently the export itself transforms aliases, but it's quite understandable users want their aliases for style dictionary. What we need to do to get there is modify the export function to translate any aliases into style dictionary readable aliases — which are written inside curly brackets `{token.alias}`. Figma Tokens allows users to also write aliases with a `$` sign prepended `$token.alias`.

**Comment by gmlnchv** [comment]
@six7 I see this has been merged, but hasn't been released yet? If so when are you planning on releasing, keen to get the aliases working with SD? Thanks!

**Comment by six7** [comment]
Hey @gmlnchv - this has been released quite a while ago. The plugin now retains aliases on SD Export. However, we'd still need an option for users to turn off this behavior, as SD can't use math right now.

Note: You can use `{token.alias}` style aliases in Figma Tokens as well, if you write them like that SD can handle them (except for math)
