### ISSUE TITLE
‘Custom’ component token sets

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#168]
Would it be possible and desirable to have more custom component sets like the one for Typography?

For instance one st where you are able to bundle all tokens related to buttons.

I tried creating a set for buttons via JSON but this obviously does not work when importing in Figma Tokens since it results in the second attached image.

<img width="532" alt="Screenshot 2021-07-08 at 11 14 58" src="https://user-images.githubusercontent.com/248921/124898036-223c2480-dfdf-11eb-981a-5329544dd1f7.png">

<img width="449" alt="Screenshot 2021-07-08 at 11 25 17" src="https://user-images.githubusercontent.com/248921/124898188-40098980-dfdf-11eb-85c9-7b7baaebc401.png">

**Comment by JeroenduC** [comment]
This would really help me with creating my design system in Figma, and later on with creating prototypes!

**Comment by six7** [comment]
Is this specifically about typography tokens? The next release (currently being worked on in the #146 branch) will allow you to have a seperate structure for your tokens, where the name isnt coupled with the type. So you could have a buttons set with all tokens that cover the button area, and a different set for cards for example.

Or did I get it wrong and it's more about creating individual compositions in your tokens like mentioned in #149 ?

**Comment by usethetics** [comment]
No, sorry that was not clear and the JSON example I provided is rather misleading as I just did a quick test by copying a typography tokenset.

This is indeed about creating sets of tokens such as a buttons set. Great to see this is being worked on! 💯
