### ISSUE TITLE
"Create styles" no longer working

### ISSUE THREAD

**Issue by embostan** [six7/figma-tokens#1698]
**Describe the bug**
The Create style feature used to work but now it just does nothing.

**To Reproduce**
1. Create a new token
2. PPress Create styles
3. Nothing is created
4. Restart Figma
5. Not fixed

**Expected behavior**
New color styles are created.

**Screenshots or Screencasts**

**Figma file (optional)**
All files have the issue

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
I cannot confirm, you'd either need to share a screen recording or more information on the steps you've taken.

My guess is you've checked `Ignore first part of token name for styles` and your tokens are named without a group (e.g. the token name is just `blue`)

Either that, or your token sets aren't activated (checkbox next to their names)
