### ISSUE TITLE
Updating line height (percentage) for fonts in FT updates in Figma styles as 'Auto' instead of percentage.

### ISSUE THREAD

**Issue by t-e-lition** [six7/figma-tokens#171]
Workflow: **Added a new percentage value in FT (line height)>>inserted this value to the heading token setting>>pressed update>>problem occurs.**

Any idea why this should happen?

![Screenshot 2021-07-14 at 09 45 25](https://user-images.githubusercontent.com/84501353/125583880-18fa26ea-c568-4c2f-bca3-51b38b9f7350.png)

**Comment by six7** [comment]
Does the problem persist if you remove the `%` from the token name? e.g. `$lineHeights.125` instead of `$lineHeights.125%`?

**Comment by t-e-lition** [comment]
Hi. Yes! Magic :) It is solved. Thank you.
