### ISSUE TITLE
Figma does not adapt newly create tokens

### ISSUE THREAD

**Issue by t-e-lition** [six7/figma-tokens#172]
Whenever I  create a new token on FT I would expect it to create it in Figma as well. This does not work and therefore I have to set the same style correspondingly manually in Figma's library. 

Are there any practice how to go about this? What is the most practical and easy way to create new tokens in this constellation?

![Screenshot 2021-07-14 at 16 28 52](https://user-images.githubusercontent.com/84501353/125639971-4a049c56-a621-4a03-916f-db060e483d49.png)

**Comment by t-e-lition** [comment]
OK - Just realised I need to press on **CREATE STYLES**

**Comment by six7** [comment]
Next release will make this more obvious. 👍
