### ISSUE TITLE
Effect styles (Drop shadow) does not get imported

### ISSUE THREAD

**Issue by seb-giroux** [six7/figma-tokens#174]
Hi,

For testing purposes, I've created a basic shadow in my file:
![image](https://user-images.githubusercontent.com/8069361/126173185-971c9ede-7dcb-4f5d-98d7-b680f334df1e.png)

..but it doesn't get imported in the "Box shadow" section when I hit the **Import styles** button.

Is it supported, and if so is it bugged?

Thanks!

**Comment by six7** [comment]
Unfortunately Box Shadows dont get jmported yet, I'd like for them to be able to be composed of multiple shadows before we tackle this, as most shadows in Figma can have multiple.

**Comment by seb-giroux** [comment]
Thanks for the answer. It's the only hurdle that keep us from using the plugin for our theme management right now. We'll wait as the rest of the plugin checks all the boxes. Impressive work! :)
