### ISSUE TITLE
S O S !

### ISSUE THREAD

**Issue by t-e-lition** [six7/figma-tokens#175]
I have made a change in the json. code in the plugin which have created an error and deleted all of my whole token setup which I have been working on since weeks(!!!) How can I reverse/recover/undo to the last stable state. Now when I start the plugin it starts as if I have opened it for the first **time..**

**Please HELP**. This is a serious issue... Thanks.

**Comment by six7** [comment]
Hey @t-e-lition — depending on how you synced your tokens a couple of solutions:

If local: Go back in time using Figma's version history. As tokens are stored on the document, undoing Figma's history will also restore tokens from thst version.

If jsonbin: Versioning is enabled for jsonbin on their website, where you can copy paste the version where it still worked.

let me know if you need further assistance.

**Comment by t-e-lition** [comment]
Hey Jan. This didnt help. I have restored my Figma to an older version but I the plugin is still empty/has no data whatsoever. 
I am clueless.

**Comment by t-e-lition** [comment]
Hi Jan. So restoring from version history on Figma did the Job. That was close 😅 

Thanks for the quick reply!!

**Comment by six7** [comment]
Great! Remember, everything you do in Tokens if it's set to Local storage is saved with Figma's document state, so you can always Cmd + Z in Figma to go back if anything goes wrong.

Do you remember what caused the plugin's JSON to be corrupted?

**Comment by t-e-lition** [comment]
Yes. Back then you advised me that it is possible to change data directly in the json code in the plugin, in case I want to create new folder or move tokens to different folders (since this option is not yet available). So I have moved one color token inside the json tree under a new folder and then all crashed.. 

<img width="483" alt="Screenshot 2021-07-21 at 09 57 14" src="https://user-images.githubusercontent.com/84501353/126453092-4fcfb1fd-5edb-4d7a-ae11-6007edf7690a.png">
<img width="491" alt="Screenshot 2021-07-21 at 09 56 50" src="https://user-images.githubusercontent.com/84501353/126453095-9f686932-a434-4d2b-9207-270bea547c47.png">
