### ISSUE TITLE
Tokens with an assigned value of zero do not work

### ISSUE THREAD

**Issue by bellentani** [six7/figma-tokens#176]
Hi, I'm here again! hehe

We are trying to apply a variable that has the value "zero" to spaces and fonts. Every time we apply this value it doesn't work.

We've identified that this happens wherever we have Tokens that have 0 as their assigned value: spacing, borders and font sizes - it happened in all cases.

But if I put a decimal value too low it works. Example: 0.00000000001

Below is a Gif illustrating the problem.

![captura](https://user-images.githubusercontent.com/1213530/126380663-3cb2ac75-8b83-4493-980d-5fb1992f087e.gif)

The JSON Sample:

 ```
"sizing": {
    "zero": 0,
    "micro": 4,
    "xs": 8,
    "sm": 12,
    "md": 16,
    "lg": 28,
    "xl": 44,
    "xxl": 72,
    "giant": 116
  },
```

Thank you very much in advance.

**Comment by bellentani** [comment]
We test again and works on Spacing, Border and other Tokens, but in Paragraph Spagin still glitched.

And when we use Negative Values (like Letter Spacing) isn't apply. 

```"letterSpacing": {
	  "tight": "-4.5%",
	  "regular": 0,
	  "wild": "5%"
	},```

**Comment by ptrckschrdtr** [comment]
The same happens to me. This is hard for my letter spacing values since I'm using this kind of negative value a lot.

**Comment by six7** [comment]
Unfortunately you cannot set a layer's size to 0, as you can't do that in Figma as well (API returns `Expected "width" to have value >= 0.01`).

For typography a workaround for now would be to set the values to `0px`, will have to investigate why this is happening.
