### ISSUE TITLE
How do I define opacity in colors

### ISSUE THREAD

**Issue by t-e-lition** [six7/figma-tokens#178]
Hi 

I would like to define in Tokens the opacity level to be used for shadow effects. How do I accomplish this?

![Screenshot 2021-07-26 at 17 21 55](https://user-images.githubusercontent.com/84501353/127015162-0ec1cd2e-04e2-4863-893c-933f96170481.png)

Cheers

**Comment by six7** [comment]
You can either use an 8-digit hexcode that contains the opacity value or you can write your colors using `rgba(255, 255, 0, 0.5)` syntax, where the last part is the opacity.

You can also reference another token inside rgba like this: `rgba($colors.primary, 0.5)`

**Comment by t-e-lition** [comment]
Works. Thanks!
