### ISSUE TITLE
Plugin UI

### ISSUE THREAD

**Issue by Tuxxu** [six7/figma-tokens#18]
I started a study on how we can maintain the consistency of the plugin interface following the Figma design language & system
Public link: [https://www.figma.com/file/i02ufiPoDjctrQjYcpwbUs/Figma-tokens?node-id=0%3A1](https://www.figma.com/file/i02ufiPoDjctrQjYcpwbUs/Figma-tokens?node-id=0%3A1)

Using this prototype, it may be easier to validate some backlog ideas. _In addition, I think it would be interesting to keep the interface versioning (design file)_

**Comment by six7** [comment]
Thanks for that @Tuxxu !

I really like it being closer to Figmas style, but I'm still missing some options that would sort of play against that:
- Choosing the property of where to apply the color token (border / fill), currently solved as a menu on the color
- All tokens listed as list view will only allow us to show a handful of tokens, I feel like having most of the tokens visible at all times is something we should strive for (perhaps a grid view like the new Figma color styles?). But we'd still need to be able to set tokens on different properties.

Pinging @color2life

**Comment by Tuxxu** [comment]
@six7  Thanks for your feedback!

I made some adjustments and the new grid view worked fine. To define the token in a given property, I used the menu that appears when we delete a color style. [(look this)](https://www.figma.com/file/i02ufiPoDjctrQjYcpwbUs/Figma-tokens?node-id=4%3A39)

Hey @color2life feel free to edit the file.

**Comment by six7** [comment]
Published a new version of Tokens with a UI overhaul that includes many of your suggestions. Was thinking of adding a Search bar similary to Figma's new style select - there I would include the list / grid toggle button so that it affects all tokes.
