### ISSUE TITLE
Apply tokens to selection

### ISSUE THREAD

**Issue by nachosdesign** [six7/figma-tokens#180]
Hello 👋

Love that Figma Tokens allows for tokens to be applied to the whole page or the whole document.

Would also like to be able to apply to only selected items.

Is this something you are considering?

Keep up the great work!

**Comment by six7** [comment]
This is already part of the `next` branch and will be part if the next major release 🎉

https://github.com/six7/figma-tokens/pull/146

**Comment by six7** [comment]
This is now live!
