### ISSUE TITLE
Update token theme instantly while toggling?

### ISSUE THREAD

**Issue by maartensaulx** [six7/figma-tokens#181]
Hi there, 

First of all, amazing work. Thank you!

I have a small question about switching between token sets.
I've defined 2 sets, 'light' and 'dark' in my Figma file.

When I'm switching between them, I need to manually press the button 'Update' in the bottom right of the plug-in to actually switch between themes. I have the feeling that this wasn't the case in a previous version. 

https://user-images.githubusercontent.com/67953561/127774271-3aa1bc35-ee19-48f6-9e1a-0473f02d664c.mov

**Comment by six7** [comment]
You're right, this was different in a previous version. I'd say we reintroduce that under consideration of the "Apply to..." / settings.

**Comment by maartensaulx** [comment]
Great idea!

**Comment by six7** [comment]
I'll keep this open and use it to track work on it 👍
