### ISSUE TITLE
Unchecking tokens doesnt reset the propery

### ISSUE THREAD

**Issue by senthil87** [six7/figma-tokens#183]
Hi Jan,

With the new version, we are now not able to uncheck the tokens to remove the styles like before. Attached the video for your reference. 

https://user-images.githubusercontent.com/5101306/127810847-da50d4be-238d-4051-b224-08a9df93ae04.mov

**Comment by six7** [comment]
Thanks for reporting! Fixed in latest release, will introduce a setting later on if that's the behaviour users want.
