### ISSUE TITLE
Trying to add a box-shadow results in crash

### ISSUE THREAD

**Issue by maartensaulx** [six7/figma-tokens#184]
Hi there, 

When I try to create a box-shadow in Figma Tokens plugin, the plugin crashes with the text:
_Something went wrong!
Cannot read property 'x' of undefined.
Restart the plugin and try again._

Attached video and export of my JSON file.

https://user-images.githubusercontent.com/67953561/127834145-7afacfc6-9372-41ba-b091-8163ad31a6dd.mov

[tokens.json.zip](https://github.com/six7/figma-tokens/files/6915679/tokens.json.zip)

**Comment by six7** [comment]
Thanks for reporting! Will deploy a fix for this later today or tomorrow morning 👍
