### ISSUE TITLE
Unable to load custom json

### ISSUE THREAD

**Issue by seb-giroux** [six7/figma-tokens#186]
Hi!

The previous version allowed us to paste our json in the **JSON** tab, which would update the **Tokens** tab.

Latest version broke that behavior. Would it be possible to bring this feature back?

 Thanks!

**Comment by six7** [comment]
Clicking Save & Update should still trigger that behaviour, does it not? Or are you getting an error there?

**Comment by seb-giroux** [comment]
You are totally right, Save and Update button works. I don't remember having to click on it for everything to sync up though. My bad!

**Comment by six7** [comment]
You didnt have to do that before, however that lead to some errors that this new behaviour tries to address. 👍 Glad its still working for you
