### ISSUE TITLE
JSONBin.io url not pointing to the correct url on jsonbin.io

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1910]
**Describe the bug**
![image](https://github.com/tokens-studio/figma-plugin/assets/109062656/471b4c97-9a39-4e87-82dc-ef8a739a21d2)

**To Reproduce**
1. Use JSONBIN
2. On the bottom left of the plugin you can go to docs on JSONbin website.
3. The url gives a 404 (not sure what the correct url should be @six7 ?)
4. URL now is: https://jsonbin.io/637369540e6a79321e4a4e89

**Comment by six7** [comment]
seems like there is no longer the possibility to link to a specific bin. let's change it to https://jsonbin.io/app/bins then
