### ISSUE TITLE
Adding more math function?

### ISSUE THREAD

**Issue by coolmanlume** [six7/figma-tokens#192]
We are starting to use your plugin intensively, and love it a lot.
One thing we're missing though is more advanced math functions, starting with `Math.round()`.
For example: if we use a scale for our font sizes we also want to use the outputs to build some buttons, but, we want these button heights to be non-decimal (pixel hitting issues).

Possible? 
We would be thrilled… !

PS: Thanks again for this already amazing plugin

**Comment by six7** [comment]
Basically everything mentioned in https://github.com/silentmatt/expr-eval should be supported. I just noticed a bug that prevented math from being evaluated if you didn't use any aliases in your project, but I do have a quick fix for that that I'll deploy later today. Other than that, if anywhere in your project you were using an alias and wanted to round something, you can define it as `round(5.553)` and it would get rounded to 6. You could also use functions such as `floor(...)` or `ceil(...)` as described in the [Unary operators section](https://github.com/silentmatt/expr-eval#unary-operators) of expr-eval

**Comment by coolmanlume** [comment]
Amazing. Thank you, Jan!
