### ISSUE TITLE
Store setting of checkbox "Ignore first part of token name for styles".

### ISSUE THREAD

**Issue by konki-vienna** [six7/figma-tokens#193]
Problem: When unchecking the checkbox "Ignore first part of token name for styles", the setting is ignored once opening the plugin for the next time.

**Comment by six7** [comment]
Thanks for reporting! The same bug seems to affect `Update on Change`, `Update Remote` and `Update styles`

**Comment by konki-vienna** [comment]
Ah, sorry. I browsed the headlines of the open issues, but somehow missed that… 😬

**Comment by six7** [comment]
Ah, no don't worry. I meant I just debugged and noticed it affects these other settings as well. Bugfix is released now, should work properly again 👍
