### ISSUE TITLE
Losing editing work in JSON file when switching between tabs

### ISSUE THREAD

**Issue by richardfoong** [six7/figma-tokens#197]
Hi Jan,

I've noticed with the new release that if i'm making any changes to JSON, when I switch over to visually see the changes in the Token tab,  i lose all the work done. I know that i have to hit update, but this now seems to also take a bit longer. Not a deal breaker, but slows down speed to get tokens updated/modified.

(Doing great work btw!)

Rich

**Comment by WardMe** [comment]
If you just want to update tokens, but don't need to see the result reflected in a component, I switch to an empty page to quickly make changes to the json.

**Comment by richardfoong** [comment]
Yep, i'm doing this as well. it's the habit i've formed in switching back and forth which trips me up. Would be good to have a warning if you are about to lose changes you've made to the JSON

**Comment by six7** [comment]
It was recently changed so that you would have to save in order for your json to apply, as the previous way was leading to far too many errors for users.

I think we could show a warning that you're about to lose progress if you switch without saving.
