### ISSUE TITLE
Suggestion: Ability to add more granular descriptions

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#199]
Currently I am creating a white-label design system in Figma where I would like to add more in-depth descriptions on particular tokens for designers to turn the white-label style into a branded style. 

In Figma Tokens we currently import JSON converted from our single source of truth via Style Dictionary. We want to be able to apply as much of the same tokens in Figma as we do in our front-end. For this to work however we think some quick pointers for designers would be vital.

One such use-case for instance is the ability to add a short description on how to apply spacing. In our design tokens we have unique tokens for both padding and margins. Our padding can be applied to a frame, while margins need to be applied to a container frame. A short description added to the popup tooltip would likely be super valuable to designers.

Something to this extend:
<img width="556" alt="Screenshot 2021-08-09 at 15 20 16" src="https://user-images.githubusercontent.com/248921/128714277-d8461839-aa5f-46b4-a2d1-27dd824dfd40.png">

Obviously this documentation will also live in the design system documentation, but it would be a nice-to-have for quick reference in Figma as well…

**Comment by six7** [comment]
Nice idea!

I think we could use the description property that we have for color and typography tokens. We could use that for all other tokens as well.

**Comment by six7** [comment]
Heads up: I completed this feature, will probably release on Monday.
