### ISSUE TITLE
Plugin not working well with Figma Styles

### ISSUE THREAD

**Issue by elrabelo** [six7/figma-tokens#210]
**Describe the bug**
When I import Figma Styles to Figma Tokens and change one value in Figma Tokens, for example a Font Family, it is not being changed in Figma. I tried this with a file from community (Tailwind CSS).

When I click on Create Styles, the plugin create others styles even I did not add anything.

**To Reproduce**
1. Download [Official Tailwind CSS Styles](https://www.figma.com/community/file/958383439532195363) from Community or you can do with another project.
2. Open Figma Tokens Plugin.
3. Click on Import.
4. Change Font Family in Tokens tab: Font Families > fontFamilies > inter > Edit Token > Font Family > Roboto Mono (for example).
5. Click on Update.

**Expected behavior**
I think it should reflect what I changed in Figma Tokens in Figma Styles.

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/8551433/130618995-7d4ebecf-cba2-4025-9344-f55cf926e245.mp4

**Versions**
- Figma Desktop App version 101.6
- Figma Tokens Version 59
- macOS Big Sur 11.5.2

**Comment by six7** [comment]
Can you try disabling `Ignore first part of token name for styles` and see if the problem still persists?

This is like the cause and was badly implemented on my end especially for new users, sorry about that.

**Comment by elrabelo** [comment]
Yes, it worked! I saw that the first part of token name was being ignored but I didn't notice this option. Thank you for the quick reply.

**Comment by six7** [comment]
Awesome! Will rework that option so others wont have that same experience 🙏
