### ISSUE TITLE
Renaming Tokens does not update Tokens applied in Figma

### ISSUE THREAD

**Issue by lqlwle** [six7/figma-tokens#211]
Contrary to the FAQ here
https://docs.tokens.studio/tokens/creating-tokens#token-groups
_"You can also change the name of the token, which will automatically update all references to this token."_

When inspecting Elements in Figma that have a certain Token attached **do not update their token.**

<img width="402" alt="image" src="https://user-images.githubusercontent.com/11554591/130625149-eeda5e3f-31b6-4167-8c81-b7f4b49620b3.png">

After changing the token-name to **$primary-900** (instead $primary-800 before), the Element that had the Token applied shows still the old reference:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/11554591/130625335-9ae94a5b-24d7-4580-a792-e9750991ec2b.png">

This means that if one needs to change the grouping or structure of the Tokens **all references are lost** throughout the whole document. This makes this not usable at all. If changes need to be done it's impossible to find all disconnected tokens in a document.

I also believe that's one of the main things that make this tool "brittle". If there would be an easy way to reconnect Tokens – or it would automatically track them and update them by itself, this would make this tool more robust.

**Comment by six7** [comment]
I agree, we should be able to edit a token name and have the plugin update all layers (time consuming but better to do right when the action is performed) AND be able to go to other documents or pages where that edit wasn't done to find these missing links and redeclare them easily, like the Missing Font dialog in Figma.

**Comment by six7** [comment]
Plus I think we should update the Docs, the term "Reference" applies to any aliases being used.

**Comment by six7** [comment]
Right now we only store the token name on each layer, this doesn't work when the token name changes as it then loses connection.

A way to solve this could be to introduce a UUID on each token, however:
- Tokens change depending on what theme is active, so the UUID would have to be somewhat dynamic
- Users might want to take a different token set from another project, paste it in and see everything change. If we strictly follow UUID this is not possible
- Maybe there's a way to do this with both UUID and token name. For example, if the token UUIDs of all tokens with a name was the same across themes, then this wouldn't be much of a problem. Users would update the name, but the UUID stays the same. The plugin would have to make sure that all tokens that share the name have the same UUID.

**Comment by fehmi** [comment]
It is really painful. Dunno, Is it possible to code something like this?

- Get old token name after change
- Scan all elements inside the document
- If layer's assigned token name matches with the old token name
- Update it with the new name

**Comment by fehmi** [comment]
Aliases also can be affected after renaming source token names.

**Comment by six7** [comment]
> Aliases also can be affected after renaming source token names.

The plugin updates those for you.



> It is really painful. Dunno, Is it possible to code something like this?
> 
> * Get old token name after change
> * Scan all elements inside the document
> * If layer's assigned token name matches with the old token name
> * Update it with the new name

Agree, it is. Updating all elements is not the right approach though (performance is bad + user might not even be on the same page where those tokens are applied).

A solution to this is the [Multi inspector](https://github.com/six7/figma-tokens/issues/355), which would show you missing links + all tokens applied to all selected layers and children (working on this next)

**Comment by six7** [comment]
Will be released with version 80 some time tomorrow morning.
