### ISSUE TITLE
Can't apply any token for a component instance

### ISSUE THREAD

**Issue by exclama** [six7/figma-tokens#22]
It's not possible to apply different tokens for component instances (Color in my case), the plugin returns "No nodes Updated".
Expected result: Apply different tokens for a component instance.

**Comment by exclama** [comment]
I think this is related to issue [Allow setting more data on each Token #11](https://github.com/six7/figma-tokens/issues/12)

**Comment by six7** [comment]
Currently we're limited by Figma regarding being unable to set relaunchData on component instances (the data that's shown on the right bottom), we can however set pluginData on instances - the user would not be able to see that tokens were set though.

I'd suggest we move forward by
- allowing to set tokens on component instances
- not setting relaunchData on those instances (user is only able to see that tokens were set in Inspector)

**Comment by evgeny-kh** [comment]
I wonder why you would want to assign tokens to an instance instead of applying it to the master component.

**Comment by exclama** [comment]
Oh, imagine you have a button master component(Button/NormalButton), with blue bg. Now you want a Warning button with orange bg. You can make another master component (Button/WarningButton) with an instance from the original button nested in it. Like this:

◆ Button/NormalButton
--- [Button elements]

◆ Button/WarningButton
--- ◇ Button/NormalButton (instance, changing bg color)


That can be made with color styles, but unfortunately can't be made with Figma Tokens.

**Comment by six7** [comment]
Fixed in newest version. Restart Figma for it to take effect.

Note: We can't show tokens on the relaunchData panel (bottom right when selecting a layer in Figmas properties panel) - however, the tokens are there.
