### ISSUE TITLE
Typography JSON format no longer works with Style Dictionary

### ISSUE THREAD

**Issue by rbare1** [six7/figma-tokens#227]
**Describe the bug**
Previously, the typography styles exported like so:
```
"Header 1": 
    "fontFamily": {
        "value": "Inter"
    },
    "fontWeight": {
        "value": "Extra Light"
    },
    "lineHeight": {
        "value": "48px"
    },
    "fontSize": {
        "value": "1.8125rem"
    },
    "letterSpacing": {
        "value": "-2.1%"
    },
    "paragraphSpacing": {
        "value": "none"
    }
},
```

and they are now exported in this format: 
```
"Header 1": {
    "value": {
        "fontFamily": "{fontFamilies.Inter}",
        "fontWeight": "{fontWeights.Extra-Light}",
        "lineHeight": "{lineHeights.Header-1}",
        "fontSize": "{fontSizes.Header-1}",
        "letterSpacing": "{letterSpacing.Header-1}",
        "paragraphSpacing": "none"
    },
    "type": "typography"
},
```

The aliases not being resolved is expected and fine, but the structure changing to combine all of the properties into a single `value` object causes the export to no longer work with the default Style Dictionary formatters (such as `scss/variables`).
The result has changed from:
```
$header-1-font-family: Inter;
$header-1-font-weight: 200;
$header-1-line-height: 3rem;
$header-1-font-size: 1.8125rem;
$header-1-letter-spacing: -0.021rem;
```

to
```
$header-1: [object Object];
```

We can write our own formatter of course for the new structure, but I wanted to see if this was intentional first.

This is our Style Dictionary config for scss:
```
scss: {
    transformGroup: "scss",
    buildPath: "dist/scss/",
    files: [
        {
            destination: "_typography.scss",
            filter: "getTypography",
            format: "scss/variables",
        },
    ],
},
```

**Comment by six7** [comment]
Thanks for reporting, I'll look into this asap.

**Comment by six7** [comment]
Fixed in Version 62. If you have any other feedback for a Style Dictionary export let me know.

Also, I'll be beta testing a GitHub sync soon if your team would like to be on that (which would allow you to automate the FT -> SD -> ... process)

**Comment by AndriiTsok** [comment]
Hi @six7 we would love to test the Github sync!

**Comment by rbare1** [comment]
@six7 Thanks for the quick fix! It would be great to test the GitHub sync!
