### ISSUE TITLE
Unselecting spacing token does not set it to 0

### ISSUE THREAD

**Issue by lukasoppermann** [six7/figma-tokens#23]
Hey,
I am not 100% sure what the correct behavior is (bes of course would be to store the previous values, but that seems to be quite an overhead). However when I set the spacing in an auto layout to token `xs` (checkmark is shown) and afterwards "unset"/remove it (checkmark is not shown) the value stays as the numeric value of `xs`.

I would expect it to be reset to `0`.

**Comment by six7** [comment]
I agree, I'd also expect it to be reset to 0 and remove the token. Thanks for bringing this up!

**Comment by six7** [comment]
Facing some problems with this one, as the current approach to "removing" tokens is just to remove the reference to the token. At the time the node is "analyzed" our controller doesn't know there used to be a token here. Will have to think some more on that one.

**Comment by six7** [comment]
Just an update: This will be easily doable once we move on from setting all token values in a single pluginData property on the node containing all tokens to having multiple seperate pluginData properties on the node (also something that we need to do to prepare for Figma allowing nodes to inherit pluginData from their parents)

**Comment by six7** [comment]
Merged and published. Most values can now be reset when unselecting a Token. Some values like Typography stay the same, as I think not every value needs to be reset.
