### ISSUE TITLE
Nested opacitiy not themable

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#232]
**Describe the bug**
When an opacity token references another opacity token changing the color of this element with theming is not working.

**To Reproduce**
1. Create token $opacity.90 with 90% opacity
2. Create token $emphasis.xy.high which references the token $opacity.90
3. Apply a color token to an element,
4. Apply the $emphasis.xy.high token to this element
5. Add a theme with these tokens and a different color token

**Expected behavior**
When changing themes the color of the element should switch

**Comment by six7** [comment]
Could you provide a screen recording and/or a file to reproduce the issue? Works just fine for me if I reproduce the steps you outlined.

**Comment by Blyawon** [comment]
It was my mistake, because the token was in the same json object :)
