### ISSUE TITLE
Font Weights not responsive to tokens

### ISSUE THREAD

**Issue by benhami1ton** [six7/figma-tokens#233]
**Describe the bug**
When using the fontWeight token type, using values similar to those seen in example files does not seem to affect font weights. It will apply the token, but it does not change the weight of the font. When I import the example JSON text, I see that fontWeight allows the expected behavior, making me wonder if there's a dependency or syntax issue that I'm missing. So the example version works fine, it's only when I try to create this token type from scratch that it won't work.

This also seems to apply to the fontFamilies token, but I haven't looked too closely to see if it's the same problem, since I'm often working with just a single font family right now.

**To Reproduce**
1. Start with a blank file.
2. Create text node.
3. Create fontWeights tokens with values like "Light", "Regular", "Bold"
4. Attempt to apply tokens to text node.

**Expected behavior**
Similar to fontSize, I'd assume that when changing the fontWeight, I'd see a direct change to just the weight, regardless of any other tokens or styles.

**JSON (optional)**
```
"font-weight": {
    "regular": {
      "value": "Regular",
      "type": "fontWeights"
    },
    "bold": {
      "value": "Bold",
      "type": "fontWeights"
    },
    "light": {
      "value": "Light",
      "type": "fontWeights"
    }
  }
```

**Comment by six7** [comment]
In order for font weights to work you always have to provide a fontFamily token as well, they only work in combination with each other (as the way Figma works you don't set a font weight, you always set a combination of the two).

The combination of the two must exist as well, the UI for that is not the best right now (and I think we might have removed an explanation of this somehow, we were educating users previously that this only works in combination).

**Comment by benhami1ton** [comment]
Thanks! I played around and figured out what you mean, and was able to get the right results. I can see how this limitation exists, since i was wondering previously how figma would handle the different naming conventions for weights (regular/400, bold/700, etc).

Would there be a way to conditionally check if a text node is missing one or the other token, and prompt/alert the user? It might be helpful in the inspect tab, but certainly as a reminder when applying tokens in the main tokens tab.

**Comment by six7** [comment]
Yes, I think we could also show that in the Inspector with not a lot of work!

I wonder if there's a way to show that in the Tokens ui as well 🤔
