### ISSUE TITLE
Create Styles not applied correctly 

### ISSUE THREAD

**Issue by richardfoong** [six7/figma-tokens#246]
I've created typography tokens in the plugin (tested both alias based and value based tokens) and when running create styles export to figma style sheet, all the type styles do not come through. They come through as 12/Auto

**To Reproduce**
Create type tokens
Click on create styles

Token examples:

```
          "display (52)": {
            "value": {
              "fontFamily": "$fontFamilies.01",
              "fontWeight": "$fontWeights.light",
              "lineHeight": "$lineHeights.header * $fontSizes.sm.10",
              "fontSize": "$fontSizes.sm.10",
              "paragraphSpacing": "$paragraphSpacing.1 * $fontSizes.sm.10"
            },
            "type": "typography"
          },
```

and tested this type as well

```
    "h3": {
      "value": {
        "fontFamily": "Roboto",
        "fontWeight": "600",
        "lineHeight": "1.5",
        "fontSize": "36",
        "letterSpacing": "1",
        "paragraphSpacing": "1"
      },
      "type": "typography"
    }
```

**Expected behavior**
Expect to see type styles match tokens

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/31367236/132779108-2481e0e1-2ba1-47b0-9d21-8e633ce85a09.png)

**Comment by six7** [comment]
Hey @richardfoong - Have you tried if setting the same properties directly in Figma works? Because from what I can see you're trying to set a font weight of `600`. This won't work, you'd have to specify something like `Regular` or `Bold`

**Comment by richardfoong** [comment]
Ah great that fixed it. I think i had them changed as devs preferred values. Will it be an option in the future to have both? Hopefully I can get them to use naming specifications.

**Comment by six7** [comment]
> Ah great that fixed it. I think i had them changed as devs preferred values. Will it be an option in the future to have both? Hopefully I can get them to use naming specifications.

Sorry for the late reply. Probably not, because Figma doesn't work with the numerical weights, we'd have to do the Mapping on our own.
