### ISSUE TITLE
User roles to avoid editing JSON

### ISSUE THREAD

**Issue by richardfoong** [six7/figma-tokens#251]
There are some great abilities that we would like multiple designers access figma tokens, but because they also get access to the JSON file with the ability to edit tokens, this would be a major headache.

I'd like to have two levels of access - admin and user. Admin has full access, users can view tokens and use the token tabs to switch global brands and dark mode (grouping these would be awesome as well) 

**Describe alternatives you've considered**
 Users - Possibly assign tokens to design, but would be hard to avoid not applying to assets
General - grouping of token tabs to create single source, multiple use (ie brand+dark+breakpoint) :D

**Comment by six7** [comment]
I'm wondering if that's something that would be solvable on JSONbin.io's end. Like, one user adds JSONbin id and correct secret, another user adds a different secret that has only read access.

Next to a Git sync I'm also working on a JSON sync where you'd be able to add a JSON source that you can read (and only read) from. This would fall in nicely.



> I'd like to have two levels of access - admin and user. Admin has full access, users can view tokens and use the token tabs to switch global brands and dark mode (grouping these would be awesome as well)

What do you mean exactly by "grouping these would be awesome" ? Can you elaborate a bit on that (I feel like this should probably belong to its own issue as it could be worked on in isolation)

**Comment by richardfoong** [comment]
Ah read only is a good option to work with! This would also stop passing/updating styles from figma to JSON as well?

The other feature would be more related around nesting groups of tokens to create options to apply a number of sets at once.  I have set up separate sets for core/sematic/component/dark and thinking of separating out breakpoint as a set. I'd like to be able to apply say the three main sets + dark and breakpoint.sm for example as a quick way to toggle multiple sets at the same time.

**Comment by six7** [comment]
> Ah read only is a good option to work with! This would also stop passing/updating styles from figma to JSON as well?

Do you mean that if users update Styles it wouldn't automatically update in JSON? Yes, as they wouldn't be able to `Import Styles` in the plugin. I'll include this in the Read from JSON source update.
