### ISSUE TITLE
Change fill token behaviour to 'fill' only by default

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#26]
'I had a question... When you select and element like shape in Figma and then choose a colour is the expected behaviour that it applies both a fill and a border? I have to keep turning borders off and then they leave them in the inspect section.'

**Comment by okayjeffrey** [comment]
@six7 I am finding the same issue when trying to apply these colors to type. It is adding the a stroke.

**Comment by six7** [comment]
Just fixed this, was bugging me like hell yesterday 😅
