### ISSUE TITLE
JSON input: order of tokens change after “Save & update”

### ISSUE THREAD

**Issue by solemone** [six7/figma-tokens#261]
Hello everyone!

Thanks for the great plugin! I might found a bug.

**Describe the bug**
For spacing tokens I use names like: 025, 050, 075, 100, 150 etc.
If I insert the following order of tokens via the JSON tab after pressing “Save & update” the order changes.

**Example Input**
```
{
  "025": {
    "value": "{primitives.spacing-base} * 0.25",
    "type": "spacing"
  },
  "100": {
    "value": "{primitives.spacing-base}",
    "type": "spacing"
  }
}
```

After pressing “Save & update” tokens starting with “0” are pushed to the end

**Example Output**
```
{
  "100": {
    "value": "{primitives.spacing-base}",
    "type": "spacing"
  },
  "025": {
    "value": "{primitives.spacing-base} * 0.25",
    "type": "spacing"
  }
}
```

**To Reproduce**
1. Go to “JSON”
2. Paste “Example Input” from above
3. Press “Save & update”
4. See new order

**Expected behavior**
Order of tokens should not change.

**Comment by six7** [comment]
Closing this in favor of https://github.com/six7/figma-tokens/issues/122

For numerical fields we currently cannot guarantee an order, but string token names should be sortable ideally.
