### ISSUE TITLE
Enable to exclude tokens from generating styles

### ISSUE THREAD

**Issue by solemone** [six7/figma-tokens#264]
**Is your feature request related to a problem? Please describe.**
I have option tokens for colors. When I generate the styles from the Figma Tokens plugin I don‘t want the options to be generated. 

**Describe the solution you'd like**
An easy fix would be that tokens and/or groups with a prefix like “_” would be excluded from generating the styles.
Another way (favorit): Groups named “Options” or “Primitives” are excluded from generating the styles. Definition could be custom via a settings of the plugin. Like “Exclude all tokens from generating styles in group: <input type="text”>”
Another way: Providing a checkbox for groups and/or tokens “Exclude from generating styles”

**Describe alternatives you've considered**
I could place the options in category “Other” but then I don’t see a preview of the color. 

**Additional context**
Option tokens need to be in the style dictionary export file. A prefix like “_” might not be bad for naming structures.

**Comment by six7** [comment]
I like the _ naming convention, wondering if some users use it right now and expect styles to be generated. I'll dig into this.

**Comment by solemone** [comment]
🥳 Thank you very much Jan!
