### ISSUE TITLE
Inheritance issue on Desktop version

### ISSUE THREAD

**Issue by nilbenis** [six7/figma-tokens#265]
**Describe the bug**
Multiple level inheritance only works on Figma's browser version and only for direct child on desktop version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create more than 2 tokens referencing one another
2. Change parent's value
3. See behaviour on desktop and browser version 

**Expected behavior**
Inheritance shall happen in multiple levels on both desktop and browser version.

Browser: Google Chrome - Version 94.0.4606.71 (Official Build) (x86_64)
OS: MacOS Big Sur - Version 11.6

https://user-images.githubusercontent.com/10983277/136521150-98bdef7f-a0db-4df3-9e11-2fc0426c000d.mov

**Comment by six7** [comment]
Unable to reproduce, tried both in Desktop and Browser and both work fine with the following setup:

```
{
  "colors": {
    "red": {
      "value": "#ff0000",
      "type": "color"
    },
    "brand": {
      "value": "$colors.red",
      "type": "color"
    }
  },
  "button": {
    "color": {
      "value": "$colors.brand",
      "type": "color"
    }
  }
}
```
