### ISSUE TITLE
Sync with json from github

### ISSUE THREAD

**Issue by lukasoppermann** [six7/figma-tokens#271]
**Is your feature request related to a problem? Please describe.**
When distributing design tokens via github, it is a potential problem if users have to download a json from a repo to update it in figma.

**Describe the solution you'd like**
It would be great if the plugin could sync with a json file (similar to jsonBin) from github. 
E.g. just point it at a github url to the raw file, add access credentials and allow it to sync this way. (Ideally it would even grab the version from a package.json if it exists)

**Describe alternatives you've considered**
Using JsonBin is not an option for every org. :( It also means another source of truth that is not the same as the one the dev team uses.

**Comment by six7** [comment]
Hey @lukasoppermann - thanks for the feedback, I really appreciate it! ❤️ 

I'm pretty far along with a github sync and am currently running the beta with some teams. If you'd like to betatest that feature I've written a [short guide](https://figma-tokens-docs-git-git-sync-beta-six7.vercel.app/sync/github).

The feature is working so far, I'm mainly looking for feedback regarding if that solution could work or if there's anything broken in edge-cases.

I've also setup a [test repository](https://github.com/six7/tokens-example) that transforms tokens stored in Figma Token to something SD can work with (no math). That repo contains a lot of code that's not needed for demonstrative purposes but I've set it up so there's a live updating token reference page at https://tokens-example.vercel.app/ - the interesting part is the github action that uses both `token-transformer` (strip tokens of math, aliases and combine themes) and `style-dictionary`

**Comment by vkoopmans-resoluut** [comment]
I got the Beta version running and syncing the json to Github. Though the part after that I can't seem to get working :)
Figma Tokens .json -> Token-Transformer -> Style-dictionary

(I blame the lack of Git knowledge on my part :D

**Comment by vkoopmans-resoluut** [comment]
Thank you, I'll try this out!
