### ISSUE TITLE
Nested components from library do not adhere to resizing tokens

### ISSUE THREAD

**Issue by neatlittlemacapps** [six7/figma-tokens#273]
**Describe the bug**
I have nested components that make up a button.
There is a size token set to define the "height" of this base component.
When altering the height token, the base component and the final button in which this is nested all size up correctly when doing this in the library.

Pulling in the component in another file, and adjusting the sizing token there does not alter the height of the component.

**To Reproduce**
1. open Pixel DS.fig file
2. make sure the tokens are loaded
3. in the 3rd tab of the tokens (T3 components) alter the button.large token (change it to 7x-large for example). and apply to the document.
4. you will see the relevant large button change.
5. Now publish this file as a library
6. create a new file and load up the libray
7. place the button from the library
8. load up the same (original) tokens
9. change the same size variable here 

**Expected behavior**
The button should change in height
instead, it remains the same height as the original component.

**Screenshots or Screencasts**
[See video](https://youtu.be/Yya-TAqKtxk)

figma and json in attach
[PXL DS.zip](https://github.com/six7/figma-tokens/files/7332074/PXL.DS.zip)
*
[Pixel DS.fig.zip](https://github.com/six7/figma-tokens/files/7332073/Pixel.DS.fig.zip)

**Comment by six7** [comment]
I think this is something we can't fix as you can't change the size of an instance. This is on Figma's end, not the plugin's end.

**Comment by six7** [comment]
Closing for now, feel free to reopen if you feel the plugin should support this in another way.
