### ISSUE TITLE
Apply tokens when matching style is applied.

### ISSUE THREAD

**Issue by lukasoppermann** [six7/figma-tokens#279]
**Is your feature request related to a problem? Please describe.**
Many of the designers using my design system prefer to use figma color and text style as it is a bit more convenient within the figma workflow. It is great that you can create style from, tokens.

However I would love to see the token being applied, when a matching style is added. And the style being applied when a token used.

**Describe the solution you'd like**
Whenever a user applies a figma style that has a matching token, the token should also be applied to the element (and thus visible in the token inspect mode)

Whenever I apply a token via the plugin, it would be great if the style (if it exists) is applied to the element instead of the raw value.

**Comment by six7** [comment]
I'll be closing this as not planned. I think we'll have a way to batch apply tokens where a style that matches the ID was applied, but we won't do that automatically.
