### ISSUE TITLE
Add new typography tokens (letter spacing, paragraph spacing)

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#28]
We should add two new tokens to typography options (letter spacing, paragraph spacing)

Include in
- Seperate tokens
- Typography decisions

**Comment by chetfarley** [comment]
Love this plugin! I would also like to be able to add text-transform as a token, for instance, to style headings as uppercase.

**Comment by six7** [comment]
Should be no problem to add and will definitely be needed if we want styles to be defined purely by tokens.

Figma offers TextCase in their Plugin API: https://www.figma.com/plugin-docs/api/TextCase/#docsNav
