### ISSUE TITLE
Style Dictionary Output References

### ISSUE THREAD

**Issue by markacianfrani** [six7/figma-tokens#284]
Looking at the docs for Style Dictionary's outputReferences support https://amzn.github.io/style-dictionary/#/version_3?id=output-references I noticed that their syntax is slightly different. 

Given that I have a very basic typography style in Figma, the plugin outputs: 
```
{
	"fontFamilies": {
		"sans": {
			"value": "sans",
			"type": "fontFamilies"
		}
	},
	"body": {
		"b1": {
			"fontFamily": {
				"value": "{fontFamilies.sans}"
			}
		}
	}
}
```

When ran through SD, using the [basic config](https://raw.githubusercontent.com/amzn/style-dictionary/main/examples/basic/config.json) we get:
```
$font-families-sans: sans;
$body-b1-font-family: [object Object];
```

Their example shows you need to reference .value in your alias. So if we change our token.json to:
```
{
	"fontFamilies": {
		"sans": {
			"value": "sans",
			"type": "fontFamilies"
		}
	},
	"body": {
		"b1": {
			"fontFamily": {
				"value": "{fontFamilies.sans.value}"
			}
		}
	}
}
```

We get:
```
$font-families-sans: sans;
$body-b1-font-family: $font-families-sans;
```
if we set `outputReferences` to true. 

Which is amazing. 

Is this something the plugin should support out of the box? I'm not sure how others are using aliases because the first example doesn't work.

**Comment by markacianfrani** [comment]
Good catch with the spec. I put in a [PR](https://github.com/amzn/style-dictionary/issues/721) on Style Dictionary itself to see if they'd be willing to make a change on their end. I feel like it's probably best to follow the spec in this case. Even though it's just a draft, I can't imagine that part changing.

**Comment by zetareticoli** [comment]
I have the same issue here with colors

<img width="432" alt="Schermata 2021-11-24 alle 12 46 11" src="https://user-images.githubusercontent.com/69706/143232798-17d056dc-ed9f-47a7-8622-6b74180540a1.png">

Adding `.value` to the end of reference breaks the color preview in the plugin

<img width="317" alt="Schermata 2021-11-24 alle 12 46 18" src="https://user-images.githubusercontent.com/69706/143232876-e9423be7-7cb4-4dcc-92ad-3466a2b65dfa.png">

But Style Dictionary works fine this ways. 

```css
$light-background: #fff;
$light-text: #111827;
$light-text-weak: #6b7280;
$light-text-light: #9ca3af;
$light-background-strong: #080b12;
$light-background-light: #f3f4f6;
$light-border: #e5e7eb;
$light-state-active: #c2410c;
$light-state-hover: #f97316;
$light-text-primary: #ea580c;
```

If I remove the `.value` I get `[object Object]` output instead.

Any update on this?

**Comment by zetareticoli** [comment]
+1

**Comment by six7** [comment]
We're waiting for a fix on Style Dictionary end for this as the W3C draft doesn't have the `.value` prop in the draft.

A PR seems to be coming 🙏 

https://github.com/amzn/style-dictionary/pull/746

**Comment by zetareticoli** [comment]
@six7 thanks for the update 🙏

**Comment by devilcoders** [comment]
@six7 Style dictionary PR merged 🎉

**Comment by zetareticoli** [comment]
When it should be released?

**Comment by jakobe** [comment]
@six7 So I guess the fix in Style Dictionary ([amzn/style-dictionary#746](https://github.com/amzn/style-dictionary/pull/746)) with the optional `.value` suffix now allows the output of Figma Tokens to be directly transformed by Style Dictionary without appending the `.value`suffix to each alias beforehand.

Not sure if it should also work the other way around? I.e. being able to reference other tokens using `{alias.value}`? As far as I can see [the spec doesn't mention this](https://design-tokens.github.io/community-group/format/#aliases-references).

If not, then this issue could be closed...

**Comment by six7** [comment]
Agree, I think we can close this one for now. If we'd decide in the future to allow aliases to not just reference the value but also description or other custom fields on a token then we'd need something like that, but for now we're good.
