### ISSUE TITLE
Gradient color styles do not work when generated from the plugin

### ISSUE THREAD

**Issue by katywatkins** [six7/figma-tokens#286]
**Describe the bug**
Gradients display in the plugin but not in Figma color styles generated by the plugin

**To Reproduce**
1. Copy JSON below into plugin
2. Hit 'Create Styles'
3. The gradients that display fine in the Figma Tokens window do not translate over to color styles

**Expected behavior**
Gradients appear in the generated styles

**Screenshots or Screencasts**
<img width="666" alt="Screen Shot 2021-10-21 at 12 22 49 PM" src="https://user-images.githubusercontent.com/1926679/138318657-abd22207-efbd-4eec-a5e1-85f6504d4376.png">

**JSON (optional)**
```
{
  "status": {
    "cancelled": {
      "type": "color",
      "value": "repeating-linear-gradient(135deg, #f8f3e0, #f8f3e0 6px, #efebda 6px, #efebda 12px)"
    },
    "test": {
      "value": "linear-gradient(#e66465, #9198e5)",
      "type": "color"
    },
    "in-progress": {
      "type": "color",
      "value": "#89CFF0"
    }
  }
}
```

**Comment by six7** [comment]
Gradient support should be way better, ideally we'd have a UI that helps users build these visually.

Right now only linear-gradients are supported, and you'd have to specify it like this:
`linear-gradient(90deg, #ffffff 0%, #000000 100%)`

There's a bug with their direction not resolving correctly, though: https://github.com/six7/figma-tokens/issues/156

**Comment by six7** [comment]
I'll close this in favor of #421 which is more generic. Thanks again for the report!
