### ISSUE TITLE
List view for themes

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#288]
**Is your feature request related to a problem? Please describe.**
I am working with 20+ themes, and soon there will be more. I've got to activate two themes at once out of this list to set my theme to a page. The horizontal scrolling in the tiny window makes this quite hard.

**Describe the solution you'd like**
A list view or dedicated page to themes without horizontal scrolling. Ideally, this list view also provides some groups which can be activated together. For example, if brand a requires theme a1 and theme a2, these could be grouped and activated together.

This would be amazing :)

**Comment by phantasmagoriadigital** [comment]
+1 for this. We use one token group/theme per component, plus base tokens group, plus semantic group, and it's painful to use the horizontal scroll. Dropdown with autocomplete and multi select checkboxes would be really great!

**Comment by Blyawon** [comment]
I like the idea with the input and autocomplete :)

**Comment by six7** [comment]
Definitely needed! The horizontal scroll was implemented as a quick win, but serious theme management is super tedious like this.

I'm open for design suggestions if you had anything specific in mind!
