### ISSUE TITLE
Typography JSON format no longer works with Style Dictionary

### ISSUE THREAD

**Issue by bfoong-equinix** [six7/figma-tokens#293]
**Describe the bug**
This is actually the same issue that was raised and [closed](https://github.com/six7/figma-tokens/issues/227) . Creating this new issue for better visibility.

![139067612-b9917645-8586-42f7-9ecb-e50b6757a96e](https://user-images.githubusercontent.com/85331145/139244554-7e87b47d-3eeb-4cb8-ba7e-813a8fc40808.png)

**Comment by six7** [comment]
Just tested this and it works. Could it be you were not using the Export function? It will only work with the Export.

https://user-images.githubusercontent.com/4548309/139600126-aa20ec8e-f54a-46d0-a213-914a9cfe52f4.mov

Closing this, feel free to reopen.

**Comment by bfoong-equinix** [comment]
Thanks for the hint. Not sure why but Export works after clicking on "Save & update".
