### ISSUE TITLE
Something went wrong! Figma Tokens Version 66

### ISSUE THREAD

**Issue by gyddfev** [six7/figma-tokens#296]
**Describe the bug**
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bvalue%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Restart the plugin and try again.

Figma Tokens Version 66

**Expected behavior**

**Screenshots or Screencasts**
[https://s6.jpg.cm/2021/10/31/I3zABT.gif](url)

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

"标题Text": {
    "34Bold": {
      "type": "typography",
      "value": {
        "fontFamily": {
          "value": "$fontFamilies.pingfang-sc"
        },
        "fontWeight": {
          "value": "Bold"
        },
        "lineHeight": {
          "value": "$lineHeights.0"
        },
        "fontSize": {
          "value": "34"
        },
        "letterSpacing": {
          "value": "$letterSpacing.0"
        },
        "paragraphSpacing": {
          "value": "$paragraphSpacing.0"
        }
      }
    },
    "32Bold": {
      "type": "typography",
      "value": {
        "fontFamily": {
          "value": "$fontFamilies.pingfang-sc"
        },
        "fontWeight": {
          "value": "$fontWeights.pingfang-sc-0"
        },
        "lineHeight": {
          "value": "$lineHeights.0"
        },
        "fontSize": {
          "value": "$fontSize.0"
        },
        "letterSpacing": {
          "value": "$letterSpacing.0"
        },
        "paragraphSpacing": {
          "value": "$paragraphSpacing.0"
        }
      }
    }
  },

**Comment by six7** [comment]
The error here lies in the definition of your typography tokens, they should be defined like this instead:

```
"32Bold": {
  "type": "typography",
  "value": {
    "fontFamily": "$fontFamilies.pingfang-sc",
    "fontWeight": "$fontWeights.pingfang-sc-0",
    ...
  }
}
```

The crash will be fixed in the next release, but the tokens should be entered like above
