### ISSUE TITLE
Exported JSON file from Figma Token plugin removes parent object

### ISSUE THREAD

**Issue by tarikhaiga** [six7/figma-tokens#301]
**Description**
Exported JSON file from Figma Token plugin removes parent object.

**To Reproduce**
1. Launch Figma Token plugin
2. If you don't have any styles, add or import some. Otherwise move to step 3
3. Navigate to JSON tab on Figma Token plugin
4. Note that there is a parent object (called 'global' by default). Click Export.
5. Open `.json` file and you will see that 

**Expected behavior**
I would expect that the exported `json` file keeps the parent object in place.

**Screenshots**
Problem:
<img width="450" alt="current problem" src="https://user-images.githubusercontent.com/13916243/140086443-ca054a9d-0ae3-4c05-af14-c72dd8f93fc5.png">
Solution:
<img width="450" alt="proposed solution" src="https://user-images.githubusercontent.com/13916243/140086516-35c322e4-a6e4-4691-8968-6c0d12815cfd.png">

**Why fix this bug?**

`token-transformer` npm module will not work properly with an input file that is the json file directly exported from Figma Tokens plugin. The `output.json` file that the module generates will have missing objects.

**Comment by jdwillemse** [comment]
@six7 What is the desired solution here? 

I made fix that maintains the parent, but this fails some tests so I'm not sure what should happen here
