### ISSUE TITLE
Apply to selection not working

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#302]
**Describe the bug**
Apply to selection applies styles to the whole page

**To Reproduce**
1. Select frame
2. Apply styles to frame with "apply to selection"

**Expected behavior**
Styles get only applied to selection

**Comment by Blyawon** [comment]
Ok, it rather seems that individual artboards are somehow linked? It's super strange.

**Comment by six7** [comment]
Just checked, works fine!

If you were applying a Color Style: Styles are global to the document, so when you change a style you change it for everything. This isn't something the plugin can't fix.

Let me know if I misunderstood 🙏

**Comment by Blyawon** [comment]
Yes, I was applying color styles. Did something change? 
I saw that now color styles also appear in the figma style panels, is this something that has to do with that?
