### ISSUE TITLE
Add pretty boxShadow input

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#312]
As we'll have support for multiple shadow tokens we need to optimize the current shadow edit UI a bit.

Early concepts:

![image](https://user-images.githubusercontent.com/4548309/140623907-ed17a910-540a-44b8-a278-02f736f57af2.png)

Constraints compared to how Figma does it:
- We need to show full token name to understand decisions
- We need to drag order around
- We need to be able to remove a specific shadow from array
- We need to add new shadows to array
- We need to support both dropShadow and innerShadow

**Comment by Blyawon** [comment]
Just wanted to create a request for this :)
Awesome!

**Comment by Blyawon** [comment]
Hey @six7 do you already have a rough idea when this is going to be implemented?

**Comment by six7** [comment]
Planning to release it this week. Just adding tests.

You could try it out in the Web UI today: https://figma-tokens-git-box-shadows-six7.vercel.app/ui.html - just create a box shadow token or import the preset (or your own json)

**Comment by Blyawon** [comment]
Awesome!
