### ISSUE TITLE
Add pretty typography input

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#313]
In addition to #312 we should also optimize the typography inputs.

Early concept:

![image](https://user-images.githubusercontent.com/4548309/140623964-f25c9b16-3dc8-4610-9788-d3f0cedb6d15.png)

With textCase and textDecoration coming this is badly needed to make up for the raw UI we've had for a long time now.

**Comment by badjar** [comment]
Bravo! This would be a big improvement.
