### ISSUE TITLE
Updating a layer that has a Typography token applied outside of the styles library file hex colors are applied instead

### ISSUE THREAD

**Issue by petercolesdc** [six7/figma-tokens#318]
**Describe the bug**
When an update is made to typography with the plugin, it unlinks Figmas text style (see screens)

**To Reproduce**
1. Go to a Figma style and apply to a piece of text
2. Open the plugin and change a variable using the 'typography settings'
3. Press update
4. All Figma text styles are now unlinked

**Expected behavior**
I would expect Figma styles to update, rather than the link become broken

**Screenshots or Screencasts**

**Figma style selected**
<img width="1190" alt="Screenshot 2021-11-09 at 14 28 09" src="https://user-images.githubusercontent.com/118106/140942742-668b212b-32d7-45ca-b9be-e8436af6abb0.png">

**When update is made, style becomes detached**
<img width="1179" alt="Screenshot 2021-11-09 at 14 28 18" src="https://user-images.githubusercontent.com/118106/140942747-71e347ff-8639-4c45-b3a0-64fe31240473.png">

**Comment by six7** [comment]
Are the styles local to that document or do they come from a library?

Is there a reason to use the plugin to apply the type token? I recommend to not apply type and color styles with the plugin but use figma's styles instead. Reason is that the plugin currently is unaware of any styles from a library (as it's not exposed by Figma) and thus applies the raw hex value. If we saved the styleId to each token, we could. Also, if the style is local to that file, the plugin does know about it and will apply the style.

Tracking that issue in https://github.com/six7/figma-tokens/issues/145

**Comment by petercolesdc** [comment]
Hiya

So i'm not using the plugin to change styles. The above happens if I change a variable that is applied to a style. So, for example, if I change the font-size on a text setting in the plugin, it then breaks the link to that style in figma as seen above.

**Comment by six7** [comment]
Could you send me a screenshot of that layer with the plugin's Inspect panel open? I think you have a Typography token applied there.

**Comment by six7** [comment]
Closing this for now, please reopen when it still appears (check that you don't have a typography token applied there)
