### ISSUE TITLE
GitHub sync: Provide support for Enterprise Server

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#319]
Customers of GitHub Enterprise Server can't currently use the GitHub sync. 

In order to allow that, we need to let the user set a baseUrl.

https://octokit.github.io/rest.js/v18

**Comment by drewbrend** [comment]
✋  GitHub Enterprise user here that is currently working with designers on our process for tokens.  Do you have a rough estimate for when this will be available?

**Comment by six7** [comment]
Currently in development, you can help this by either trying it in the Web UI: https://figma-tokens-git-github-sync-enterprise-six7.vercel.app/ui.html

or downloading the package an trying the development version: https://github.com/six7/figma-tokens/suites/4405486526/artifacts/116311808
