### ISSUE TITLE
Spaces in token name doesn't work

### ISSUE THREAD

**Issue by jakobe** [six7/figma-tokens#323]
**Describe the bug**
It seems like spaces in token names are not allowed by the plugin? Even though there's no visual indication (e.g. a red border on the input) it appears the plugin doesn't allow you to put a space in the name when you're adding/editing a token and it can't lookup an alias with spaces in it's name?

**To Reproduce**

_Edit:_
1. Edit any token
2. Add a space in the name
3. See the "Update" button being disabled

_Lookup:_
1. Edit any token
2. Add a space in the alias value
3. See the lookup value / bar disappear

**Expected behavior**
AFAIK Style Dictionary doesn't imply any rules regarding naming of tokens (casing, spaces etc), so I don't see why the plugin should. I.e. it makes it impossible to use a style / token called "Light Blue" for example.

**Screenshots or Screencasts**
**🚫  Not allowed:**
![image](https://user-images.githubusercontent.com/9556693/141785160-960e130a-d87a-4bd9-adf6-78a47e751ebd.png)

**✅  Working:**
![image](https://user-images.githubusercontent.com/9556693/141785249-95e916e0-950d-4c7a-a14e-6de2abf7ccb4.png)

**❌ NOT working:**
  ![image](https://user-images.githubusercontent.com/9556693/141785286-ade104af-bab3-4386-a8bf-3c79db1fd8f7.png)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by jchiem** [comment]
I think one problem with the current implementation is that it's possible to import design tokens with spaces in the name, but you are unable to rename/save them unless you remove the spaces in the name.

**Comment by jakobe** [comment]
> I think one problem with the current implementation is that it's possible to import design tokens with spaces in the name, but you are unable to rename/save them unless you remove the spaces in the name.

Yes @jchiem, you are right that kinda enforces the problem. And since Figma allows spaces in names of Styles and Style Dictionary allows spaces in keys, I don't see any reason why the plugin shouldn't :)

**Comment by six7** [comment]
I agree, should be an easy fix.

The W3C draft also has a space in their example token name, so this should be supported. https://design-tokens.github.io/community-group/format/#name-and-value

**Comment by six7** [comment]
Fixed in release 69 🎉
