### ISSUE TITLE
FIgma Tokens Github Integration not saving credentials

### ISSUE THREAD

**Issue by phil-isaacs** [six7/figma-tokens#325]
**Describe the bug**

I've been trying to set up Github Sync integration. I've followed the instructions per the documentation (set up my repo and personal access token" but the plug in doesn't seem to recognize or save the credentials data. So every time I go to the plugin I see no data regarding the my github repo. I was under the impression (based on the documentation) that once I set up my credentials I would see that a entry for it in the plugin under the Github tab.

**Comment by phil-isaacs** [comment]
Okay, it was actually my own error. I had to dig into the console logs but it was that i didn't authorise my Organization to recognize the token. 

The error looks like this. Check your Console log.

`Error pushing to GitHub HttpError: Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.
    at <anonymous>:130:2235
VM585:116 Error HttpError: Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.
    at <anonymous>:130:2235`

If anyone else runs into this issue (it's not in the docs per say) but once you create an Access token you need to save it and then configure it by selecting the "Configure SSO" option. Otherwise it won't work.

**Comment by Velrethar** [comment]
I have not been able to find the "Configure SSO" option. Is that in the plugin, or is that in the repo I make on GitHub?
