### ISSUE TITLE
Gradient's orientation after importing

### ISSUE THREAD

**Issue by ahhauhhu** [six7/figma-tokens#326]
**Describe the bug**
Gradient's orientation is changed after the color has been imported into the plugin, from vertical to horizontal. But when applying that gradient from the plugin to a shape in Figma, the gradient stay the same as before, vertical.

**To Reproduce**
1. Create a style of a gradient color with vertical orientation
2. Import the style into the plugin
3. The orientation of the gradient is now horizontal from the look of the color's preview
4. When applying that gradient to a CSS demo, the orientation is horizontal
5. When applying that gradient to a shape in Figma, the orientation is vertical

**Expected behavior**
In CSS, orientation of the gradient should stay vertical after importing

**Screenshots or Screencasts**
Gradient is vertical before importing: 
![image](https://user-images.githubusercontent.com/30395676/142134624-1c45c0fc-7e4f-4c7f-ab35-fbe05a6ff32e.png)

Gradient is horizontal after importing:
![image](https://user-images.githubusercontent.com/30395676/142134669-87262032-65b7-4f7e-8c78-a5e36ab2f799.png)
![image](https://user-images.githubusercontent.com/30395676/142135267-f3b4c921-315b-4c93-b6e6-a5f55f98954b.png)

Gradient is horizontal as shown in a CSS demo:
![image](https://user-images.githubusercontent.com/30395676/142135208-fd6b2a15-9330-4bfb-88cb-1ed78d43e5dd.png)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Fixed in version 77! 🎉
