### ISSUE TITLE
Clearer Headers & Nesting

### ISSUE THREAD

**Issue by okayjeffrey** [six7/figma-tokens#33]
## Situation:
In the master color area I have two types of color sections. 
- Master Scales 
  - [Color name]
- Theme
  - [Use case]

## Issue
It is pretty difficult to differentiate between a heading and sub-heading for scan-ability. I AM STOKED though that it supports the nesting and didn't just break like other things I have used in the past.

<img width="415" alt="01 - Opening Up 2020-10-12 17-44-16" src="https://user-images.githubusercontent.com/99021/95802608-d0b27380-0cb2-11eb-8c3b-ce7b3cc67478.png">

### Sub-issue
The color white does not show in the grid view. Maybe a slight border around it?

**Comment by six7** [comment]
Noticed this yesterday as well, that's something that got introduced by a recent UI update. Will fix this!

**Comment by six7** [comment]
@okayjeffrey should be (a bit) better now!

**Comment by okayjeffrey** [comment]
Sick thanks will check it out soon!
