### ISSUE TITLE
Renaming Token loses connection to objects

### ISSUE THREAD

**Issue by vkoopmans-resoluut** [six7/figma-tokens#330]
**Describe the bug**
If a token like border radius is applied to an object, and the specific token name is changed, the object loses the connection to that token 

**To Reproduce**
1. apply border radius to a rectangle
2. Change name of token within Figma Tokens
3. rectangle lost it's connection to that token

**Expected behavior**
I would imagine I could just change the name

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by Andyrrrrr** [comment]
Also came here to point this out. Would be very nice to be able to freely re-name tokens and maintain the connection.

**Comment by six7** [comment]
Closing this in favor of https://github.com/six7/figma-tokens/issues/211
