### ISSUE TITLE
Border-color token does not apply as layer style

### ISSUE THREAD

**Issue by alaurag** [six7/figma-tokens#331]
**Describe the bug**
When applying color token to a layer's border, the color is applied as a color, and not as a color style.
If applying the same color token to a layer's fill, then the color is applied as expected, that is, as a color style

**To Reproduce**
1. Select the object you want to apply the border-color to.
2. Right click on the color token and select "Border"
3. The color is applied as a color and not as a color style. This can be checked by looking into the Design Panel.

**Expected behavior**
The color token is applied as a color style.

**Screenshots or Screencasts**
![Figma Tokens stroke color issue](https://user-images.githubusercontent.com/94849290/142879158-e8d24309-bd54-4360-a03d-4306f67ed1c4.png)

**Figma file (optional)**
Just create a new file and add, I.e., a rectangle. Then, apply the color token to both the stroke and the fill

**JSON (optional)**
[tokens.json.zip](https://github.com/six7/figma-tokens/files/7581938/tokens.json.zip)

**Comment by enamulkhanbd** [comment]
how to define stroke inside or outside?

**Comment by samuelcouto** [comment]
> how to define stroke inside or outside?

I'm having exactly the same issue... Is it even possible to define a border to be set `Outside` ? By default I'm seeing that all borders are set to `Inside`.
