### ISSUE TITLE
YAML...? [Request]

### ISSUE THREAD

**Issue by okayjeffrey** [six7/figma-tokens#34]
Just been thinking a lot of the larger libraries are using YAML for easier integration with non-engineering contributors for ease of use. It has an easier syntax which might lead to less errors so edits can be made easier in plugin directly.

**Comment by okayjeffrey** [comment]
Also to clarify this one... not exporting YAML but having it as an alternative input method

**Comment by six7** [comment]
I'm not very experienced with converting JSON to YML but I can't imagine it would be very difficult to add. We could I think make it so that a user could switch input modes from YML to JSON if it's that easy to convert

**Comment by okayjeffrey** [comment]
Sadly I'm more visual and only know enough to be dangerous in react. 😐

But this nice article by [Nathan Curtis](https://link.medium.com/676cW8D8Fab) outlines how they use YAML that's pretty nice and they reference [YamlJS](https://www.npmjs.com/package/yamljs)

Input modes is a cool idea, because on your roadmap "syncing to a JSON file" That could be another input type "external file". Because I feel like the need of the raw text field might still be valid.

**Comment by six7** [comment]
Closing this as not planned.
