### ISSUE TITLE
[GitHub Sync]: Introduce branch switch

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#341]
It would be great to have a branch switch like VSCode has. When user has tokens that haven't been pushed ask if they want to discard. The branch switcher should show all available branches and give an option to create a new branch.

**Comment by iamnbutler** [comment]
We'd love this so we can be more pragmatic about working in a dev/staging branch, and have a stable/main branch for the prod app. It'd be awesome to easily switch between the two.

**Comment by six7** [comment]
Will be part of the next release 🙏
