### ISSUE TITLE
Token-transformer readme wrong command

### ISSUE THREAD

**Issue by scharbaux** [six7/figma-tokens#343]
**Describe the bug**
Not really a bug, rather a discrepancy in the tokens-transformer Readme documentation. The command displayed to transform tokens to Style Dictionary uses `npm` (which will throw the error "Command "tokens-transformer" not found.") but should be using `node` as per the correct command in the Docs > Sync > GitHub section.

The same error is visible in the npm package's description [here](https://www.npmjs.com/package/token-transformer).

**Comment by scharbaux** [comment]
Was gonna make a quick PR to update the Readme but it seem like I'd require some contributor permission for that. Not a big deal I guess someone can piggy back an open PR to update this. 😄

**Comment by six7** [comment]
Thanks for reporting! I updated the readme (had to deploy a new version anyway) and included install instructions to install globally so `node token-transformer` works
