### ISSUE TITLE
Github Sync: Groups are not maintained and all of them are under Others

### ISSUE THREAD

**Issue by senthil-kk20** [six7/figma-tokens#345]
When I pull the JSON from Github, the groupings are not working as expected. All of them are added under others but the local JSON was rendered properly

Attached is the screenshot.
<img width="417" alt="Screenshot 2021-11-29 at 2 50 27 PM" src="https://user-images.githubusercontent.com/5101306/143840857-a2d5985c-181f-466f-82cc-c8b148ac239f.png">

**Comment by six7** [comment]
How does your JSON input look like? Do each of these tokens in JSON have a `type: color` property? The plugin usually puts tokens into the `other` category when it can't find a `type` property on the token.

**Comment by six7** [comment]
Closing this for now, feel free to reopen if the issue persists
