### ISSUE TITLE
Apply type styling unclear

### ISSUE THREAD

**Issue by okayjeffrey** [six7/figma-tokens#35]
I totally found this by accident! Its a rad feature but was not super discoverable... Especially when the color blind setting is on.

# Concept
Maybe creating a builder at the bottom, so when the parameters are chosen it shows them building in a bar

![Concept](https://user-images.githubusercontent.com/99021/96032361-682ed800-0e13-11eb-8727-79d958057306.png)

**Comment by six7** [comment]
I really like that! Makes selecting tokens a bit more readable. especially like that it would work towards a Compositions mode #31 where a user could select multiple tokens, group them together to generate a composition.

**Comment by okayjeffrey** [comment]
@six7 thanks glad you like it! 

Interesting this kinda leads into another question I had... obviously people will still use the default styles in Figma, so do you ever plan to create a reference/association to actual styles? Because the compositions would be super powerful then, make a composition then create a style. Then have the style referenced.

So you'd basically be mirroring the doc styling BUT have the power of all the building block tokens.

**Comment by six7** [comment]
Right now when you hit the `Create Styles` button the plugin checks if there are local styles that have the same name - yes it will update that style, if not it will create it. If you then change any tokens the styles get updated as well.

Working on adding typography import right now which basically takes your existing styles and extracts used values into their tokens but keeping  reference in the typography composition.

**Comment by qvsoft** [comment]
It's better if we can show the values in case token can be applied in different way, eg: Border Radius 5(TopLeft + BottomRight), or Spacing 10(Vertical). So we don't need to right click on the token to see which kind of value had been applied.
And is there anyway we can show the value in figma panel at bottom right, now it just show the name without value?
![2021-06-03_18-40-28](https://user-images.githubusercontent.com/3038514/120639189-4ade7500-c49b-11eb-8e76-fe298baa0e4d.png)

**Comment by qvsoft** [comment]
And if we apply token to component, then if we select the instance, the token also be highlight, it would be good if we have an indicator to know that the token is applied in master component, or also be applied/override in instance.
