### ISSUE TITLE
[token-transformer]: Parent object keys are stripped during token-transform

### ISSUE THREAD

**Issue by jdwillemse** [six7/figma-tokens#350]
**Describe the bug**
When I run the token-transform script on a Github exported file the top-level keys (in my case the theme names) are removed and the objects are merged

**To Reproduce**
I have this as my input file that needs to be converted 
```json
{
  "global": {
    "spacing": {
      "scale": {
        "value": "2",
        "type": "spacing"
      },
      "xs": {
        "value": "4",
        "type": "spacing"
      },
      "sm": {
        "value": "{spacing.xs} * {spacing.scale}",
        "type": "spacing"
      }
    }
  },
  "theme": {
    "spacing": {
      "scale": {
        "value": "3",
        "type": "spacing"
      },
      "xs": {
        "value": "6",
        "type": "spacing"
      }
    }
  }
}
```
When I run `token-transformer` I get the following output
```json
{
  "spacing": {
    "scale": {
      "value": 3,
      "type": "spacing"
    },
    "xs": {
      "value": 6,
      "type": "spacing"
    },
    "sm": {
      "value": 18,
      "type": "spacing"
    }
  }
}
```

**Expected behavior**
I expect the output to be 
```json
{
  "global": {
    "spacing": {
      "scale": {
        "value": 2,
        "type": "spacing"
      },
      "xs": {
        "value": 4,
        "type": "spacing"
      },
      "sm": {
        "value": 8,
        "type": "spacing"
      }
    }
  },
  "theme": {
    "spacing": {
      "scale": {
        "value": 3,
        "type": "spacing"
      },
      "xs": {
        "value": 6,
        "type": "spacing"
      }
    }
  }
}
```

**Comment by jdwillemse** [comment]
@six7 I do not know if this is related, but should `theme.sizing.sm.value` equal 20 or 30 here?
```json
{
    "global": {
        "sizing": {
            "scale": {
                "value": "2",
                "type": "spacing"
            },
            "sm": {
                "value": "{sizing.scale} * 10",
                "type": "spacing"
            }
        }
    },
    "theme": {
        "sizing": {
            "scale": {
                "value": "3",
                "type": "spacing"
            },
            "sm": {
                "value": "{sizing.scale} * 10",
                "type": "spacing"
            }
        }
    }
}
```
I would expect 30, but this is not the case

**Comment by six7** [comment]
What do you think about having this as a parameter you pass to token-transformer? 

For me stripping the parent keys make total sense, as my themes do not need to be aware that they're part of the light or dark theme.

However, I think having this as an option where the user would get the output would be ideal.

Also: Yes, should be 30 🤔

**Comment by jdwillemse** [comment]
When the root keys are stripped the tokens nested below with the same name are merged (see the output in this bug ticket). I find it surprising as a user that the structure in the Figma interface is not maintained after the transformation without any warning. If this is desired it can be an option along with the other option that offers to remove the first word from the export. I don't think it should be the default behaviour.

Could you maybe share an export of your token setup to show how you use it where this is not a problem? My team is using this plugin in production for the first time so we might be using it in an unusual way 🤷🏻  😅

**Comment by jdwillemse** [comment]
Would it be acceptable to modify the plugin in such a way that aliases are always absolute rather than relative? This would remove all ambiguity from the alias implementation.

This is how style dictionary handles aliases https://amzn.github.io/style-dictionary/#/version_3?id=transitive-transforms. 

Here is what the JSON would look like:
```json
{
    "global": {
        "sizing": {
            "scale": {
                "value": "2",
                "type": "spacing"
            },
            "sm": {
                "value": "{global.sizing.scale} * 10",
                "type": "spacing"
            }
        }
    },
    "theme": {
        "sizing": {
            "scale": {
                "value": "3",
                "type": "spacing"
            },
            "sm": {
                "value": "{theme.sizing.scale} * 10",
                "type": "spacing"
            }
        }
    }
}
```

**Comment by six7** [comment]
> Would it be acceptable to modify the plugin in such a way that aliases are always absolute rather than relative? This would remove all ambiguity from the alias implementation.
> 
> This is how style dictionary handles aliases https://amzn.github.io/style-dictionary/#/version_3?id=transitive-transforms.
> 
> Here is what the JSON would look like:
> 
> ```json
> {
>     "global": {
>         "sizing": {
>             "scale": {
>                 "value": "2",
>                 "type": "spacing"
>             },
>             "sm": {
>                 "value": "{global.sizing.scale} * 10",
>                 "type": "spacing"
>             }
>         }
>     },
>     "theme": {
>         "sizing": {
>             "scale": {
>                 "value": "3",
>                 "type": "spacing"
>             },
>             "sm": {
>                 "value": "{theme.sizing.scale} * 10",
>                 "type": "spacing"
>             },
>            "lg": {
>                 "value": "{global.sizing.scale} * 10",
>                 "type": "spacing"
>             }
>         }
>     }
> }
> ```

I'm worried this will make themeability worse. Right now it's very flexible as the theme name doesn't infer with the token name, meaning you can have this:

```
light:
  theme.colors.bg.default: white

black:
  theme.colors.bg.default: black
```

If theme names would be part of aliases then you'd lose the ability to dynamically reference `{theme.colors.bg.default}` and instead you had to reference `dark.theme.colors.bg.default` unless I'm missing something? I'd like to think of token sets in the plugin as folders in style dictionary.

**Comment by jdwillemse** [comment]
Ok, let's take your use case as a starting point. Here's how I would expect it to look from an implementation standpoint. In CSS one would define the colour schemes in the following way

```scss
h1 {
  color: $light-color-text
}

@media (prefers-color-scheme: dark) {
  h1 {
    color: $dark-color-text
  }
}
```

To get to this one would assume the following token export should work
```json
{
    "global": {
        "color": {
            "black": {
                "value": "#111111",
                "type": "color"
            },
            "white": {
                "value": "#eeeeee",
                "type": "color"
            }
        }
    },
    "light": {
        "color": {
            "text": {
                "value": "{color.black}",
                "type": "color"
            }
        }
    },
    "dark": {
        "color": {
            "text": {
                "value": "{color.white}",
                "type": "color"
            }
        }
    }
}
```
This is not the case currently. The transformer outputs this 
```json
{
  "color": {
    "text": {
      "value": "#eeeeee",
      "type": "color"
    },
    "black": {
      "value": "#111111",
      "type": "color"
    },
    "white": {
      "value": "#eeeeee",
      "type": "color"
    }
  }
}
```
Please help me understand what I'm missing here. I don't understand how you use this.

**Comment by six7** [comment]
I think your approach differs from mine. I simply override my design decisions, because if I had to change each css variable when changing between light to dark mode this would take a significant amount of time.

Here's my approach:
https://github.com/six7/figma-tokens-example-multi

I just changed a root css (.dark-theme) that just changes the css variables.

IMO design decisions shouldn't be tied to a theme when it comes to naming. It's really just a decision for `color-text` - the implementation itself shouldn't be aware of `dark-color-text`.

Here's a couple examples that follow this approach: https://github.com/six7/figma-tokens-examples

That way, creating a new theme is a matter of changing the variables, you don't have to touch the implementation.

**Comment by jdwillemse** [comment]
Ah I take your point about the theme overrides. The code example is super useful, thanks.

There is still a problem with ambigious aliases. In this example `light.sm.value` equals 30
```json
{
  "global": {
    "sizing": {
      "scale": {
        "value": "2",
        "type": "spacing"
      },
      "sm": {
        "value": "{sizing.scale} * 10",
        "type": "spacing"
      }
    }
  },
  "light": {
    "sizing": {
      "scale": {
        "value": "3",
        "type": "spacing"
      },
      "sm": {
        "value": "{sizing.scale} * 10",
        "type": "spacing"
      }
    }
  }
}

```
but in this example `light.theme.sm.value` equals 20
```json
{
  "global": {
    "sizing": {
      "scale": {
        "value": "2",
        "type": "spacing"
      },
      "sm": {
        "value": "{sizing.scale} * 10",
        "type": "spacing"
      }
    }
  },
  "light": {
    "theme": {
      "sizing": {
        "scale": {
          "value": "3",
          "type": "spacing"
        },
        "sm": {
          "value": "{sizing.scale} * 10",
          "type": "spacing"
        }
      }
    }
  }
}

```
I would expect the behaviour to be the same regardless of the sub structure.

**Comment by Vanals** [comment]
I think I am having your same issue @jdwillemse.

I have a Figma Tokens object with Light and Dark sets.
```
{
  "NK-Light": {
    "inkContrast": {
      "value": "{whiteTint090}",
      "type": "color",
      "description": "Headlines or copy where emphasis is needed"
    },
    "inkPositive": {
      "value": "{whiteTint090}",
      "type": "color",
      "description": "For scenarios where the message needs positive intent"
    },
    "whiteTint090": {
      "value": "#ffffffe6",
      "type": "color",
      "description": "WhiteTint090"
    }
  },
  "NK-Dark": {
    "inkContrast": {
      "value": "{neutral100}",
      "type": "color",
      "description": "Headlines or copy where emphasis is needed"
    },
    "inkPositive": {
      "value": "{whiteTint090}",
      "type": "color",
      "description": "For scenarios where the message needs positive intent"
    },
    "neutral100": {
      "value": "#0a0a0a",
      "type": "color",
      "description": "Neutral100"
    }
  }
}
```

Running the transformer,  Light and Dark gets stripped out (not allowing me to recognize anymore what is dark and light) and tokens with the same name are merged, keeping only one of the values.

```
{
  "inkContrast": {
    "value": "#0a0a0a",
    "type": "color",
    "description": "Headlines or copy where emphasis is needed"
  },
  "inkPositive": {
    "value": "#ffffffe6",
    "type": "color",
    "description": "For scenarios where the message needs positive intent"
  },
  "neutral100": {
    "value": "#0a0a0a",
    "type": "color",
    "description": "Neutral100"
  },
  "whiteTint090": {
    "value": "#ffffffe6",
    "type": "color",
    "description": "WhiteTint090"
  }
}
```

Instead, I would like something like:


```
{
  "NK-Light": {
    "inkContrast": {
      "value": "{NK-Light.whiteTint090}",
      "type": "color",
      "description": "Headlines or copy where emphasis is needed"
    },
    "inkPositive": {
      "value": "{NK-Light.whiteTint090}",
      "type": "color",
      "description": "For scenarios where the message needs positive intent"
    },
    "whiteTint090": {
      "value": "#ffffffe6",
      "type": "color",
      "description": "WhiteTint090"
    }
  },
  "NK-Dark": {
    "inkContrast": {
      "value": "{NK-Dark.neutral100}",
      "type": "color",
      "description": "Headlines or copy where emphasis is needed"
    },
    "inkPositive": {
      "value": "{NK-Dark.whiteTint090}",
      "type": "color",
      "description": "For scenarios where the message needs positive intent"
    },
    "neutral100": {
      "value": "#0a0a0a",
      "type": "color",
      "description": "Neutral100"
    }
  }
}
```

So that SD won't complain about broken aliases, OR having the aliases resolved as well would do it.


The feature of sets is supported in the FT plugin but when is about to transform it to use it in SD I find it impossible to make it work so far.
If I have understood correctly it is the same mentioned in this post right? @six7 @jdwillemse? Otherwise I can make another ticket. 

Lastly, I was wondering, probably this would fix this problem:  https://github.com/six7/figma-tokens/issues/423 
As if we can export a FT  object with the references solved, keeping the OBJ structure then should be fine.

Like:

```
{
  "NK-Light": {
    "inkContrast": {
      "value": "#ffffffe6",
      "type": "color",
      "description": "Headlines or copy where emphasis is needed"
    },
    "inkPositive": {
      "value": "#ffffffe6",
      "type": "color",
      "description": "For scenarios where the message needs positive intent"
    },
    "whiteTint090": {
      "value": "#ffffffe6",
      "type": "color",
      "description": "WhiteTint090"
    }
  },
  "NK-Dark": {
    "inkContrast": {
      "value": "#0a0a0a",
      "type": "color",
      "description": "Headlines or copy where emphasis is needed"
    },
    "inkPositive": {
      "value": "#0a0a0a",
      "type": "color",
      "description": "For scenarios where the message needs positive intent"
    },
    "neutral100": {
      "value": "#0a0a0a",
      "type": "color",
      "description": "Neutral100"
    }
  }
}
```
