### ISSUE TITLE
Introduce Token chooser to let users pick token aliases as value

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#351]
Right now users have to type aliases by hand, which is tedious and requires the user to know all token names.

We should introduce a way to pick tokens and insert them as an alias. One idea could be something like react-mention, or simply a button that lets you choose from tokens and then inserts that.

**Comment by dmackerman** [comment]
Yes, absolutely love this idea. This becomes somewhat trivial when editing source JSON directly, but having a helper (really, really like the autocomplete idea) in the UI would be great!

**Comment by six7** [comment]
Shipped in 97 for basic token values
