### ISSUE TITLE
[GitHub Sync]: Plugin losing access tokens sometimes

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#356]
Reported via Slack:

> Is it only me, or are Personal Access Tokens in GitHub sync not retained? After restarting Figma I have to enter the key again each time…
> 
> Maybe it has to do with the fact that I am working on multiple design systems, each with their own Figma Tokens instance… Oh well, not a biggie, just a bit annoying having to enter the key each time.
> 
> GitHub didn't have such an issue before. It has happened after the last update (V71)

**Comment by usethetics** [comment]
I can verify that I still use the personal access token when opening the plugin.

Mind you; I am working with two different files that point to the _same repo_, the only _difference is the file path_.

https://user-images.githubusercontent.com/248921/145072319-f67d99e9-930e-405c-a041-a247e4d49ddf.mov

_

**Comment by six7** [comment]
Ok thank you, that helps! I think this might be an issue with recently released support for this: Same repo, different filePath. Here's the original issue: https://github.com/six7/figma-tokens/issues/327

We'll have to look into this, but this is super helpful 👍

**Comment by XavierVilars** [comment]
Hello I have exactly the same problem. And when I give again the personnal access token then it load but some sets show list of empty token with a red dot in them....

**Comment by samwalshnz** [comment]
I'm currently experiencing this problem with ADO

**Comment by XavierVilars** [comment]
Same on my side with Github.

**Comment by six7** [comment]
This is fixed in version 125. This error appeared when usually only when multiple users were using the plugin and were switching branches.
