### ISSUE TITLE
Opacity value in colors

### ISSUE THREAD

**Issue by snds** [six7/figma-tokens#359]
It would be great to be able to allow the user to use a set of opacity values or tokens directly in the color swatch dialog. The output could be generated either as a flat hex or as rgba.

![Screen Shot 2021-12-08 at 11 35 37 AM](https://user-images.githubusercontent.com/570874/145272596-6c8263e9-a67e-4090-9595-a2c448d888ac.png)

**Comment by six7** [comment]
You can do that already! You can set `rgba({alias}, 0.5)` to generate 50% opacity on a token. The plugin will handle it for you and generate `rgba(255, 255, 15, 0.5)` for example.
