### ISSUE TITLE
Control opacity of nested color tokens

### ISSUE THREAD

**Issue by Andyrrrrr** [six7/figma-tokens#360]
I'm defining most of my color tokens with HSLA syntax. This is working really nicely since I can first create a hue value token, then create a range of colors using it. I run into a problem though when I want to reference an already-created HSLA token and only only change its opacity.

Here's a long-winded, but hopefully clear example. I first set up this token as an "Other" type:

`hue.primary = 210`

Then I create some primary colors using it:

`primary = HSLA({hue.primary}, 100%, 36%, 1)`
`primary-light = HSLA({hue.primary}, 100%, 99%, 1)`
`primary dark = HSLA({hue.primary}, 100%, 12%, 1)`

Perfect so far, but here's the catch. Let's say I'm using the primary-dark token as my text color and I want to make a disabled text color where its opacity is 40%. This is the token I tried to write and realized I was not of the smart variety:

`disabled-text = rgba({primary-dark}, 0.4)`

The problem here is that this new token evaluates to:

`rgba(HSLA (210, 100%, 12%, 1), .4)`

Which of course doesn't work because you can't embed an HSLA value like that into rgba syntax.

What I'd ideally like to do is be able to just stick a % after my original token reference to tell it to use a certain opacity. Maybe something like this?

`disabled-text = {primary-dark}, 40%`

I'm not a developer though, so that's probably a terrible idea syntax-wise.

Another solution that I'm not too keen on would be to create all of the HSL values I need as "Other" type tokens, then use those tokens to embed into HSLA color specs. That would give me the ability to change the A value as needed. That would also create a huge nested mess though.

Any thoughts on how I could accomplish what I'm after here?

**Comment by six7** [comment]
Hm, this works for me. Could be because your hsla is uppercase?

```
{
  "base": {
    "value": "130",
    "type": "color"
  },
  "hslaToken": {
    "value": "hsla({base}, 100%, 55%, 1)",
    "type": "color"
  },
  "rgba": {
    "value": "rgba({hslaToken}, 0.5)",
    "type": "color"
  }
}
```

**Comment by six7** [comment]
I'll close this for now, let me know if it still didn't work.

**Comment by Andyrrrrr** [comment]
Yep, that appears to have been the issue — uppercase HSLA. Thank you so much!
