### ISSUE TITLE
Issues with interpreting math in token transformer

### ISSUE THREAD

**Issue by r-nazarenko** [six7/figma-tokens#364]
**1. Unary operators require `.value` added to the alias name which is not supported by the plugin**

Example:
`round({font.size.s}/{font.scale}/2)*2` throws an error

<img width="1220" alt="Screenshot 2021-12-10 at 13 27 16" src="https://user-images.githubusercontent.com/95086469/145567220-0e9b4620-e8fa-4963-ad5a-31a95ed05456.png">

To make this work, it needs to be changed to
`round({font.size.s.value}/{font.scale.value}/2)*2`

**2. Math with basic operators seems not to be transformed to raw values**
Example:

```
"size": {
      "default": {
        "value": "16",
        "type": "sizing"
      },
      "0,25x": {
        "value": "{size.default} * 0.25",
        "type": "sizing"
      }
     ...
}
```

turns into
<img width="309" alt="Screenshot 2021-12-10 at 13 36 59" src="https://user-images.githubusercontent.com/95086469/145568405-026d5e8d-c67d-437b-ba21-12c1ac8390a3.png">

**Comment by r-nazarenko** [comment]
I think the 2nd issue might come from those `rem` values added to the basic value out of nowhere. But our developer says this is basic transform setup, so we might need to investigate it

**Comment by six7** [comment]
Are you using token-transformer? Or Style Dictionary? The plugin currently has no way of even dealing with `.value` tokens at the end so that's why I'm asking.

I'll dig into this over the next couple of days, I think there might be something going on with Math transforms. Keep in mind the plugin cannot calculate `16rem * 0.25` - it'd have to be `16 * 0.25`

**Comment by r-nazarenko** [comment]
We are using token transformer, as title states. I'm aware that plugin doesn't support `.value`, our devs created a method that adds it to exported JSON file as a temporary solution since transformer doesn't seem to work without it. 
Thanks for the `rem` insight — I'll ask devs to double check their setup.

**Comment by r-nazarenko** [comment]
It appears everything works fine — our developer has confused Token Transformer with Style Dictionary and used SD instead😀. I guess this process of handing tokens from Figma to platform-specific code isn't really straightforward.

Sorry for misleading, I think the issue can be closed.
