### ISSUE TITLE
Keep alias reference as variable CSS/Sass instead of value

### ISSUE THREAD

**Issue by zetareticoli** [six7/figma-tokens#365]
I usually create a default set of tokens (space, colors, font size, etc) that could be consumed by other ones.

Example:

```css
--headline-one: var(--font-size-7);
``` 

In this example I have two tokens:
- `--font-size-7` which sets a specific font size
- `--headline-one` which uses the previous one for its font-size property

Actually, I can do this via Figma tokens using the `{alias}`. But it prints out the compiled value.

What I want instead is the ability to keep the reference as the alias does, printing out the variable name instead of the value.

**Comment by six7** [comment]
Would this issue describe what you're trying to do? https://github.com/six7/figma-tokens/issues/305

I think the two are duplicate

**Comment by six7** [comment]
No worries 👍
