### ISSUE TITLE
Better delete message

### ISSUE THREAD

**Issue by lukasoppermann** [six7/figma-tokens#369]
Hey,

when deleting a json set it would be nice if the name of the set would be in the message to make sure the right one is deleted.

E.g. in the title: Delete token set "**Test**"?
Where **Test** is the name of the token set.

Should hopefully be a tiny fix but is a nice UX improvement.

**Comment by six7** [comment]
Thanks for that feedback, will be easy to add. 🙏

**Comment by six7** [comment]
Closed with V72
