### ISSUE TITLE
Plugin doesn't save tokens

### ISSUE THREAD

**Issue by zetareticoli** [six7/figma-tokens#371]
**Describe the bug**
Every time I open the plugin, all the data relating to the saved tokens are gone. I've also pushed the JSON file to a GitHub repository but clicking on "Pull" doesn't recover them.

It's the third or fourth time I re-create tokens list from scratch.

**Expected behavior**
Clicking on "Update" I assume it saves the tokens.

**Comment by six7** [comment]
To understand the issue: youre using local storage and in that same document after hitting update and restarting the plugin no tokens are found?


Or are you using github sync and you pushed tokens and hitting the 'Push tokens' button?

**Comment by zetareticoli** [comment]
I started using the plugin using local storage. But then, after loosing all tokens for the 2nd time, I tried syncing to GitHub (see attached screen)
<img width="484" alt="Schermata 2021-12-16 alle 09 29 00" src="https://user-images.githubusercontent.com/69706/146335738-e5ce9681-540b-499a-bb44-956da81321b0.png">

**Comment by Elianetapia** [comment]
I'm having the same issue!

**Comment by six7** [comment]
Hm, I'm curious how to reach that state. If you are able to provide a recording or a way to recreate that bug please let me know

**Comment by zetareticoli** [comment]
Hi, it happened again. This is how:

1. I create tokens in the plug-in window
2. I close Figma
3. I re-open Figma and click on plug-in 
4. All tokens disappeared (see screens below)

<img width="524" alt="Schermata 2022-01-17 alle 10 32 29" src="https://user-images.githubusercontent.com/69706/149744091-b6f1bcbc-b474-492b-8d0f-ab575b2084fb.png">

**Comment by six7** [comment]
Are you using GitHub sync by chance? If so you need to click on the library icon to push your changes, as we don't save local state yet.

**Comment by zetareticoli** [comment]
I didn't use any sync options. I thought it saves tokens locally. Would try syncing on GitHub and let you know. Thanks

**Comment by six7** [comment]
Can you go to the Sync tab to see what's set there and maybe post a screenshot of this here? Because the `library` icon in the top right with the blue dot indicates some sort of Sync is active and has changed values that need to be pushed.

**Comment by six7** [comment]
I'm closing this for now, I think you've got a sync setup here. If this issue persists and you're on local sync please feel free to reopen

**Comment by zetareticoli** [comment]
Yes, thank you. Pulling and then pushing again on GitHub solved the problem. 🙏
