### ISSUE TITLE
A way to include a period in the token's name

### ISSUE THREAD

**Issue by ekfuhrmann** [six7/figma-tokens#372]
**Is your feature request related to a problem? Please describe.**
I am trying to include a period in a token's name without it creating a nested group. An example I have would be for something like spacing where the base value for your spacing group would be 1, and then you can calculate the different spaces off of that base value.

So, for example if I'm using a base 8 system, I'd create a base that would perhaps be something along the lines of `spacing(1)` which would then be equal to `8`. From there I could then create spacings for all my needs based on the calculation from that base. 

Expanded example below:

```
spacing(0.5)    // 4px
spacing(1)      // 8px (base)
spacing(1.5)    // 12px
spacing(2)      // 16px
spacing(3)      // 24px
spacing(4)      // 32px
...
```

What is really nice about a system like this is that if you decide down the road you need a `6px` spacing, rather than having to update all of your spacing tokens in your system (and documenting it as well), you could simply add a `spacing(0.75)` token and be on your way. As such it's far more flexible and scalable than using something like `xs, sm, md, lg, xl, ...`.

If there is a better alternative for handling this, I'm all ears for learning some different solutions.

**Describe the solution you'd like**
Perhaps ignoring periods inside of brackets, or providing another way to show decimals.

**Describe alternatives you've considered**
I was hopeful that I could perhaps use a slash to delineate a ratio (e.g. `spacing(1/2)`) but that runs into the same problem and would fall apart on ratios for other higher values.

**Additional context**
This pattern can be seen in rather large design systems. [Material UI comes to mind in handling spacing this way](https://mui.com/components/grid/#spacing).

**Comment by r-nazarenko** [comment]
You can jus use comma instead of period, even though it's not a correct way to write decimals

**Comment by ekfuhrmann** [comment]
@r-nazarenko I did toy with that idea, but unfortunately that creates a disconnect between the design and development environments as dev uses a decimal.

**Comment by WardMe** [comment]
@ekfuhrmann in our design system we decided to use two scales:
- Limited known set of scale: t-shirt sizes (sm, md, lg for box-shadow, border radius, …)
- Unlimited unknown set of scale: 0 - 1000 (where 100 is our default for dimensions en 500 for color)

```
/* Colors */
$brand.primary.400 // Lighter primary color
$brand.primary.500 // Primary color
$brand.primary.600 // Darker primary color
$brand.primary.700 // Darkest primary color

/* Dimensions */
$dimension.0 // 0px
$dimension.25 // 4px
$dimension.50 // 8px
$dimension.75 // 12px
$dimension.100 // 16px
$dimension.150 // 24px
$dimension.200 // 32px
```

**Comment by braveux-designers** [comment]
@WardMe This is helpful and a pretty good alternative. Thanks for this!

**Comment by ekfuhrmann** [comment]
@WardMe This is helpful and a good alternative. Thanks for the suggestion!

**Comment by six7** [comment]
I'll close this issue as the underlying structure relies so much on dot to separate tokens this would cause more work compared to the value it would bring.
