### ISSUE TITLE
您好，请问您会长期更新这个插件吗？

### ISSUE THREAD

**Issue by huangzhongzhong** [six7/figma-tokens#38]
您好，请问您会长期更新这个插件吗？
因为要长期使用，停止更新后就会造成不好的影响。
所以想问您是否确认会长期（1年以上）维护更新这个插件呢？
因为英语不好，所以只能附上机器翻译的英文版，请您谅解。
Hello, will you update this plug-in in the long term?
Because to use for a long time, stop updating will cause bad effects.
So are you sure that you will maintain and update this plugin for a long period of time (more than 1 year)?
Due to the poor English, the English version of machine translation can only be attached. Please understand.

**Comment by six7** [comment]
Hey @huangzhongzhong ! While I do have planned to keep working on it for a long time I of course can't guarantee that I will maintain this repo, but as it's open source there's nothing stopping you from forking it and improving it!
