### ISSUE TITLE
Plugin doesn't work anymore

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#384]
**Describe the bug**
Super weird, yesterday everything was working fine and now it doesn't anymore.
When I select something I've applied tokens to, the tokens aren't shown anymore in inspect or in the token-overview.
In the Figma Panel, it still says that the layer is connected to the Tokens.
When I create a new layer and apply a token to it, the plugin is stuck at "updating" and the whole page is unresponsive.

**To Reproduce**
1. Try to use Figma Tokens

**Comment by Blyawon** [comment]
Pulling from jsonbin and github works fine, just applying and inspecting the tokens makes the plugin and page unresponsive. I've tried it in the Figma App, Chrome and two different Macs, with VPN and without.

**Comment by six7** [comment]
This should be fixed again now, sorry for the inconvenience.
