### ISSUE TITLE
404 Page Not Found from Sync is here in Figma Plugin

### ISSUE THREAD

**Issue by chsWeb** [six7/figma-tokens#386]
# Bug: type - title

**SUMMARY:**
When launching Figma Tokens, the “Read more” link in the “Sync is here” screen leads to a 404 page error.

**STEPS TO REPRODUCE:**
1. Launch Figam Tokens
2. Click next on the Welcome to Figma Tokens screens until you get to “Sync is here!” Screen.
3. Click Read more

**EXPECTED RESULT:**
Expected to see the details linked to on this page https://docs.tokens.studio/sync.

**ACTUAL RESULT:**
Received a 404 page error.

![image](https://user-images.githubusercontent.com/873222/147250165-9b758eed-fb4e-4221-978a-2a202310541d.png)

**Comment by six7** [comment]
Thanks for reporting! Should now be fixed
