### ISSUE TITLE
Text Encoding in Description from Github

### ISSUE THREAD

**Issue by vandesign** [six7/figma-tokens#388]
**Describe the bug**
Cyrillic in the description has the wrong encoding in Figma

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/5607130/147485977-36c0a77d-65c2-4c02-9383-7c746ce57916.png)
![image](https://user-images.githubusercontent.com/5607130/147486043-105fbfdc-cf2c-42bf-bdf6-8234e7cd7747.png)

**Comment by six7** [comment]
Thanks for reporting! I'm guessing this has to do with the way we process the contents of the JSON on GitHub.

We're using btoa, I think we'll need to tinker with that method to allow non latin1 characters: https://developer.mozilla.org/en-US/docs/Web/API/btoa

**Comment by vandesign** [comment]
Thanks for the great job! I will wait for progress on this issue.

**Comment by six7** [comment]
Fixed in Version 89, will release in a bit.

**Comment by vandesign** [comment]
Awesome! Thank you very much! ♥
