### ISSUE TITLE
Spacing 值无法分别设定水平间距，垂直间距，项目间距

### ISSUE THREAD

**Issue by huangzhongzhong** [six7/figma-tokens#39]
Spacing 值无法分别设定水平间距，垂直间距，项目间距，希望后续更新加上。比如我希望将 96,96,96 设置为 96,48,0
Spacing cannot be separated by setting horizontal Spacing, vertical Spacing, project Spacing and hopefully being updated later added.
![image](https://user-images.githubusercontent.com/46183365/96333166-e51fb300-109a-11eb-825c-4c09a846ae20.png)

**Comment by six7** [comment]
Have you tried right-clicking the token? I'm aware that this is somewhat hidden, but when you right click a token you get a context menu.

**Comment by huangzhongzhong** [comment]
不好意思，是我没探索清楚插件，感谢你的回复，我已经成功学会设置了。
I am sorry that I did not fully explore the plug-in. Thanks for your reply. I have learned to set it successfully.

**Comment by six7** [comment]
No problem, it's rather the fault of the plugin for not showing options better
