### ISSUE TITLE
Import button seems non-responsive

### ISSUE THREAD

**Issue by hchiam** [six7/figma-tokens#393]
Awesome plugin! I'm looking into [importing tokens](https://docs.tokens.studio/styles#importing-styles-later-on) from a JSON file, but I'm not sure what I'm doing wrong. Clicking "Import" shows a modal, but then clicking the 2nd "Import" button only closes the modal and does nothing else on my screen: 

![clicking import button shows modal but then clicking the 2nd import button only closes the modal and does nothing else](https://user-images.githubusercontent.com/18131787/148629066-b23bae60-8425-48c2-b342-d0ee72d6ad4d.gif)

Chrome. Mac. 

As a workaround, I can still copy-paste the text of the JSON file into the JSON tab. The sync feature is very exciting.

**Comment by six7** [comment]
Are there any styles in the document? Import will use local styles (color, text, shadow) and generate tokens from these.

**Comment by hchiam** [comment]
Oh sorry, I see what you mean, looking at https://youtu.be/Ka1I5TphDb0?t=13m46s it's more like the Import button actually pulls styles from the page ("import from page to figma-tokens"). I misunderstood the button to mean that I can take an existing JSON file from my computer to populate tokens ("import from file to figma-tokens"), instead of manually copy-pasting the text. User error 😆 Would it make sense to have a hover/focus tooltip? It could be a quicker fix than adding an import button to the JSON tab, or adding drag-and-drop.

**Comment by six7** [comment]
Those all make sense! The plugin definitely needs a better Import file/Export file to quickly load from your computer and not just one set at a time.

I'm thinking of making the Import / Create Styles section one button with different options (Import or Create), as it would then be in a Styles context. I think that could help as well while reducing the number of available options, what do you think?

**Comment by six7** [comment]
I've created a new issue to tackle this: I'll close this one, feel free to comment on the new one!

https://github.com/six7/figma-tokens/issues/394
