### ISSUE TITLE
Tokens are not displayed in the figma frontend right after adding auto layout to a frame

### ISSUE THREAD

**Issue by mnldkr** [six7/figma-tokens#399]
**Describe the bug**
Currently I can't apply any tokens to a frame right after adding auto layout to it. It applies the token in the inspect view, but it is not shown in the figma frontend. Right now I always need to restart the plugin after creating a new auto layout frame

**To Reproduce**
1. activate auto layout  e.g. on two text layers
2. Try to add colors, spacing etc. to this new auto layout frame

**Expected behavior**
If I create a new auto layout frame and directly apply tokens to it, they should be displayed in the frontend.

**Comment by six7** [comment]
I'm unable to reproduce this here, could you provide a screen recording?

**Comment by six7** [comment]
Closing this for now, seems to work fine for me. Feel free to reopen if issues should persist.
