### ISSUE TITLE
Add the "show behind transparant areas" option in dropshadows

### ISSUE THREAD

**Issue by neatlittlemacapps** [six7/figma-tokens#407]
**Is your feature request related to a problem? Please describe.**
Figma allows for checking the "show behind transparant areas" when creating a dropshadow.
Creating the dropshadow through tokens does not allow setting this option.

**Describe the solution you'd like**
Add the option to the shadows token panel per shadow:

<img width="350" alt="Screenshot 2022-01-18 at 12 53 56" src="https://user-images.githubusercontent.com/60575307/149932949-5c8404ac-6a69-4086-bbe7-74946a7f7454.png">

**Describe alternatives you've considered**
I'd have to overrule the created style manually for each library created using the tokens.

**Comment by juwain** [comment]
+1

applying shadow-tokens to elements (click Update) always sets "show behind…" option of shadow-effect to true, so you have to uncheck this option in the effect settings every time manually

**Comment by jasenchen** [comment]
+1

**Comment by bartberden** [comment]
+1

**Comment by six7** [comment]
Heads up: There's a 👍 emoji on the original issue description that you can use to upvote. I won't keep track of "+1 comments"

**Comment by StefanEndress** [comment]
+1
