### ISSUE TITLE
textCase properties not working in typography

### ISSUE THREAD

**Issue by r3p0x** [six7/figma-tokens#412]
**Describe the bug**
I have been exhaustively trying to get the textCase used inside a Typography (like h1). But somehow it does not apply the textCase no matter what I do. At the same time the textCase properties work perfectly fine if I use them independently from Typography.

**To Reproduce**
1. Create a textCase uppercase value
2. Create a typography variable and apply the textCase.uppercase
3. Apply to a text and you should see it not working.

**Comment by six7** [comment]
Cannot reproduce this. Feel free to reopen if the issue should persist. Check that textCase has that value, then it should work.

https://user-images.githubusercontent.com/4548309/150651887-10e8b91a-0ef7-4b12-b7dd-862588a3a548.mp4

**Comment by Razinsky** [comment]
I have the same problem in general with font attributes and typography. When selecting any font attribute or typography style, it doesn't get applied. I'm on the latest Figma desktop v107.1.

**Comment by Razinsky** [comment]
I found what was not working. The font-weight value did not have the proper casing. Now it works. The weird this is that I imports the tokens from my current Figma text styles, I _think_ maybe there is a problem with the import? Otherwise, yep all is well now 👍
