### ISSUE TITLE
[Git Sync]: Support for GitLab

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#414]
### Discussed in https://github.com/six7/figma-tokens/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **mischi33** December 16, 2021</sup>
Is it possible to sync Figma Tokens with a GitLab repo as well? If not, is this feature planned some time in the future?</div>

**Comment by richardclick** [comment]
I need this as well 🙏

**Comment by raffaelenocerino** [comment]
Hi, thank you for the continuous support offfered. Is it possbile to know (more or less) when this enhancement will be made available? 
Thanks a lot!

**Comment by six7** [comment]
> Hi, thank you for the continuous support offfered. Is it possbile to know (more or less) when this enhancement will be made available? Thanks a lot!

*Very* soon! There's a PR open that takes care of that. If you want to help, you could check out that branch and test if everything works as expected! 🙏

**Comment by six7** [comment]
Will be part of the next release 🎉 We'll do a longer test phase for the next release so it might be a couple weeks.

**Comment by youngbeom-shin** [comment]
Hi, Do we have any plans to support the GitLab version of self-managed ?

**Comment by six7** [comment]
Can you confirm it's not working for self managed right now? We're aware of an issue with subteams/subgroups, but enterprise should work. If it's not working and you're not using subgroups, would you mind creating a new issue?
