### ISSUE TITLE
Self-referencing tokens crash the plugin

### ISSUE THREAD

**Issue by sethakkerman** [six7/figma-tokens#422]
**Describe the bug**
The plugin completely freezes Figma. I tried it on all browsers and the native app for MacOS>

**To Reproduce**
Trigger Plugin to Start. When I open the plugin, it gets stuck on Hold On, Updating and freezes Figma. That occurs in all browsers and the native app. One extra note if it helps. Above is says Version 78, but the bottom left area of the plugin dialog says Version 77 even though I removed and re-added it.

**Expected behavior**

**Screenshots or Screencasts**
Screencast of error including console notes - https://www.dropbox.com/s/h6uoi6fhcjxyhbo/figma-tokens-freezing-with-console-data_AdobeCreativeCloudExpress.mp4?dl=0

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
{
  "version": "78",
  "updatedAt": "Wed Jan 19 2022 13:09:58 GMT-0600 (Central Standard Time)",
  "values": {
    "global": {
      "br-small": {
        "value": "2",
        "description": "Border Radius - Small",
        "type": "borderRadius"
      },
      "br-none": {
        "value": "0",
        "description": "Border Radius - None",
        "type": "borderRadius"
      },
      "br-medium": {
        "value": "4",
        "description": "Border Radius - Medium",
        "type": "borderRadius"
      },
      "br-large": {
        "value": "8",
        "description": "Border Radius - Large",
        "type": "borderRadius"
      },
      "br-xtra-large": {
        "value": "16",
        "description": "Border Radius - Xtra-Large",
        "type": "borderRadius"
      },
      "br-full": {
        "value": "32",
        "description": "Border Radius - Full",
        "type": "borderRadius"
      },
      "color": {
        "hex": {
          "primary-rubine": {
            "value": "#E20177",
            "description": "Brand Color - Rubine Red",
            "type": "color"
          },
          "primary-pacific": {
            "value": "#1B4298",
            "description": "Brand Color - Pacific",
            "type": "color"
          },
          "primary-white": {
            "value": "#FFFFFF",
            "description": "Brand Color - White",
            "type": "color"
          },
          "secondary-charcoal": {
            "value": "#171717",
            "description": "Brand Color - Charcoal",
            "type": "color"
          },
          "secondary-evergreen": {
            "value": "#54B948",
            "description": "Brand Color - Evergreen",
            "type": "color"
          },
          "secondary-sky": {
            "value": "#009DDC",
            "description": "Brand Color - Sky",
            "type": "color"
          },
          "tertiary-marigold": {
            "value": "#FEDB00",
            "description": "Brand Color - Marigold",
            "type": "color"
          },
          "tertiary-jade": {
            "value": "#3CDBC0",
            "description": "Brand Color - Jade",
            "type": "color"
          },
          "neutral-coolgray-100%": {
            "value": "#53565A",
            "description": "Neutral Gray 100%",
            "type": "color"
          },
          "neutral-coolgray-80%": {
            "value": "#74767A",
            "description": "Neutral Gray 80%",
            "type": "color"
          },
          "neutral-coolgray-50%": {
            "value": "#A6A7A9",
            "description": "Neutral Gray 50%",
            "type": "color"
          },
          "neutral-coolgray-20%": {
            "value": "#D7D8D8",
            "description": "Neutral Gray 20%",
            "type": "color"
          }
        },
        "notes": {
          "build-kit-note": {
            "value": "#721FAD",
            "description": "Build Kit Note",
            "type": "color"
          }
        },
        "hsl-rubine-red": {
          "100": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 10%)",
            "description": "Rubine Red - 100",
            "type": "color"
          },
          "200": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 20%)",
            "description": "Rubine Red - 200",
            "type": "color"
          },
          "300": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 30%)",
            "description": "Rubine Red - 300",
            "type": "color"
          },
          "400": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 40%)",
            "description": "Rubine Red - 400",
            "type": "color"
          },
          "500": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 45%)",
            "description": "Rubine Red - 500",
            "type": "color"
          },
          "600": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 55%)",
            "description": "Rubine Red - 600",
            "type": "color"
          },
          "700": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 70%)",
            "description": "Rubine Red - 700",
            "type": "color"
          },
          "800": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 80%)",
            "description": "Rubine Red - 800",
            "type": "color"
          },
          "900": {
            "value": "hsl({color.hsl-rubine-red._hue}, 99%, 90%)",
            "description": "Rubine Red - 900",
            "type": "color"
          },
          "_hue": {
            "value": "329",
            "description": "Rubine Red Hue",
            "type": "color"
          }
        }
      },
      "size-base": {
        "value": "16",
        "description": "Size Base",
        "type": "sizing"
      },
      "size-large": {
        "value": "{size-base} * 2",
        "description": "Size Large (2x Size Base)",
        "type": "sizing"
      },
      "size-xlarge": {
        "value": "{size-base} * 2.5",
        "description": "Size XLarge (2.5x Size Base)",
        "type": "sizing"
      },
      "size-medium": {
        "value": "{size-base} * 1.5",
        "description": "Size Medium (1.5x Size Base)",
        "type": "sizing"
      },
      "font-montserrat": {
        "value": "montserrat",
        "description": "Montserrat",
        "type": "fontFamilies"
      },
      "font-montserrat-regular": {
        "value": "Regular",
        "description": "Montserrat Regular",
        "type": "fontWeights"
      },
      "font-nanumgothic-regular": {
        "value": "Regular",
        "description": "Nanum Gothic Regular",
        "type": "fontWeights"
      },
      "font-montserrat-SemiBold": {
        "value": "SemiBold",
        "description": "Montserrat SemiBold",
        "type": "fontWeights"
      },
      "font-montserrat-Bold": {
        "value": "Bold",
        "description": "Montserrat Bold",
        "type": "fontWeights"
      },
      "font-nanumgothic-Bold": {
        "value": "Bold",
        "description": "Nanum Gothic Bold",
        "type": "fontWeights"
      },
      "font-montserrat-ExtraBold": {
        "value": "ExtraBold",
        "description": "Montserrat ExtraBold",
        "type": "fontWeights"
      },
      "font-nanumgothic-ExtraBold": {
        "value": "ExtraBold",
        "description": "Nanum Gothic ExtraBold",
        "type": "fontWeights"
      },
      "body-regular": {
        "value": "16",
        "description": "Body Regular",
        "type": "fontSizes"
      },
      "body-small": {
        "value": "13",
        "description": "Body Small",
        "type": "fontSizes"
      },
      "120%": {
        "value": "120%",
        "description": "1.2 Line Height",
        "type": "lineHeights"
      },
      "100%": {
        "value": "100%",
        "description": "1.0 Line Height",
        "type": "lineHeights"
      },
      "heading-one": {
        "value": "{body-regular} * 2.666",
        "description": "Heading One",
        "type": "fontSizes"
      },
      "font-nanum-gothic": {
        "value": "NanumGothic",
        "description": "Nanum Gothic Font Family",
        "type": "fontFamilies"
      },
      "spacing-base": {
        "value": "{spacing-base} / 2",
        "description": "Spacing Base (16px)",
        "type": "spacing"
      },
      "spacing-1,5": {
        "value": "{spacing-base} * 1.5",
        "description": "Spacing 1.5 (24px)",
        "type": "spacing"
      },
      "spacing-0,5": {
        "value": "{spacing-base} / 2",
        "description": "Spacing .5 (8px)",
        "type": "spacing"
      }
    }
  }
}

**Comment by six7** [comment]
Thanks for reporting. You do have a token that references itself:

```
"spacing-base": {
"value": "{spacing-base} / 2",
"description": "Spacing Base (16px)",
"type": "spacing"
},
```

Quickfix: Don't do that.

Will work on something in the meantime, this shouldn't crash the plugin.

**Comment by sethakkerman** [comment]
@six7 I fixed that and it's not crashing anymore!

**Comment by sethakkerman** [comment]
@six7 I'll close this ticket for now, but for your knowledge, that did crash the plugin if it's something else you need to investigate.

**Comment by six7** [comment]
Added a fix for this so it doesn't crash anymore. Will work on some test coverage etc and then release. I'll keep this open but rename 👍 

Thanks again for a detailed report ❤️

**Comment by sethakkerman** [comment]
Absolutely! Anything I can do to help. This plugin blows my mind. Love it.
