### ISSUE TITLE
Reference export

### ISSUE THREAD

**Issue by RWOverdijk** [six7/figma-tokens#426]
**Is your feature request related to a problem? Please describe.**

I'd like to be able see which tokens have been used where. Ideally on a component level. With traditional figma colors for example you can see the name and then use that to use the correct variable upon implementation. With the figma tokens plugin the value just gets set and I can't see which token has been used, and so I don't know which token to use when implementing a feature.

**Describe the solution you'd like**

An option to maybe export an abstract representation of references. Select a component and see an abstract hierarchy with for example the auto layout options, boxes, text and vectors as well as the tokens used for the values involved.

I know something like this is possible because the plugin already has these references (it updates the values in the document whenever you change a token). On top of that I know figma exposes these values with their API because I've built my own plugin to generate code (auto attributes based on variants and enums based on those values). I didn't use tokens, but my need for tokens lead me to Figma tokens.

**Describe alternatives you've considered**

I've considered grouping every value for every component. So `button.primary.backgroundColor` and `button.primary.verticalPadding` for example and then using those when implementing the button's primary variant. I don't like this because the components are then part of a pretty large list of tokens in an already (imo) unwieldy modal.

On top of that I also don't like the idea in case of specific screens. I could technically separate those out but it will quickly become a lot to keep track of.

**Additional context**

I think a feature like this could eventually lead to a pretty reliable code generator (probably not this plugin, but another plugin that depends on this one). Since I already have logic to figure out variants, enums, types, hierarchy in an AST this could be used to generate anything from swiftUI to react components (Style Dictionary but including code).

If this sounds useful to you as well and I'm not just dreaming about some silyl feature that makes no sense I'd be happy to help out with this. I'd need some insider info on the current structure of the project and maybe some sparring about the idea. There's only so much I can put in a github issue without making the readers fall asleep.

**Comment by six7** [comment]
@RWOverdijk This sounds really awesome! Sorry for taking so long to respond. I think this is something that would be really incredible to work on, would gladly assist you in getting started or discussing this in a zoom call.
