### ISSUE TITLE
Plugin stops on every action performed

### ISSUE THREAD

**Issue by sakaavee** [six7/figma-tokens#430]
**Describe the bug**
Created a color token that passes a Hue value. But after adding the plugin stopped working for some time. No other actions are allowed.

This happens to every action I perform on that plugin. Not able to close the plugin have to close the file.

**Comment by six7** [comment]
Can you try on an empty file to see if issue persists?

**Comment by sakaavee** [comment]
It works smoothly on new file and the file which is was facing issue. I changed from **Apply to document** to **selection**

And the file which I worked is a heavy one. 

Thanks for the workaround 🙏

**Comment by six7** [comment]
👍 The reason for this is that when `Update on change` is checked the plugin will update all selection/page/document (whatever's selected) on every change of tokens. This can be a performance-heavy operation, as for page with many layers it has to traverse the whole layer tree, which can take a while.

With the next update this will be faster, but `Selection` will always be fastest when you don't yet want to make changes to everything.

Closing this as this will be resolved by the next update.
