### ISSUE TITLE
Token values should be trimmed on input and when passing to Figma

### ISSUE THREAD

**Issue by ns-tailu** [six7/figma-tokens#432]
**Describe the bug**
#hex color sometimes won't work

**To Reproduce**
1. open plugin
2. create new color token
3. enter hex code
4. update style -> style with no property(in token panel it shows the color)

**Expected behavior**
when inputting hex code in the token panel and updating the color style, style should not be "no property". The property needs to align the color input in the token panel.

**Screenshots or Screencasts**
![Screen Shot 2022-02-03 at 10 10 39 AM](https://user-images.githubusercontent.com/91100938/152403198-36e4099c-b495-4c04-a93f-f9ddc2458082.png)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by ns-tailu** [comment]
Need to switch to rgb then it works, the blue200, blue400 show no property. The JSON looks no problems.

**Comment by six7** [comment]
Could it be you tried those without the # symbol? The plugin won't pick those up, as it requires them to be written like `#ff0000`

**Comment by ns-tailu** [comment]
Find out the reason. I have a space after the hex code. It'll be great if this small friction can be fixed. Thanks for the reply!
