### ISSUE TITLE
borderWidth tokens

### ISSUE THREAD

**Issue by jamestnew** [six7/figma-tokens#44]
Having the ability to set the borderRadius is great, and it would be enhanced further if the borderWidth could be set with a token as well. This way defaults could be set up for small, medium and large UI components.

**Comment by six7** [comment]
Shouldn't be too hard to implement, sounds good! Would you say `borderWidth `is enough, or would other stroke properties such as `strokeCap`, `strokeAlign`, `dashPattern `make sense? I'd say we can always add more tokens (and combine them in compositions later)

**Comment by jamestnew** [comment]
I think as a starting point the `borderWidth` and `strokeAlign` properties would give enough flexibility. Anything else is a bonus.

**Comment by six7** [comment]
`borderWidth `is in now! I'll add other properties such as `strokeAlign` etc later - `dashPattern` would make sense as well I think as that's something that has to be done manually right now. Those will make sense in compositions when you can do something like this:

```
dndZone: {
  borderWidth: '$borderWidth.default',
  border: '$colors.gray.500',
  dashPattern: '$dashPattern.large',
  strokeAlign: 'center'
}
```
