### ISSUE TITLE
Option to Save & Update JSON with keyboard shortcut.

### ISSUE THREAD

**Issue by sakaavee** [six7/figma-tokens#448]
Currently I am working with creating Color values based on hue range. 
I have to edit the hue value and hit save and update. Mouse travel time is high.

**Describe the solution you'd like**
It would be helpful if we can save json with a keyboard shortcut.

**Comment by six7** [comment]
For now you could tab through, but I agree it would be nice if Save & Update was the first tab target! 👍

**Comment by sakaavee** [comment]
Yes, that would be nice 👍 and looking forward to see shortcut in release line 😊
