### ISSUE TITLE
Tokens sometimes not updated, when switching component variants

### ISSUE THREAD

**Issue by elbenfro** [six7/figma-tokens#451]
**Bug description**
A bug came up when I created instances of components with variants and switching the variant of an instance.
The switched variant may still have a connection to the old token.

**Reproduction:**
For example: I have a component like a button. Variant 1 has applied a token with color yellow, variant 2 has applied a token with color red. 
1. Now I create an instance of the component with variant 1 (yellow).
2. In the Figma-Panel on the right side I switch the variant to variant 2. Now I see the button in yellow. But, when I now look at the Figma Tokens plugin, either in the "Tokens" or in the "Inspect" Tab, I see still the Token from variant 1 connected. If I would hit the "Update" Button in the plugin, the color would switch to yellow again. 
Closing and opening the Figma Tokens plugin bypasses the problem.

The workaround would be to switch the variant, then close the plugin and reopen the plugin again. Then it shows the correct Token.
This only happens, when one (or more) Tokens are applied directly to the component (or to a component variant). If a token is applied in a deeper/nested level, i.e. within another frame within a component, it works as expected

**Expected behavior**
When switching the variant and in case, the variant has another (or no) Token applied, the plugin should also show the correct Token (or no token, when the newly selected variant has no token).

**Screenshots or Screencasts**
Screen 1: Instance of variant 1 created, Token "yellow" connected
(Note: The component is just an empty frame with a token directly applied to the variant)
![figma_token_bug_1](https://user-images.githubusercontent.com/99404146/153413658-aba63888-64a3-4600-a513-1c91c5666069.PNG)
Screen 2: Variant changed to "variant2", the plugin still shows the yellow token
![figma_token_bug_2](https://user-images.githubusercontent.com/99404146/153413664-cbd6a7d1-ab16-4b3c-89a1-a7f1c5df0a6d.PNG)
Screen 3: Hitting the "Update" button in the plugin - the wrong token is applied to the instance (This step is optional for the bug, but this is what could happen when using the plugin)
![figma_token_bug_3](https://user-images.githubusercontent.com/99404146/153413666-2a337334-eedb-4a56-be3b-cb3b902cc950.PNG)
Screen 4: After closing and re-opening the plugin and clicking on "Update" again, the correct token is applied finally, and also shown as connected.
![figma_token_bug_4](https://user-images.githubusercontent.com/99404146/153413675-642d7f7b-d0de-4599-b63f-2aee897f3683.PNG)

**Comment by six7** [comment]
Thanks for reporting! this will be fixed in V80 which I'll probably release early tomorrow 👍

**Comment by six7** [comment]
Fixed in #456 and released in V80.
