### ISSUE TITLE
Allow deep referencing token values of object-based tokens (typography, boxShadow)

### ISSUE THREAD

**Issue by fredboyle** [six7/figma-tokens#457]
**Describe the bug**
When attempting to reference typography values in other tokens it does not function as expected.

**To Reproduce**
1. Create a new typography token (ex. typography.base)
2. Set `fontSize` to 16
3. Create an additional typography token (ex. typography.h1)
4. Set `fontSize` of second token to `{typography.base.fontSize} * 2`
5. Save/update
6. New `typography.h1` token does not have a `fontSize` value of 32

**Expected behavior**
`typography.h1` token should have a `fontSize` value of 32

**Comment by six7** [comment]
Just to understand correctly: You'd like to reference the value of a composite token in another token? This isn't possible as of now. A reference currently can only point to a specific token (not to composite tokens such as boxShadow/typography, not to its subvalues)

**Comment by fredboyle** [comment]
@six7 So a typography token cannot be referenced to by other tokens? That's unfortunate as it prevents the proper creation of [typographic scale systems](https://spencermortensen.com/articles/typographic-scale/).

Is this a feature that is on the near future roadmap? Or would a pull-request change be accepted to add this functionality?

**Comment by six7** [comment]
What you can do in the meantime is create tokens that make up your typography tokens and you'd then use those tokens as a reference.

The default json preset has such a structure: https://github.com/six7/figma-tokens/blob/main/src/config/default.json

That being said, I'd love to support the scenario you described and I'd like to use this issue to track work on that.

**Comment by MatthiasDunker** [comment]
@six7 Are you already on it? I would be happy to help, if needed (although I am quite busy until the end of next week).

**Comment by six7** [comment]
Not currently on it, feel free to contribute there!

**Comment by six7** [comment]
We just merged this into the next release branch. Will probably ship in the next two weeks! 🎉
