### ISSUE TITLE
Cannot open Figma Tokens plugin (immediate crash)

### ISSUE THREAD

**Issue by kmck** [six7/figma-tokens#458]
**Describe the bug**

Hi there! It looks like an update was just released a couple hours ago, so I am guessing it's related.

The Figma Tokens plugin is crashing immediately on open for me. I encountered this on an existing file, but it also happened when just trying to open the plugin in a brand new file.

Here's what's in the console:

```
TypeError
  message: "cannot read property 'inspectDeep' of undefined"
  stack: "    at <anonymous> (PLUGIN_5_SOURCE)\n    at call (native)\n    at c (PLUGIN_5_SOURCE)\n    at <anonymous> (PLUGIN_5_SOURCE)\n    at <anonymous> (PLUGIN_5_SOURCE)\n    at ou (PLUGIN_5_SOURCE)\n    at a (PLUGIN_5_SOURCE)\n    at <anonymous> (PLUGIN_5_SOURCE)\n    at n (PLUGIN_5_SOURCE)\n"
```

**To Reproduce**
1. Right click on canvas
2. Click on "Plugins > Figma Tokens"
3. Plugin window shows for a second then disappears
4. F12 message appears in Figma, error in console

**Expected behavior**

Figma Tokens plugin opens.

**Comment by six7** [comment]
Thanks for reporting, will fix this tomorrow morning 👍
