### ISSUE TITLE
Remove token missing

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#462]
**Describe the bug**
Since the latest update, tokens can't be romoved anymore. In the inspect mode, tokens are being listed, but the delete icon is missing.
<img width="402" alt="Bildschirmfoto 2022-02-14 um 14 12 40" src="https://user-images.githubusercontent.com/78965152/153870719-0e204933-cc99-4d17-ab95-1333dde6b85a.png">

**Comment by clairedenning** [comment]
We have the same problem here. 
![image](https://user-images.githubusercontent.com/49988488/153908927-e03dc0a2-7848-426b-a718-b7e4e952567c.png)

**Comment by six7** [comment]
Removing tokens moved to the Multi Inspector, select all tokens that you'd like to remove and then click Remove selected.

Debug is now what it says it is: A debug view.


https://user-images.githubusercontent.com/4548309/153948281-8058996a-3c41-447a-b86d-41c7291a3df4.mp4

**Comment by clairedenning** [comment]
It is working today, thank you

**Comment by Blyawon** [comment]
Thanks :)
