### ISSUE TITLE
No tokens found in inspect mode

### ISSUE THREAD

**Issue by Blyawon** [six7/figma-tokens#463]
**Describe the bug**
Since the last update, tokens are not being displayed in the inspect mode. It worked on release, not they are not being displayed.
<img width="401" alt="Bildschirmfoto 2022-02-14 um 14 13 36" src="https://user-images.githubusercontent.com/78965152/153870880-95e1f721-bc59-452e-9d1d-cb80f5bc8653.png">

They are still being displayed under "debug and anotate"

**Comment by clairedenning** [comment]
We have the same issue. I have tested this in a new file and it's the same. Tokens that are applied do NOT show in the Inspect tab, only in debug and anotate. And there is no way in the inspect panel to remove tokens that have been applied. This is a BIG problem for us :|

**Comment by clairedenning** [comment]
![image](https://user-images.githubusercontent.com/49988488/153900034-6896fb1a-24ad-4d4e-8203-35834f62674e.png)

**Comment by six7** [comment]
Thanks, fixed in 83!
