### ISSUE TITLE
[Inspector] / Remap: Add autocompletion or Select when swapping tokens

### ISSUE THREAD

**Issue by dmackerman** [six7/figma-tokens#464]
**Is your feature request related to a problem? Please describe.**
Really like the new token swapping feature. The only problem I'm seeing is that it is difficult to remember token names in a large system.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/289938/153918503-3a566dc3-e07e-4765-8762-53a59afcb78b.png">

It would be great if this was an autocomplete, or some UI that allowed for easier selection of new tokens.

**Comment by six7** [comment]
Yes, this is exactly as planned. FYI: This is what we've planned for the next iteration of Multi inspect:



| Current | Ship 2 |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/4548309/154147700-314bca7c-5a24-4b29-9f5e-0d31b06a41c3.png)| ![image](https://user-images.githubusercontent.com/4548309/154147621-7dd683bb-a4ef-4260-8fa3-f01d0f9ff65d.png) |

**Comment by six7** [comment]
I'll reopen this and track progress in this issue 👍

**Comment by arronhunt** [comment]
@six7 Looks like the remap is going to support autocomplete, will that also apply to aliases? https://github.com/six7/figma-tokens/issues/351
