### ISSUE TITLE
Removing tokens via Multi Inspector removes relaunchData

### ISSUE THREAD

**Issue by clairedenning** [six7/figma-tokens#467]
**To Reproduce**
1. Select the layer that has tokens applied
2. Check what tokens are applied in the plugin UI (Inspect tab) and compare it to the tokens shown in the figma UI
3. Remove applied tokens via plugin UI and see that ALL other tokens seem to have been removed according to the figma UI.

**Expected behavior**
Plugin UI and Figma UI should both show the same tokens applied

**Screengrabs**
1. In plugin UI the focus border colour appears to be applied, however does not show in the Figma UI.
2. Having selected the border focus colour and removed it ALL of the tokens disappear from the Figma UI, even though they still show in the plugin UI.
![image](https://user-images.githubusercontent.com/49988488/154112374-5d975471-591f-4826-8407-41c099464191.png)
![image](https://user-images.githubusercontent.com/49988488/154112596-b558f7f3-18d0-4ba8-af2c-0654a6f16a04.png)

**Comment by clairedenning** [comment]
Also, when attempting to undo these changes, tokens are not RE-applied where they once were. I am left unsure as to whether they were actually applied in the first place

**Comment by uipetals** [comment]
I am also facing the same issue. But what I am doing is, I closed the **Figma Tokens** window and reopened it then applied the same token then It's working. Maybe you can try that until we get the fixed version :)

**Comment by clairedenning** [comment]
@uipetals That doesn't work for me. In fact, when I reopen the plugin, the tokens which I just removed are still applied. Other than these little glitches, I'm loving the recent updates @six7 :)

**Comment by six7** [comment]
Thanks for reporting! Seems like we remove all `relaunchData` (the stuff in the figma ui bottom right) when removing a token via Inspect.

To clarify: Those tokens itself are not removed, just the `relaunchData` in the bottom right is (which is just being used to show users SOME tokens are applied here, but other than that this serves no purpose)

**Comment by clairedenning** [comment]
Thanks for the update. So is the plugin still doing its job or should we wait for a fix?

**Comment by six7** [comment]
No need to wait, it's really just that button on the bottom right that's affected (however that has nothing to do with applied tokens). Also that button isn't reliable anyway as it doesn't work for instances
