### ISSUE TITLE
Notify the user they're losing unsaved progress if they don't push with GitHub sync

### ISSUE THREAD

**Issue by uipetals** [six7/figma-tokens#468]
**Describe the bug**
I have connected my Github account in Figma Tokens and whenever I made any changes/new tokens created then I used to move my changes to Github, But when I close the Figma Tokens window before I move my changes then when I reopen it all my changes are erasing.

**To Reproduce**
1. Go to 'Figma Tokens'
2. Click on 'Create any new token'
3. Before moving changes to Github 'Close window before pushing to Github'
4. Changes are erasing

**Expected behavior**
If there is a way to prompt a message saying "There are some unsaved changed, do you want to push to github"

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
I don't think we can intercept Figma's close action before it closes the plugin window, but that idea would be great!

Another issue that would solve this would be to save locally and ask user on next launch if they'd want to pull or restore local tokens: https://github.com/six7/figma-tokens/issues/353

**Comment by six7** [comment]
We now shipped a local storage for GitHub so you can restore changes on relaunch.
