### ISSUE TITLE
Aliases across different token sets

### ISSUE THREAD

**Issue by lucaspetes** [six7/figma-tokens#480]
**Describe the bug**

It is not possible to use exported JSONs the same way the plugin does.

Figma Tokens use token sets on an override/cascading basis: as you activate sets, they work kinda as a single big set - which keep aliases to tokens in different sets working and resolve conflicts by using the values in the order of appearance.

When exporting sets in JSON - to be later used in `token-transformer` - those cross-references are lost, making it impossible to resolve aliases that were originally defined in a different set.

This forces every single set/theme to duplicate a lot of tokens that sometimes we'd like to keep immutable, such as sizes, spacings and some of the font properties. 

**To Reproduce**
1. Create a 'global' token set
2. Create a token set for a different theme that contains e.g. typography styles.
3. Try to change, for example, only the Font Family of these new styles, keeping everything else the same as in global (even better if it could be empty)
4. Export sets in JSON (I happen to need expand typography and separate sets in different files, but it wouldn't make much difference in this case)
5. Run token-transformer.

Aliases won't be correctly parsed across different token sets (only on the same set, which is ok).

Separate files: referenced tokens from a different set won't be included as part of the JSON
Single file: referenced tokens won't have their aliases renamed to point to the right sets like {global.token}

A reference on Figma Tokens to something like {global.token} would crash the plugin.

**Expected behavior**
Referenced tokens to be exported with each set or to be resolved at the time they are exported OR
Allow references to tokens in different sets, like a h1 style "theme.fontFamily + global.lineHeight + global+fontSize".

**Comment by dmackerman** [comment]
Yes, I noticed this as well. I'm currently struggling to _truly_ use the Figma Tokens JSON format as the source of truth, because in a lot of ways we're reliant on the `token-transformer` to actually get these tokens _into_ code. 

I'm almost wondering if the nicer way to go about this is to write a standard `style-dictionary` configuration, because the issue with different themes and aliasing isn't present there, and then transform _that_ output into Figma Tokens style JSON.

**Comment by six7** [comment]
Can't reproduce, can you give me more info as to what I did wrong in this example?

Think of token sets like files in style dictionary. File names are not part of the token name.

https://user-images.githubusercontent.com/4548309/155484130-3571828c-69ea-47c8-8577-386384614c3f.mp4
