### ISSUE TITLE
[Git Sync]: Azure DevOps

### ISSUE THREAD

**Issue by unpunnyfuns** [six7/figma-tokens#494]
As you are registering interest for Git solutions to be supported, it would really make my day if you supported Azure DevOps. 😺

https://azure.microsoft.com/en-us/services/devops/repos/

**Comment by ianturk** [comment]
Would make my day too!

**Comment by jagalletta** [comment]
My team would benefit from this as well.

**Comment by doverphone** [comment]
Another vote for this feature!

**Comment by BlakeDWBrown** [comment]
This would be great! When can we expect the release?

**Comment by jagalletta** [comment]
You guys are awesome. Thank you!
