### ISSUE TITLE
Feedback on updating tokens with the Update button

### ISSUE THREAD

**Issue by pascalrops** [six7/figma-tokens#497]
When I change tokens and click on update (bottom recht), the button stays active and doesn't give feedback I clicked the "update" button. 

Idea:
- Make the "update" button disabled when nothing changed 

This way you get feedback about that something happened after clicking it. And it's also clear you did or you didn't change anything in the tokens. 

<img width="499" alt="Screenshot 2022-03-02 at 10 40 11" src="https://user-images.githubusercontent.com/100764558/156336672-af9e9a56-7910-46f3-b1c2-f76c2f66eed9.png">

**Comment by six7** [comment]
Hey, thanks for raising this issue - sorry it took me so long.

Unfortunately we currently don't know when an Update would lead to exactly the same results on a selection as it could be that somewhere deep down a layer tree there's a token that wasn't updated. This would require the user to scan even more layers upon selecting, leading to poorer performance overall.

Maybe there's something we could do about that in the future, but for now we'll have to do with that.
