### ISSUE TITLE
Integrate Sync to external service

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#5]
A user shouldn't have to enter the same tokens again and again.

Instead we should offer external sync options: 

A) Automatically
User updates token values - we update the JSON on the server

B) Manual
User updates token values - presses "Save" - local JSON gets sent to server

This brings a different problem: What if in the meantime the server has a newer version of a JSON, perhaps by a different user?

**Comment by chris-pearce** [comment]
This would be a great addition.

**Comment by andywd7** [comment]
Have you seen how lukasoppermann does the syncing with his [figma design-tokens plugin](https://github.com/lukasoppermann/design-tokens). Uses github action/workflows to sync with a repository. This would be a really great feature as well as with something like jsonbin.io

**Comment by six7** [comment]
> Have you seen how lukasoppermann does the syncing with his [figma design-tokens plugin](https://github.com/lukasoppermann/design-tokens). Uses github action/workflows to sync with a repository. This would be a really great feature as well as with something like jsonbin.io

Yeah, this is an awesome solution — I'm currently working on JSONbin integration, but the option to add a github repo should work just as well!
