### ISSUE TITLE
[Dev] Plugin will not run

### ISSUE THREAD

**Issue by rickyzhangca** [six7/figma-tokens#508]
**Describe the bug**
Plugin will not run and prompts error when one is trying to build and run it locally.

**To Reproduce**

1. Run `yarn`.
2. Run `yarn build:watch`.
3. Open Figma -> Plugins -> Development -> New Plugin... and choose manifest.json file from this repo.
4. Select `Tokens`: right click on canvas -> Plugins -> Development -> Tokens.

**Expected behavior**
Plugin should run.

**Screenshots or Screencasts**
<img width="537" alt="image" src="https://user-images.githubusercontent.com/16908811/156940945-afcf1d4d-f384-44f5-a7eb-9220ac7fe2a0.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/16908811/156940956-9196a7ca-6236-4aa3-aded-2c11c3e6ead0.png">

**Comment by six7** [comment]
Watch mode is broken since we introduced `mathjs` - you'll have to run `yarn build` instead.

**Comment by six7** [comment]
This is now fixed, pull latest main and watch mode should be working again 🙏
