### ISSUE TITLE
Ability to undo the previous action if you made it by mistake

### ISSUE THREAD

**Issue by guyenner** [six7/figma-tokens#510]
**Is your feature request related to a problem? Please describe.**
Since we are still testing out the tokens, we make mistakes on the values all the time. It's quite frustrating to have to redo all of the tokens if you hit on a wrong button by accident: example "clear", "load preset", or just simply want to revert to the previous actions.  

**Describe the solution you'd like**
1) Make the "clear" and "load preset" btns a bit harder to find, or give it a confirmation/ warning when the buttons are clicked.
2) If there's a Cmd +z function for the last 5-10 events that would be great!

**Describe alternatives you've considered**
There's really no alternatives. Right now you have to redo everything. 

**Additional context**

**Comment by six7** [comment]
Good points! I'd like to split this issue into 2 so we can work on them separately:

I've created https://github.com/six7/figma-tokens/issues/512 for the work on the confirm dialog, which should be an easy fix compared to Undo (which would be really awesome as well!)

**Comment by six7** [comment]
Closing this as completed 🎉 Will be part of the next release
