### ISSUE TITLE
Unable to export dark and light themes to Figma style 

### ISSUE THREAD

**Issue by guyenner** [six7/figma-tokens#511]
**Is your feature request related to a problem? Please describe.**
Right now, I can only either export light theme tokens or dark theme tokens to Figma style, along with the global tokens. I have to rename the style in Figma color styles so that it exports the other theme and reorder them, which is what we want to avoid. 

**Describe the solution you'd like**
An ability to create styles for all of the themes simultaneously, and in the Figma style, [light and dark] are structured as a parent folder. And in Figma tokens, you don't need to append light & dark on every token. 
Example: 
**Figma token**: [Light] : background.default = {colors.grey.10}, [Dark]: background.default = {colors.grey .100}
**Figma color style:** : 
background/ dark/ default
background/light/default
(Background is a folder)

**Describe alternatives you've considered**
I append the tokens with .light and .dark, which makes the token names very long and cumbersome.

**Additional context**

**Comment by six7** [comment]
Renaming tokens to `light.background.default` and `dark.background.default` wouldn't work for you? Just trying to understand the full use case here, as I'm currently re-evaluating the Themes feature and there'll be some changes in the future I want to be fully aware of the needs around that 👍

**Comment by guyenner** [comment]
Good question. In theory it’s ok, but our DS will have a namespace (for different brands) and other themes prepending, so light and dark better to be suffix than prefix I think. 
In addition, if we change it to `light.background.default`, how do you suggest we should name for global tokens Bs light/dark tokens?

**Comment by six7** [comment]
I usually put the global namespace there: `global.colors.blue.500`

Or for prepending a brand namespace: `brandA.light.background.default` - however that is a different approach, I usually don't keep light/dark in my token names and instead just export to a light.json file / dark.json file with token-transformer

**Comment by guyenner** [comment]
Yea that was my preferred approach: export the json file for dark and light. However, if I don’t prepend in the tokens it won’t show up correctly in Figma styles and make it very difficult to navigate. Also, it can only create style either light or dark

**Comment by six7** [comment]
Have you considered separate libraries for light and dark mode? IMO that's the better approach then having all styles in 1 file. You can easily swap libraries then: https://jansix.at/blog/creating-design-systems-based-on-design-tokens-figma-tokens

**Comment by guyenner** [comment]
I see. It's an interesting thought and I can def try. Just so I clarify what you said, we will have 3 libraries: global, light and dark in Figma libraries?

**Comment by six7** [comment]
Exactly, that way you can simply swap out these libraries. With the plugin you'd just expose different sets when creating these styles.

As your names are the same, you could use a plugin like Themer to swap applied styles in your documents.

I've written a blog post on that approach: https://jansix.at/blog/creating-design-systems-based-on-design-tokens-figma-tokens

**Comment by six7** [comment]
Update on this: This will be possibly with the upcoming non-local styles feature, where you'll be able to prepend the theme name in the styles
