### ISSUE TITLE
GitHub sync of JSON breaks if a token name includes a full stop

### ISSUE THREAD

**Issue by SophimayP** [six7/figma-tokens#517]
**Describe the bug**
Hi there! Really enjoying the plugin, thank you!

I'm just having a small issue to with my spacing tokens not syncing into Figma correctly from GitHub. I think it might be because we use "." in the name of the spacing tokens (we have spacing tokens named 0.5, 1.5, 2.5 and 3.5, to align with the [Tailwind spacing system](https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale) which is proportional).

I'm guessing this conflicts with using the "." in token names to auto nest them: "In the modal that appears, give your token a name, for example colors.blue with a value of #0000FF, save your progress by clicking Create.". Because once I import the tokens from GitHub, the JSON is altered when I view it in the plug in, and any of the spacing tokens with "." in the name are not visible.

Would there be any way around this?

**To Reproduce**
1. Import some JSON where a token has a "." in the name
2. Compare the before and after

**Expected behavior**
The spacing tokens named 0.5, 1.5, 2.5 and 3.5 to have come through like the others.

**JSON**
My spacing tokens look like this in my code editor and in GitHub
```"spacing": {
      "0" : {
        "value": "0",
        "rem": "0",
        "type": "spacing"
      },
      "px" : {
        "value": "1",
        "rem": "0.0625rem",
        "type": "spacing"
      },
      "0.5" : {
        "value": "2",
        "rem": "0.125rem",
        "type": "spacing"
      },
      "1" : {
        "value": "4",
        "rem": "0.25rem",
        "type": "spacing"
      },
      "1.5" : {
        "value": "6",
        "rem": "0.375rem",
        "type": "spacing"
      },
      "2" : {
        "value": "8",
        "rem": "0.5rem",
        "type": "spacing"
      },
```

Then when I sync that in the Figma Token plugin, the JSON comes in like this:

```"spacing": {
    "0": {
      "5": {
        "value": "2",
        "rem": "0.125rem",
        "type": "spacing"
      },
      "value": "0",
      "rem": "0",
      "type": "spacing"
    },
    "1": {
      "5": {
        "value": "6",
        "rem": "0.375rem",
        "type": "spacing"
      },
      "value": "4",
      "rem": "0.25rem",
      "type": "spacing"
    },
    "2": {
      "5": {
        "value": "10",
        "rem": "0.625rem",
        "type": "spacing"
      },
      "value": "8",
      "rem": "0.5rem",
      "type": "spacing"
    },```

**Comment by six7** [comment]
I'll be closing this as not planned because as of the W3C draft `.` is a forbidden character in token names

https://tr.designtokens.org/format/#character-restrictions
