### ISSUE TITLE
Make it harder to delete tokens

### ISSUE THREAD

**Issue by chris-pearce** [six7/figma-tokens#52]
Currently, it's all too easy to completely delete your tokens when in the `JSON` tab via the **Reset to Default** and **Clear** buttons: 

<img width="797" alt="Mad Paws Design System – Figma 2020-11-12 16-23-08" src="https://user-images.githubusercontent.com/1342772/98900464-ec08dc80-2505-11eb-95bf-910c07afdbda.png">

One idea is to serve up a confirmation modal dialog that forces you to confirm the action.

**Comment by six7** [comment]
I think a modal asking the user to confirm the destructive action would be good.

What I usually do if Im unhappy with any token deletions Ive done is just go Cmd + Z the latest actions in Figma itself and then restart the plugin - perhaps  Undo would also be a good option for the plugin itself?

**Comment by six7** [comment]
Added a confirm dialog before performing any destructive action:

![image](https://user-images.githubusercontent.com/4548309/100019358-2f086100-2dde-11eb-8aaf-9db0e8a52f1f.png)
