### ISSUE TITLE
Allow the currently active sync setting to be deleted

### ISSUE THREAD

**Issue by JamieMoriarty** [six7/figma-tokens#526]
**Is your feature request related to a problem? Please describe.**
Currently I can only 'Add new credentials' or 'Edit' existing ones. I would like to be able to delete existing settings, especially since they (potentially) contain PAT for GitHub and other sensitive information. I'm not even able to fill in 'garbage info' afterwards because the plugin is then unable to connect to GitHub - a nice feature when you're adding a synch config the first time, less nice when you are trying anonymize data after initial add.

**Describe the solution you'd like**
A delete button next to the 'Edit' option which permanently deletes the configuration would be ideal

**Comment by six7** [comment]
As a quick fix: Change sync to local, then you can delete the item.

**Comment by JamieMoriarty** [comment]
Nice, thank you 😄
