### ISSUE TITLE
append unit does not work

### ISSUE THREAD

**Issue by engegu** [six7/figma-tokens#527]
Cannot append a unit to a calculation result as shown in the documentation 
<img width="837" alt="image" src="https://user-images.githubusercontent.com/38129827/158364564-15bb50e4-039f-481a-b946-88a15101c53c.png">

**Comment by six7** [comment]
Ah, right. You'd have to wrap just the calculation (without the unit) in its own alias for now (that you then use to add rem), which is a bit tedious.

**Comment by six7** [comment]
[Changed docs](https://docs.tokens.studio/tokens/using-math) to explain how it would work, thanks for reporting!
