### ISSUE TITLE
My documentation tokens keep disappearing

### ISSUE THREAD

**Issue by engegu** [six7/figma-tokens#547]
For the second time today my documentation tokens have vanished, no plugin crash or anything, just gone… is there some kind of know issue here -    there are close to a hundred of these swatches and theyve all reverted their 3 linked values. The inspect shows no tokens applied to the objects.

![image](https://user-images.githubusercontent.com/38129827/159930227-faae8f43-aefb-4375-81e4-6a6101e62ca5.png)

**Comment by engegu** [comment]
And, any way to back them up? Im not inclined to remap them for a third time only for this to happen again :(

**Comment by six7** [comment]
Not that I'm aware of, are you able to reproduce this? By `reverted` do you mean they're gone or have they reverted to what a main component was using?

Are you using the plugin solo or with other designers using it at the same time? Any pointers would be greatly appreciated 🙏

**Comment by engegu** [comment]
I will try to reproduce it if i can during the coming workdays.

Tokens were applied to instances, not the master. whilst working on other things in the documents I on two occasions noticed the instanced were initialized, and my nice dynamic values from documentation tokens were gone. I am unsure of exactly what triggered this, but i can think of a few things:

1. I 've experienced semi-frequent Figma plugin runtime error (i think it was… that red toast thing pops up in the bottom of the screen) alerts while working with Figma Tokens, requiring a restart of Figma in order to open Figma Tokens again in the same document.

2. I did make some minor adjustments to the main component, nothing i should thing would trigger a rest of overrides causing a loss of tokens, but i might be wrong.

On another note, some way of applying documentation tokens more quickly would be awesome, when i have eight series of 050, 100, 150, 200 etc colors and want to get 3-4 values for each swatch from doc tokens, thats a lot of manual work (specially if they reset :D )

Thanks again for a great plugin, really shapes the way we work with Figma now.

**Comment by engegu** [comment]
I am soloing atm, other designer will get read only eventually for refrencing purposes.

**Comment by six7** [comment]
Thanks for the context, I'll try to keep an an eye on this and see if I can reproduce.

> On another note, some way of applying documentation tokens more quickly would be awesome, when i have eight series of 050, 100, 150, 200 etc colors and want to get 3-4 values for each swatch from doc tokens, thats a lot of manual work (specially if they reset :D )

On that note: I recently published something for the Automator community that creates documentation layers for you really quickly, but I definitely want to have something like this in the plugin natively!

**Comment by engegu** [comment]
Got a link for your automation? I’ve yet to try that, pricing puts me a bit off until I see something I NEED 😅

**Comment by six7** [comment]
Should be up at the automation.community soon, until then it's also here: https://github.com/six7/automator/blob/main/create-documentation.json

**Comment by engegu** [comment]
Thanks!

**Comment by engegu** [comment]
Been trying this out today, cannot get it to produce anything but an empty autolayout - are there any other plugins i need for it to work correctly? Also would it work with remote tokens? (Been trying on local ones just in case)

**Comment by six7** [comment]
Perhaps this helps:

Basically, have a layer selected that serves as a template. Then, name layers according to what property should be set (e.g. `__fill`, `__tokenValue`)

https://user-images.githubusercontent.com/4548309/160466324-c5613c3f-73d9-49f5-8e8c-7c7503c71523.mp4

**Comment by six7** [comment]
I haven't had any feedback like this - which is why I'm closing this issue. Let me know if it appears again.
