### ISSUE TITLE
Math with units doesn't work as documented

### ISSUE THREAD

**Issue by etokheim** [six7/figma-tokens#548]
**Describe the bug**
> Adding units
> The plugin cannot calculate if one of your tokens had the unit included (e.g. spacing.sm = 2rem). In that case you can either decide to remove the unit or append the unit after the operation **(e.g. {spacing.xs} * {spacing.scale}rem)**

[Docs](https://docs.tokens.studio/tokens/using-math#adding-units)

**To Reproduce**
According to the docs, shouldn't this equation render 256rem?:
![image](https://user-images.githubusercontent.com/23167168/160126080-76502115-0ba8-4757-8a18-b91e56306892.png)

It works as expected without the units:
![image](https://user-images.githubusercontent.com/23167168/160126088-336b11f5-1ed0-4885-8142-552e428b9b29.png)

(I tried adding some spaces or wrapping the calculation in parenthesis's, but it didn't help)

**Comment by six7** [comment]
Yeah, that part of the docs contains wrong information unfortunately, will update that!

Math operations cannot be mixed with units, so the following will not work:

`{size.rem} * {size.scale}rem`

Extracting the math part into its own token will work:

size.calculation: `{size.rem} * {size.scale}`
other token: `{size.calculation}rem`

**Comment by six7** [comment]
[Changed docs](https://docs.tokens.studio/tokens/using-math) to explain how it would work, thanks for reporting!
