### ISSUE TITLE
font-family tokens with single quotes

### ISSUE THREAD

**Issue by marco-condello** [six7/figma-tokens#560]
is there a way to export font-family tokens with single quotes?

or perhaps an automation on styledictionary that translates
this → $ font-family-titillium: Titillium Web;
in this → $ font-family-titillium: 'Titillium Web';

**Comment by six7** [comment]
You can use the following style dictionary transform:

```
/**
 * Transform font families to string value
 */
 StyleDictionary.registerTransform({
  name: "type/fontFamilies",
  type: "value",
  transitive: true,
  matcher: (token) => token.type === "fontFamilies",
  transformer: (token) => `'${token.value}'`,
});
```
