### ISSUE TITLE
Reference Shadow tokens

### ISSUE THREAD

**Issue by daniel-casado** [six7/figma-tokens#565]
**Is your feature request related to a problem? Please describe.**
My team is following the token heirarchy described by [Adobe Spectrum](https://spectrum.adobe.com/page/design-tokens/). Using references to other tokens as values is great to create these hierarchies, except that we can't reference a shadow token to create an alias or component level token

**Describe the solution you'd like**
For it be possible for a shadow token to get its entire value (blur, offset, color and mutilple shadows) from another shadow token.

**Describe alternatives you've considered**
Another way to put it it would be to dissasemble a shadow token the same way the typography token gets dissasemled, but that wouldn't make a lot of sense in general.

**Comment by six7** [comment]
Definitely needed, will hopefully be able to tackle this soon. 🙏

**Comment by six7** [comment]
We just merged this into the next release branch, should be released in the next two weeks or so.
