### ISSUE TITLE
Box shadow tokens don't apply

### ISSUE THREAD

**Issue by ervasive** [six7/figma-tokens#567]
**Describe the bug**
I'm not sure if this is a known issue, but it seems that box shadow tokens do not work for me.

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/85254/160869912-6fe4dbc6-e97a-4ad0-819a-8a1b034273d4.mp4

**JSON (optional)**
```JSON
{
  "base": {
    "value": {
      "x": "2",
      "y": "2",
      "blur": "10",
      "spread": "5",
      "color": "#000000",
      "type": "dropShadow"
    },
    "type": "boxShadow"
  }
}
```

**Comment by six7** [comment]
Fixed in version 90. Thanks for reporting 🙏

**Comment by spalz** [comment]
> Fixed in version 90. Thanks for reporting 🙏

Error repeats, one in one, I don't know how to continue working on the design system

https://user-images.githubusercontent.com/20950310/169387002-231c8c6b-7db5-4330-8aa1-7c3dbd9d99ec.mov

**Comment by six7** [comment]
> > Fixed in version 90. Thanks for reporting 🙏
> 
> 
> 
> Error repeats, one in one, I don't know how to continue working on the design system
> 
> 
> 
> https://user-images.githubusercontent.com/20950310/169387002-231c8c6b-7db5-4330-8aa1-7c3dbd9d99ec.mov
> 
> 
> 
> <img width="899" alt="Screen Shot 2022-05-20 at 01 32 16" src="https://user-images.githubusercontent.com/20950310/169387760-3dc01533-f562-4349-9c4a-c0b974101cc9.png">
> 
> 
> 
> 

Red dot indicates a missing token. You need to activate light or dark theme in your example.

**Comment by spalz** [comment]
> Red dot indicates a missing token. You need to activate light or dark theme in your example.

I'm sorry, I thought that the error was similar, but I was wrong.

The documentation does not specify how box Shadow can be transmitted, it was transmitted in the same way as background-gradient
I tried a lot of options but never came to a decision
```
value: "1 1 1 1 rgba(0, 0, 0, 1)"
value: "1 1 1 rgba(0, 0, 0, 1)"
value: "1 1 1 1 rgba(0, 0, 0, 1)"
value: "1 1 1 rgba(0, 0, 0, 1)"
value: "dropShadow 1 1 1 1 rgba(0, 0, 0, 1)"
value: "innerShadow 1 1 1 rgba(0, 0, 0, 1)"
value: "drop 1 1 1 1 rgba(0, 0, 0, 1)"
value: "inner 1 1 1 rgba(0, 0, 0, 1)"
```
