### ISSUE TITLE
italic font family?

### ISSUE THREAD

**Issue by marco-condello** [six7/figma-tokens#596]
how can I set the design tokens to export an italic variant of a font? e.g font-family-titillium-italic

**Comment by six7** [comment]
As the italic version is just using a different font weight / file you'd just be setting the font weight to `Italic` - with font family being set to `Titilium`.

**Comment by marco-condello** [comment]
it is not a problem of using the plugin but of output in json. 
“Italic” is not a font-weight, so the generated variable

**"font-style-italic": {

    "value": "Italic",

  "type": "fontWeights"

  },**
  
   is incorrect

**Comment by six7** [comment]
but italic is a font weight? there's no "italic" setting in figma, instead you choose a different font weight.

also in css you choose a specific font file for using italic. otherwise it's just faux italic.

**Comment by six7** [comment]
Closing this as there's no support to do this in Figma other than setting it as a font weight.
