### ISSUE TITLE
Allow importing a local .json file

### ISSUE THREAD

**Issue by 3dyonic** [six7/figma-tokens#599]
Currently we cannot load a Json into the Figma Plugin.
Just use it to generate one. 
Since token are very sensitive and require their own flow and registration process we would like to build are tokens outside of Figma and use the Figma plugin not as the creation layer but rather as bridge to the Figma related processes.

**Describe the solution you'd like**
I would like to be able to load a structured Json into Figma and be able to populate document styles from it.
After import i would like to be able to sync (exist now only for values i create within the plugin)

**Describe alternatives you've considered**
Creating Token manually , managing them in tables, using style dictionary

**Additional context**
https://github.com/amzn/style-dictionary/blob/main/examples/basic/tokens/color/base.json

**Comment by esthercheran** [comment]
You could use one of the sync options like GitHub or JSONBin. Or just paste a json object in the JSON tab. Or am I missing something about your requirement?

**Comment by six7** [comment]
This one is about loading a token file, which users might have previously exported vis the plugin.

I'd see this part of a flow where users are able to export their tokens to file(s) and later import that same file(s) again.
