### ISSUE TITLE
a mistake in sorting by name 

### ISSUE THREAD

**Issue by ifryan** [six7/figma-tokens#601]
<img width="203" alt="image" src="https://user-images.githubusercontent.com/34430609/163098160-3d62f44c-e804-4f83-958a-94ba0e14a6e5.png">
when I imported my color styles which I named it by number (01-10) in, the color named "blue.10" always ranks ahead, while the color “blue.01” ranks below.

**Comment by six7** [comment]
Unfortunately thats the way json sorts. I'd recommend to use 50, 100, 200, ...

We currently can only sort tokens that aren't numbers
