### ISSUE TITLE
How to reference variables between token sets?

### ISSUE THREAD

**Issue by surfinzap** [six7/figma-tokens#624]
I have a global token set with defined colors:
![image](https://user-images.githubusercontent.com/1387798/164209792-bcfd7928-f6f2-41e3-9fca-fc78ddf9d290.png)

is there a way to reference a variable from one token set (global) in another token set (light)?
![image](https://user-images.githubusercontent.com/1387798/164210995-50739ff9-eba9-484d-96a0-f21fdccb3b0d.png)
these options do not seem to work:
- Black
- colors.Black
- global.Black
- global.colors.Black

**Comment by yceballost** [comment]
Same problem here, how can I use a single color palette for two themes?

**Comment by darioaschero** [comment]
`{colors.Black}` or `{Black}` depend on how you named your tokens. 
The name of the set (eg. global) does not need to be included in the alias. 

<img width="1006" alt="Screenshot 2022-04-21 at 15 58 00" src="https://user-images.githubusercontent.com/13731944/164477091-ed00ab78-efc6-490e-833e-9a0d1e591948.png">
<img width="967" alt="Screenshot 2022-04-21 at 16 09 03" src="https://user-images.githubusercontent.com/13731944/164477140-1eb3c397-71c3-4d8f-bc12-591a10f87a23.png">
<img width="295" alt="Screenshot 2022-04-21 at 16 10 12" src="https://user-images.githubusercontent.com/13731944/164477209-0b4f9ff5-c98f-4829-9ece-fb3f3688ccf1.png">

**Comment by surfinzap** [comment]
> For what i see from the screenshot, your sets are not activated. By ticking the checkbox you activate a set. <img alt="Screenshot 2022-04-21 at 15 53 01" width="150" src="https://user-images.githubusercontent.com/13731944/164474109-c5ede259-807f-4371-90a1-bb7909db93f6.png"> Once your global set is activated you should be able to reference to its tokens. eg. {Black}

Thanks! I thought I'm overlooking some details.

Maybe it would be good to mention that in docs: https://docs.tokens.studio/token-sets

**Comment by six7** [comment]
Will update docs soon to reflect the new ui. Closing this one, feel free to reopen!
