### ISSUE TITLE
Can't create Figma styles

### ISSUE THREAD

**Issue by LehtinenRiku** [six7/figma-tokens#628]
Suddenly, the file I'm currently working on doesn't allow to "Create styles" from tokens. It doesn't matter what's in the JSON. If I remove everything and add just one color for example, it still doesn't work. If I create a new file, then the style creation works - with the JSON I just worked with, or with for example one color.

Can Figma file be somehow corrupted, and how to avoid that?

Is this known issue? This seems more like a file specific problem. No other plugins in use. Tried to restart Figma and even computer.

**Comment by esthercheran** [comment]
What happens if you duplicate the file and try it?

**Comment by six7** [comment]
Is 'ignore first part...' off in the settings screen?

**Comment by chriskerr-performio** [comment]
I ran into this a few times @LehtinenRiku.,,,, just double check you have the theme(s) you want to create from selected in the left hand panel. If they aren't selected, it doesn't create styles and the UI doesn't give any feedback

**Comment by LehtinenRiku** [comment]
> I ran into this a few times @LehtinenRiku.,,,, just double check you have the theme(s) you want to create from selected in the left hand panel. If they aren't selected, it doesn't create styles and the UI doesn't give any feedback

This was the reason. I changed the name of the set and it then apparently changed it to unselected.

It's only visible when hovering the set name. Maybe show the tickbox always? Or some other indicator when set is not active.

![unselected](https://user-images.githubusercontent.com/11766672/164612743-e8428c70-85d9-4cd3-8e55-fdac2c0ef8ac.png)

![unselected-hover](https://user-images.githubusercontent.com/11766672/164612769-2409acad-2dd7-4fd7-ab3e-c0b828300537.png)

Thank you!

**Comment by six7** [comment]
Thanks @LehtinenRiku - we'll try to fix 2 things here:

- Fix that it unselects when you rename s set
- Increase visibility when it's inactive

**Comment by kendrick** [comment]
@chriskerr-performio, thanks for the tip! @six7, thanks for such a rad plugin and for being so involved in the community around it!

**Comment by christophsolo90** [comment]
This tip was a livesaver! I was already panicking as I couldn't update the styles anymore. 

Kudos!

**Comment by six7** [comment]
Closing this as we hopefully made it more obvious that there's a checkbox to be ticked with V97.
