### ISSUE TITLE
Normalize values in JSON output

### ISSUE THREAD

**Issue by StudioSpindle** [six7/figma-tokens#63]
The output of the token export copies the style names 1on1. 

So for example if you have the following color styles:

![Screenshot 2020-12-16 at 11 42 11](https://user-images.githubusercontent.com/9882035/102338148-c010c900-3f93-11eb-9998-45ed7a1bbed9.png)

The output is: 

```
{
  "colors": {
    "Support ": {
      " Accent": "#0143ff",
      " Grey Dark": "#556a7b",
      " Grey": "#a3b0ba",
      " Grey Light": "#edf1f5",
      " White": "#ffffff",
      " Black": "#000000"
    }
  }
}
```

The spaces and capitals aren't conventional for JSON output. 

developer.mozilla.org uses **snake_casing** ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#Examples))
w3cschools uses **camelCasing** in their examples ([source](https://www.w3schools.com/js/js_json.asp))

Which format to choose exectly might be a configurable setting or it could just be a standard for this library.

But the idea to normalize the JSON output, is that something that's desired?

**Comment by StudioSpindle** [comment]
@six7 If you think this is an good idea, and we can agree on the desired functionality I'd be happy to file in a MR.

**Comment by six7** [comment]
I like it! Some things I would consider essential:

As currently we only look for the name when mapping tokens to their Figma styles to update the values I would prefer it if the solution could work with both of these cases:
- a user sets names as `Parent / Child` (note the spaces)
- a user sets names as `Parent/Child` (no spaces)

If the mapping solution could look for both these names with an empty string before and after the name then that would be great! I just want to avoid people not having their tokens mapped to their styles because we now strip all the spaces.

Feel free to create a MR for that, and thank you! 🙏

**Comment by StudioSpindle** [comment]
Cool!

I think the mapping tokens to Figma styles will be untouched. I meant regarding the export of the JSON.

I was thinking in the lines of either (don't mind the exact styling):

**A setting in the JSON tab:**

|---|---|
|  ![JSON formatting](https://user-images.githubusercontent.com/9882035/102608139-b325de00-4129-11eb-98f4-7e87c24e7e22.png) |  ![JSON formatting Open](https://user-images.githubusercontent.com/9882035/102608151-b9b45580-4129-11eb-9b44-4d08620d405f.png) |


**An export functionality:**

|---|---|---|
| ![export button](https://user-images.githubusercontent.com/9882035/102608176-c173fa00-4129-11eb-8ccd-7fd62faa5601.png) | ![export options](https://user-images.githubusercontent.com/9882035/102608200-c9cc3500-4129-11eb-88b1-72a174882b7a.png) | ![export options open](https://user-images.githubusercontent.com/9882035/102608220-d5b7f700-4129-11eb-8e01-e52da8e46298.png)|

This would be a solution to build further upon for other options. Maybe something for a later iteration.

**Comment by six7** [comment]
Oh thats quite neat, Ive had something like that in mind for an Export action. I was leaning towards putting Export into its own tab, as we'll have quite a few options there in the future. But we can always rearrange when we get there.

What would happen if I clicked Export? Fill a textarea with the json / yml / whatever in the way the user set it to?

I think I'd prefer option B as the settings are purely for exporting, could be confusing seeing it next to the JSON input (maybe JSON input should also someday move closer to Tokens (as really its just an Input right now).

If you want to work on this Export functionality I'd gladly accept any PR in this area, I think that could be a great intro to Exporting. If you need any help let me know! 🙏🙏
