### ISSUE TITLE
JsonBin sync not working

### ISSUE THREAD

**Issue by nan4k7** [six7/figma-tokens#630]
**Describe the bug**
Hi! I'm having problems with jsonbin sync, it ain't uploading changes to the site.

**To Reproduce**
1. Add jsonbin creds on plugin
2. Create new token and update

**Expected behavior**
New token should be synced to jsonbin and it doesn't sync

**Screenshots or Screencasts**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/8295972/164497994-318e3418-eba2-4075-bc39-3c9c89732c62.png)
![MicrosoftTeams-image2](https://user-images.githubusercontent.com/8295972/164498003-d10610b6-acb8-43ec-a495-6e50fbdc06a5.png)
![MicrosoftTeams-image3](https://user-images.githubusercontent.com/8295972/164498008-2a1503ed-1570-43ad-8818-c431fb2c2dfe.png)

**Comment by nan4k7** [comment]
Hi @six7 ! yeah it was checked...

Now i removed the bin and created a new one and everything seems to be syncing

**Comment by six7** [comment]
> Hi @six7 ! yeah it was checked...
> 
> 
> 
> Now i removed the bin and created a new one and everything seems to be syncing 

Hm, any chance the credentials got invalid? Otherwise unless those were changed it should keep working.
