### ISSUE TITLE
Add a color picker to edit color tokens

### ISSUE THREAD

**Issue by fbielsky** [six7/figma-tokens#638]
**Is your feature request related to a problem? Please describe.**
To create color tokens actually I have to copy the hex code of a particular color which is very time consuming.

**Describe the solution you'd like**
While editing a color it would be helpful to change the color using a color picker, to choose colors directly used in my designs.

**Additional context**
<img width="828" alt="image" src="https://user-images.githubusercontent.com/104068053/165072336-f8bd2a65-0476-4026-ae34-3bc296e5c244.png">

**Comment by esthercheran** [comment]
We did develop this feature, but a color picker inside figma resulted in stability issues and caused to plugin to hang or crash. We will revisit this feature at a later moment, probably when the color picker input becomes more stable.

**Comment by six7** [comment]
While investigating for the picker we have today we were also looking at a pipette, but that was not something that was possible. Will close as not planned, unfortunately.
