### ISSUE TITLE
Documentation tokens not updating after change to value

### ISSUE THREAD

**Issue by ChippyWhips** [six7/figma-tokens#642]
**Describe the bug**
When using Documentation Tokens to hook up text to a live value such as token [name or value] the text using the Documentation Token is not updated if the [name or value] is changed. It does however update if after the change you deselect the documentation reference, and then reselect it.

**To Reproduce**
Steps to reproduce the behaviour:
As per video attached:
1. select a text layer that is using a documentation token (for example [token name])
2. verify that it is linked correctly to the documentation token
3. edit that token (for example change the name)
4. see that the text layer using the [token name] does not update to reflect the renamed token
5. "unlink" the text layer from the documentation token
6. "relink" the text layer to the documentation token (for example [token name])
7. see that the new name is now reflected in the text layer

**Expected behaviour**
When editing a token - be that it's name, value, or description, any text layer linked to it's documentation tokens should update immediately to reflect the changes made.

**Screenshots or Screencasts**
https://user-images.githubusercontent.com/10211530/165400992-d3c08b5d-c043-46a4-8bd7-f8157a534de5.mov
 

**JSON (optional)**
If possible, attach the JSON that leads to this bug.
```
{
  "space": {
    "2": {
      "value": "0.125rem",
      "type": "spacing",
      "description": "2px"
    },
    "4": {
      "value": "0.25rem",
      "type": "spacing",
      "description": "4px"
    },
    "8": {
      "value": "0.5rem",
      "type": "spacing",
      "description": "8px"
    },
    "12": {
      "value": "0.75rem",
      "type": "spacing",
      "description": "12px"
    },
    "18": {
      "value": "1.125rem",
      "type": "spacing",
      "description": "18px"
    },
    "24": {
      "value": "1.5rem",
      "type": "spacing",
      "description": "24px"
    },
    "32": {
      "value": "2rem",
      "type": "spacing",
      "description": "32px"
    },
    "40": {
      "value": "2.5rem",
      "type": "spacing",
      "description": "40px"
    },
    "56": {
      "value": "3.5rem",
      "type": "spacing",
      "description": "56px"
    },
    "72": {
      "value": "4.5rem",
      "type": "spacing",
      "description": "72px"
    },
    "104": {
      "value": "6.5rem",
      "type": "spacing",
      "description": "104px"
    },
    "136": {
      "value": "8.5rem",
      "type": "spacing",
      "description": "136px"
    },
    "172": {
      "value": "10.75rem",
      "type": "spacing",
      "description": "172px"
    }
  },
  "size": {
    "2": {
      "value": "{space.2}",
      "type": "sizing",
      "description": "2px"
    },
    "4": {
      "value": "{space.4}",
      "type": "sizing",
      "description": "4px"
    },
    "8": {
      "value": "{space.8}",
      "type": "sizing",
      "description": "8px"
    },
    "12": {
      "value": "{space.12}",
      "type": "sizing",
      "description": "12px"
    },
    "18": {
      "value": "{space.18}",
      "type": "sizing",
      "description": "18px"
    },
    "24": {
      "value": "{space.24}",
      "type": "sizing",
      "description": "24px"
    },
    "32": {
      "value": "{space.32}",
      "type": "sizing",
      "description": "32px"
    },
    "40": {
      "value": "{space.40}",
      "type": "sizing",
      "description": "40px"
    },
    "56": {
      "value": "{space.56}",
      "type": "sizing",
      "description": "56px"
    },
    "72": {
      "value": "{space.72}",
      "type": "sizing",
      "description": "72px"
    },
    "104": {
      "value": "{space.104}",
      "type": "sizing",
      "description": "104px"
    },
    "136": {
      "value": "{space.136}",
      "type": "sizing",
      "description": "136px"
    },
    "172": {
      "value": "{space.172}",
      "type": "sizing",
      "description": "172px"
    }
  }
}
```

Closing note:
Thank you for all the work you're putting into this amazing plugin 🙌 ❤️

**Comment by six7** [comment]
Hey there, thanks for reporting!

Can you confirm this works:

- Edit a token
- When asked to Remap, choose Yes (like you did)
- Press `Update` on the bottom right of the plugin (with the layers selected that you want updated or `Apply to page` set)

**Comment by ChippyWhips** [comment]
Howdy 👋 

Yes I can confirm that the additional step of hitting the bottom right 'Update' CTA does update the references as expected. Perhaps this is the missing step I was not aware of 😅

**Comment by LehtinenRiku** [comment]
Also make sure you have that Token set activated when you edit a value. Otherwise is won't update dokumentation tokens in a document. Learned that the hard way.

**Comment by six7** [comment]
I'm leaning towards just updating the remapped layers after Remap, as that is what you were expecting to happen anyway. My original intent was that this might not be what users would want, as they might not have the correct token sets activated. But I think that was a wrong assumption to make.
