### ISSUE TITLE
Typogrpahy/Text styles not being created when using alias tokens

### ISSUE THREAD

**Issue by chriskerr-performio** [six7/figma-tokens#645]
**Describe the bug**
When using alias tokens in the typography token sub-elements (font size, line height, etc), when you create the text styles back into Figma, the text style is created (with the correct text style name) but the values are all the same  and not inline with the alias token references(font family: inter, font weight: regular, font size: 12pt, line height: auto)

This was also raised (perhaps incorrectly, apologies @six7) in the discussions section: https://github.com/six7/figma-tokens/discussions/631

**To Reproduce**
1. Apply alias tokens to typeography sub-elements
2. Click on Create Styles
3. View text style properties

**Expected behavior**
Text styles are created using the values of the aliases referenced

**Screenshots or Screencasts**
<img width="750" alt="164527401-846ac9cc-69b6-4adc-bf06-11bac5084c7d" src="https://user-images.githubusercontent.com/100885654/165641231-fe486537-5d72-4220-98ef-5387f201173a.png">
<img width="240" alt="164534245-2b757b75-d36f-44b7-8971-07d99c87e336" src="https://user-images.githubusercontent.com/100885654/165641238-d7defee2-59b5-4158-8946-026effdfcc05.png">
<img width="235" alt="Screen Shot 2022-04-28 at 08 21 52" src="https://user-images.githubusercontent.com/100885654/165641249-b9d15c25-0c93-4b98-b57f-4bcfdbf4723e.png">

**Figma file (optional)**
Empty Figma file with the output of the above bug reported
https://www.figma.com/file/zdVVk1zkGTWIf6JY0bi3J9/Text-Style-Creation-Issue?node-id=0%3A1

**JSON (optional)**
Attached extract for typography and referenced alias tokens
[typography_tokens.json.zip](https://github.com/six7/figma-tokens/files/8578176/typography_tokens.json.zip)

**Comment by six7** [comment]
👋  I noticed you're using the wrong font weights.

Make sure that the font weight / font family combination exists in Figma.

You have:
`Open Sans`
`400`

In Figma, there is no 400.

There is `Regular`.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/4548309/165710969-b646c185-44e5-41f5-b287-1e152e2d9f4b.png">

**Comment by chriskerr-performio** [comment]
Ah thanks @six7, that didn't even cross my mind..... I'll see if this fixes it.... any thoughts on how do we create a font-family agnostic weighting scale then?

**Comment by six7** [comment]
I'd always have a family/weight pair, as it's not really possible to have one without the other right now if you want a specific weight (maybe we'll have a way to specify numeric weights some day).

Closing this one, feel free to reopen if it persists 🙏
