### ISSUE TITLE
UX considerations

### ISSUE THREAD

**Issue by StudioSpindle** [six7/figma-tokens#65]
| | |
|---|---|
| ![Screenshot 2020-12-18 at 12 33 59](https://user-images.githubusercontent.com/9882035/102610393-66440680-412d-11eb-8d18-30eabcf7d1dd.png) | **Reset to Default (button)** <br> Is an action that is not only applicable to the JSON tab but also to tokens. Also it takes up important real estate on that location. It's expected not to be used that often. (right?)<br><br>**Button: Enable color UI (little droplet)**<br>Is only applicable for the Tokens tab. Has no meaning on the other tabs.<br><br>**Inspect**<br> Seems to be applicable only for a layer, not groups or symbols. Maybe the name is too ambiguous? |

Would it be an idea to:
- Place "Reset to default" and "Import styles" at the same "level". Perhaps in a menu. 
- Move the droplet inside just the "Tokens" tab
- Rename "Inspect" to "Inspect layer"

**Comment by six7** [comment]
Totally, good catch!

A menu for various actions such as Reset, Clear, Import Styles (which could be split into Text and Color) in the top right makes a lot of sense.

And I agree about the droplet, has no meaning and can be moved to the Tokens tab.

Inspect Im not so sure, wanted to stay close to Figmas own behaviour, but were not really constrained by space so we could as well expand the naming 👍
