### ISSUE TITLE
Can't parse boxShadow tokens if it has reference in value property

### ISSUE THREAD

**Issue by anatoliiborkivski** [six7/figma-tokens#653]
**Describe the bug**
Can't parse boxShadow tokens if it has reference in value property

**To Reproduce**
npm run examples (in project from this repository)
JSON tokens
{
  "effect": {
    "type": "boxShadow",
    "value": {
      "x": "0",
      "y": "0",
      "blur": "0",
      "spread": "3",
      "color": "{single-blue}",
      "shadowType": "innerShadow"
    }
  },
  "single-blue": {
    "description": null,
    "type": "color",
    "value": "#044affff"
  }
}
webShadow transformer
<img width="677" alt="image" src="https://user-images.githubusercontent.com/104621409/165921842-ba7374e7-d6b6-4125-adc6-ab5926ae181b.png">

**Expected behavior**
<img width="432" alt="image" src="https://user-images.githubusercontent.com/104621409/165922222-2e447924-d9e9-4e92-a675-6e0da02266ee.png">

**Actual behavior**
<img width="349" alt="image" src="https://user-images.githubusercontent.com/104621409/165921980-ee397142-8d3c-465b-9ad1-7e562675d871.png">

Works fine if there is no references in properties
JSON
{
  "effect": {
    "type": "boxShadow",
    "value": {
      "x": "0",
      "y": "0",
      "blur": "0",
      "spread": "3",
      "color": "red",
      "shadowType": "innerShadow"
    }
  },
  "single-blue": {
    "description": null,
    "type": "color",
    "value": "#044affff"
  }
}
<img width="331" alt="image" src="https://user-images.githubusercontent.com/104621409/165922530-341854d0-0fcc-4000-be86-125ec7b73b38.png">

**Comment by mihkeleidast** [comment]
I believe your custom transform needs to have `transitive: true` to properly transform references, see https://amzn.github.io/style-dictionary/#/transforms?id=transitive-transforms

**Comment by anatoliiborkivski** [comment]
@mihkeleidast you are right, thanks , I've been struggling on in for few weeks

**Comment by six7** [comment]
I believe this is resolved, right? Feel free to reopen if not.
