### ISSUE TITLE
boxShadow token tooltip does not render correctly after saving JSON

### ISSUE THREAD

**Issue by mihkeleidast** [six7/figma-tokens#668]
**Describe the bug**

boxShadow tokens' values from a JSON do not render correctly in the token tooltip, instead showing the raw array/object.

**To Reproduce**
1. Import the JSON below to Figma Tokens
2. Switch to the listing view
3. Hover over a token 
4. See that the tooltip contents are not rendered as expected

**Expected behavior**

I expect the shadow token tooltip to render correctly immediately after saving the JSON.

**Screenshots or Screencasts**

Immediately after saving the JSON, the tooltip renders like this:
![image](https://user-images.githubusercontent.com/1892091/166415162-ce697af0-3ee4-4a34-9667-fe3325a07c72.png)
![image](https://user-images.githubusercontent.com/1892091/166415464-7a390929-1de5-4359-8b36-5a84ae7ae7f8.png)

If I edit the token in Figma or some value in the JSON (like the y value) and re-save, it will render correctly:
![image](https://user-images.githubusercontent.com/1892091/166415250-e2a188fb-d614-482b-b309-65fb0c12c3cf.png)

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

```json
{
  "boxShadow": {
    "xsmall": {
      "value": {
        "x": "0",
        "y": "1",
        "blur": "2",
        "spread": "0",
        "color": "rgba(0, 0, 0, 0.08)",
        "type": "dropShadow"
      }
    },
    "small": {
      "value": [
        {
          "x": "0",
          "y": "2",
          "blur": "4",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.08)",
          "type": "dropShadow"
        },
        {
          "x": "0",
          "y": "1",
          "blur": "2",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.08)",
          "type": "dropShadow"
        }
      ]
    }
  }
}
```

**Comment by esthercheran** [comment]
you're creating multiple "dropShadow", but the token itself also requires a type of "boxShadow":

```
"small": {
      "value": [
        {
          "x": "0",
          "y": "2",
          "blur": "4",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.08)",
          "type": "dropShadow"
        },
        {
          "x": "0",
          "y": "1",
          "blur": "2",
          "spread": "0",
          "color": "rgba(0, 0, 0, 0.08)",
          "type": "dropShadow"
        }
      ],
    "type": "boxShadow" // Add box shadow here
    }
```

**Comment by mihkeleidast** [comment]
That makes it work, thanks! I wonder if that can be automated though, as the plugin does look at the structure of the token to categorize it correctly - could it infer the type for the tooltip value as well?

**Comment by esthercheran** [comment]
It is because the token is recognised as type "other" since there is no type, and for other, the tooltip shows the raw value as it does not know what to expect. It could be anything from a string, to object, to array. For tokens to function well, a type is always required in the root of the token.

**Comment by mihkeleidast** [comment]
It was recognized correctly as a box shadow based on the first grouping in the JSON, my screenshots did not reflect that. Only the tooltip is not rendering correctly. But I think this is solved by adding the type, thanks!
