### ISSUE TITLE
Rename token creates duplicate

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#67]
I just started experimenting with figma-tokens today, looks very promising!

One issue that I encounter is that when renaming a token it creates a duplicate rather than overwriting the original token. 

For instance, if I want to rename `border-radius-square` to `border-radius--square` it creates another token instance after which I have to remap all elements using that token to the correctly named token.

**Comment by six7** [comment]
Ah, yes — thanks for reporting! Thats something the plugin should handle for you if you do it via the UI, the functionality just hasn't been written yet. But we definitely need this.

Basically when a token is updated we should check if the token has existed before and if so clear the old one and update any tokens that referenced the old token name to the new one. Right now it just sets a new one, which is probably never what the user wants.

I'd say when you rename a group the same thing should happen. That might get a little trickier though and could require us to iterate over all contents and do what we did for a single one.

**Comment by usethetics** [comment]
In the meantime, renaming the tokens in the JSON tab is a good work-around.Should’ve spotted that earlier!

**Comment by romeetosun** [comment]
Hello! I'm experimenten with Tokens too and I can't find how to crear a token that defines border colours.
Am I doing something wrong?

**Comment by six7** [comment]
Getting a fix online for this today, renaming a token now updates all occurrences. Renaming an object currently is not supported, but also not possible yet.

@romeetosun Have you tried right-clicking the "Fills" tokens? There you can selected "border", effectively applying a border color to the currently selected object.
