### ISSUE TITLE
Can't parse color rgba token that referencing another rgb token

### ISSUE THREAD

**Issue by anatoliiborkivski** [six7/figma-tokens#677]
Hi guys!

Input token
<img width="402" alt="image" src="https://user-images.githubusercontent.com/104621409/166960938-997cc946-f4bf-428b-8d20-6faf10a69337.png">

Output variable
<img width="484" alt="image" src="https://user-images.githubusercontent.com/104621409/166961146-0daa7765-8b0d-44d3-ad6b-c61c18e38830.png">

Parsing with npm run examples from this repo
Is this the expected behaviour?
What do i need to do to get value like this:  rgba(255, 255, 255, 0.7)?

**Comment by six7** [comment]
Here's a function that does this for you:

```
const { parseToRgba } = require("color2k");

/**
 * Helper: Transforms hex rgba colors used in figma tokens: rgba(#ffffff, 0.5) =? rgba(255, 255, 255, 0.5). This is kind of like an alpha() function.
 */
function transformHEXRGBa(value) {
  if (value.startsWith("rgba(#")) {
    const [hex, alpha] = value
    .replace(")", "")
    .split("rgba(")
    .pop()
    .split(", ");
    const [r, g, b] = parseToRgba(hex);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  } else {
    return value;
  }
}
```
