### ISSUE TITLE
Flexible vs. fixed units for token values

### ISSUE THREAD

**Issue by usethetics** [six7/figma-tokens#68]
I am not sure whether this is possible due to Figma’s implementation of these but I am wondering if it is possible to use flexible instead of fixed values for (some) tokens.

For instance, currently I am working on a typographic scale where the line-height is dependant on the font-size. For headings, narrow text, etc. I use a multiplier of 1.2 × font-size and for body text 1.5 × the font-size. Ultimately I use two tokens for line-height; a `line-height--tight` (1.2 ×) and a `line-height--loose` (1.5 ×).

What I am essentially doing in order to achieve this, is to enter the font-size in Figma’s line-height field followed by one of these multiplier tokens, like so:

![Screenshot 2021-01-07 at 14 46 27](https://user-images.githubusercontent.com/248921/103900021-94e34a80-50f7-11eb-8856-d72c2917a933.png)

Would it be possible to facilitate this?

**Comment by six7** [comment]
Yes, totally possible!

Here's a short video demonstrating how that works.

1) Add line height tokens (1.1 and 1.4 respectively)
2) References line height tokens and font size values in typography of text style

![CCl0Zbtaps](https://user-images.githubusercontent.com/4548309/103998184-17bde100-519c-11eb-8945-65683dbce60e.gif)

**Comment by usethetics** [comment]
Awesome, thanks for the extensive explanation!
