### ISSUE TITLE
Update action is not preserving color tokens on duplicated components

### ISSUE THREAD

**Issue by Cl3men** [six7/figma-tokens#694]
**Describe the bug**
When you try to update tokens on the duplicated component which has color token set afterward the update action will override the color token.

**To Reproduce**
1. Create a component and set the color token
2. use component instance and override the original color token with a new one
3. Duplicate instance and click on update in Figma tokens plugin

**Expected behavior**
Color tokens should not be changed with the update action

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/41045236/167798451-128fa695-bb48-4b50-b76c-9d96bdf28071.mp4

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Does this still appear for you with the current version of the plugin?

**Comment by six7** [comment]
Closing this, I think we have fixed this in a previous release. Feel free to reopen if it persists
