### ISSUE TITLE
New color tokens are not showing up in the widget

### ISSUE THREAD

**Issue by abinashmohanty** [six7/figma-tokens#710]
**Color tokens are not showing in figma token widget**
When I checked my jsonbin file, these are present. However, I can't see them in the figma plugin widget

**jsonbin**
```
"Primary": {
        "20": {
          "value": "rgba(242,113,49,0.2)",
          "type": "color"
        },
        "50": {
          "value": "rgba($Primary, 0.5)",
          "type": "color"
        },
        "value": "#f27132",
        "type": "color",
        "new": {
          "50": {
            "value": "rgba(242,113,49,0.5)",
            "type": "color"
```
**Figma Widget*
![CleanShot 2022-05-14 at 01 06 11@2x](https://user-images.githubusercontent.com/8434934/168377719-7e0147df-c472-4fce-8d79-6bde74f94868.jpg)

**Comment by six7** [comment]
The plugin currently doesn't support having a token that shares the name with a token group, the W3C currently recommends this.

I would advise to change your current "Primary" color to "Primary.default" as we currently do not plan to allow tokens that share names with token groups.

**Comment by abinashmohanty** [comment]
Thanks for the suggestion. I will do that :)
