### ISSUE TITLE
Set selections reset after pushing changes to Github

### ISSUE THREAD

**Issue by laundrycat7** [six7/figma-tokens#713]
Hi there, 

Whenever I make changes to my tokens and push them to Github, after loading and saving I get the confirmation message. However my currently selected themes become deselected. I have to reselect the ones I'm working in.

1. Open Figma Tokens (v99)
2. Make changes to tokens
3. Push changes to Github
4. See confirmation on changes pushed to Github
5. See selected themes have been deselected and nothing is selected

As with previous versions I expect nothing to really change once I see the confirmation changes. Themes I'm working in continue to be selected and I go about my day.

![image](https://user-images.githubusercontent.com/81506527/168528255-73a23479-5851-46b7-a5ca-fc09b496dd85.png)
![image](https://user-images.githubusercontent.com/81506527/168528096-4789c560-7968-4810-ba35-8c7203cb7274.png)

Thanks for looking into this!

**Comment by six7** [comment]
Just released this in version 102 🎉
