### ISSUE TITLE
URL Sync not Saving Connection with Valid Response

### ISSUE THREAD

**Issue by BlakeDWBrown** [six7/figma-tokens#716]
**Describe the bug**
URL sync is not saving the connection after the json object is returned. If I copy and paste the json object into the color set in the plug in it loads just fine. Nothing appears to be showing up in the console, network request shows 200 response with the valid JSON object. Blob is hosted on an azure storage account with anonymous blob access. Appears to have started around version 97.

**To Reproduce**
1. Install Plugin/Reinstall 
2. Open Figma Tokens Plug in and navigate to URL Sync
3. Add new credentials with URL of my test url "https://lunarstorageqa.blob.core.windows.net/build/figma-tokens.json"
4. Valid response from network request but get an error connecting with nothing meaningful in the console

**Expected behavior**
Would expect the credentials to save to the Figma Tokens plugin and be able to refresh the URL sync to pull changes

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/105505108/168612096-9d7bdde3-9712-4fa8-b1c6-bf1a4fc81ca7.png)
![image](https://user-images.githubusercontent.com/105505108/168612157-6bc922e4-8bce-4ec1-a94d-60b2f1f358f0.png)
![image](https://user-images.githubusercontent.com/105505108/168613225-b5c1261e-f13c-466d-b266-d4767002506c.png)

**JSON File**
[figma-tokens.txt](https://github.com/six7/figma-tokens/files/8700837/figma-tokens.txt)

**Comment by mihkeleidast** [comment]
@BlakeDWBrown just in case you haven't seen this, in #753 there's a bit more discussion about a similar issue, and it seems like the issue for most has been some missing `type`s on some of the tokens.

**Comment by BlakeDWBrown** [comment]
@mihkeleidast This resolved my issue! Thank you for diving into this for me. Hope we can get some better error message for that issue. Thank you!
