### ISSUE TITLE
JSON editor crashes often when entering $ in value

### ISSUE THREAD

**Issue by nathancooper** [six7/figma-tokens#72]
When entering a variable, often when typing $ the JSON window goes blank.
I've attached a picture of the window when this happens - about 50% of the time.

<img width="236" alt="Screen Shot 2021-02-02 at 6 18 06 PM" src="https://user-images.githubusercontent.com/319205/106688479-0c838880-6583-11eb-877c-04dd87aa4a3b.png">

<img width="438" alt="Screen Shot 2021-02-02 at 6 14 10 PM" src="https://user-images.githubusercontent.com/319205/106688213-86ffd880-6582-11eb-9b01-084b180843a5.png">

**Comment by six7** [comment]
Getting a fix online for this later today! Thanks for reporting @nathancooper !

Just a note: You'd need to write your `usr-base` as `8`, not `8px`
