### ISSUE TITLE
Access project in subgroup on gitlab

### ISSUE THREAD

**Issue by iPrytz** [six7/figma-tokens#724]
First, Thank you for adding support for Gitlab, it works well!
Except in this following case:  when the project is inside a subgroup.
 
**Is your feature request related to a problem? Please describe.**
Trying to connect Gitlab to a repo which is inside a subgroup. 
Get an error saying it cant connect, and when trying the requests the project i try to connect to is not in the response since it is a subgroup. 

**Describe the solution you'd like**
When trying to add a Gitlab as storage, 
Set query param in the request to `include_subgroups=true` by default, or add an option to include subgroups

**Describe alternatives you've considered**
Not sure, could always move the projects to root but that shouldn't be necessary

**Comment by six7** [comment]
Is there anything that can go wrong if we add `include_subgroups=true`? Or do we need to only add that to subgroups?
