### ISSUE TITLE
Github Enterprise repo URL issue

### ISSUE THREAD

**Issue by john777is** [six7/figma-tokens#725]
Hello,

I have a problem with the Github (Enterprise instance) Sync feature, it looks like the plugin is trying to use an incorrect URL pattern which doesn't match the one which is used in the enterprise instance of Github. So the `//repos` and `//branches` parts are being added, in my case it should be:  `github.domain.com/design-system/tokens-v2/` but instead it tries to connect to `github.domain.com/design-system//repos/tokens-v2//branches`. Changing the value in the baseURL field doesn't help. Please see the details in the attached screenshot from the **Add new credentials** panel and the dev-tools. 

Is it a bug? 

Additionally, wanted to ask more about the Enterprise instance of Github, if the repo is behind a firewall and only accessible when client is connected to a VPN, will the plugin be able to access the repo?

![issue-1](https://user-images.githubusercontent.com/105864043/169303757-461ca0cf-88e8-4e38-872d-9e67fd73ceec.jpg)

![issue-2](https://user-images.githubusercontent.com/105864043/169300843-1811123a-86c3-40bd-977c-ceb3c6652b56.jpg)

**Comment by six7** [comment]
Change baseUrl to be `https://github.xyz.com/api/v3` and your Repository to be `design-system/tokens-v2` - this should do the trick.

**Comment by john777is** [comment]
> Change baseUrl to be `https://github.xyz.com/api/v3` and your Repository to be `design-system/tokens-v2` - this should do the trick.

It worked! Thank You for such an amazing plugin 🙌🏻
