### ISSUE TITLE
The documentation for Gitlab is not linked correctly.

### ISSUE THREAD

**Issue by Membad** [six7/figma-tokens#728]
When selecting the Token Storage option Gitlab and then clicking the "Read the guide" link you end up on https://docs.tokens.studio/sync/gitlab which currently doesn't exist.

1. Go to Settings > Token Storage > Gitlab.
2. Click on "Read the guide".
3. The browser navigates to https://docs.tokens.studio/sync/gitlab.
4. The link returns a 404. The docs also doesn't have a page for Gitlab as far as I can tell.

**Comment by esthercheran** [comment]
Docs have been updated. Closing the issue.
