### ISSUE TITLE
Themization does not work. 

### ISSUE THREAD

**Issue by ikstro** [six7/figma-tokens#731]
Themization does not work. The plugin stopped generating styles.

1. Trying to activate a Dark theme or Font theme.
2. The dark theme is built on semantic colors through styles.
3. But the plugin doesn't change the styles in Figma

Checked all the files where it used to work. No result.

![photo_2022-05-20_14-53-26](https://user-images.githubusercontent.com/56383911/169547527-abbfd423-5aa4-4efd-aeb5-48f1ec55b257.jpg)

Also checked on Cabana
https://www.cabanaforfigma.com/
https://www.figma.com/file/GYSLZABwsHxNivXVw1N7fc/Cabana-for-Figma---Ultimate-(Demo)?node-id=0%3A1
Don't work)

Figma console shows errors:
------- Clearing and silencing console.log from Figma -------
VM1012:204          GET https://stripe-keygen.herokuapp.com/get-license?userId=659022025953631544 404 (Not Found)

**Comment by six7** [comment]
Can you check `Ignore first part of token name for styles` is unchecked in `Settings`? This is usually the source for this problem.

**Comment by ikstro** [comment]
Yes, it helped!
I wouldn't have thought of it myself.

**Comment by six7** [comment]
Great! Closing this, feel free to reopen if there's still an issue.
