### ISSUE TITLE
Data loss when closing plug-in window with Github sync enabled

### ISSUE THREAD

**Issue by mario-melodics** [six7/figma-tokens#746]
Without any warning all uncommitted work is lost when the plug-in window is closed when Github sync is enabled. This is entirely unexpected.

- Have Github sync enabled
- Create a token (eg a new color)
- Verify that you have uncommitted changes (blue arrow in the bottom left corner)
- Close the Figma Tokens plug-in window
- Reopen Figma Tokens

**Expected behavior**
Uncommitted changes persist and can be committed to Github
Ie local storage should always remain the fallback

**Comment by mario-melodics** [comment]
Thanks for your great work - often said, but very true here: Figma Tokens is a game changer. 🚀

**Comment by mario-melodics** [comment]
This and #713 make the integration (which is as general a approach amazing) very hard to work with

**Comment by six7** [comment]
We'll have both of those issues fixed in the next major release. We'll have a local storage then so you can choose to use last saved progress or pull from remote.

**Comment by mario-melodics** [comment]
Awesome news, will verify once out. Thank you 🙏

**Comment by six7** [comment]
Just released this in version 102 🎉
