### ISSUE TITLE
Export - Typography alias incorrectly exported

### ISSUE THREAD

**Issue by humaanuk** [six7/figma-tokens#750]
**Bug**
When exporting an alias typography style with 'Expand typography' option selected, the json renders a Name/Value pair of the original style reference. e.g. {s, t, y, l, e, 0, 1} instead of the associated fontSize, fontWeight, lineHeight etc.

**Reproduce**
1. Create a single typography style using Import (style01)
2. Create a new typography style (alias02) and select 'alias mode' button (4 circles)
3. Enter the original style in the aliasName {style01}
4. Hit 'Update'
5. Hit 'Export' and check 'Expand typography'
8. The exported alias typography is transformed into an object with Name Value pairs that reference the Name of the original style, not its values.

Note: If you don't 'Expand typography' you just get [Object, object] in the output.

**Expected behavior**
Expect the new alias style to have the same references as the original style. e.g. If original fontSize = 16, then the alias fontSize should also = 16 etc. 

**Screenshots**
<img width="526" alt="create-alias" src="https://user-images.githubusercontent.com/43551462/170210595-5ed6afa4-4aad-46be-bcc5-c155382d2936.png">

<img width="517" alt="export-expanded-alias" src="https://user-images.githubusercontent.com/43551462/170210848-530f9060-bd51-43c8-9458-5ef3253dd669.png">

**Figma file**
[Figma file containing a reproducible example](https://www.figma.com/file/J3VQ8zMsUIzrARc9Fp2z04/FigmaTokens-Bug-ExportTypography?node-id=0%3A1)

**Comment by six7** [comment]
Thanks for creating this, seems like this one slipped through when we worked on the new alias mode for typography tokens.
