### ISSUE TITLE
Gitlab credentials failing "Check your credentials"

### ISSUE THREAD

**Issue by MKHenson** [six7/figma-tokens#753]
**Describe the bug**
We are trying to sync with gitlab using the URL method as well as the Gitlab method, however both always result in the same error "There was an error connecting. Check your credentials"

**To Reproduce**
1. Open Figma Tokens
2. Go to settings
3. Select URL Token Storage
4. Click add new credentials
5. Enter a name
6. Enter the headers { "PRIVATE-TOKEN": "**ACCESS_TOKEN_FROM_GITLAB_WITH_READ_API**" }
7. Specify a valid url to a gitlab file in the URL section.

**Expected behavior**
When we click save, that the modal closes and the sync is performed. 

** Actual Behavior **
When we click save, an error appears. Using the exact same method before I was able to successfully sync. However, recently this no longer works even after re-creating all credentials. I checked in the network tab to see if gitlab was responding with the file in question, and I can see that it actually does return a valid response. So I dont understand why we're seeing the error reported in the modal. 

**Screenshots or Screencasts**
![Screenshot 2022-05-25 at 12 28 03](https://user-images.githubusercontent.com/2727104/170251981-70d53580-0e9f-4c30-a9a1-4bd3559322c9.png)
![Screenshot 2022-05-25 at 12 19 56](https://user-images.githubusercontent.com/2727104/170251987-f04086fe-4d38-4718-9ea1-1fd274b9ba03.png)

**Comment by six7** [comment]
Hey @MKHenson 👋 

Have you tried using the GitLab sync? You're using the URL sync right now.

**Comment by mihkeleidast** [comment]
See also #716, I've also been trying to set up sync, but it always fails with the same error in the UI, irregardless of what sync method is chosen (I've tried URL and JSONBin). The network requests always succeed correctly.

**Comment by MKHenson** [comment]
Hi @six7, yes we tried the gitlab sync and we get the same error

**Comment by MKHenson** [comment]
@mihkeleidast Yes that looks very similar to the issue

**Comment by six7** [comment]
Are you all using subgroups in gitlab by chance?

**Comment by MKHenson** [comment]
Hi @six7, no we're not using any sub groups

**Comment by mihkeleidast** [comment]
I'm debugging this (i.e. my URL sync issue) by loading the plugin locally and adding a bunch of console.logs everywhere. Currently it seems like it fails at the response JSON token schema validation, not with actual fetching. I'll try to go deeper next week, see if I can figure out what exactly is wrong with my JSON.

The error reporting and logging there could definitely be improved, as it seems that the "There was an error connecting. Check your credentials." error message is static and does not change depending on what actually goes wrong.

**Comment by mihkeleidast** [comment]
Ha, could not let it go, debugged it further and found out that some of my tokens did not have `type` set on them, which was my mistake, as I was adding them dynamically through a style-dictionary transform and had missed a switch case.

@six7 is there a reason why the "type" on every token is required? If I pasted that JSON manually in the plugin, it either figured out the type based on the token path (e.g. if it was a token in size category, it showed up under "Size" in plugin as well) OR put it down under "Other", where it was not usable, but everything else worked.

**Comment by six7** [comment]
> @six7 is there a reason why the "type" on every token is required? If I pasted that JSON manually in the plugin, it either figured out the type based on the token path (e.g. if it was a token in size category, it showed up under "Size" in plugin as well) OR put it down under "Other", where it was not usable, but everything else worked.

this is one of the things i want to improve, to allow tokens to come in without a type (it's implied type would then be whatever the `value` field is (e.g. string, number, etc - nothing that you'd be able to apply with the current methods). Or types to be defined on the group level, as outlined in the [current w3c draft](https://tr.designtokens.org/format/#type-0).

**Comment by nilbenis** [comment]
> Ha, could not let it go, debugged it further and found out that some of my tokens did not have `type` set on them, which was my mistake, as I was adding them dynamically through a style-dictionary transform and had missed a switch case.
> 
Yeap. That solved my “connection” issue too. Just as a note, I was using the same JSON (missing type in 3 tokens) in a previous version without error. Some change made the version less forgiven.
