### ISSUE TITLE
Set aliasing not resolving within Figma

### ISSUE THREAD

**Issue by zslabs** [six7/figma-tokens#755]
**Describe the bug**
Really appreciate you creating this tool! 🙌

Given a `dark` set which has alias values to a `global` set, running `token-transformer` resolves correctly, but the value is not shown in Figma.

**To Reproduce**

With the following config (using a single file as from what I gather only a single file is supported for GitHub push):

```
{
  "global": {
    "color": {
      "white": {
        "value": "#f0f0f0",
        "type": "color"
      },
      "black": {
        "value": "#222",
        "type": "color"
      },
      "background": {
        "value": "{color.white}",
        "type": "color"
      },
      "foreground": {
        "value": "{color.black}",
        "type": "color"
      }
    }
  },
  "dark": {
    "color": {
      "background": {
        "value": "{color.black}",
        "type": "color"
      },
      "foreground": {
        "value": "{color.white}",
        "type": "color"
      }
    }
  },
  "$themes": []
}
```

Running this through `token-transformer`

```
token-transformer ./data/tokens.json ./data/transformed/global.json global
token-transformer ./data/tokens.json ./data/transformed/dark.json global,dark global
```

I'm given the following:

```
// global.json
{
  "color": {
    "white": {
      "value": "#f0f0f0",
      "type": "color"
    },
    "black": {
      "value": "#222",
      "type": "color"
    },
    "background": {
      "value": "#f0f0f0",
      "type": "color"
    },
    "foreground": {
      "value": "#222",
      "type": "color"
    }
  }
}

// dark.json
{
  "color": {
    "background": {
      "value": "#222",
      "type": "color"
    },
    "foreground": {
      "value": "#f0f0f0",
      "type": "color"
    }
  }
}
```

Which I can then run through Style Dictionary just fine. But, when viewing this in Figma, the alias does not resolve:

<img width="401" alt="Screen Shot 2022-05-25 at 2 03 35 PM" src="https://user-images.githubusercontent.com/1018402/170333251-ef40ce3b-5737-4b29-8f31-7362d2f6c46f.png">

**Expected behavior**
Alias values should resolve within Figma

**Comment by six7** [comment]
Make sure the sets are checked. In your screenshot they are not. FT will only use the sets that are either `checked` or `treated as source`

**Comment by zslabs** [comment]
Agh, thank you very much - checking was what I needed to do there and makes perfect sense why it wouldn't resolve without it. Really appreciate it!
![ruh-roh](https://user-images.githubusercontent.com/1018402/170339456-68eb6904-fc02-4ab7-817e-9dda4caca942.gif)
