### ISSUE TITLE
Allow users to select which type of styles to create

### ISSUE THREAD

**Issue by leovogel** [six7/figma-tokens#756]
**Is your feature request related to a problem? Please describe.**
I sometimes create a new style in Figma Tokens that should exist in Figma, sometimes even creating several or dozens at a time, and I want to have Figma Tokens create all of those new styles for me in Figma. However I manage my color styles and typography styles in separate files from my main design system file. When I click Create Styles in Figma Tokens it creates all three Figma Styles and I then need to delete the two groups that don't belong in the file I'm working in (such as typography and shadows when working on my Colors file).

**Describe the solution you'd like**
Similar to how you can import a specific group of styles I want to be able to create a specific group of styles by selecting the styles I want in a checklist.

Create Styles
[ ] Color Styles
[ ] Typography Styles
[ ] Shadow Styles

**Describe alternatives you've considered**
The only alternative would be to move all of my color and typography styles into my main design system file but I don't want to do this as I find it easier to manage everything by keeping them separate. I have also had issues when working with Zeroheight that I was told could be mitigated by keeping them separate.

**Additional context**
None

**Comment by six7** [comment]
Thanks for the feedback! I have something like that in mind for a revamped Styles functionality, where you're able to choose what styles to create (like in Import).

I'll add this one to the [Tracking issue](https://github.com/six7/figma-tokens/issues/394) as it covers one of the items!
