### ISSUE TITLE
run build:watch error

### ISSUE THREAD

**Issue by Edison-Liao** [six7/figma-tokens#757]
Describe the bug
Execute the project according to the document, but it doesn't work properly

To Reproduce

* Run `yarn` to install dependencies.
* Run `yarn build:watch` to start webpack in watch mode.
* Open `Figma` -> `Plugins` -> `Development` -> `New Plugin...` and choose `manifest.json` file from this repo.
* Create a Pull Request for your branch

But after executing 'yarn', run 'yarn build: Watch'

Expected behavior
Expect to tell me how to run the plug-in normally, instead of executing build every time to see the changes
 Thank you so much

Screenshots or Screencasts
![image](https://user-images.githubusercontent.com/30523347/170240136-dedb6dca-5aab-491d-a4eb-d365fe715367.png)

**Comment by six7** [comment]
is this the full output? it seems some parts are missing. Either way I feel this is an error with your yarn setup? Is it installed?

**Comment by Edison-Liao** [comment]
> is this the full output? it seems some parts are missing. Either way I feel this is an error with your yarn setup? Is it installed?

Yarn is installed, otherwise it should not be possible to run 'yarn' to generate node modules 
![image](https://user-images.githubusercontent.com/30523347/170904591-67f22991-2afc-4563-8b80-f18d564a8938.png)

**Comment by six7** [comment]
And you typed `yarn build` or `yarn build:watch` ?

The screenshot doesnt show what command you ran

**Comment by Edison-Liao** [comment]
![image](https://user-images.githubusercontent.com/30523347/170933618-3e36fb46-3473-4fe7-8ec5-80408e35f38b.png)
Running 'yarn run build:watch' or 'yarn build:watch' returns an error, but running 'yarn build' can build normally

**Comment by six7** [comment]
Weird, seems to me more like an error related to `yarn` than to this plugin then

**Comment by Edison-Liao** [comment]
It is strange that if the error is' YARN ', 'YARN Run Build' should also report an error, not just 'YARN Run Build :watch'

**Comment by six7** [comment]
Closing this as it's likely related to your build environment or node version.
