### ISSUE TITLE
HSLA - Input field values wo/ limitations

### ISSUE THREAD

**Issue by sakaavee** [six7/figma-tokens#766]
**Describe the bug**
I am trying to set the saturation value for a color to 10% but the field allows a count of more than 100.

https://user-images.githubusercontent.com/59090839/170727255-88bb675e-59c4-4628-86eb-a26db15be6e6.mov

**Comment by six7** [comment]
Thanks for reporting. We're investigating and working on a fix 👍

**Comment by six7** [comment]
will be fixed in the next major release end of next week 👍

**Comment by six7** [comment]
This is now released 🎉
