### ISSUE TITLE
Gap tokens do not work on autolayout frames with "auto" gap

### ISSUE THREAD

**Issue by ssashqo** [six7/figma-tokens#769]
When you have "auto" in gap setting of auto layout  frame, a token with static value does not apply this value instead of "auto"

**To Reproduce**
1. Create auto layout with two+ elements. 
2. Set gap between elements to "auto".
3. Apply any space token with any numeric value.

**Expected behaviour**
gap between elements should be set to whatever value is in the space token

**Comment by six7** [comment]
Would you expect this to change `Space between` back to `Packed` ? Because this is what would happen

**Comment by six7** [comment]
Got it, will add it to the next release backlog
