### ISSUE TITLE
Update the slack address in the documentation

### ISSUE THREAD

**Issue by youngbeom-shin** [six7/figma-tokens#779]
Hi!
I found that the slack link in documentation is no longer active， could you please update it.

Doc:https://docs.tokens.studio/?ref=pf
Slack link:https://figmatokens.slack.com/join/shared_invite/zt-1930hf3jr-j09cMMi2F9SXnMvc7t23ew#/shared-invite/error

Thanks for this plugin, it's really helpful!

**Comment by mikekamminga** [comment]
Thanks for letting us know, here's an invite for you: 
https://join.slack.com/t/figmatokens/shared_invite/zt-1977abss1-OIRQ6xEsBvQVZHogXlZTrg

We'll update the link on the website.

**Comment by six7** [comment]
Updated 👍 

We should think of something where we don't have to update every 100 members.
