### ISSUE TITLE
Stroke Colors

### ISSUE THREAD

**Issue by davidhellmann** [six7/figma-tokens#78]
Hey,

I've a set color tokens. Is it possible to use this colors also for Stroke colors?
Maybe a solution is to hold the OPT Key and click on that token? Otherwise I have to set my stroke colors hard but sounds not like a plan :)

**Comment by six7** [comment]
Yes, that's possible, you can right-click any color token and you should be able to select `Fill` or `Border` — you can then also choose a `border width` token to go along with it.

I'm not too happy with the right-click action, but I haven't thought about a good alternative just yet, especially as this one is so close to Figma's own behaviour.

![image](https://user-images.githubusercontent.com/4548309/108509795-ff260800-72bd-11eb-83fd-626f6896c9b1.png)

**Comment by davidhellmann** [comment]
Ah! Thanks. 
But not possible to use CMD Click or OPT Click for secondary options? :)

**Comment by six7** [comment]
Ahh, you mean clicking cmd / opt + to trigger a secondary action? I like that!

Could combine that with another key to trigger a third / 4th option as well 👌

**Comment by davidhellmann** [comment]
Yeah, sounds great! How many layers are possible atm? :D

**Comment by six7** [comment]
Currently the maximum actions we have are 4, on Spacing (All, Horiz, Vertical, Gap) — however these will change to the new auto layout properties (All, Top, Left  Right, Bottom)

**Comment by BobbyJoStefflTR** [comment]
Can you elaborate a bit on this? What if you only want this particular color token to be applied as a stroke? Should you tie it to a style in some way?

**Comment by six7** [comment]
You can already apply a token to a layer's border by right-clicking and choosing Stroke. Layer needs to have a stroke set in Figma or have a borderWidth token set.

Should probably optimize that by defaulting to 1px borderWidth
