### ISSUE TITLE
Sets deselected after push to GitHub

### ISSUE THREAD

**Issue by GregoryLC** [six7/figma-tokens#780]
**Describe the bug**
After syncing with GitHub, all active sets are deselected

**To Reproduce**
1. Click the push button 
2. All actives sets are deselected
 
**Expected behavior**
Keeping all active sets after syncing

**Screenshots or Screencasts**
![Capture d’écran 2022-05-31 à 11 00 43](https://user-images.githubusercontent.com/104354276/171135821-1a83246e-411c-423a-8c3d-8536e92a20c3.png)
![Capture d’écran 2022-05-31 à 11 01 06](https://user-images.githubusercontent.com/104354276/171135822-856e7bc4-d71b-4101-b317-d44e9bd52050.png)
![Capture d’écran 2022-05-31 à 11 01 25](https://user-images.githubusercontent.com/104354276/171135825-735d18b3-9381-4c90-b9d8-c6b81eac46c3.png)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.
can't upload json file (message "we don't support that file type")

**Comment by LehtinenRiku** [comment]
I would give anything if this was fixed asap 🙏

**Comment by six7** [comment]
> I would give anything if this was fixed asap 🙏

This is now released 🎉
