### ISSUE TITLE
Text Alias preview: text size & line height are swapped

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#797]
Seems like in text alias preview text size = line height and line height = text size (edited) 

![image](https://user-images.githubusercontent.com/66366384/171563439-cd32e17c-aee0-4882-bbaa-35ccddcec8b6.png)

**Comment by six7** [comment]
I noticed this is because of the way this list was implemented, instead of showing the right labels according to the keys we show the labels as they are defined in the json, however not for the values.
