### ISSUE TITLE
Allow removing tokens with the UI

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#8]

**Comment by chris-pearce** [comment]
Hi! Love the plugin. Any update on this one? Cheers.

**Comment by six7** [comment]
Have it very high on my list of quick wins, should hopefully not be too hard.

**Comment by six7** [comment]
Have the code somewhat ready, will publish an update later in the day.

Deleting a token can now be done by right clicking that token and selecting Delete Token.

As more and more functions go into the context menu I wonder if or how I could make it more apparent that a user can right-click. Getting a lot of feedback about not knowing that one can right-click (dont want to clutter the UI though, Figma also has no clear indicator of what can be right-clicked).

![image](https://user-images.githubusercontent.com/4548309/99048574-07232d00-2596-11eb-8ac6-022cdd2b78f3.png)
