### ISSUE TITLE
Loosing all tokens modification when quiting whitout synchronizing ...

### ISSUE THREAD

**Issue by XavierVilars** [six7/figma-tokens#801]
**Describe the bug**
After modifying tokens if I quit without pushing my modification to Github and then if I'm come back I loose all my work. Seems that a pull is done from Github and it override everything. **Huge waste of time** !!!

**To Reproduce**

preriquisite : sync with Github.

1. Open Figma-Token
2. change some token
3. quit
4. come back and everything is lost

**Expected behavior**
If i quit and come back everything is like I left.

**Comment by LehtinenRiku** [comment]
Yes, super annoying. No way to store current progress to Figma file @six7 ?

**Comment by six7** [comment]
Will be fixed in the next release 👍

**Comment by six7** [comment]
This is now released 🎉
