### ISSUE TITLE
Remapping applied tokens doesn't update canvas

### ISSUE THREAD

**Issue by ianturk** [six7/figma-tokens#804]
**Describe the bug**
Remapping a token, say from DarkTheme.Text.Primary to LightTheme.Text.Primary updates the token in Figma Tokens but doesn't apply the updated color on the Figma canvas.

**To Reproduce**
1. Select component with token needed to be remapped. 
2. Remap token to new token
3. Updated token value isn't applied to the component

**Expected behavior**
The remapped value would apply to the selected layer in the Figma canvas.

**Comment by ianturk** [comment]
Looks like the update button on the Tokens tab will update but it isn't clear to do so from the inspect tab.

**Comment by six7** [comment]
We're changing that in the next release to auto update after remap👍

**Comment by six7** [comment]
This is now released 🎉
