### ISSUE TITLE
Figma tokens and style-dictionary tokens naming

### ISSUE THREAD

**Issue by mikeozornin** [six7/figma-tokens#817]
This is an issue from twitter reply (https://twitter.com/six7/status/1533017292262584320).

**Is your feature request related to a problem? Please describe.**
I'm trying to make our company's UI Kit two-way synced with our components. We have our UI components both for Angular and React so I want to make manual changes as little as possible.

We use style-dictionary  for tokens in our web components. It seems, Figma Tokens uses something different. Difference are both in naming style and names itself.

| Figma Tokens  | Style-dictionary |
| ------------- | ------------- |
| fontFamily  | font-family  |
| textCase  | text-transform  |

I see style-dictionary convention and style-dictionary tools and links in your examples, but couldn't understand why format doesn't match.

**Describe the solution you'd like**
I'd like to see Figma Tokens able to read and write tokens from style-dictionary format. Or maybe transform tool is a good solution too.

**Comment by mikeozornin** [comment]
Just after posting I found a npm package for that transform. Will ask our frontend guys to help with it and maybe my issue is already solved.

https://www.npmjs.com/package/@divriots/style-dictionary-to-figma

**Comment by six7** [comment]
Can you describe what it is that doesnt work? I use style dictionary with custom transforms and it works just fine.

**Comment by mikeozornin** [comment]
I described Figma Tokens with no transform and style-dictionary format due to I have no transform script or tool. 

So I hope https://www.npmjs.com/package/@divriots/style-dictionary-to-figma will help for me and work as you custom transform.

**Comment by six7** [comment]
Ah got it. Style dictionary relies on name to infer type, figma tokens does not and instead uses a type property. Long term both tools will align closer as a w3c spec becomes a reality.
