### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by romeetosun** [six7/figma-tokens#82]
hello! me again <3
I'm very keen with this plug in, I'm using it everyday!
But I want to make a consult, today with my team we were working on our design system but the spacing does not work, and we don't understand why!
Is there any tutorial? maybe we skipped a step.
Thanks for your time, have a nice day!

**Comment by six7** [comment]
Hey @romeetosun

I've just added a documentation page with a short video on Spacings on [docs.tokens.studio/tokens/spacing-tokens](https://docs.tokens.studio/tokens/spacing-tokens) — I hope this short guide solves any confusion on spacing tokens you might have had.

If you have any information that's missing from that page, please let me know!

**Comment by romeetosun** [comment]
You are so great, thank you so much!
Tomorrow I'll check this document.
<3


romee.-
about.me <http://about.me/romeetosun>

**Comment by six7** [comment]
Closing this for now, please reopen if anything is still unclear 🙏

**Comment by romeetosun** [comment]
sure!

romee.-
about.me <http://about.me/romeetosun>
