### ISSUE TITLE
Unable to remove tokens from multiple parent component variants at once

### ISSUE THREAD

**Issue by leo-daupler** [six7/figma-tokens#826]
**Describe the bug**
Unable to remove tokens from multiple parent component variants at once.

**To Reproduce**
Select multiple component variants, apply a token, click the token again to remove.
token is still applied to variants.

**Expected behavior**
Token is removed from all variants.

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by felixbridell** [comment]
I noticed this yesterday as well when trying to remove tokens using the inspect panel. This has worked before…

**Comment by bswerd** [comment]
I'm experiencing the same bug. At this point it's a deal-breaker for me to go to production with our Figma library... 

I even wrote a plugin to go in and nullify all of the `sharedPluginData` under the `tokens` namespace, but that didn't work either: Still had tokens applied when restarting Figma Tokens and going to Inspect.
