### ISSUE TITLE
Token values getting replaced after "Finding and caching tokens" completes

### ISSUE THREAD

**Issue by jamietotten** [six7/figma-tokens#829]
**Describe the bug**
The plugin (which is awesome) is replacing token values. So far our team has observed colours being randomly replaced (by colours that don't exist in our colour palette), and spacing tokens for example a `medium` token (32px) gets replaced with a `large` tokens (64px). 

**To Reproduce**
1. Go to \any file using the Figma Tokens plugins
2. Start the plugin
3. Wait for the file nodes to update "Finding and caching tokens...(110s remaining)"
4. Once the update finishes, tokens get replaced 

**Expected behavior**
I expect the plugin to not modify the design on load.

**Screenshots or Screencasts**
Here are 2 screenshots, a before and after. In the before, you can see the plugin updating nodes and calculating time, then in the after you see updated colours. Not shown here - this has also applied other random spacing values.

**BEFORE PLUGIN NODE UPDATE**
![Before](https://user-images.githubusercontent.com/658163/172484792-c967eb6e-597d-463a-8391-650195a5987b.png)

**AFTER PLUGIN NODE UPDATE**
Note the orange text replaced. This colour isn't in the colour tokens either which makes this extremely odd.
![After](https://user-images.githubusercontent.com/658163/172484822-970c2f2f-bceb-42aa-9a95-3a004d5242bf.png)

**Comment by six7** [comment]
Is there a style named like the token that got applied? Or what value does the text layer have once its orange? 👀

**Comment by six7** [comment]
Independent of that we'll revert that tokens are updated on plugin launch which is unexpected indeed.

**Comment by jamietotten** [comment]
> Is there a style named like the token that got applied? Or what value does the text layer have once its orange? 👀

Hey Jan, thanks for the reply and awesome plugin! 

There is no style named like the token that got applied because the value that got applied (#FDB735) isn't even a token value in our system, which is the strangest part. I just tried it again and It happened again.
