### ISSUE TITLE
Adding tokens through URL Token Storage fails

### ISSUE THREAD

**Issue by neatlittlemacapps** [six7/figma-tokens#832]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings' and 'URL - Token Storage'
2. Click on 'Add new credentials'
3. enter name and URL to tokenset
4. Click "Save"
5. -> Nothing happens

**Expected behavior**
Tokens should load.
doing the same through Github does work (same tokenset)

**Screenshots or Screencasts**
https://www.loom.com/share/15ea4503b3534c6d954e4e07175c31e2

**Figma file (optional)**
Bug happens on any file

**JSON (optional)**
I'd rather not but as the screencast shows, both Github and URL are pointing to the same JSON file So I'd expect that to be valid.

**Comment by dutscher** [comment]
If i have old token url and click there save, i got it twice in the list.
there is a index storage bug i guess.
cheers

**Comment by ejlayne** [comment]
+1, also running into this issue

**Comment by neatlittlemacapps** [comment]
Oh, thank you @ejlayne I thought I was going mad.

**Comment by tmsn123** [comment]
> Oh, thank you @ejlayne I thought I was going mad.

nope, same problem here

**Comment by neatlittlemacapps** [comment]
Aaand... Does anyone else notices components for which I could swear I "removed" tokens from now all of a sudden still have those tokens assigned to them? almost as if the internal dbase structure of which tokens are assigned to what layers changed. Or am I getting paranoid?

**Comment by six7** [comment]
> Aaand... Does anyone else notices components for which I could swear I "removed" tokens from now all of a sudden still have those tokens assigned to them? almost as if the internal dbase structure of which tokens are assigned to what layers changed. Or am I getting paranoid? <img alt="Screenshot 2022-06-09 at 17 10 11" width="1099" src="https://user-images.githubusercontent.com/60575307/172881457-f4689d88-af74-444a-93fe-407ae86b9701.png">

There was an issue yesterday that was fixed that could have caused that behavior to appear briefly. Not related to URL storage though.
