### ISSUE TITLE
Applied token gets removed on restarting the plugin

### ISSUE THREAD

**Issue by esthercheran** [six7/figma-tokens#833]
**Describe the bug**
On applying a token on a Figma component, closing and restarting the plugin the applied token gets un-applied.

**To Reproduce**
1. Create a Figma component
2. Apply a token eg. borderRadius
3. Close the plugin
4. Restart the plugin
5. The applied token is removed

**Expected behavior**
On closing and restarting the plugin, the token should remain applied

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/66366384/172600803-95528cfa-54c4-4c7f-b77a-92f2a4768537.mov

**Comment by six7** [comment]
Fixed in 107
