### ISSUE TITLE
Apply border width to specific sides (left, top, right, bottom)

### ISSUE THREAD

**Issue by leo-daupler** [six7/figma-tokens#836]
**Is your feature request related to a problem? Please describe.**
If I change a component with a border width token applied to only have a border on the left upon updating my files the width is reapplied and all four sides have a border again.

**Describe the solution you'd like**
Similar to how border radius can be set for each corner, allow setting the border width for each side.

**Describe alternatives you've considered**
I don't know of an alternative.

**Additional context**
None

**Comment by six7** [comment]
> Is it that Figma doesn't support it in the plugin API? Because Figma did recently add support for setting borders separately in Figma itself.
> 
> 
> 
> <img width="265" alt="CleanShot 2022-06-17 at 15 17 09@2x" src="https://user-images.githubusercontent.com/98129992/174306024-36eed043-2d44-4a59-9875-046d0da65159.png">

Yes, those haven't been added to their plugin api yet.

**Comment by wolfXDnet** [comment]
[API Version 1 update 48](https://www.figma.com/plugin-docs/blog/2022/06/08/version-1-update-48/) states to have the functionality added...
