### ISSUE TITLE
Override token applied to parent component with new token settings

### ISSUE THREAD

**Issue by leo-daupler** [six7/figma-tokens#844]
**Is your feature request related to a problem? Please describe.**
I have a main button component where all four corners have a 4px border radius set with a token. I am then using this main button component to build a split button component and the corners need to be 0px for the corners in the middle of the split button component but I am unable to override the parent component token.

**Describe the solution you'd like**
Allow overriding parent component tokens for a child component used inside another component.

**Describe alternatives you've considered**
Create a bunch more variants to get around this limitation making managing the main button component much more cumbersome and a larger Figma file as well.

**Additional context**
None

**Comment by six7** [comment]
Can you check again with the recent release? This should work even with `0` - just tested it.

**Comment by six7** [comment]
I'll be closing this - please reopen if the issue persists (my guess is our recent release fixed this)
