### ISSUE TITLE
After entering keywords in the input box, the drop-down box can automatically filter irrelevant tokens and display relevant tokens.

### ISSUE THREAD

**Issue by mswbol** [six7/figma-tokens#868]
After entering keywords in the input box, the drop-down box can automatically filter irrelevant tokens and display relevant tokens.When I create new tokens, the value refers to tokens. Because there are many existing tokens, I cannot quickly find and select the desired tokens.

I hope the author can give priority to the implementation of this function, which can improve work efficiency and reduce the time-consuming of finding tokens.

**Comment by six7** [comment]
I don't understand yet the scope of this issue, can you elaborate more or with a concept?

**Comment by six7** [comment]
Closing this, feel free to reopen when you have more info for us
