### ISSUE TITLE
Improve error messages when connecting to a remote repository

### ISSUE THREAD

**Issue by pandabrand** [six7/figma-tokens#869]
**Describe the bug**
I am trying to github sync to manage my tokens, when add my credentials I get this error `There was an error connecting. Check your credentials.`
I have tried this with two access tokens I have generated, one brand new and another that used to test the Design Tokens plugin. That one works in connecting with my github repo, but I can't in this plugin.

**To Reproduce**
1. Go to File > Plugins > Figma Tokens
2. Click on Settings > GitHub > Add new Credentials
3. Fill out credentials 

**Expected behavior**
It connects to Github or at least let's me know what is wrong with my credentials in greater detail.

**Comment by six7** [comment]
Is there a tokens file stored that you're setting as filePath? The plugin currently also gives the credentials error even when it was the file that couldnt be parsed. (Which we should fix). If you can link to that file here i could check what's wrong with that one

**Comment by designhawg** [comment]
I found this guidance to be very helpful. Maybe adding a tooltip that instructs the user to have a file created at the location designated in the credentials form would provide the missing piece of information. While I am not a developer, I have used GitHub for projects for a decade and was looking for all manner of errors with my tokens and permissions settings to solve this issue. I never thought it would be the actual file pathway/lack of pre-existing files causing the issue.

**Comment by cheryl-c-tirerack** [comment]
I am having issues with credentials and guess what, no valuable feedback. This appears to be marked closed because for some people creating the file in the repo first fixes it. This does not solve the fact that there is 0 useful information provided.
I have created the repo and my token and all I get is
Error syncing with GitHub, check credentials

**Comment by hjabbing** [comment]
Something that might also help is checking the api response in your browser console. I opened it in another tab and got the error "A project name is required in order to reference a Git repository by name". I added the project name to my organisation url and it worked.

**Comment by starblazingunicorn** [comment]
I have similar problem. I followed the instruction, still getting `Error syncing with GitHub, check credentials` :/

**Comment by arturvolokhin** [comment]
If you meet a similar problem, check your data in "Repository (owner/repo) field". You have to write link to your repo, not name.
For example, if your repo has `https://gitlab.com/superdeveloper/figma-tokens` url, you have to write `superdeveloper/figma-tokens` to the field.

Good luck.
<img width="353" alt="Снимок экрана 2024-09-04 в 14 05 01" src="https://github.com/user-attachments/assets/c53c99eb-5f59-4e0a-8ef0-a79900fd592a">
