### ISSUE TITLE
Enterprise support/plan

### ISSUE THREAD

**Issue by PatrickJS** [six7/figma-tokens#870]
Do you have an Enterprise support option? We need a few features added to the plugin to improve the UX in figma

**Comment by six7** [comment]
We do not yet but we plan to. Would love to find out more about your needs / those features you mentioned - can you elaborate here or would a zoom meeting make more sense?

**Comment by PatrickJS** [comment]
Whats the best way to contact you for zoom?

**Comment by PatrickJS** [comment]
meeting sent titled "Meeting with Jan Figma Tokens" this is for Experian USA

**Comment by PatrickJS** [comment]
@six7 please make sure you can join or respond to the invite for another time
Keith Barney sent the invite for us.
Wednesday, June 15, 2022 from 9:30 AM to 10:30 AM PST
