### ISSUE TITLE
Adjust order of tokens in Inspect/Annotate

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#872]
We currently show tokens as they were applied, both in Inspect and when creating annotation layers.

We should use a certain specified order so that it's easier to predict where a property will appear.

In this example, it's hard to read as every value appears in another place.

![Image](https://user-images.githubusercontent.com/4548309/173253444-254cde92-541f-45d7-a878-1b9a449ff892.png)

![Image](https://user-images.githubusercontent.com/4548309/173253446-ce2e14e6-26e8-4471-9d5b-aa27bcebf602.png)

For example, an order could be
- color (fill, border)
- spacing (all, pt, pr, pb, pl, vertical, horizontal, gap)
- sizing (all, width, height)
- border (width: all, top, right, bottom, left, radius)
- shadow
- opacity
- typography: first typography then all properties
- composition
- documentation: name, raw value, value, description

We could use the properties listing stored in `src/constants/Properties.ts` - we might need to change that order to reflect the above.

**Comment by esthercheran** [comment]
This is not working as expected
