### ISSUE TITLE
Colors are not shown 

### ISSUE THREAD

**Issue by sebasebasebaseba** [six7/figma-tokens#89]
![grafik](https://user-images.githubusercontent.com/26087379/112435921-ac6cbf80-8d45-11eb-91f5-e69df2db548f.png)
As you can see in the screenshot, the defined colors are not shown in the plugin. Is there a way to fix this?

Thx a lot for this great plugin! This is really awsome

**Comment by six7** [comment]
@sebasebasebaseba Thanks for raising this issue. Could you paste the JSON? And also do you use any token sets (themes) where maybe the colors that are referenced are not activated?

**Comment by sebasebasebaseba** [comment]
thx for the quick response! Here is my JSON at least the colors:
```
{
  "colors": {
    "Primary": {
      "value": "FF10FF"
    },
    "Primary_b": {
      "value": "1953DA"
    },
    "Primary_c": {
      "value": "16F7FA"
    },
    "Primary_d": {
      "value": "FBBE42"
    },
    "Gray_20": {
      "value": "222222"
    },
    "font_white": {
      "value": "eeeeee"
    },
    "Gray_30": {
      "value": "333333"
    }
  },
```

The issue is, that the color preview it not working. I recorded a video showing that the colors are not shown inside the plugin, but it's working like expected.

https://user-images.githubusercontent.com/26087379/112467772-c0291d80-8d67-11eb-8b42-db029d8aa306.mp4

**Comment by six7** [comment]
Ah, I see. If you add a `#` to each of your token values, does it work? I think Figma ignores that the hash sign is missing, but the plugin currently does not.

**Comment by sebasebasebaseba** [comment]
And now it's working! Thx for the support!

I totally love your plugin and hopefully i can use it in former projects. If so, i will let you know to which products it contributes :)

![grafik](https://user-images.githubusercontent.com/26087379/112471725-86a6e100-8d6c-11eb-8ab9-a1854fcc0619.png)

**Comment by six7** [comment]
Awesome! One suggestion: You can group your tokens to be grouped by e.g. Primary, Gray, etc.

To do that you can go into the edit Colors dialog (the one next to the Create Styles button) and create a new folder. More on that here: https://docs.tokens.studio/tokens/creating-tokens#token-groups
