### ISSUE TITLE
Exported JSON issues with rgba using references

### ISSUE THREAD

**Issue by samit4me** [six7/figma-tokens#890]
**Is your feature request related to a problem? Please describe.**
When specifying a color using [RGBA](https://docs.figmatokens.com/tokens/color-tokens#alpha-values-opacity) that references another token (e.g. `rgba($core.primary.light, 0.4)`) It works perfectly fine in Figma, but the exported JSON value does NOT transform the reference and this appears to make it incompatible with Style Dictionary.

The exported JSON:
```JSON
...
"light": {
    "value": "#e6f5ff",
    "type": "color"
},
...
"bg-hover": {
    "value": "rgba($core.primary.light, 0.4)",
    "type": "color"
}
```

The resulting CSS Variable after Style Dictionary:
```CSS
--<prefix>-bg-hover: rgba($core.primary.light, 0.4);
```

**Describe the solution you'd like**
Would like the actual color value to be exported, so using the example above.

The exported JSON:
```JSON
"bg-hover": {
    "value": "#e6f5ff66",
    "type": "color"
}
```

**Describe alternatives you've considered**
Thought this could be an issue with Style Dictionary, but I'm unsure how this could be solved on that end.

**Additional context**

**Comment by six7** [comment]
You'd need to transform that kind of rgba/hex modifier in a transformer for style dictionary as it's using a syntax that isn't standard.

Ideally we'll move away from rgba(#hex) tokens altogether and instead have a concept of modifiers where alpha is one of them.

**Comment by six7** [comment]
Closing this in favor of https://github.com/six7/figma-tokens/issues/423 as it will solve the issue you had
