### ISSUE TITLE
Introduce color text input validator.

### ISSUE THREAD

**Issue by mikekamminga** [six7/figma-tokens#892]
Right now, any value is valid. [Documentation](https://docs.tokens.studio/tokens/color-tokens) states only few options are valid, but actually this is not the case - simple "X" will also be allowed and color will default to black without any indication that this token is incorrect. If downstream parsers depend on it, it will break them, potentially also breaking CI/CD pipeline connected to them, unless handled as fallback

**Comment by six7** [comment]
Duplicate of https://github.com/six7/figma-tokens/issues/421

Lets close this one and keep discussion there? Or am I misunderstanding?

**Comment by mikekamminga** [comment]
Closing the issue, it's a duplicate
