### ISSUE TITLE
Tiered libraries & token consumption

### ISSUE THREAD

**Issue by john777is** [six7/figma-tokens#901]
Hi, 

I'd like to ask for a best practice recommendation for a tiered Figma library architecture which is powered by tokens via the FT plugin. My Figma library setup looks like so:

- I have split my libraries into two tiers (Figma projects), the first one is dedicated to the libraries which store only Figma styles, effects, and design tokens via the FT plugin. The second tier is dedicated to standalone UI Component, Icon set, and Illustration libraries which consist of no local styles and effects, all component layers are powered by styles from tier 1 library (tier 1 libraries prior to the FM tokens were used for theming using Figma's library swapping feature).

- Tier 1 design tokens library which stores the design tokens is synced with a Github repo.

- The tier 1 design token library consists of foundational, contextual, and component token sets. The contextual and component set token values are entirely powered by aliases.

- Only the foundational token set tokens have corresponding Figma styles and effects.

**Issues/questions:**

1. When a token from a contextual or component token set is applied to a layer, the applied value is being applied statically (e.g. in the case of a color token, it just applies the HEX value) without a style (from the foundational set, since its value is set to an alias linking to a foundational token which has a matching Figma style). Shouldn't the matching Figma style, which was referenced, be applied to the layer as well? Or is it recommended to create the missing styles for those tokens (via the Styles > Create Styles)? As I have a lot of contextual and component level tokens, keeping all the corresponding styles and effects in the same library seems like overkill, having in mind that the values of all those tokens are aliases and are matching the styles from the foundational set. Could you recommend what would be the best approach for such a use case?

2. Since the tier 2 component libraries consist of no local styles, whenever a token is being applied to a layer, the FT plugin only applies the token, and its value but the pertaining style (from the tier 1 library, foundational set/style) is not being applied, it seems that there's no connection between the JSON file from the repo and the original library the tokens were created in. Is there any workaround or way to associate that JSON file with a specific Figma library file so that when applying tokens in external files, not only the token but the pertaining style from an external library be applied to the layer as well? For now, it seems that the only workaround is to first apply the token via the FT plugin and then manually apply the needed external style from the library. Are there other workarounds or best practices for such a use case?

Btw, thank you for the best Figma plugin out there!

**Comment by six7** [comment]
The upcoming non local styles feature will solve that for you, we currently have that in Beta. Whenever you create or import styles in a Theme context we will save the style id's under a theme.

That way we'll apply the corresponding style instead of the raw hex value. 

We'll however require styles for tier 1 to be created, but I'd recommend to do that in a dedicated library either one for each theme or all themes inside one lib with the theme name prepending (we'll have functionality for that!)

If you want to beta test this, let me know in a twitter dm!

**Comment by john777is** [comment]
> The upcoming non local styles feature will solve that for you, we currently have that in Beta. Whenever you create or import styles in a Theme context we will save the style id's under a theme.
> 
> We'll however require styles for tier 1 to be created, but I'd recommend to do that in a dedicated library either one for each theme or all themes inside one lib with the theme name prepending (we'll have functionality for that!)

So, it will apply an external style (retaining the connection to the library file) + the token to the layer without creating a local style duplicate in the file, right? As ideally, all styles and tokens should live in the external tier 1 library files only.


>
> If you want to beta test this, let me know in a twitter dm!

Is the upcoming version going to be released soon?

**Comment by six7** [comment]
Yes.

We're iterating on the beta currently but hopefully will have a version that we feel confident by for a release.

**Comment by john777is** [comment]
Thanks 🙏🏻. OK, I'll wait for it.
