### ISSUE TITLE
Improve UX copy for recovery of local changes modal window

### ISSUE THREAD

**Issue by mikekamminga** [six7/figma-tokens#908]
On restart of plugin, when there are uncommitted local changes, the modal window is confusing and could be improved:

![image](https://user-images.githubusercontent.com/988169/174269785-de6e8744-1714-4109-9bb0-c83377db4b84.png)

**Comment by six7** [comment]
Thats quite a long button text for the Pull action, could be improved I guess?

+1 for reversing though!

**Comment by Einar-Weibust-Hansen** [comment]
A suggestion for text iteration:

**Recover local changes?**
You have local changes unsaved to the remote storage. 
No, Yes
