### ISSUE TITLE
Token set disappears after reopening Plugin

### ISSUE THREAD

**Issue by keeganedwin** [six7/figma-tokens#917]
Created new sizing tokens for a component under a sub-branch (not main) and pushed.
After pulling for the recently created token set, the file is updated - token set exists.
But on reopening the plugin, the token set no longer exists under the same sub-branch - as if never created in the first place.  

Expected behavior
<img width="411" alt="Screenshot 2022-06-21 at 4 17 00 PM" src="https://user-images.githubusercontent.com/93133012/174782710-96585afa-b043-40b3-af56-eea8d072ca0d.png">

This what it is supposed to look like after pulling.

Current behaviour
<img width="410" alt="Screenshot 2022-06-21 at 4 21 07 PM" src="https://user-images.githubusercontent.com/93133012/174782907-b40d7994-27b5-46e0-bf95-c65cdffbe9f5.png">

Behaviour after reopening the plugin, the sizing token set no longer exists.

**Comment by wishayajeen** [comment]
I'm having the same issue. Mine happened after my colleague added the same Github credential.
Our workaround now is I need to add a duplicated credential every time after reopening the plugin, and look for pull request popup after adding the credential.

**Comment by six7** [comment]
Could you provide a screenshare? Can you confirm the set does exist on your repository? I'm thinking this is a cache issue which we've solved in a development build, but would like to make sure.

**Comment by wishayajeen** [comment]
https://user-images.githubusercontent.com/8456599/175699878-a682593e-bb1a-44e9-8d7e-b5d1d6312178.mp4
Recording here. Today my workaround doesn't work anymore.

**Comment by keeganedwin** [comment]
It may have indeed been a cache issue. If I'm not mistaken the branch tree
was cleared of previous cluttered commits and it seemed to have resolved
the issue.

**Comment by six7** [comment]
> Today my workaround doesn't work anymore.

Make sure you set your file-path to `data/tokens.json` - note the missing `s` in your recording
