### ISSUE TITLE
Token transformer not working for box shadow

### ISSUE THREAD

**Issue by bavarnasivakumar** [six7/figma-tokens#918]
I have two sets, core and theme. When I add box shadow to core set and try to use it in theme, the box shadow from core set is not reference properly.

**Input.json**

{
  "core": {
    "action": {
      "value": {
        "x": "0",
        "y": "-4",
        "blur": "0",
        "spread": "0",
        "color": "#183484",
        "type": "innerShadow"
      },
      "type": "boxShadow"
    },
    "statusTextColor": {
      "value": "#ffffff",
      "type": "color"
    }
  },
  "theme": {
    "shadow": {
      "boxShadow": {
        "default": {
          "value": "{action}",
          "type": "boxShadow"
        }
      }
    },
    "status": {
      "value": "{statusTextColor}",
      "type": "color"
    }
  }
}

**command run**

token-transformer ./tokens/test.json src/tokens/output_test.json core,theme core

Output.json

{
  "shadow": {
    "boxShadow": {
      "default": {
        "value": {
          "0": "{",
          "1": "a",
          "2": "c",
          "3": "t",
          "4": "i",
          "5": "o",
          "6": "n",
          "7": "}"
        },
        "type": "boxShadow"
      }
    }
  },
  "status": {
    "value": "#ffffff",
    "type": "color"
  }
}

Tried adding expand shadow:

token-transformer ./tokens/test.json src/tokens/output_test.json core,theme core --expandShadow=true

Output:

{
  "shadow": {
    "boxShadow": {
      "default": {
        "0": {
          "value": "{",
          "type": "0"
        },
        "1": {
          "value": "a",
          "type": "1"
        },
        "2": {
          "value": "c",
          "type": "2"
        },
        "3": {
          "value": "t",
          "type": "3"
        },
        "4": {
          "value": "i",
          "type": "4"
        },
        "5": {
          "value": "o",
          "type": "5"
        },
        "6": {
          "value": "n",
          "type": "6"
        },
        "7": {
          "value": "}",
          "type": "7"
        }
      }
    }
  },
  "status": {
    "value": "#ffffff",
    "type": "color"
  }
}

Expected behaviour:
Shadow value to be updated properly.

**Comment by six7** [comment]
Just released version 0.0.24 of token-transformer with support for this.
