### ISSUE TITLE
Composition Tokens Do Not Transform

### ISSUE THREAD

**Issue by centaurreader** [six7/figma-tokens#933]
**Describe the bug**
Composition tokens run through token-transformer result in a value of `"[object Object]"`.

**To Reproduce**
Using the following raw tokens from Figma Tokens:
```
{
  "global": {
    "borderRadius": {
      "lg": {
        "value": "1",
        "type": "spacing"
      }
    },
    "colors": {
      "white": {
        "value": "#ffffff",
        "type": "color"
      },
      "gray": {
        "200": {
          "value": "#cccccc",
          "type": "color"
        }
      }
    }
  },
  "components": {
    "cards": {
      "default": {
        "type": "composition",
        "value": {
          "borderRadius": "$borderRadius.lg",
          "fill": "$colors.white",
          "border": "$colors.gray.200"
        }
      }
    }
  }
}
```
and running `token-transformer tokens-raw.json tokens-new.json` results in:
```
{
  ...
  "cards": {
    "default": {
      "type": "composition",
      "value": "[object Object]"
    }
  },
  ...
}
```

**Expected behavior**
I am not sure what the expected behavior should be or how style-dictionary would parse such a token. Is this feature only intended to be used in figma?

**Comment by six7** [comment]
Thanks for reporting, we're working on this. Hopefully we'll have a new build by early next week.

**Comment by six7** [comment]
Just released version 0.0.24 of token-transformer with support for this.

**Comment by arasheedrzf** [comment]
Hi @six7 – Thanks. I have the prop version of the plugin. I've installed 0.0.24 and the output looks fine but the style-dictionary returns [object object]. This is my output:

"atoms": {
    "button-primary": {
      "value": {
        "fill": "#004ea8",
        "textCase": "none",
        "textDecoration": "none",
        "fontSizes": "12px"
      },
      "type": "composition"
    }
  }
  
  Any recommendations?

**Comment by six7** [comment]
> Hi @six7 – Thanks. I have the prop version of the plugin. I've installed 0.0.24 and the output looks fine but the style-dictionary returns [object object]. This is my output:
> 
> 
> 
> "atoms": {
> 
>     "button-primary": {
> 
>       "value": {
> 
>         "fill": "#004ea8",
> 
>         "textCase": "none",
> 
>         "textDecoration": "none",
> 
>         "fontSizes": "12px"
> 
>       },
> 
>       "type": "composition"
> 
>     }
> 
>   }
> 
>   
> 
>   Any recommendations?

You'll need to have a style dictionary transform that turns this into the desired output. For composition tokens that could be a css class.

By default style dictionary isnt able to treat objects yet
