### ISSUE TITLE
Exporting with "Include parent key" or "All token sets" breaks aliases

### ISSUE THREAD

**Issue by evul** [six7/figma-tokens#940]
When exporting tokens, checking the "Include parent key" checkbox changes the node structure of the JSON and therefore breaks all aliases. If you run this output through Style Dictionary you'll get a "Reference doesn't exist" error because alias paths are now invalid. However, even if the aliases were resolved somehow in the export and transformed successfully by SD, there would still be an issue with using the variables coming from that output with CSS/SCSS that is built to work with an expected set of design tokens. Because now the token/variables names are different from what the CSS is expecting.

If you're only exporting one token set, then this issue can be avoided by not checking the "Include parent key" checkbox. But if you have multiple token sets and you want to export them all at once rather than one at a time, checking "All token sets" disables the "Include parent key" checkbox and will add a parent key to the JSON for each token set, even if the parent key checkbox was not checked before selecting "All token sets". 

As an example, if I create a token set in the plugin called `colors`, with a color token called `primary` and then reference it in another token called `background`, as follows:

```
{
  "color": {
    "primary": {
      "value": "#0066CC",
      "type": "color"
     },
    [...]
    "background": {
      "value": "{color.primary}",   <--- valid alias
      "type": "color"
    }
}
```
In the plugin view, I will see that `background` has inherited the value of `primary` and if exported without a parent key, it will be valid and will be transformed properly.

But when exporting with "Include parent key" or "All token sets" checked, the parent key `colors` is added, altering the JSON structure and invalidating the alias paths:

```
{
   "colors" {
      "color": {
        "primary": {
          "value": "#0066CC",
          "type": "color"
         },
        [...]
        "background": {
          "value": "{color.primary}",  <--- alias is now invalid
          "type": "color"
        }
    }
}
```

Now if you run this output through Style Dictionary, it thinks the reference is undefined because it is looking for `color.primary` when the path is now `colors.color.primary`.

But as I mentioned above, even if the aliases were to be resolved somehow in the export, there would still be an issue using the variables coming from that output with CSS/SCSS because now the token/variable names are different from what is expected. Using the above example, if the SCSS is expecting a variable called`$color-primary`, it won't compile using the token value from the output since it's not going to match with `$colors-color-primary`.

Whether I'm pasting JSON into the plugin or adding tokens manually through the plugin UI, my expectation is that what I put in is going to come out the same way. If the plugin is altering the JSON structure in the output based on settings, I think this will only cause issues with being able to use that output in a design token based development pipeline.

I think I understand why the parent key is added when exporting multiple token sets (not so much as an option for exporting a single set though). You would end up with bad JSON having identically named nodes in parallel, like `color`.  So instead you would have to merge sets somehow. 

Maybe a solution would be for the "All token sets" setting to export each set as an individual JSON file in one go, instead of having to export each set one at a time? This would be my preferred method since it would mirror how I have my design token JSON files structured already.

**Comment by six7** [comment]
You'll need to manually split your file into many for now, first level key is the filename.

[Here's](https://gist.github.com/six7/ddb9b1f0d0c6e434be4f1cdb8bfe56e1) a script to do that.

We're working on multi-file export right now, so the request with all token sets exporting individual files will be possible soon 👍
