### ISSUE TITLE
Setting "Ignore first part of token name for styles" does not apply to import styles

### ISSUE THREAD

**Issue by Wrecklaimer** [six7/figma-tokens#942]
**Describe the bug**
The setting "Ignore first part of token name for styles" only affects syncing from token to style, but not the other way around. When using the "Import Styles" option, the setting does not recognize tokens that are used as style source.

**To Reproduce**
1. Check Figma Tokens setting "Ignore first part of token name for styles"
2. Create a color token "colors.red.100"
3. Create a color style "red/100"
4. Update token
5. It updates the equivalent style
6. Update style
7. Use "Import styles" option
8. The color style is detected as new, not as an update to an existing token

**Expected behavior**
The "Import style" option should detect updates to existing tokens when using the "Ignore first part of token name for styles" setting.

**Comment by six7** [comment]
I'm afraid we won't be able to support that any time soon as 'colors' could just as well be anything else, or even multiple tokens could match if one is called colors.red.100 and another global.red.100.

We'll provide better support for this with advanced theming which keeps a connection between styles and tokens

**Comment by Wrecklaimer** [comment]
I understand that there might not be a 1-to-1 match. But the process already lets you pick which items to import, so couldn't it just include options for each of the *.red.100 matches? Maybe only match on type color for good measure.

Also, doesn't import only ever apply to the currently selected token set? So for your scenario to happen, you would have to had made two red.100 tokens in the same token set. That seems like the above solution producing multiple matches would be uncommon and an expected outcome for those choosing to do that.

Either way, I'm just trying to figure a sustainable way to keep this plugin working smoothly with Figma's native styles. I know someone will inevitably edit a style and be frustrated that it's out-of-sync.

**Comment by six7** [comment]
We'll soon be introducing a way to store style connections on a Theme level where we store style id, that way you could name your token however you want after a connection has been established.

**Comment by six7** [comment]
Closing this, we shipped `Connected styles` which allow you to connect styles to tokens. Give it a go! This issue is something we won't be getting to, but we hope the style connection solves that for you.
