### ISSUE TITLE
Text elements changing resizing properties when applying Sizing tokens.

### ISSUE THREAD

**Issue by cedricwaxwing** [six7/figma-tokens#959]
**Describe the bug**
When setting a font size (or changing value to documentation value via token) on a text element, it changes it to:
- "Fixed" resizing instead of "Hug" 
![image](https://user-images.githubusercontent.com/80348806/176943647-9bec2f24-b7ae-43d3-bc17-bdecc166a698.png)

- "Fixed Size" instead of "Auto Width"
![image](https://user-images.githubusercontent.com/80348806/176943668-0c78b67e-1efd-413d-9bea-a9d4fe4a3884.png)

Which results in squashed typesetting for any type that is in an auto layout:

From this:
![image](https://user-images.githubusercontent.com/80348806/176943891-297bf77b-f09e-4443-9e04-e4666ffe345d.png)

To this:
![image](https://user-images.githubusercontent.com/80348806/176943814-8f27d722-5ebb-4226-a687-e8364b6ad908.png)

**To Reproduce**
1. Create a text element
2. Apply a Sizing token to it.
4. See how the resizing properties (mentioned above) change.

**Expected behavior**
Applying a token should only update the intended token value (in this case, applying a sizing token should only affect the fontsize property, and not the resizing properties)

**Comment by six7** [comment]
Can you confirm you're applying a `fontSize` token to your text layer? It seems like you're applying a `sizing` token?

**Comment by cedricwaxwing** [comment]
Doh! Thank you.
