### ISSUE TITLE
Problem with Typography tokens

### ISSUE THREAD

**Issue by bellentani** [six7/figma-tokens#97]
On last update the plugin stoped work with Fonts/Typography tokens. 

To test (and make shure that isnt a sintax error on my JSON File) I opened a new file and fill with sample data, same problem.

Then I change the font to `Courier New` to illustrate the problema. When I changed to Inter or Roboto (the ´heading´ and ´body´ tokens) nothing happens. And this is a huge problem for all typography tokens (_Font family_, _Font weight_, _Font size_ and all others, including _Typography compositions_)

![image](https://user-images.githubusercontent.com/1213530/113083536-bdd52200-91b2-11eb-99be-df215202138d.png)

Testing on Windows Client and Web, with the same console error:

![image](https://user-images.githubusercontent.com/1213530/113084549-91baa080-91b4-11eb-9e20-6003b3f22e11.png)

**Comment by six7** [comment]
Thanks for reporting! Currently in the process of writing tests for all cases, this part didn't have any tests so far. Found the error and will release a new version with a fix soon. Then I'd like to introduce tests for that part, so that we do have a more robust foundation.

**Comment by bellentani** [comment]
Thanks a lot. You made a awesome/fantastic/genious plugin! <3
