### ISSUE TITLE
CORS origin not set for URL token storage

### ISSUE THREAD

**Issue by fredboyle** [six7/figma-tokens#970]
**Describe the bug**
CORS origin header is not set for URL token storage mechanism.

This prevents retrieval of the JSON file from the URL since we're unable to adjust the CORS allowed origin on the storage bucket (Google Cloud Storage) in order to allow Figma Tokens to access the resource.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'URL'
3. Click on 'Add credentials'
4. Enter info for CORS protected resource
5. Cick on 'Save'
6. See error

**Expected behavior**
URL resource should load without error.

**Screenshots or Screencasts**
<img width="674" alt="Screen Shot 2022-07-05 at 16 30 05" src="https://user-images.githubusercontent.com/32829/177411129-3646d038-12bc-4aef-aa69-d27445d2dbbe.png">

<img width="1719" alt="Screen Shot 2022-07-05 at 16 30 17" src="https://user-images.githubusercontent.com/32829/177411154-dbfbd1d0-250c-4cde-89ff-275b1cd39aef.png">

**Comment by six7** [comment]
You should be able to set headers yourself in the `Headers` field. However in your case it seems rather such a header would need to be set on the resource, not on Figma Token's end.

Here's a guide for Google Cloud Storage: https://cloud.google.com/storage/docs/cross-origin

**Comment by fredboyle** [comment]
@six7 Thanks for the response. The issue is, as you can see in the console screenshot, is that the request from Figma Tokens has no "origin" value set. This prevents us from setting up an allow entry in our Google Cloud Storage resource.

I did attempt to set headers on the request in the Figma Tokens plugin but without success. Is there a specific syntax the plugin requires for headers that I should perhaps try?

**Comment by fredboyle** [comment]
@six7 Please see [this test when using https://test-cors.org](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fstorage.googleapis.com%2Fpantheon-design-system-assets-sandbox%2Ffigma%2Ffigma-tokens.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) to the JSON file in question.

The proper headers are being returned but Figma continues to be unable to retrieve the file. Our bucket is temporarily set to be unrestricted but this isn't functioning and cannot be used long-term.

Could you point us to the code in the Figma Tokens plugin that makes this request so we could investigate and/or do some testing with a local copy of the plugin?

Thanks for your help.

**Comment by six7** [comment]
> @six7 Please see [this test when using https://test-cors.org](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fstorage.googleapis.com%2Fpantheon-design-system-assets-sandbox%2Ffigma%2Ffigma-tokens.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) to the JSON file in question.
> 
> The proper headers are being returned but Figma continues to be unable to retrieve the file. Our bucket is temporarily set to be unrestricted but this isn't functioning and cannot be used long-term.
> 
> Could you point us to the code in the Figma Tokens plugin that makes this request so we could investigate and/or do some testing with a local copy of the plugin?
> 
> Thanks for your help.

Sure, here it is: https://github.com/six7/figma-tokens/blob/3286f5fe9b584235a67cf4135776a23142bd72ef/src/storage/UrlTokenStorage.ts#L50

**Comment by fredboyle** [comment]
Seems I found the culprit. It is a [limitation of Figma plugins](https://www.figma.com/plugin-docs/making-network-requests). CORS requests are only possible for resources that allow any origin.
