### ISSUE TITLE
Request to support multiple file support in token transformer

### ISSUE THREAD

**Issue by bavarnasivakumar** [six7/figma-tokens#981]
**Is your feature request related to a problem? Please describe.**
We had a huge json file that was not getting loaded in the plugin. So we have purchased pro version. Now we got multiple file support. Each set is a json file. But now we are not able to use token transformer since it supports only single file.

**Describe the solution you'd like**
Token transformer supporting folder, where folder can be the source and sets and excludes can be the json file names inside. 

Eg: multifile/
core.json
semantic.json
theme.json

transform multifile output.json core,semantic,theme core,semantic

here multifile -> input
output.json -> output file
core,semantic,theme -> sets
core,semantic -> excludes

**Describe alternatives you've considered**
Token transformer supporting files merge, where folder can be the source and it will merge all the required sets to a single json that can be used.

Eg: Eg: multifile/
core.json
semantic.json
theme.json

transform multifile output.json core,semantic,theme 

here multifile -> input
output.json -> output file
core,semantic,theme -> sets

output.json will contain the merged json containing contents from core, semantic and theme json that is in token transformer supported format.

**Comment by six7** [comment]
Token transformer does support multiple files: https://docs.figmatokens.com/sync/github#using-multi-file-sync

**Comment by bavarnasivakumar** [comment]
My folder structure is as below

<img width="334" alt="image" src="https://user-images.githubusercontent.com/92791528/177686803-a1b810a5-84ea-4b8d-8d25-98d029260238.png">

I tried running the below command

token-transformer multifile ./src/tokens/test.json 01core,03semantic/mobile,02components/alert 01core,03semantic/mobile

Getting this error:

node:internal/fs/utils:345
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at transform (/usr/local/lib/node_modules/token-transformer/index.js:78:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/token-transformer/index.js:102:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

Let me know if this is the right way or if I am missing anything.

**Comment by six7** [comment]
Oh I understand! You're setting your include and exclude sets as directories as well.

That's not supported right now, so you'd have to pass all set names instead:

`token-transformer multifile ./src/tokens/test.json 01core/colors,01core/type,03semantic/mobile,02components/alert 01core/colors,01core/type,03semantic/mobile`

Btw does the `01core` folder exist? Can't see it in the screenshot.

I'll create an issue as a followup to this to make sure we add support to indicate folders as include and excludes.

**Comment by bavarnasivakumar** [comment]
01core is the filename. similarly 03semantic is folder name, mobile is file name.

**Comment by six7** [comment]
What version of token-transformer are you using?

**Comment by bavarnasivakumar** [comment]
"token-transformer": "^0.0.24" @six7

**Comment by six7** [comment]
And you're running that command from the root directory where `multifile` lives? From what I'm able to [gather from your error](https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a) is that it's not able to parse a file as it's a directory instead.

**Comment by mikekamminga** [comment]
@six7 I got on a call yesterday and tried running the token-transformer on my system with their files and everything works fine, seemed there were some system/folder permission issues in their current set-up.

**Comment by six7** [comment]
Got it, closing this one then.
